### ISSUE TITLE
e35: nil-ptr during merge

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#10101]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1204a04]

goroutine 8309289 [running]:
github.com/ledgerwatch/erigon-lib/seg.(*Decompressor).MakeGetter(...)
	github.com/ledgerwatch/erigon-lib@v1.0.0/seg/decompress.go:621
github.com/ledgerwatch/erigon-lib/state.(*InvertedIndexRoTx).mergeFiles(0xc33b281740, {0x319bb68, 0xc2c0315b80}, {0xc2c0327380, 0x4, 0x4?}, 0x861c4680, 0x8799bec0, 0xc000f04690)
	github.com/ledgerwatch/erigon-lib@v1.0.0/state/merge.go:721 +0x5e4
github.com/ledgerwatch/erigon-lib/state.(*HistoryRoTx).mergeFiles(0xc2c030bd60, {0x319bb68, 0xc2c0315b80}, {0xc2c0327380, 0x4, 0x4}, {0xc2c0327360, 0x4, 0xc0b15e7b00?}, {0x861c4680, ...}, ...)
	github.com/ledgerwatch/erigon-lib@v1.0.0/state/merge.go:833 +0x188
github.com/ledgerwatch/erigon-lib/state.(*DomainRoTx).mergeFiles(0xc32ac05760, {0x319bb68, 0xc2c0315b80}, {0xc2c03273a0, 0x4, 0x4?}, {0xc2c0327380, 0x4, 0x4}, {0xc2c0327360, ...}, ...)
	github.com/ledgerwatch/erigon-lib@v1.0.0/state/merge.go:521 +0x2a5
github.com/ledgerwatch/erigon-lib/state.(*AggregatorRoTx).mergeFiles.func2()
	github.com/ledgerwatch/erigon-lib@v1.0.0/state/aggregator.go:1362 +0x28d
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 7752561
	golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x96

```

**Comment by awskii** [comment]
investigating issue with staticFilesInRange where .efi file was not found during merge which could be related

**Comment by AskAlexSharov** [comment]
@awskii aha! got logs where tons of bad things happened and then nil-ptr. 
Main reason is: `deleting some histor files - because step 1485 has not enough files (was not complete)` - we deleting our own files (which we building in background) when do `reopen folder` :-)

Then I see: 
```
[snapshots] buildFilesInBackground       err="domain collate-build: open storage v history decompressor: open /mnt/erigon/snapshots/history/v1-storage.1485-1486.v: no such file or directory"
```

and then nil-ptr :-)

[last_1k_lines.txt](https://github.com/ledgerwatch/erigon/files/15162685/last_1k_lines.txt)

[full.txt.zip](https://github.com/ledgerwatch/erigon/files/15162691/full.txt.zip)

ok, right solution is: stop deleting files and protect from them by `recalcVisibleFiles`.

**Comment by AskAlexSharov** [comment]
hotfixing it by https://github.com/ledgerwatch/erigon/pull/10143

**Comment by AskAlexSharov** [comment]
and protection added https://github.com/ledgerwatch/erigon/pull/10144
