### ISSUE TITLE
CL: concurrent map write

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#10139]
network `holesky`, branch `e35` b9d5d8b205c23780faf36c717cc9b38e348140af

```
[DBUG] [04-30|06:37:56.463] OnBlock                                  elapsed=2.00319161s
[DBUG] [04-30|06:37:56.517] Caplin is sending forkchoice             app=caplin stage=ForkChoice
[DBUG] [04-30|06:37:56.519] [ExecutionClientRpc] Calling EL          method=engine_newPayloadV3
[DBUG] [04-30|06:37:56.523] block has invalid parent                 slot=1546388 hash=0x1b8409c2987c12f1c6ed1cc191c4149e15d05aa88e11b5bbf11010243f890cf3
[DBUG] [04-30|06:37:56.524] [ExecutionClientRpc] Calling EL          method=engine_forkchoiceUpdatedV1
[DBUG] [04-30|06:37:56.527] [ExecutionClientRpc] Calling EL          method=engine_newPayloadV3
[DBUG] [04-30|06:37:56.533] block has invalid parent                 slot=1546388 hash=0x1b8409c2987c12f1c6ed1cc191c4149e15d05aa88e11b5bbf11010243f890cf3
[DBUG] [04-30|06:37:56.539] import operations                        time=75.413148ms
[DBUG] [04-30|06:37:56.948] Incremented state history                elapsed=79.509µs preverifiedValidators=1699880
[DBUG] [04-30|06:37:56.948] Imported chain segment                   app=caplin stage=ForkChoice hash=0x75795c3e332e088bb4b72e4b55d86d4ef74b27488a7a2de3deb6588fb8989a11 slot=1546389 alloc=8.9GB sys=19.5GB
[DBUG] [04-30|06:37:56.950] clstage finish                           app=caplin stage=ForkChoice in=505.44441ms next=ListenForForks
[DBUG] [04-30|06:37:56.950] clstage finish                           app=caplin stage=ListenForForks in=14.53µs next=CleanupAndPruning
[DBUG] [04-30|06:37:56.951] clstage finish                           app=caplin stage=CleanupAndPruning in=1.72689ms next=SleepForSlot
[DBUG] [04-30|06:37:56.951] sleeping until next slot                 app=caplin stage=SleepForSlot slot=1546390 time=2024-04-30T06:38:00+0000 dur=3.04808369s
[DBUG] [04-30|06:37:56.952] [ExecutionClientRpc] Calling EL          method=engine_newPayloadV3
[DBUG] [04-30|06:37:56.957] block has invalid parent                 slot=1546388 hash=0x1b8409c2987c12f1c6ed1cc191c4149e15d05aa88e11b5bbf11010243f890cf3
[DBUG] [04-30|06:37:56.960] [ExecutionClientRpc] Calling EL          method=engine_newPayloadV3
[DBUG] [04-30|06:37:56.965] block has invalid parent                 slot=1546388 hash=0x1b8409c2987c12f1c6ed1cc191c4149e15d05aa88e11b5bbf11010243f890cf3

fatal error: concurrent map iteration and map write

goroutine 26675 [running]:
github.com/ledgerwatch/erigon/cl/pool.(*OperationPool[...]).Insert(0x31d1560, {0xa1, 0xc6, 0xa5, 0x1b, 0xef, 0x65, 0x55, 0x63, 0xf0, ...}, ...)
	github.com/ledgerwatch/erigon/cl/pool/operation_pool.go:38 +0x23a
github.com/ledgerwatch/erigon/cl/phase1/network/services.(*aggregateAndProofServiceImpl).ProcessMessage(0xc0630ab340, {0x218?, 0x218?}, 0x4?, 0xc008a33c78?)
	github.com/ledgerwatch/erigon/cl/phase1/network/services/aggregate_and_proof_service.go:143 +0x79f
github.com/ledgerwatch/erigon/cl/phase1/network.(*GossipManager).routeAndProcess(0xc0630c72b0, {0x31af848, 0xc0000d5180}, 0xc0b1963aa0)
	github.com/ledgerwatch/erigon/cl/phase1/network/gossip_manager.go:184 +0xb06
github.com/ledgerwatch/erigon/cl/phase1/network.(*GossipManager).onRecv(0xc0630c72b0, {0x31af848, 0xc0000d5180}, 0xc0b19639e0, 0xc010419e50?)
	github.com/ledgerwatch/erigon/cl/phase1/network/gossip_manager.go:120 +0x13a
github.com/ledgerwatch/erigon/cl/phase1/network.(*GossipManager).Start.func1.1()
	github.com/ledgerwatch/erigon/cl/phase1/network/gossip_manager.go:232 +0x13b
created by github.com/ledgerwatch/erigon/cl/phase1/network.(*GossipManager).Start.func1 in goroutine 26753
	github.com/ledgerwatch/erigon/cl/phase1/network/gossip_manager.go:239 +0xb4




```

**Comment by yperbasis** [comment]
Demoting priority to high because Caplin is not our default yet
