### ISSUE TITLE
[e3] crash on sepolia

### ISSUE THREAD

**Issue by wmitsuda** [ledgerwatch/erigon#10285]
vanilla E3 + external CL

Using today's main, commit `e2c5661b970df7ebc98d81a4ff747b5985f56558`

```
INFO[05-11|16:06:17.833] [4/12 Execution] Prune done              in=5m46.258513259s
O 0 0
INFO[05-11|16:06:24.857] Timings (slower than 50ms)               Snapshots=2.011s Senders=45.708s Execution=10m32.627s TxLookup=1m20.206s Prune Execution=5m46.258s commit=7.019344426s alloc=2.0GB sys=4.0GB
INFO[05-11|16:06:24.871] [4/12 Execution] starting                from=5882535 to=5882534 fromTxNum=225305788 offsetFromBlockBeginning=0 initialCycle=false useExternalTx=true
[dbg] mmmm... do we need action here????
INFO[05-11|16:06:24.874] head updated                             hash=0x06419b61d612291717252464072615b4379ae2537112dc717b75eee09711bb98 number=5882534
INFO[05-11|16:06:24.875] Timings (slower than 50ms)               commit=201.77µs alloc=2.0GB sys=4.0GB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x10764619e]

goroutine 747198 [running]:
github.com/ledgerwatch/erigon/turbo/execution/eth1.(*EthereumExecutionModule).updateForkChoice.func2()
        github.com/ledgerwatch/erigon/turbo/execution/eth1/forkchoice.go:337 +0x1e
github.com/ledgerwatch/erigon/turbo/execution/eth1.(*EthereumExecutionModule).updateForkChoice(0xc00127dcc0, {0x10860e448, 0xc001a860f0}, {0x7c, 0xf, 0xab, 0xf5, 0x88, 0xf7, 0x11, ...}, ...)
        github.com/ledgerwatch/erigon/turbo/execution/eth1/forkchoice.go:478 +0x28ea
created by github.com/ledgerwatch/erigon/turbo/execution/eth1.(*EthereumExecutionModule).UpdateForkChoice in goroutine 747197
        github.com/ledgerwatch/erigon/turbo/execution/eth1/forkchoice.go:84 +0x316
```

**Comment by somnathb1** [comment]
Can you share the full trace of the error?

**Comment by wmitsuda** [comment]
that’s the full trace, no more logs after that
