### ISSUE TITLE
erigonvm panic

### ISSUE THREAD

**Issue by holiman** [ledgerwatch/erigon#10298]
#### System information

Erigon version: `./erigon --version`

```
root@e4e439e89b18:/# /erigon_vm  --version
erigon_vm version 3.00.0-dev-f4df7c22
```

OS & Version: Windows/Linux/OSX

Executed as part of `holiman/omnifuzz`, built by goevmlab: https://github.com/holiman/goevmlab/blob/master/docker/Dockerfile#L47 
```
 docker run -it -v /home/user/workspace/goevmlab/evms/testdata/:/testdata  holiman/omnifuzz
```

#### Expected behaviour

Executes statetest fine

#### Actual behaviour
```
root@e4e439e89b18:/# /erigon_vm  --json --nomemory --noreturndata statetest /testdata/cases/eofcode.json 
panic: interface conversion: *mdbx.MdbxTx is not kv.TemporalGetter: missing method DomainGet

goroutine 1 [running]:
github.com/ledgerwatch/erigon/turbo/rpchelper.NewLatestStateReader(...)
	github.com/ledgerwatch/erigon/turbo/rpchelper/helper.go:150
github.com/ledgerwatch/erigon/tests.MakePreState(0xc00119ec88, {0x1bd82b0, 0xc0005f04e0}, 0xc00128e4e0, 0x1, 0x1)
	github.com/ledgerwatch/erigon/tests/state_test_util.go:330 +0xc34
github.com/ledgerwatch/erigon/tests.(*StateTest).RunNoVerify(0xc00119f1d0, {0x1bd82b0, 0xc0005f04e0}, {{0xc000684f72?, 0x27bd820?}, 0xc00119eec0?}, {0x1, {0x1bc6f78, 0xc000a21db8}, 0x0, ...})
	github.com/ledgerwatch/erigon/tests/state_test_util.go:197 +0x205
github.com/ledgerwatch/erigon/tests.(*StateTest).Run(0xc00119f1d0, {0x1bd82b0?, 0xc0005f04e0?}, {{0xc000684f72?, 0x1000?}, 0x0?}, {0x1, {0x1bc6f78, 0xc000a21db8}, 0x0, ...})
	github.com/ledgerwatch/erigon/tests/state_test_util.go:166 +0x8d
main.aggregateResultsFromStateTests(0xc0010ffb90, {0x1, {0x1bc6f78, 0xc000a21db8}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	github.com/ledgerwatch/erigon/cmd/evm/staterunner.go:152 +0x7ad
main.runStateTest({0x7ffdab10bdd9?, 0x0?}, {0x1, {0x1bc6f78, 0xc000a21db8}, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	github.com/ledgerwatch/erigon/cmd/evm/staterunner.go:112 +0xbe
main.stateTestCmd(0xc000525740)
	github.com/ledgerwatch/erigon/cmd/evm/staterunner.go:84 +0x5d3
github.com/urfave/cli/v2.(*Command).Run(0x26e9900, 0xc000525740, {0xc001292360, 0x2, 0x2})
	github.com/urfave/cli/v2@v2.27.2/command.go:276 +0x97d
github.com/urfave/cli/v2.(*Command).Run(0xc0000ff1e0, 0xc000524f80, {0xc0000401e0, 0x6, 0x6})
	github.com/urfave/cli/v2@v2.27.2/command.go:269 +0xbb7
github.com/urfave/cli/v2.(*App).RunContext(0xc0005c7400, {0x1bbf5e0, 0x2828de0}, {0xc0000401e0, 0x6, 0x6})
	github.com/urfave/cli/v2@v2.27.2/app.go:333 +0x58b
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.27.2/app.go:307
main.main()
	github.com/ledgerwatch/erigon/cmd/evm/main.go:193 +0x45
```

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
fixed in https://github.com/ledgerwatch/erigon/pull/10305
