### ISSUE TITLE
staticFilesInRange can't find .efi 

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#10635]
got today on mainnet
```
[INFO] [06-06|04:36:52.326] [snapshots] PruneSmallBatches finished   took=26.728598478s stat="accounts| 592201 kv's step 1041-1041; vii 1553666 txs and 5477377 vals in 1626.56M-1628.12M; code| 34348 kv's step 1039-1041; vii 11196 txs and 12070 vals in 1626.56M-1628.12M; commitment| 3844109 kv's step 1041-1041; storage| ii 943514 txs and 3829104 vals in 1626.56M-1628.12M; logaddrs| ii 943422 txs and 1438561 vals in 1626.56M-1628.12M; logtopics| ii 943422 txs and 4838205 vals in 1626.56M-1628.12M; tracesfrom| ii 634458 txs and 1069017 vals in 1627.48M-1628.12M; tracesto| ii 660979 txs and 1574035 vals in 1627.46M-1628.12M"
[INFO] [06-06|04:36:52.336] [7/15 Execution] Transaction replay      blk=14924932 tx/s=2.6 buffer=26.1MB/1.0GB stepsInDB=1.00 step=1043.1 alloc=8.4GB sys=10.7GB
[INFO] [06-06|04:37:00.910] [snapshots] aggregated                   step=1042 took=55.372672856s
[INFO] [06-06|04:37:00.910] [snapshots] merge state accounts(val:1040-1042, hist:1040-1042, idx:1040-1042), storage(val:1024-1040, hist:1040-1042, idx:1040-1042), code(val:1024-1040, hist:1024-1040, idx:1024-1040), commitment(val:1024-1040), logAddr=1024-1040, logTopic=1024-1040, traceFrom=1024-1040, traceTo=1024-1040
[INFO] [06-06|04:37:05.546] [7/15 Execution] Transaction replay      blk=14925363 tx/s=5579.2 buffer=41.8MB/1.0GB stepsInDB=1.00 step=1043.1 alloc=5.6GB sys=10.7GB
[INFO] [06-06|04:37:25.540] [7/15 Execution] Transaction replay      blk=14926116 tx/s=6799.9 buffer=69.5MB/1.0GB stepsInDB=1.00 step=1043.2 alloc=5.4GB sys=10.7GB
[INFO] [06-06|04:37:45.581] [7/15 Execution] Transaction replay      blk=14926912 tx/s=7027.5 buffer=97.8MB/1.0GB stepsInDB=1.00 step=1043.3 alloc=5.0GB sys=10.7GB
[INFO] [06-06|04:38:05.544] [7/15 Execution] Transaction replay      blk=14927745 tx/s=7680.4 buffer=124.3MB/1.0GB stepsInDB=1.00 step=1043.4 alloc=8.0GB sys=10.7GB
[INFO] [06-06|04:38:25.556] [7/15 Execution] Transaction replay      blk=14928536 tx/s=7352.3 buffer=150.7MB/1.0GB stepsInDB=1.00 step=1043.5 alloc=7.2GB sys=10.8GB
[INFO] [06-06|04:38:45.558] [7/15 Execution] Transaction replay      blk=14929321 tx/s=6921.1 buffer=176.8MB/1.0GB stepsInDB=1.00 step=1043.6 alloc=6.5GB sys=10.8GB
[INFO] [06-06|04:39:01.940] [mem] memory stats                       Rss=60.8GB Size=0B Pss=60.4GB SharedClean=751.0MB SharedDirty=0B PrivateClean=50.5GB PrivateDirty=9.6GB Referenced=60.8GB Anonymous=9.6GB Swap=0B alloc=8.2GB sys=10.8GB
[INFO] [06-06|04:39:05.541] [7/15 Execution] Transaction replay      blk=14930033 tx/s=6161.4 buffer=199.5MB/1.0GB stepsInDB=1.00 step=1043.7 alloc=5.5GB sys=10.8GB
[INFO] [06-06|04:39:25.558] [7/15 Execution] Transaction replay      blk=14930859 tx/s=7160.0 buffer=228.6MB/1.0GB stepsInDB=1.00 step=1043.8 alloc=7.9GB sys=10.8GB
[INFO] [06-06|04:39:45.550] [7/15 Execution] Transaction replay      blk=14931605 tx/s=6485.0 buffer=254.8MB/1.0GB stepsInDB=1.00 step=1043.8 alloc=7.0GB sys=10.8GB
[INFO] [06-06|04:40:05.544] [7/15 Execution] Transaction replay      blk=14932267 tx/s=5671.6 buffer=278.8MB/1.0GB stepsInDB=1.00 step=1043.9 alloc=5.9GB sys=10.8GB
[INFO] [06-06|04:40:25.555] [7/15 Execution] Transaction replay      blk=14932909 tx/s=5502.2 buffer=302.5MB/1.0GB stepsInDB=1.00 step=1044.0 alloc=6.2GB sys=10.8GB
[INFO] [06-06|04:40:50.615] [applying step 1043][agg] computing trie progress=65k/2557k alloc=7.0GB sys=11.1GB
[INFO] [06-06|04:41:10.615] [applying step 1043][agg] computing trie progress=117k/2557k alloc=5.7GB sys=11.1GB

[INFO] [06-06|04:41:30.615] [applying step 1043][agg] computing trie progress=199k/2557k alloc=7.8GB sys=11.1GB
[INFO] [06-06|04:41:50.615] [applying step 1043][agg] computing trie progress=285k/2557k alloc=7.4GB sys=11.1GB
[INFO] [06-06|04:42:02.141] [mem] memory stats                       Rss=83.7GB Size=0B Pss=83.3GB SharedClean=824.1MB SharedDirty=0B PrivateClean=72.6GB PrivateDirty=10.3GB Referenced=83.6GB Anonymous=10.3GB Swap=0B alloc=8.8GB sys=11.1GB
[INFO] [06-06|04:42:10.614] [applying step 1043][agg] computing trie progress=380k/2557k alloc=8.4GB sys=11.1GB
[INFO] [06-06|04:42:30.614] [applying step 1043][agg] computing trie progress=542k/2557k alloc=5.6GB sys=11.1GB
[INFO] [06-06|04:42:50.615] [applying step 1043][agg] computing trie progress=675k/2557k alloc=5.4GB sys=11.1GB
[INFO] [06-06|04:43:10.616] [applying step 1043][agg] computing trie progress=786k/2557k alloc=8.5GB sys=11.1GB
[INFO] [06-06|04:43:30.615] [applying step 1043][agg] computing trie progress=941k/2557k alloc=5.4GB sys=11.1GB
[INFO] [06-06|04:43:31.204] [snapshots] state merge done accounts(val:1040-1042, hist:1040-1042, idx:1040-1042), storage(val:1024-1040, hist:1040-1042, idx:1040-1042), code(val:1024-1040, hist:1024-1040, idx:1024-1040), commitment(val:1024-1040), logAddr=1024-1040, logTopic=1024-1040, traceFrom=1024-1040, traceTo=1024-1040
[WARN] [06-06|04:43:31.291] lookupFileByItsRange: file not found     stepFrom=1024 stepTo=1032 domain=AccountKeys files=0-1024;1032-1033;1033-1034;1034-1035;1035-1036;1036-1037;1037-1038;1038-1039;1039-1040;1024-1040;1040-1042;1042-1043; _visibleFiles=0-1024;1024-1040;1040-1041;1041-1042; visibleFilesCount=4 filesCount=12
[CRIT] [06-06|04:43:31.291] storage file of steps %d-%d not found
   LOG15_ERROR=
panic: History.staticFilesInRange: required file not found: v1-storage.1024-1032.efi

goroutine 644 [running]:
github.com/ledgerwatch/erigon-lib/state.(*DomainRoTx).staticFilesInRange(0xc000002d80, {0x1, 0x60db8840, 0x610b3748, 0x5f5e1000, 0x60db8840, 0x0, 0x5f5e100, 0x1, 0x1, ...})
	github.com/ledgerwatch/erigon-lib@v1.0.0/state/merge.go:364 +0x2c5
github.com/ledgerwatch/erigon-lib/state.(*AggregatorRoTx).staticFilesInRange(_, {{{0x0, 0x0, 0x0, 0x0, 0x5f5e100, 0x0, 0x5f5e100, 0x0, 0x0, ...}, ...}, ...})
	github.com/ledgerwatch/erigon-lib@v1.0.0/state/aggregator_files.go:61 +0x187
github.com/ledgerwatch/erigon-lib/state.(*Aggregator).mergeLoopStep(0xc00168e000, {0x1efb1b0, 0xc000a33a40})
	github.com/ledgerwatch/erigon-lib@v1.0.0/state/aggregator.go:666 +0x4e5
github.com/ledgerwatch/erigon-lib/state.(*Aggregator).MergeLoop(...)
	github.com/ledgerwatch/erigon-lib@v1.0.0/state/aggregator.go:697
github.com/ledgerwatch/erigon-lib/state.(*Aggregator).BuildFilesInBackground.func1.1()
	github.com/ledgerwatch/erigon-lib@v1.0.0/state/aggregator.go:1653 +0x105
created by github.com/ledgerwatch/erigon-lib/state.(*Aggregator).BuildFilesInBackground.func1 in goroutine 75
	github.com/ledgerwatch/erigon-lib@v1.0.0/state/aggregator.go:1646 +0x507
```

**Comment by AskAlexSharov** [comment]
I think it's because merge can look into dirty files, but dirty files can don't have indices yet - which is normal.

**Comment by awskii** [comment]
but in this case it seems that bigger range has been aggregated already and 1024-1040 already available and files 32-40 are available as well while 24-32 has been removed steps before.
