### ISSUE TITLE
Cant start erigon with internalcl

### ISSUE THREAD

**Issue by nanahos** [ledgerwatch/erigon#10668]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Erigon's discord](https://github.com/ledgerwatch/erigon#erigon-discord-server).
erigon version : 2.60.0-rc1-32f7775c
os &version : ubuntu 22.04.4 LTS
erigon command : @myserver:~/erigon$ ./build/bin/erigon --internalcl --http.vhosts="*" --http.addr="0.0.0.0" --http.api=eth,web3,net,debug,trace,txpool

I Tried to excute erigon with internalcl 
but always that make error situation 
if i triy without internalcl but it is operate block 1900000 but it is not synce...
how solve tahat problem 

goroutine 11080 [IO wait]:
runtime.gopark(0x46a7bc?, 0xb?, 0x0?, 0x0?, 0x282?)
        runtime/proc.go:398 +0xce fp=0xc087f78b08 sp=0xc087f78ae8 pc=0x4632ce
runtime.netpollblock(0x4ec558?, 0x42ba86?, 0x0?)
        runtime/netpoll.go:564 +0xf7 fp=0xc087f78b40 sp=0xc087f78b08 pc=0x45b9b7
internal/poll.runtime_pollWait(0x72dc345e9d00, 0x72)
        runtime/netpoll.go:343 +0x85 fp=0xc087f78b60 sp=0xc087f78b40 pc=0x490de5
internal/poll.(*pollDesc).wait(0xc0875b2a00?, 0xc08830fc08?, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc087f78b88 sp=0xc087f78b60 pc=0x50a2c7
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0875b2a00, {0xc08830fc08, 0x1, 0x1})
        internal/poll/fd_unix.go:164 +0x27a fp=0xc087f78c20 sp=0xc087f78b88 pc=0x50b5ba
net.(*netFD).Read(0xc0875b2a00, {0xc08830fc08?, 0xc08832b5c0?, 0x72dc7f0d9a68?})
        net/fd_posix.go:55 +0x25 fp=0xc087f78c68 sp=0xc087f78c20 pc=0x6056a5
net.(*conn).Read(0xc099ebe9e8, {0xc08830fc08?, 0x23e2a40?, 0x435001?})
        net/net.go:179 +0x45 fp=0xc087f78cb0 sp=0xc087f78c68 pc=0x618425
go:(*struct { *net.TCPConn; github.com/multiformats/go-multiaddr/net.maEndpoints }).Read(0x10?, {0xc08830fc08?, 0xc087f78da8?, 0x66d8f3fdaf00?})
        <autogenerated>:1 +0x26 fp=0xc087f78ce0 sp=0xc087f78cb0 pc=0x18a41a6
github.com/multiformats/go-multistream.(*byteReader).ReadByte(0xc0883526b0)
        github.com/multiformats/go-multistream@v0.4.1/multistream.go:322 +0x4d fp=0xc087f78d18 sp=0xc087f78ce0 pc=0x1866e4d
github.com/multiformats/go-varint.ReadUvarint({0x3135a40, 0xc0883526b0})
        github.com/multiformats/go-varint@v0.0.7/varint.go:80 +0x51 fp=0xc087f78d60 sp=0xc087f78d18 pc=0x182b991
github.com/multiformats/go-multistream.lpReadBuf({0x66dbcbf15d40?, 0xc088365530})
        github.com/multiformats/go-multistream@v0.4.1/multistream.go:286 +0x8f fp=0xc087f78dc8 sp=0xc087f78d60 pc=0x1866c6f
github.com/multiformats/go-multistream.ReadNextTokenBytes({0x66dbcbf15d40?, 0xc088365530?})
        github.com/multiformats/go-multistream@v0.4.1/multistream.go:269 +0x25 fp=0xc087f78e00 sp=0xc087f78dc8 pc=0x1866b45
github.com/multiformats/go-multistream.ReadNextToken[...](...)
        github.com/multiformats/go-multistream@v0.4.1/multistream.go:258
github.com/multiformats/go-multistream.readMultistreamHeader({0x66dbcbf15d40?, 0xc088365530?})
        github.com/multiformats/go-multistream@v0.4.1/client.go:331 +0x25 fp=0xc087f78e48 sp=0xc087f78e00 pc=0x1866485
github.com/multiformats/go-multistream.SelectWithSimopenOrFail[...]({0xc0824d9780, 0x1?, 0x1}, {0x66dbcbf15d10, 0xc088365530?})
        github.com/multiformats/go-multistream@v0.4.1/client.go:141 +0x1af fp=0xc087f78f20 sp=0xc087f78e48 pc=0x19a658f
github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity.func1()
        github.com/libp2p/go-libp2p@v0.31.0/p2p/net/upgrader/upgrader.go:328 +0x133 fp=0xc087f78fe0 sp=0xc087f78f20 pc=0x19a4a53
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc087f78fe8 sp=0xc087f78fe0 pc=0x496c21
created by github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity in goroutine 10881
        github.com/libp2p/go-libp2p@v0.31.0/p2p/net/upgrader/upgrader.go:319 +0xfb

**Comment by awskii** [comment]
Hello @nanahos, thanks for report! can you tell more about what happened? This is part of trace which highly likely not related to core issue. 

Have you executed blocks with internalcl before? or you starting existing node synced with some CL provider (lighthouse eg) and then tried to use Caplin via --internalcl? 

Full log would be appreciated

**Comment by AskAlexSharov** [comment]
closing due to inactivity. feel free to re-open if need.
