### ISSUE TITLE
e3 - Panic on genesis sync

### ISSUE THREAD

**Issue by wmitsuda** [ledgerwatch/erigon#10717]
I tried to do genesis sync (no snapshots) on e3 sepolia + external CL (LH) and it crashed.

Using commit from main: `53c817bb996398bd9c2cd4fbf2640ceee6f0ef7b`.

CLI: `~/erigon/build/bin/erigon --datadir /mnt/erigon-e3-sepolia/erigon --chain sepolia --no-downloader --torrent.upload.rate=100k --http.api "eth,net,erigon,ots" --ws --http.addr "0.0.0.0" --http.vhosts "*" --http.corsdomain "*" --externalcl`

```
INFO[06-12|06:08:57.879] Timings: Post-Forkchoice (slower than 50ms) Prune Snapshots=59ms
INFO[06-12|06:08:58.294] [sync] limited big jump                  from=100000 amount=5000
INFO[06-12|06:08:58.371] [3/12 Senders] Started                   from=100000 to=105000
INFO[06-12|06:08:58.414] [4/12 Execution] starting                from=100001 to=105000 fromTxNum=200003 offsetFromBlo
ckBeginning=0 initialCycle=true useExternalTx=true
INFO[06-12|06:08:58.549] RPC Daemon notified of new headers       from=103976 to=105000 amount=1024 hash=0x083b2b4ee33
4d3f9cdd72ac9afaca8b7029b3ca0551a2927014e4193c9ba9f48 header sending=771.083µs log sending=261ns
INFO[06-12|06:08:58.549] head updated                             number=105000 hash=0x083b2b4ee334d3f9cdd72ac9afaca8b
7029b3ca0551a2927014e4193c9ba9f48
INFO[06-12|06:08:58.549] Timings (slower than 50ms)               Execution=124ms commit=1.321442ms alloc=6.4GB sys=12
.1GB
INFO[06-12|06:08:58.912] [sync] limited big jump                  from=105000 amount=5000
INFO[06-12|06:08:58.992] [3/12 Senders] Started                   from=105000 to=110000
INFO[06-12|06:08:59.026] [4/12 Execution] starting                from=105001 to=110000 fromTxNum=210003 offsetFromBlo
ckBeginning=0 initialCycle=true useExternalTx=true
INFO[06-12|06:08:59.208] RPC Daemon notified of new headers       from=108976 to=110000 amount=1024 hash=0xc1a9c887752
2f0313baad02773c21440347a48691ba4d3c6c4f14a671e666b09 header sending=1.56355ms log sending=310ns
INFO[06-12|06:08:59.209] head updated                             number=110000 hash=0xc1a9c8877522f0313baad02773c2144
0347a48691ba4d3c6c4f14a671e666b09
INFO[06-12|06:08:59.209] Timings (slower than 50ms)               Execution=153ms commit=1.916117ms alloc=6.6GB sys=12
.1GB
INFO[06-12|06:08:59.810] [sync] limited big jump                  from=110000 amount=5000
panic:

goroutine 10229391 [running]:
github.com/ledgerwatch/erigon/eth/consensuschain.Reader.GetBlock(...)
        github.com/ledgerwatch/erigon/eth/consensuschain/consensus_chain_reader.go:67
github.com/ledgerwatch/erigon/consensus/ethash.getUncles({0x31f8aa0, 0xc0aa582300}, 0xc0aa592580)
        github.com/ledgerwatch/erigon/consensus/ethash/consensus.go:169 +0x1ca
github.com/ledgerwatch/erigon/consensus/ethash.(*Ethash).VerifyUncles(0xc1ba5d8540?, {0x31f8aa0?, 0xc0aa582300}, 0xdf0
61d07fd2c8d34?, {0xc145672118, 0x1, 0x9ee4ec67b7d3e375?})
        github.com/ledgerwatch/erigon/consensus/ethash/consensus.go:144 +0x7d
github.com/ledgerwatch/erigon/consensus/merge.(*Merge).VerifyUncles(0xc00169e390, {0x31f8aa0, 0xc0aa582300}, 0xc0aa592
580, {0xc145672118, 0x1, 0x1})
        github.com/ledgerwatch/erigon/consensus/merge/merge.go:103 +0xe4
github.com/ledgerwatch/erigon/turbo/execution/eth1.(*EthereumExecutionModule).updateForkChoice(0xc000826a00, {0x31de3c
8, 0xc001809810}, {0x33, 0x93, 0xf4, 0x8f, 0xc4, 0x67, 0x2a, ...}, ...)
        github.com/ledgerwatch/erigon/turbo/execution/eth1/forkchoice.go:319 +0x1997
created by github.com/ledgerwatch/erigon/turbo/execution/eth1.(*EthereumExecutionModule).UpdateForkChoice in goroutine
 10540
        github.com/ledgerwatch/erigon/turbo/execution/eth1/forkchoice.go:96 +0x32b

```

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/10732
