### ISSUE TITLE
Erigon and integration command log: unable to parse PSI data

### ISSUE THREAD

**Issue by MrFreezeDZ** [ledgerwatch/erigon#10735]
#### System information

Erigon version: `./erigon --version` 2.60.0 and 2.60.1

OS & Version: Windows/Linux/OSX
Docker Image from https://hub.docker.com/r/thorax/erigon running in GKE

Commit hash for version 2.60.0: 7883a4e3c99a22ccc826906f7ecdab61afee74f8

Erigon Command (with flags/config):
We use a pruned node here which has all prune flags set to a specific block from last year. Right now I am not able to deliver the full command, but if it is necessary I will provide the full command later.

Chain/Network: 
bor-mainnet 

#### Expected behaviour
We are able to use the integration command and run erigon after using the newer image.

#### Actual behaviour
The integration command and the erigon command produce error messages containing following lines:
```
time="2024-06-13T09:39:43Z" level=error msg="unable to parse PSI data: read /sys/fs/cgroup/cpu.pressure: operation not supported"
time="2024-06-13T09:39:43Z" level=error msg="unable to parse PSI data: read /sys/fs/cgroup/memory.pressure: operation not supported"
```
and:
```
panic: fail to open mdbx: create table: BorCheckpointEnds, mdbx_dbi_open: MDBX_NOTFOUND: No matching key/data pair found
```

#### Steps to reproduce the behaviour
We saw the problem after upgrading to version 2.60.1 from 2.59.3

We run this erigon instance in Google Kubernetes Engine in version 2.59.3. In our helm chart is a runInDebug flag that starts the erigon image but with a very long sleep: 
```yaml
          {{ if eq .Values.erigon.startInDebug true }}
          command: ["/bin/sh", "-c", "exec /bin/sh -c 'trap : TERM INT; sleep 9999999999d & wait'"]
          {{ else }}
```
When we upgrade to the image version 2.60.0 or 2.60.1 and start the image with our sleep command we can reproduce the behavior with the integration command.

Without our sleep command erigon starts with all parameters which directly reproduces the bahavior.

#### Backtrace

integration command prints the following error:
```
/ $ integration print_stages --datadir=/data --chain=bor-mainnet
ERRO[0000] unable to parse PSI data: read /sys/fs/cgroup/cpu.pressure: operation not supported 
ERRO[0000] unable to parse PSI data: read /sys/fs/cgroup/memory.pressure: operation not supported 
ERRO[0000] unable to parse PSI data: read /sys/fs/cgroup/io.pressure: operation not supported 
ERRO[0000] unable to parse PSI data: read /sys/fs/cgroup/cpu.pressure: operation not supported 
ERRO[0000] unable to parse PSI data: read /sys/fs/cgroup/memory.pressure: operation not supported 
ERRO[0000] unable to parse PSI data: read /sys/fs/cgroup/io.pressure: operation not supported 
INFO[06-13|09:33:12.673] logging to file system                   log dir=/data/logs file prefix=integration log level=info json=false
ERRO[0000] unable to parse PSI data: read /sys/fs/cgroup/cpu.pressure: operation not supported 
ERRO[0000] unable to parse PSI data: read /sys/fs/cgroup/memory.pressure: operation not supported 
ERRO[0000] unable to parse PSI data: read /sys/fs/cgroup/io.pressure: operation not supported 
INFO[06-13|09:33:12.692] [db] open                                label=chaindata sizeLimit=12TB pageSize=16384
panic: fail to open mdbx: create table: BorCheckpointEnds, mdbx_dbi_open: MDBX_NOTFOUND: No matching key/data pair found

goroutine 1 [running]:
github.com/ledgerwatch/erigon-lib/kv/mdbx.MdbxOpts.MustOpen({{0x1e515d0, 0xc001380000}, 0xc000f42000, 0x1c4ed20, {0xc000e9f2d0, 0xf}, 0x0, 0x20000000000, 0x80000000, 0xffffffffffffffff, ...})
        github.com/ledgerwatch/erigon-lib@v1.0.0/kv/mdbx/kv_mdbx.go:465 +0xc5
github.com/ledgerwatch/erigon/cmd/integration/commands.openDB({{0x1e515d0, 0xc001380000}, 0xc000f42000, 0x1c4ed20, {0xc000e9f2d0, 0xf}, 0x0, 0x20000000000, 0x80000000, 0xffffffffffffffff, ...}, ...)
        github.com/ledgerwatch/erigon/cmd/integration/commands/root.go:75 +0x78
github.com/ledgerwatch/erigon/cmd/integration/commands.glob..func22(0x2aa4d40, {0x19af8bf?, 0x4?, 0x19af75b?})
        github.com/ledgerwatch/erigon/cmd/integration/commands/stages.go:323 +0xea
github.com/spf13/cobra.(*Command).execute(0x2aa4d40, {0xc000a77cc0, 0x2, 0x2})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x2aa41c0)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(0x4678dc?, {0x1e478d0?, 0xc000ea8d20?})
        github.com/spf13/cobra@v1.8.0/command.go:1032 +0x47
main.main()
        github.com/ledgerwatch/erigon/cmd/integration/main.go:18 +0xe6
```

The logs when starting erigon contain the similar looking errors like this:
```
$ kubectl logs -n polygon erigon-594f8564c7-kktjb -f
time="2024-06-13T09:39:33Z" level=error msg="unable to parse PSI data: read /sys/fs/cgroup/cpu.pressure: operation not supported"
time="2024-06-13T09:39:33Z" level=error msg="unable to parse PSI data: read /sys/fs/cgroup/memory.pressure: operation not supported"
time="2024-06-13T09:39:33Z" level=error msg="unable to parse PSI data: read /sys/fs/cgroup/io.pressure: operation not supported"
time="2024-06-13T09:39:33Z" level=error msg="unable to parse PSI data: read /sys/fs/cgroup/cpu.pressure: operation not supported"
time="2024-06-13T09:39:33Z" level=error msg="unable to parse PSI data: read /sys/fs/cgroup/memory.pressure: operation not supported"
time="2024-06-13T09:39:33Z" level=error msg="unable to parse PSI data: read /sys/fs/cgroup/io.pressure: operation not supported"
{"file prefix":"erigon","json":false,"log dir":"/data/logs","log level":"info","lvl":"info","msg":"logging to file system","t":"2024-06-13T09:39:33.358443066Z"}
{"git_branch":"heads/v2.60.0","git_commit":"7883a4e3c99a22ccc826906f7ecdab61afee74f8","git_tag":"v2.60.0-dirty","lvl":"info","msg":"Build info","t":"2024-06-13T09:39:33.363302776Z"}
{"lvl":"info","msg":"Starting Erigon on Bor Mainnet...","t":"2024-06-13T09:39:33.363361966Z"}
{"ETH":500,"lvl":"info","msg":"Maximum peer count","t":"2024-06-13T09:39:33.365012856Z","total":500}
{"APIs":"eth,admin,debug,net,trace,web3,erigon,txpool","lvl":"info","msg":"starting HTTP APIs","port":8545,"t":"2024-06-13T09:39:33.365170566Z"}
{"level":"WRN","lvl":"info","msg":"torrent verbosity","t":"2024-06-13T09:39:33.365435516Z"}
{"cap":50000000,"lvl":"info","msg":"Set global gas cap","t":"2024-06-13T09:39:35.469668935Z"}
{"download.rate":"300mb","ipv4-enabled":true,"ipv6-enabled":true,"lvl":"info","msg":"[Downloader] Running with","t":"2024-06-13T09:39:35.471299634Z","upload.rate":"4mb"}
{"label":"chaindata","lvl":"info","msg":"Opening Database","path":"/data/chaindata","t":"2024-06-13T09:39:35.471429885Z"}
{"label":"chaindata","lvl":"info","msg":"[db] open","pageSize":16384,"sizeLimit":"12TB","t":"2024-06-13T09:39:35.505148882Z"}
{"lvl":"info","msg":"Re-Opening DB in exclusive mode to apply migrations","t":"2024-06-13T09:39:35.533052448Z"}
{"label":"chaindata","lvl":"info","msg":"[db] open","pageSize":16384,"sizeLimit":"12TB","t":"2024-06-13T09:39:35.541826448Z"}
{"lvl":"info","msg":"Apply migration","name":"prohibit_new_downloads_lock2","t":"2024-06-13T09:39:35.542245308Z"}
{"lvl":"info","msg":"Applied migration","name":"prohibit_new_downloads_lock2","t":"2024-06-13T09:39:35.552063037Z"}
{"lvl":"info","msg":"Updated DB schema to","t":"2024-06-13T09:39:35.552117797Z","version":"6.1.0"}
{"label":"chaindata","lvl":"info","msg":"[db] open","pageSize":16384,"sizeLimit":"12TB","t":"2024-06-13T09:39:35.558851526Z"}
{"lvl":"warn","msg":"Sanitizing invalid bor miner gas price","provided":"1000000000","t":"2024-06-13T09:39:35.678743295Z","updated":"30000000000"}
{"lvl":"warn","msg":"Sanitizing invalid bor min fee cap","provided":1,"t":"2024-06-13T09:39:35.678852675Z","updated":30000000000}
{"config":"{ChainID: 137, Homestead: 0, DAO: \u003cnil\u003e, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: \u003cnil\u003e, Gray Glacier: \u003cnil\u003e, Terminal Total Difficulty: \u003cnil\u003e, Merge Netsplit: \u003cnil\u003e, Shanghai: \u003cnil\u003e, Cancun: \u003cnil\u003e, Prague: \u003cnil\u003e, Osaka: \u003cnil\u003e, Engine: bor, NoPruneContracts: map[]}","genesis":"0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b","lvl":"info","msg":"Initialised chain configuration","t":"2024-06-13T09:39:35.678909105Z"}
time="2024-06-13T09:39:43Z" level=error msg="unable to parse PSI data: read /sys/fs/cgroup/cpu.pressure: operation not supported"
time="2024-06-13T09:39:43Z" level=error msg="unable to parse PSI data: read /sys/fs/cgroup/memory.pressure: operation not supported"
time="2024-06-13T09:39:43Z" level=error msg="unable to parse PSI data: read /sys/fs/cgroup/io.pressure: operation not supported"
```

**Comment by AskAlexSharov** [comment]
`integration run_migrations`

**Comment by MrFreezeDZ** [comment]
Thanks that fixed our problem.
