### ISSUE TITLE
dl: nil ptr during numPieces check

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#10811]
`main`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe6fbf2]

goroutine 577607 [running]:
github.com/anacrolix/torrent/metainfo.(*Info).NumPieces(...)
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-10/metainfo/info.go:134
github.com/anacrolix/torrent.(*Torrent).numPieces(...)
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-10/torrent.go:888
github.com/anacrolix/torrent.(*Torrent).NumPieces(...)
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-10/t.go:84
github.com/anacrolix/torrent.requestUpdate(0xc0318f6f08)
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-10/webseed-peer.go:237 +0x52
github.com/anacrolix/torrent.(*webseedPeer).requester.func2()
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-10/webseed-peer.go:219 +0x17
created by time.goFunc
```

**Comment by AskAlexSharov** [comment]
seems fixed
