### ISSUE TITLE
dl: prints in logs `client` object

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#10993]
happens here: 
```

goroutine 5662 [running]:
github.com/anacrolix/torrent.(*Peer).writeStatus(...)
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-9.0.20240703034519-7de3cf068d4d/peer.go:308
github.com/anacrolix/torrent.(*Torrent).writePeerStatuses(0x503b2c0?, {0x503b2c0, 0xc04c883480}, {0xc05620ee38, 0x1, 0x1?}, 0x1?)
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-9.0.20240703034519-7de3cf068d4d/torrent.go:975 +0xe5
github.com/anacrolix/torrent.(*Torrent).writeStatus(0xc03eb45008, {0x503b2c0, 0xc04c883480})
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-9.0.20240703034519-7de3cf068d4d/torrent.go:965 +0x4a7
github.com/anacrolix/torrent.(*Client).WriteStatus(0xc000581808, {0x503d980, 0xc04c8b9c50})
	/home/ubuntu/go/pkg/mod/github.com/erigontech/torrent@v1.54.2-alpha-9.0.20240703034519-7de3cf068d4d/client.go:183 +0xb6a
github.com/ledgerwatch/erigon-lib/downloader.getProgressStatus(0xc000581808, {0xc0451b9608, 0x58, 0x17?})
	/home/ubuntu/erigon/erigon-lib/downloader/downloader.go:2302 +0x1c5
github.com/ledgerwatch/erigon-lib/downloader.(*Downloader).ReCalcStats(0xc00015a820, 0x2540be400)
	/home/ubuntu/erigon/erigon-lib/downloader/downloader.go:2211 +0x382a
github.com/ledgerwatch/erigon-lib/downloader.(*GrpcServer).Add(0xc000094d28, {0x5059ae0, 0xc000a64eb0}, 0xc04c52ab80)
	/home/ubuntu/erigon/erigon-lib/downloader/downloader_grpc_server.go:85 +0xbb3
github.com/ledgerwatch/erigon-lib/direct.(*DownloaderClient).Add(0xc03ecfeee0, {0x5059ae0, 0xc000a64eb0}, 0xc04c52ab80, {0xc04c8062d0?, 0x42ecbe?, 0xc0017bc180?})
	/home/ubuntu/erigon/erigon-lib/direct/downloader_client.go:36 +0x5c
github.com/ledgerwatch/erigon/turbo/snapshotsync.RequestSnapshotsDownload({0x5059ae0, 0xc000a64eb0}, {0xc04c52c008, 0x3c, 0xb2}, {0x5060240, 0xc03ecfeee0})
	/home/ubuntu/erigon/turbo/snapshotsync/snapshotsync.go:85 +0x87
github.com/ledgerwatch/erigon/turbo/snapshotsync.WaitForDownloader({0x5059ae0, 0xc000a64eb0}, {0xc0232b69c3, 0xd}, 0x1, 0x1, {0x1, {0x50605c0, 0xc000da5cf8}, {0x50605c0, ...}, ...}, ...)
	/home/ubuntu/erigon/turbo/snapshotsync/snapshotsync.go:357 +0xe51
github.com/ledgerwatch/erigon/eth/stagedsync.DownloadAndIndexSnapshotsIfNeed(_, {_, _}, {_, _}, {{0x5070d50, 0xc035c30000}, {{0xc000c99629, 0x7}, 0xc000a07640, ...}, ...}, ...)
	/home/ubuntu/erigon/eth/stagedsync/stage_snapshots.go:266 +0xeb9
github.com/ledgerwatch/erigon/eth/stagedsync.SpawnStageSnapshots(_, {_, _}, {_, _}, {{0x5070d50, 0xc035c30000}, {{0xc000c99629, 0x7}, 0xc000a07640, ...}, ...}, ...)
	/home/ubuntu/erigon/eth/stagedsync/stage_snapshots.go:175 +0x1cf
github.com/ledgerwatch/erigon/eth/stagedsync.PipelineStages.func1(0x0, 0xc04c50aa20, {0x0?, 0x731ec89fd348?}, {{0x0, 0x0}, {0x0, 0x0}, 0x0}, {0x506f8c8, ...})
	/home/ubuntu/erigon/eth/stagedsync/default_stages.go:199 +0x153
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc0440858c0, 0xc0421b08c0, {0x5070d50, 0xc035c30000}, {{0x0, 0x0}, {0x0, 0x0}, 0x0}, 0x1, ...)
```

at this time: 
```
[dbg] before write status
[dbg] after write status
before print debug logs
    0.000000% of 92889249 bytes (93 MB)
    Infohash: f52bab195f716f4cf6ca49101f6631ad2825d241
    Metadata length: 993
    Piece length: 2097152 (0.25 chunks)
    Num Pieces: 45 (0 completed)
    Piece States: 45.?
    Piece availability frequency: 10: 45
    Reader Pieces:
    Enabled trackers:
```

it's very big and looks like: 
```
      last msg: 0.29s ago, connected: 2391.62s ago, last helpful: never, itime: 39m51.60210094s, etime: 14.374266ms
      40/40 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eI-, dr: 0.0 KiB/s
      requested pieces:
    - 51.178.78.133:42069-194.53.86.16:65368
      peer id: "-GT0003-\x16\x89\u047b\x11\xc0\xd6qt\xba\x18\xc7"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 11 unsent events
      bep40-prio: 4cc95ea4
      last msg: 27.61s ago, connected: 2390.30s ago, last helpful: never, itime: 39m50.269525027s, etime: 32.915556ms
      40/40 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eI-, dr: 0.0 KiB/s
      requested pieces:
    - 51.178.78.133:42069-62.12.164.254:64583
      peer id: "-GT0003-\xa8\xff\xc54\x96\xbc\xe7\x04\a\xcd\xf0\x01"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 11 unsent events
      bep40-prio: 4c2da8dc
      last msg: 50.07s ago, connected: 2502.55s ago, last helpful: never, itime: 41m41.872800598s, etime: 41.488777ms
      40/40 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eI-, dr: 0.0 KiB/s
      requested pieces:
    - 51.178.78.133:42069-129.146.160.64:59284
      peer id: "-GT0003-\xc4\r\xcc\xec\xef\xab\x11\x7f\xce^,i"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 11 unsent events
      bep40-prio: 44a3ecce
      last msg: 44.29s ago, connected: 2453.42s ago, last helpful: never, itime: 40m53.267713215s, etime: 155.371453ms
      40/40 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eI-, dr: 0.0 KiB/s
      requested pieces:
    - 0.0.0.0:42069-147.28.178.133:42069
      peer id: "-GT0003-\x8c\xdd\xfe7\xa6\xcb\x15*\xafe4~"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 11 unsent events
      bep40-prio: 3b2839c2
      last msg: 16.72s ago, connected: 2479.86s ago, last helpful: never, itime: 41m19.346076897s, etime: 0s
      40/40 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eIU-, dr: 0.0 KiB/s
      requested pieces:
    - 51.178.78.133:42069-3.89.89.75:40916
      peer id: "-GT0003-t\x1c\x1b\xc5J\xe01\x14\x9f\x8e\xd9;"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 11 unsent events
      bep40-prio: 347720f1
      last msg: 13.00s ago, connected: 2491.36s ago, last helpful: never, itime: 41m31.275699733s, etime: 88.637138ms
      40/40 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eI-, dr: 0.0 KiB/s
      requested pieces:
    - 51.178.78.133:42069-163.114.159.81:43342
      peer id: "-GT0003-\xf2D\x7fT\xc9\xefI\xfd\t\x88\xc5d"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 11 unsent events
      bep40-prio: 013f9b0c
      last msg: 39.87s ago, connected: 2361.94s ago, last helpful: never, itime: 39m21.926099429s, etime: 11.821151ms
      40/40 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eI-, dr: 0.0 KiB/s
      requested pieces:
    0.000000% of 48408635 bytes (48 MB)
    Infohash: 7f79e789d107b519534d1ecafb1c05ca147d321a
    Metadata length: 573
    Piece length: 2097152 (0.25 chunks)
    Num Pieces: 24 (0 completed)
    Piece States: 24.?
    Piece availability frequency: 10: 24
    Reader Pieces:
    Enabled trackers:
        URL                                                Extra
        "udp4://open.stealth.si:80/announce"               next ann: 14m16s, last ann: 0 peers
        "udp4://opentracker.i2p.rocks:6969/announce"       next ann: 25s, last ann: error getting ip: lookup opentracker.i2p.rocks on 127.0.0.53:53: no such host
        "udp4://tracker.openbittorrent.com:6969/announce"  next ann: anytime, last ann: announcing: context deadline exceeded
        "udp4://tracker.opentrackr.org:1337/announce"      next ann: 20m6s, last ann: 0 peers
        "udp4://tracker.torrent.eu.org:451/announce"       next ann: 16m40s, last ann: 0 peers
    DHT Announces: 0
    (torrent.TorrentStats) {
     ConnStats: (torrent.ConnStats) {
      BytesWritten: (torrent.Count) 123709,
      BytesWrittenData: (torrent.Count) 0,
      BytesRead: (torrent.Count) 53702,
      BytesReadData: (torrent.Count) 0,
      BytesReadUsefulData: (torrent.Count) 0,
      BytesReadUsefulIntendedData: (torrent.Count) 0,
      ChunksWritten: (torrent.Count) 0,
      ChunksRead: (torrent.Count) 0,
      ChunksReadUseful: (torrent.Count) 0,
      ChunksReadWasted: (torrent.Count) 0,
      MetadataChunksRead: (torrent.Count) 0,
      PiecesDirtiedGood: (torrent.Count) 0,
      PiecesDirtiedBad: (torrent.Count) 0
     },
     TotalPeers: (int) 11,
     PendingPeers: (int) 1,
     ActivePeers: (int) 10,
     ConnectedSeeders: (int) 10,
     HalfOpenPeers: (int) 0,
     PiecesComplete: (int) 0
    }
    webseeds:
    10 peer conns:
    - 51.178.78.133:42069-136.62.73.179:48784
      peer id: "-GT0003-\x86\xd2R\x18\x8c\xa7m\u01e1\x84J\xac"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 12 unsent events
      bep40-prio: ecb534bb
      last msg: 16.32s ago, connected: 2476.23s ago, last helpful: never, itime: 41m16.115457702s, etime: 116.435459ms
      24/24 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eI-, dr: 0.0 KiB/s
      requested pieces:
    - 0.0.0.0:42069-78.56.89.146:42069
      peer id: "-GT0003-\x85\xdb\x7f\xc1\xfeP/d\"Q\x13\x98"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 12 unsent events
      bep40-prio: cde93484
      last msg: 15.36s ago, connected: 2140.74s ago, last helpful: never, itime: 35m40.65168836s, etime: 56.31003ms
      24/24 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eIU-, dr: 0.0 KiB/s
      requested pieces:
    - 0.0.0.0:42069-139.64.137.122:42069
      peer id: "-GT0003-\x9d\x99\x98\x9a\xcd1LS\x1f\xc8N\xfa"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 12 unsent events
      bep40-prio: 7df32bac
      last msg: 19.89s ago, connected: 2206.92s ago, last helpful: never, itime: 36m46.69182916s, etime: 111.620214ms
      24/24 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eIU-, dr: 0.0 KiB/s
      requested pieces:
    - 51.178.78.133:42069-37.59.18.113:29930
      peer id: "-GT0003-\xc9\xca\x163\xb57\x98\xe89\xa3\x1ec"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 12 unsent events
      bep40-prio: 73eeb13d
      last msg: 10.56s ago, connected: 2203.55s ago, last helpful: never, itime: 36m43.542020429s, etime: 5.458324ms
      24/24 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eI-, dr: 0.0 KiB/s
      requested pieces:
    - 0.0.0.0:42069-210.185.60.47:6562
      peer id: "-GT0003-\xbf\xa8\x8bK\x99\x81\x87\x17Y3\xe7q"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 12 unsent events
      bep40-prio: 52bd1772
      last msg: 0.54s ago, connected: 2267.37s ago, last helpful: never, itime: 37m46.733186724s, etime: 320.792622ms
      24/24 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eIU-, dr: 0.0 KiB/s
      requested pieces:
    - 0.0.0.0:42069-194.53.86.16:22976
      peer id: "-GT0003-\x16\x89\u047b\x11\xc0\xd6qt\xba\x18\xc7"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 12 unsent events
      bep40-prio: 4cc95ea4
      last msg: 8.17s ago, connected: 2369.19s ago, last helpful: never, itime: 39m29.123362547s, etime: 68.02798ms
      24/24 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eIU-, dr: 0.0 KiB/s
      requested pieces:
    - 51.178.78.133:42069-34.159.183.8:16396
      peer id: "-GT0003-\xb8\x19\xc4Jy\x1c\xeb\xabe\x19\xd7 "
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 12 unsent events
      bep40-prio: 39c5c41e
      last msg: 37.97s ago, connected: 2337.72s ago, last helpful: never, itime: 38m57.708509275s, etime: 14.231426ms
      24/24 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eI-, dr: 0.0 KiB/s
      requested pieces:
    - 0.0.0.0:42069-34.147.179.92:8192
      peer id: "-GT0003-\u01a2S\xb4\x8f`u\xa8\x11_zk"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 2 conns, 12 unsent events
      bep40-prio: 38cb7e26
      last msg: 15.12s ago, connected: 2178.90s ago, last helpful: never, itime: 36m18.871792927s, etime: 26.1872ms
      24/24 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eIU-, dr: 0.0 KiB/s
      requested pieces:
    - 0.0.0.0:42069-45.93.203.58:43068
      peer id: "-GT0003-jG5\xd0J\xe3\x17\x93\xaa\xf7\x06\x06"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 12 unsent events
      bep40-prio: 2da7a8af
      last msg: 20.45s ago, connected: 2124.71s ago, last helpful: never, itime: 35m24.600318011s, etime: 110.109764ms
      24/24 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eIU-, dr: 0.0 KiB/s
      requested pieces:
    - 0.0.0.0:42069-163.114.159.81:10834
      peer id: "-GT0003-\xfa\xeb\x97\f\xea\x0f\xc9W\x04h\xe5\x18"
      extensions: 0000000000100005 (ltep, fast, dht)
      ltep extensions: map[ut_holepunch:3 ut_metadata:1 ut_pex:2]
      pex: 1 conns, 12 unsent events
      bep40-prio: 013f9b0c
      last msg: 9.96s ago, connected: 2043.08s ago, last helpful: never, itime: 34m3.045060536s, etime: 25.92257ms
      24/24 completed, 0 pieces touched, good chunks: 0/0:0 reqq: 0+0/(1/1024):0/1024, flags: i-eIU-, dr: 0.0 KiB/s
      requested pieces:
```

**Comment by AskAlexSharov** [comment]
aaaaah. i did `| grep -v DBUG` and this is reason why i didn't see `[snapshots] torrent status` prefix. oh, `\n` makes logs non-greppable.

**Comment by AskAlexSharov** [comment]
disabled this logs by https://github.com/ledgerwatch/erigon/pull/10998
created ticket to re-enable somehow future https://github.com/ledgerwatch/erigon/issues/10999
