### ISSUE TITLE
Handling new payload: panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by susuper** [ledgerwatch/erigon#11099]
#### System information

Erigon version: 2.60.2

OS & Version: Ubuntu 24.04 LTS

Commit hash: 2f41075a

Erigon Command (with flags/config):
`/usr/local/sbin/gnosis-erigon --chain=gnosis --datadir=/_data/gnosis/erigon --internalcl --prune=hrtc --http.addr=127.0.0.1 --http.port=8545 --http.api=eth,web3,net,debug,trace,txpool --ws --ws.port=8546 --authrpc.addr=127.0.0.1 --authrpc.port=8551 --authrpc.jwtsecret=/usr/local/etc/gnosis/jwt.txt --port=30303 --lightclient.discovery.port=9222 --lightclient.discovery.tcpport=9222 --maxpeers=128 --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --log.dir.disable --nat=extip:X.X.X.X`

Consensus Layer:
Caplin

Consensus Layer Command (with flags/config):
`/usr/local/sbin/gnosis-erigon --chain=gnosis --datadir=/_data/gnosis/erigon --internalcl --prune=hrtc --http.addr=127.0.0.1 --http.port=8545 --http.api=eth,web3,net,debug,trace,txpool --ws --ws.port=8546 --authrpc.addr=127.0.0.1 --authrpc.port=8551 --authrpc.jwtsecret=/usr/local/etc/gnosis/jwt.txt --port=30303 --lightclient.discovery.port=9222 --lightclient.discovery.tcpport=9222 --maxpeers=128 --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --log.dir.disable --nat=extip:X.X.X.X`

Chain/Network: 
Gnosis

#### Expected behaviour
The node is syncing normally.

#### Actual behaviour
```
[INFO] [07-10|02:03:40.492] [NewPayload] Handling new payload        height=34887405 hash=0x14f2a888a89f06e40ce7b96ada450ad74c37f21fc421e2281e1c069f69b16ed7
panic: runtime error: integer divide by zero

goroutine 446647380 [running]:
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.processRewardsAndPenaltiesPostAltair({0x31e9400, 0xc06bda9140}, {0xc0cf062000, 0x3b332, 0x0?}, {0xc07484a280, 0x3, 0x3})
        github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_rewards_and_penalties.go:46 +0x697
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.ProcessRewardsAndPenalties({0x31e9400, 0xc06bda9140}, {0xc0cf062000, 0x3b332, 0x475b0}, {0xc07484a280, 0x3, 0x3})
        github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_rewards_and_penalties.go:230 +0xf9
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.ProcessEpoch({0x31e9400, 0xc06bda9140})
        github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_epoch.go:47 +0x17c
github.com/ledgerwatch/erigon/cl/transition/impl/eth2.(*impl).ProcessSlots(0xc000780808?, {0x31e9400, 0xc06bda9140}, 0xf8f930)
        github.com/ledgerwatch/erigon/cl/transition/impl/eth2/operations.go:987 +0x196
github.com/ledgerwatch/erigon/cl/transition/machine.TransitionState({0x31afc20, 0xc0acd98110}, {0x31e9400, 0xc06bda9140}, 0xc039c615e0)
        github.com/ledgerwatch/erigon/cl/transition/machine/transition.go:11 +0x4d
github.com/ledgerwatch/erigon/cl/transition.TransitionState(...)
        github.com/ledgerwatch/erigon/cl/transition/compat.go:18
github.com/ledgerwatch/erigon/cl/phase1/forkchoice/fork_graph.(*forkGraphDisk).GetState(0xc038b9e008, {0x89, 0x55, 0x95, 0xdc, 0x58, 0x1c, 0xee, 0xb7, 0xa0, ...}, ...)
        github.com/ledgerwatch/erigon/cl/phase1/forkchoice/fork_graph/fork_graph_disk.go:356 +0x433
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).getCheckpointState(0xc037b42908, {0xc05fe2b170, 0x28, 0x28})
        github.com/ledgerwatch/erigon/cl/phase1/forkchoice/utils.go:106 +0x154
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).GetHead(0xc037b42908)
        github.com/ledgerwatch/erigon/cl/phase1/forkchoice/get_head.go:41 +0x199
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func10({0x3191128, 0xc08caf0960}, {0x31a5f28, 0xc03ea424c0}, 0xc051ec5dc0, {0x1a, 0xf8f93, 0xf8f94, 0xf8f940, 0xf8f940, ...})
        github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:563 +0x65
github.com/ledgerwatch/erigon/cl/clstages.(*StageGraph[...]).StartWithStage.func1()
        github.com/ledgerwatch/erigon/cl/clstages/clstages.go:40 +0xd9
created by github.com/ledgerwatch/erigon/cl/clstages.(*StageGraph[...]).StartWithStage in goroutine 6235
        github.com/ledgerwatch/erigon/cl/clstages/clstages.go:34 +0x3a5
```

#### Steps to reproduce the behaviour
Syncing node from scratch, no special pre-conditions.

**Comment by AskAlexSharov** [comment]
update to `2.60.3`
