### ISSUE TITLE
RPC method eth_getTransactionByHash crashed

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#1307]
My rpcdaemon keeps crashing with the following logs:

Commit: `9ad6978259bc5a31cb58ee4e80b82e34d30e12c0`

```
WARN [10-27|11:33:04.500] Served                                   conn=31.7.187.202:53144 method=eth_getTransactionByHash reqid=1 t="188.914µs" err="method handler crashed"
WARN [10-27|11:33:40.776] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [10-27|11:33:40.776] Served                                   conn=31.7.187.202:53170 method=eth_getTransactionByHash reqid=1 t="170.004µs" err="transaction 08f71be1ab9a39e6663d14255869c8b679764995f83a5be8e36ecedb4ab7f748 not found"
ERROR[10-27|11:33:50.300] RPC method eth_getTransactionByHash crashed: rpc error: code = Canceled desc = context canceled
goroutine 124149 [running]:
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call.func1(0xc001a80480, 0x18, 0xc00129fd50)
	github.com/ledgerwatch/turbo-geth/rpc/service.go:200 +0xba
panic(0x10686a0, 0xc001ee4068)
	runtime/panic.go:969 +0x175
github.com/ledgerwatch/turbo-geth/ethdb.(*ObjectDatabase).Begin(0xc0003013b0, 0x13157c0, 0xc0017d4700, 0x2, 0x13157c0, 0x1076ae0, 0xb6140007ff3e5, 0x203000)
	github.com/ledgerwatch/turbo-geth/ethdb/object_db.go:361 +0xea
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*APIImpl).GetTransactionByHash(0xc0000cd220, 0x13157c0, 0xc0017d4700, 0x6c07dcfb71ce9247, 0x8b4fcb6b135fc00c, 0xa0257a5f79eb3006, 0xd25a7995e358a9ea, 0x0, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/eth_txs.go:16 +0x93
reflect.Value.call(0xc000032f80, 0xc000010fd8, 0x13, 0x118c6b1, 0x4, 0xc00276a730, 0x3, 0x3, 0xc00276a760, 0xc0020fcd60, ...)
	reflect/value.go:475 +0x8c7
reflect.Value.Call(0xc000032f80, 0xc000010fd8, 0x13, 0xc00276a730, 0x3, 0x3, 0x16, 0x0, 0x0)
	reflect/value.go:336 +0xb9
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call(0xc000293e60, 0x13157c0, 0xc0017d4700, 0xc001a80480, 0x18, 0xc0020fcd60, 0x1, 0x1, 0x0, 0x0, ...)
	github.com/ledgerwatch/turbo-geth/rpc/service.go:206 +0x2c5
github.com/ledgerwatch/turbo-geth/rpc.(*handler).runMethod(0xc0015145a0, 0x13157c0, 0xc0017d4700, 0xc00279c0e0, 0xc000293e60, 0xc0020fcd60, 0x1, 0x1, 0x1)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:388 +0x8a
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCall(0xc0015145a0, 0xc002f38c00, 0xc00279c0e0, 0xc0029116c0)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:336 +0x294
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCallMsg(0xc0015145a0, 0xc002f38c00, 0xc00279c0e0, 0x1302a01)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:298 +0x1be
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleMsg.func1(0xc002f38c00)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:139 +0x46
github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc.func1(0xc0015145a0, 0xc0020fcd00)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:226 +0xd2
created by github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:222 +0x66
```

**Comment by MysticRyuujin** [comment]
It looks like it has something to do with a missing `0x` prefix on the tx hash.

Geth and Turbo-Geth requires the `0x` prefix, Nethermind does not. rpcdaemon shouldn't crash though :smile:

**Comment by MysticRyuujin** [comment]
Ok I take that back too. If I actually send a JSON RPC Request without the 0x prefix I get:
```
WARN [10-27|12:05:54.856] Served                                   conn=127.0.0.1:42132    method=eth_getTransactionByHash reqid=1707272302 t="30.379µs"  err="invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type common.Hash"
```

Which tells me that it's not related to the `0x` at all. I don't know why it was crashing now, but it succeeds now...

**Comment by tjayrush** [comment]
Can you send the actual `curl` command you used? That will help debug the problem. I can see you're calling `eth_getTransactionByHash`, but I don't see the actual parameters you're sending.

The RPC daemon will report a crash, but it continues to run, that's why you're seeing that message. It's weird. It says `crashed` but also says, `served`. Not sure how it can do both.

**Comment by MysticRyuujin** [comment]
It's not me sending the original RPC request, but to the best of my know, that method only accepts 1 parameter, the hash of the tx which in this case is:
`0x08f71be1ab9a39e6663d14255869c8b679764995f83a5be8e36ecedb4ab7f748`

Someone was essentially calling many many many requests when I noticed it.

**Comment by tjayrush** [comment]
Oh. I see. You're just finding the crash in your logs.

I just started a test to hit my local TG node basically continually. (I'll report back here if it crashes.) Do you have any idea what "many many many" means? Millions? Thousands? Thousands of millions?

**Comment by MysticRyuujin** [comment]
Based on my logs we had over 500k requests, but those requests were load balanced across our nodes....

Maybe 100k?

**Comment by tjayrush** [comment]
I ran about 100,000,000 continuous RPC requests over about a four hour period. Mix of `eth_getTrans...`, `eth_getReceipt`, and `eth_blockNumber`. Not a great test, but no crash. It would be nice to find a way to some real stress testing.

I found through a Google search that `crashed: rpc error: code = Canceled desc = context canceled goroutine` may have something to do with the request taking too long (timing out).

Just a theory, but if that's the case, perhaps the issue is poor error reporting. Perhaps on a time out it should just report a time out and not a stack trace.

**Comment by MysticRyuujin** [comment]
I think a timeout is a reasonable educated guess. I wouldn't put too much effort into this if it's not reproducing.

**Comment by vorot93** [comment]
Got a similar error for `eth_getBlockByNumber`:

```
ERROR[10-30|13:11:26.813] RPC method eth_getBlockByNumber crashed: rpc error: code = Canceled desc = context canceled
goroutine 144729 [running]:
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call.func1(0xc000458000, 0x14, 0xc0005a7d50)
        github.com/ledgerwatch/turbo-geth/rpc/service.go:200 +0xba
panic(0x10846a0, 0xc00016a020)
        runtime/panic.go:969 +0x1b9
github.com/ledgerwatch/turbo-geth/ethdb.(*ObjectDatabase).Begin(0xc000350c00, 0x13321e0, 0xc0002c8100, 0x2, 0x7fad1ef69e01, 0xc000532710, 0x43557b, 0xc000532740)
        github.com/ledgerwatch/turbo-geth/ethdb/object_db.go:369 +0xea
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*APIImpl).GetBlockByNumber(0xc00007e690, 0x13321e0, 0xc0002c8100, 0x1d4c00, 0x0, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/eth_block.go:17 +0x96
reflect.Value.call(0xc000192a80, 0xc0000b6870, 0x13, 0x11a9c8f, 0x4, 0xc00063c360, 0x4, 0x4, 0xc00063c390, 0xc000210870, ...)
        reflect/value.go:475 +0x8c7
reflect.Value.Call(0xc000192a80, 0xc0000b6870, 0x13, 0xc00063c360, 0x4, 0x4, 0x16, 0x10, 0x0)
        reflect/value.go:336 +0xb9
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call(0xc0002a9f20, 0x13321e0, 0xc0002c8100, 0xc000458000, 0x14, 0xc000210870, 0x2, 0x2, 0x0, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/rpc/service.go:206 +0x2c5
github.com/ledgerwatch/turbo-geth/rpc.(*handler).runMethod(0xc0002e43f0, 0x13321e0, 0xc0002c8100, 0xc00030a000, 0xc0002a9f20, 0xc000210870, 0x2, 0x2, 0x2)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:388 +0x8a
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCall(0xc0002e43f0, 0xc0002107b0, 0xc00030a000, 0xc00069c6c0)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:336 +0x294
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCallMsg(0xc0002e43f0, 0xc0002107b0, 0xc00030a000, 0x1322e01)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:298 +0x1be
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleMsg.func1(0xc0002107b0)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:139 +0x46
github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc.func1(0xc0002e43f0, 0xc0004840e0)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:226 +0xd2
created by github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:222 +0x66
```

**Comment by AskAlexSharov** [comment]
i think it's fixed for now. feel free to re-open if not
