### ISSUE TITLE
LMDB assert after machine freeze

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#1325]
[crash_tg.log](https://github.com/ledgerwatch/turbo-geth/files/5463925/crash_tg.log)

After update to newer LMDB version - error changed to:

[crash_tg-2.log](https://github.com/ledgerwatch/turbo-geth/files/5463928/crash_tg-2.log)

Discussion: https://discord.com/channels/687972960811745322/687972960811745326/771623625794912296

**Comment by AlexeyAkhunov** [comment]
Reproduced slightly different stack trace:
```
INFO [11-02|19:06:23.005] [5/14 Execution] Executed blocks         number=11164389 blk/second=3.867 batch=127.44MiB alloc=720.67MiB sys=1.32GiB numGC=164
INFO [11-02|19:06:53.141] [5/14 Execution] Executed blocks         number=11164528 blk/second=4.633 batch=129.29MiB alloc=771.40MiB sys=1.32GiB numGC=165
mdb.c:2135: Assertion 'rc == 0' failed in mdb_page_dirty()
SIGABRT: abort
PC=0x7f6f2e73b18b m=13 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 310 [syscall, locked to thread]:
runtime.cgocall(0x10f0a60, 0xc01efd7868, 0x7d6e00000000)
        runtime/cgocall.go:133 +0x5b fp=0xc01efd7838 sp=0xc01efd7800 pc=0x43073b
github.com/ledgerwatch/lmdb-go/lmdb._Cfunc_lmdbgo_mdb_cursor_put2(0x7d6ecc0068b0, 0xc03a015600, 0xc, 0xc0384e2000, 0x336, 0x20000, 0x7f6e00000000)
        _cgo_gotypes.go:317 +0x4d fp=0xc01efd7868 sp=0xc01efd7838 pc=0x78220d
github.com/ledgerwatch/lmdb-go/lmdb.(*Cursor).Put.func1(0xc0182d4470, 0xc03a015600, 0xc, 0xc, 0xc0384e2000, 0x336, 0xc12, 0x20000, 0x5906b9)
        github.com/ledgerwatch/lmdb-go@v1.17.1/lmdb/cursor.go:243 +0xa9 fp=0xc01efd78b8 sp=0xc01efd7868 pc=0x78c809
github.com/ledgerwatch/lmdb-go/lmdb.(*Cursor).Put(0xc0182d4470, 0xc03a015600, 0xc, 0xc, 0xc0384e2000, 0x336, 0xc12, 0x20000, 0xc000098a78, 0xc000088c58)
        github.com/ledgerwatch/lmdb-go@v1.17.1/lmdb/cursor.go:243 +0x9f fp=0xc01efd7920 sp=0xc01efd78b8 pc=0x7858bf
github.com/ledgerwatch/turbo-geth/ethdb.(*LmdbCursor).append(...)
        github.com/ledgerwatch/turbo-geth/ethdb/kv_lmdb.go:775
github.com/ledgerwatch/turbo-geth/ethdb.(*LmdbCursor).Append(0xc019f94c60, 0xc03a015600, 0xc, 0xc, 0xc0384e2000, 0x336, 0xc12, 0x12a5860, 0xc)
        github.com/ledgerwatch/turbo-geth/ethdb/kv_lmdb.go:1291 +0x225 fp=0xc01efd7a48 sp=0xc01efd7920 pc=0xa79085
github.com/ledgerwatch/turbo-geth/ethdb.(*TxDb).Append(0xc009216050, 0x14b9d75, 0x3, 0xc03a015600, 0xc, 0xc, 0xc0384e2000, 0x336, 0xc12, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/ethdb/tx_db.go:74 +0xd4 fp=0xc01efd7ab0 sp=0xc01efd7a48 pc=0xa93054
github.com/ledgerwatch/turbo-geth/core/rawdb.AppendReceipts(0x16f3040, 0xc009216050, 0xaa5b97, 0xc037def000, 0xd8, 0x100, 0xc037bc5200, 0x16e04c0)
        github.com/ledgerwatch/turbo-geth/core/rawdb/accessors_chain.go:531 +0x1fc fp=0xc01efd7b70 sp=0xc01efd7ab0 pc=0xb9fdbc
github.com/ledgerwatch/turbo-geth/eth/stagedsync.SpawnExecuteBlocksStage(0xc01a4c1280, 0x16f12a0, 0xc000028150, 0x1e588c0, 0xc0005a0480, 0xc00017aca8, 0xc000101860, 0x0, 0x1, 0x20000000, ...)
        github.com/ledgerwatch/turbo-geth/eth/stagedsync/stage_execute.go:128 +0x9ed fp=0xc01efd7f80 sp=0xc01efd7b70 pc=0xd2acad
github.com/ledgerwatch/turbo-geth/eth/stagedsync.DefaultStages.func5.1(0xc01a4c1280, 0x16bc700, 0xc000566de0, 0x9, 0x16e0740)
        github.com/ledgerwatch/turbo-geth/eth/stagedsync/stagebuilder.go:169 +0xfa fp=0xc01efd8038 sp=0xc01efd7f80 pc=0xd4ddba
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).runStage(0xc000566de0, 0xc00007f180, 0x16e0740, 0xc000028150, 0x16e0740, 0xc000028150, 0x8, 0x10)
        github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:224 +0x155 fp=0xc01efd8100 sp=0xc01efd8038 pc=0xd43f35
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).Run(0xc000566de0, 0x16e6320, 0xc000028150, 0x16e6320, 0xc000028150, 0xc00017aca8, 0x16f12a0)
```

**Comment by AskAlexSharov** [comment]
@AlexeyAkhunov on which version?
