### ISSUE TITLE
eth_gasPrice crashed: runtime error: invalid memory address or nil pointer

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#1383]
Could be related to #1382 

Commit: `67de2a3a4661adc746cc420fcb17fb6655287917`

```
ERROR[12-01|17:42:42.270] RPC method eth_gasPrice crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 19109160 [running]:
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call.func1(0xc0004b4dc0, 0xc, 0xc000a4fd50)
	github.com/ledgerwatch/turbo-geth/rpc/service.go:200 +0xba
panic(0x1062da0, 0x1968940)
	runtime/panic.go:969 +0x1b9
math/big.(*Int).Cmp(0xc00020f9c0, 0x0, 0x1)
	math/big/int.go:328 +0x44
github.com/ledgerwatch/turbo-geth/eth/gasprice.bigIntArray.Less(...)
	github.com/ledgerwatch/turbo-geth/eth/gasprice/gasprice.go:219
sort.doPivot(0x1332ea0, 0xc0018e5ae0, 0x0, 0x3d, 0xc000ab6c58, 0xc000600800)
	sort/sort.go:121 +0x537
sort.quickSort(0x1332ea0, 0xc0018e5ae0, 0x0, 0x3d, 0xc)
	sort/sort.go:190 +0x9a
sort.Sort(0x1332ea0, 0xc0018e5ae0)
	sort/sort.go:218 +0x7a
github.com/ledgerwatch/turbo-geth/eth/gasprice.(*Oracle).SuggestPrice(0xc00017e700, 0x13362e0, 0xc000376f40, 0x0, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/eth/gasprice/gasprice.go:158 +0xbcc
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*APIImpl).GasPrice(0xc000140c30, 0x13362e0, 0xc000376f40, 0x0, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/eth_system.go:74 +0x8d
reflect.Value.call(0xc0002da840, 0xc000010680, 0x13, 0x11ac452, 0x4, 0xc000eb0f30, 0x2, 0x2, 0xc0011c2be8, 0x476fec, ...)
	reflect/value.go:476 +0x8c7
reflect.Value.Call(0xc0002da840, 0xc000010680, 0x13, 0xc000eb0f30, 0x2, 0x2, 0x1008b40, 0x0, 0x0)
	reflect/value.go:337 +0xb9
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call(0xc0002da8a0, 0x13362e0, 0xc000376f40, 0xc0004b4dc0, 0xc, 0x1ac7838, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ledgerwatch/turbo-geth/rpc/service.go:206 +0x2c5
github.com/ledgerwatch/turbo-geth/rpc.(*handler).runMethod(0xc003f0b320, 0x13362e0, 0xc000376f40, 0xc00017e620, 0xc0002da8a0, 0x1ac7838, 0x0, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:399 +0x8a
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCall(0xc003f0b320, 0xc000eb0ed0, 0xc00017e620, 0xc0018f26c0)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:347 +0x298
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCallMsg(0xc003f0b320, 0xc000eb0ed0, 0xc00017e620, 0x1326f01)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:301 +0x1be
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleMsg.func1(0xc000eb0ed0)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:142 +0x46
github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc.func1(0xc003f0b320, 0xc001da27c0)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:229 +0xd2
created by github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:225 +0x66
```

**Comment by tjayrush** [comment]
I saw this same error for a short time yesterday.

I did `make clean` then `make` and the issue (which was consistent until then) went away. Couldn't reproduce it after that.

**Comment by MysticRyuujin** [comment]
It's certainly not a regular occurrence, I don't have any idea what's causing it, but it occurred around the same time as the other issue.

**Comment by frostRed** [comment]
Same error on 12.03 version (tg and rpcdameon). And the stack info also is identical.

**Comment by AskAlexSharov** [comment]
tested on syncing and synced nodes now - all looks good. feel free to open new issue if you still have problems
