### ISSUE TITLE
Hangs on shutdown

### ISSUE THREAD

**Issue by vorot93** [ledgerwatch/erigon#1411]
_Not_ in the middle of staged sync.

```
goroutine 2027746 [sync.Cond.Wait, 2 minutes]:
runtime.goparkunlock(...)
	runtime/proc.go:312
sync.runtime_notifyListWait(0xc00064c2d0, 0x0)
	runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc00064c2c0)
	sync/cond.go:56 +0x9d
google.golang.org/grpc.(*Server).GracefulStop(0xc000642fc0)
	google.golang.org/grpc@v1.33.1/server.go:1695 +0x1ee
github.com/ledgerwatch/turbo-geth/eth.(*Ethereum).Stop(0xc000664a50, 0xc001a66c40, 0xc001a66b20)
	github.com/ledgerwatch/turbo-geth/eth/backend.go:852 +0x186
github.com/ledgerwatch/turbo-geth/node.(*Node).stopServices(0xc0002c8d20, 0xc00001c990, 0x1, 0x1, 0xc00de3e340, 0xc00af98120)
	github.com/ledgerwatch/turbo-geth/node/node.go:304 +0xc2
github.com/ledgerwatch/turbo-geth/node.(*Node).Close(0xc0002c8d20, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/node/node.go:224 +0x145
created by github.com/ledgerwatch/turbo-geth/cmd/utils.StartNode.func1
	github.com/ledgerwatch/turbo-geth/cmd/utils/cmd.go:82 +0x16a
```

**Comment by MysticRyuujin** [comment]
Here's mine:

```
INFO [12-23|09:06:53.201] Commit cycle                             in=113.420948ms
INFO [12-23|09:07:02.918] Got interrupt, shutting down...          sig=terminated
INFO [12-23|09:07:02.918] Got interrupt, shutting down... 
INFO [12-23|09:07:02.918] Blockchain stopped 
INFO [12-23|09:07:02.918] Ethereum protocol stopped 
INFO [12-23|09:07:13.114] Looking for peers                        peercount=0 tried=72 static=0
INFO [12-23|09:07:23.253] Looking for peers                        peercount=0 tried=57 static=0
INFO [12-23|09:07:33.253] Looking for peers                        peercount=0 tried=50 static=0
INFO [12-23|09:07:43.586] Looking for peers                        peercount=0 tried=38 static=0
INFO [12-23|09:07:53.586] Looking for peers                        peercount=0 tried=63 static=0
INFO [12-23|09:08:03.587] Looking for peers                        peercount=0 tried=53 static=0
INFO [12-23|09:08:13.682] Looking for peers                        peercount=0 tried=56 static=0
INFO [12-23|09:08:23.764] Looking for peers                        peercount=0 tried=57 static=0
INFO [12-23|09:08:33.858] Looking for peers                        peercount=0 tried=49 static=0
INFO [12-23|09:08:44.013] Looking for peers                        peercount=0 tried=52 static=0
INFO [12-23|09:08:54.097] Looking for peers                        peercount=0 tried=60 static=0
INFO [12-23|09:09:04.097] Looking for peers                        peercount=0 tried=50 static=0
```

`kill -6` attached

[shutdown.log.zip](https://github.com/ledgerwatch/turbo-geth/files/5735846/shutdown.log.zip)
