### ISSUE TITLE
Rpcdaemon "method handler crashed" will make all requests failed

### ISSUE THREAD

**Issue by frostRed** [ledgerwatch/erigon#1423]
#### System information

version: `2020.12.03`
OS & Version: Linux
Commit hash : `142e397`

#### Expected behavior
If one request's handler crashed, just respond to one error. Not make the next all requests failed.

#### Actual behaviour

All requests will fail during the next few seconds.

In Grafana, I found the private API count decrease to 0.

![image](https://user-images.githubusercontent.com/2486301/103079664-386c2f80-460f-11eb-8882-8fa71176d118.png)

#### Steps to reproduce the behavior

I don't' know which JSON-RPC request crashed the rpcdaemon. I will provide it if I find.

#### Backtrace

````
WARN [12-24|09:06:56.807] Served                                   conn=172.16.161.180:56044 method=web3_clientVersion        reqid=1             t="13.342µs"     err="the method web3_clientVersion does not exist/is not available"
WARN [12-24|09:07:02.538] Served                                   conn=172.16.144.36:33344  method=web3_clientVersion        reqid=1             t="46.554µs"     err="the method web3_clientVersion does not exist/is not available"
WARN [12-24|09:07:06.299] Served                                   conn=172.16.161.180:56378 method=web3_clientVersion        reqid=1             t="12.648µs"     err="the method web3_clientVersion does not exist/is not available"
WARN [12-24|09:07:10.135] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.139] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.139] Served                                   conn=172.16.161.180:55322 method=eth_call                  reqid=1608799918659 t=30.02831035s   err="execution aborted (timeout = 5m0s)"
WARN [12-24|09:07:10.139] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.139] Served                                   conn=172.16.161.180:55328 method=eth_call                  reqid=1608799919160 t=30.027261564s  err="execution aborted (timeout = 5m0s)"
WARN [12-24|09:07:10.139] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.139] Served                                   conn=172.16.161.180:55324 method=eth_call                  reqid=1608799919105 t=30.028388318s  err="execution aborted (timeout = 5m0s)"
WARN [12-24|09:07:10.140] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.146] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.147] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.148] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.159] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.164] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.165] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.176] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.177] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.178] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.187] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
ERROR[12-24|09:07:10.195] RPC method eth_call crashed: rpc error: code = Canceled desc = context canceled
goroutine 473590 [running]:
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call.func1(0xc000306130, 0x8, 0xc000925d50)
        github.com/ledgerwatch/turbo-geth/rpc/service.go:200 +0xba
panic(0x10b2220, 0xc00058e330)
        runtime/panic.go:969 +0x1b9
github.com/ledgerwatch/turbo-geth/ethdb.(*ObjectDatabase).Begin(0xc00045dfb0, 0x136e6c0, 0xc000a05480, 0x2, 0x10c0780, 0xba0a0, 0x104e0a0, 0xc000c6f8a0)
        github.com/ledgerwatch/turbo-geth/ethdb/object_db.go:397 +0xea
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*APIImpl).Call(0xc000238be0, 0x136e6c0, 0xc000a05480, 0x0, 0xc000429100, 0x0, 0x0, 0x0, 0xc00084ee00, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/eth_call.go:26 +0xa2
reflect.Value.call(0xc00021c580, 0xc00021a738, 0x13, 0x11dd6b6, 0x4, 0xc000d19e80, 0x5, 0x5, 0xc000d19eb0, 0xc000e83450, ...)
        reflect/value.go:476 +0x8c7
reflect.Value.Call(0xc00021c580, 0xc00021a738, 0x13, 0xc000d19e80, 0x5, 0x5, 0x16, 0x10, 0x0)
        reflect/value.go:337 +0xb9
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call(0xc000201260, 0x136e6c0, 0xc000a05480, 0xc000306130, 0x8, 0xc000e83450, 0x3, 0x3, 0x0, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/rpc/service.go:206 +0x2c5
github.com/ledgerwatch/turbo-geth/rpc.(*handler).runMethod(0xc000982510, 0x136e6c0, 0xc000a05480, 0xc000194460, 0xc000201260, 0xc000e83450, 0x3, 0x3, 0x3)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:399 +0x8a
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCall(0xc000982510, 0xc000bd4870, 0xc000194460, 0xc0009cb6c0)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:347 +0x298
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCallMsg(0xc000982510, 0xc000bd4870, 0xc000194460, 0x135f401)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:301 +0x1be
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleMsg.func1(0xc000bd4870)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:142 +0x46
github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc.func1(0xc000982510, 0xc00084eda0)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:229 +0xd2
created by github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:225 +0x66
 
WARN [12-24|09:07:10.195] Served                                   conn=172.16.161.180:55370 method=eth_call                  reqid=1608799919493 t=30.029410912s  err="method handler crashed"
WARN [12-24|09:07:10.210] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.210] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.389] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.393] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.421] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.438] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.472] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.479] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.486] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.487] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.502] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
WARN [12-24|09:07:10.504] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"

````

**Comment by mandrigin** [comment]
I cannot reproduce it locally
