### ISSUE TITLE
Header not found when enable --download.v2 on existing node

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#1800]
```
INFO [04-25|11:09:05.933] [fef757260fceeac1497b7d7bd11f829505ca0a93867e97595684e6ae411d8dda] Error while running peer: reading message: EOF
INFO [04-25|11:09:06.412] [605f1019470e3822df7a854c53c5cd7288f8133770cbf6393835ccdcd858609e] Start with peer
INFO [04-25|11:09:06.679] [605f1019470e3822df7a854c53c5cd7288f8133770cbf6393835ccdcd858609e] Error while running peer: reading message: EOF
INFO [04-25|11:09:08.285] [1b4b0de697d4469591b5c95fe18a0b6f42c5be05474c196f075c7caa8a350bdb] Start with peer
INFO [04-25|11:09:09.072] [1/5 Headers] Wrote block headers        number=12307166 blk/second=0.033 batch=16.29KiB alloc=668.85MiB sys=951.33MiB numGC=29
INFO [04-25|11:09:11.300] [97c4fb10ff5408a8d251fbfe74596ddfd753d45a32f86b16fc0912067ea91309] Start with peer
INFO [04-25|11:09:11.505] [97c4fb10ff5408a8d251fbfe74596ddfd753d45a32f86b16fc0912067ea91309] Error while running peer: reading message: EOF
INFO [04-25|11:09:11.741] NewBlockMsg{blockNumber: 12307167} from [1943135489ba630805394b905e5468bb503d7a1a7f1e0c78d9fd7c555d30776d]
Top seen height: 12307167
INFO [04-25|11:09:11.928] Processed                                highest=12307167
INFO [04-25|11:09:11.928] [1/5 Headers] DONE                       in=3m2.856833965s
INFO [04-25|11:09:11.933] [3/5 Bodies] Processing bodies...        from=12307141 to=12307167
ERROR[04-25|11:09:11.933] Could not find canonical header          block number=12307142
ERROR[04-25|11:09:11.933] Header not found                         block number=12307142
panic:

goroutine 157 [running]:
github.com/ledgerwatch/turbo-geth/turbo/stages/bodydownload.(*BodyDownload).RequestMoreBodies(0xc0001fe140, 0x1f7c118, 0xc000625790, 0xbbcac6, 0x6084eb67, 0x1f5a010, 0xc0000e8200, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/turbo/stages/bodydownload/body_algos.go:138 +0x1555
github.com/ledgerwatch/turbo-geth/eth/stagedsync.BodiesForward(0xc013520020, 0x1f67a70, 0xc00174d9c0, 0x1f7c118, 0xc000625790, 0xc0001fe140, 0xc0017144b0, 0xc0017144c0, 0xc0017144d0, 0x1f5a010, ...)
	github.com/ledgerwatch/turbo-geth/eth/stagedsync/stage_bodies_new.go:112 +0x1d74
github.com/ledgerwatch/turbo-geth/turbo/stages.ReplacementStages.func3.1(0xc013520020, 0x1f49560, 0xc00b778540, 0x1f5a600, 0xc000625790)
	github.com/ledgerwatch/turbo-geth/turbo/stages/stageloop.go:153 +0xe5
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).runStage(0xc00b778540, 0xc00b754690, 0x1f5a600, 0xc000625790, 0x1f5a600, 0xc000625790, 0x2, 0x4)
	github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:226 +0x14c
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).Run(0xc00b778540, 0x7f486035cb68, 0xc000625790, 0x7f486035cb68, 0xc000625790, 0x0, 0xc00b762640)
	github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:198 +0x34b
github.com/ledgerwatch/turbo-geth/turbo/stages.StageLoop(0x1f67a70, 0xc00174d9c0, 0x1f7c118, 0xc000625790, 0xc00046c0e0, 0xc00023eea0, 0x2709620, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/turbo/stages/stageloop.go:87 +0x537
github.com/ledgerwatch/turbo-geth/cmd/headers/download.Loop(0x1f67a70, 0xc00174d9c0, 0x1f7c118, 0xc000625790, 0xc00046c0e0, 0xc0000e8200)
	github.com/ledgerwatch/turbo-geth/cmd/headers/download/downloader.go:258 +0x85
created by github.com/ledgerwatch/turbo-geth/eth.(*Ethereum).Start
	github.com/ledgerwatch/turbo-geth/eth/backend.go:858 +0x2ed
exit status 2
```

**Comment by AskAlexSharov** [comment]
Reproducable on sync from scratch: 
```
INFO [04-25|11:42:12.483] [3/14 Bodies] Processing bodies...       from=0       to=12308653
ERROR[04-25|11:42:12.484] Could not find canonical header          block number=1
ERROR[04-25|11:42:12.485] Header not found                         block number=1
panic:

goroutine 156 [running]:
github.com/ledgerwatch/turbo-geth/turbo/stages/bodydownload.(*BodyDownload).RequestMoreBodies(0xc0002e00a0, 0x1f76658, 0xc0003ab800, 0x1, 0x60853974, 0x1f547d0, 0xc0000be200, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/turbo/stages/bodydownload/body_algos.go:138 +0x1555

```

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/turbo-geth/pull/1886
