### ISSUE TITLE
rawdb.ReadHeaderNumber returns nil: when play with --download.v2 flag

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#1809]
Probably need to maintain some db invariants before each commit.
But I'm not sure how I did it... Maybe used flag first, then run TG without flag (or opposite). Sorry.
```
INFO [04-26|08:23:19.102] Block synchronisation started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x117ddc0]

goroutine 531 [running]:
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).findAncestor(0xc000916540, 0xc00001bef0, 0xbbe6af, 0x0, 0x0, 0x8)
	github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:657 +0xe0
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).syncWithPeer(0xc000916540, 0xc00001bef0, 0x9227f19adbb9a102, 0xe147d5a19fe94ec6, 0x374f991738d24e5d, 0x5a119dc62ae7c378, 0xbbe6af, 0xc000134b40, 0x1ded7f8, 0x0, ...)
	github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:388 +0x41b
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).synchronise(0xc000916540, 0xc0012dfd00, 0x40, 0x9227f19adbb9a102, 0xe147d5a19fe94ec6, 0x374f991738d24e5d, 0x5a119dc62ae7c378, 0xbbe6af, 0xc000134b40, 0x1ded7f8, ...)
	github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:367 +0x395
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).Synchronise(0xc000916540, 0xc0012dfd00, 0x40, 0x9227f19adbb9a102, 0xe147d5a19fe94ec6, 0x374f991738d24e5d, 0x5a119dc62ae7c378, 0xbbe6af, 0xc000134b40, 0x1ded7f8, ...)
	github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:285 +0x9e
github.com/ledgerwatch/turbo-geth/eth.(*handler).doSync(0xc0000beb00, 0xc00069c030, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/eth/sync.go:280 +0xc5
github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).startSync.func1(0xc001441080, 0xc00069c030)
	github.com/ledgerwatch/turbo-geth/eth/sync.go:273 +0x38
created by github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).startSync
	github.com/ledgerwatch/turbo-geth/eth/sync.go:273 +0x76
exit status 2
```

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/turbo-geth/pull/1886
