### ISSUE TITLE
rpc filters, unprocessable payload and tg crash

### ISSUE THREAD

**Issue by 0xD34D81** [ledgerwatch/erigon#1818]
#### System information

Geth version: `tg version 2021.05.1-alpha`
OS & Version: Linux

#### Expected behaviour

When starting the daemon and without any connection, no errors.

#### Actual behaviour

When starting the rpcdaemon, an error is logged with high frequence and tg crashes at some point

#### Steps to reproduce the behaviour

Wait for tg to sync and run rpcdaemon on dual mode.

#### Backtrace

`rpcdaemon`
````
WARN [04-26|14:25:37.442] rpc filters, unprocessable payload       err="json: cannot unmarshal object into Go value of type types.Transaction"
WARN [04-26|14:25:37.446] rpc filters, unprocessable payload       err="json: cannot unmarshal object into Go value of type types.Transaction"
WARN [04-26|14:25:37.452] rpc filters, unprocessable payload       err="json: cannot unmarshal object into Go value of type types.Transaction"
WARN [04-26|14:25:37.455] rpc filters, unprocessable payload       err="json: cannot unmarshal object into Go value of type types.Transaction"
WARN [04-26|14:25:37.485] rpc filters, unprocessable payload       err="json: cannot unmarshal object into Go value of type types.Transaction"
WARN [04-26|14:25:37.488] rpc filters, unprocessable payload       err="json: cannot unmarshal object into Go value of type types.Transaction"
````

`tg`
```
panic: sync: negative WaitGroup counter

goroutine 406575 [running]:
sync.(*WaitGroup).Add(0xc014b31fd0, 0xffffffffffffffff)
        sync/waitgroup.go:74 +0x147
sync.(*WaitGroup).Done(...)
        sync/waitgroup.go:99
github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver.(*EthBackendServer).Subscribe.func1(0xc00148cb40, 0xc0007d2420, 0xc00081df98)
        github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver/ethbackend.go:76 +0x32e
github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver.(*Events).OnNewHeader(0xc00069e6e0, 0xc00148cb40)
        github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver/events.go:48 +0xb3
github.com/ledgerwatch/turbo-geth/eth/stagedsync.NotifyNewHeaders(0xbbef40, 0xbbef40, 0x1f6cec8, 0xc00069e6e0, 0x1f80d78, 0xc00069c180, 0x2, 0x2)
        github.com/ledgerwatch/turbo-geth/eth/stagedsync/stage_finish.go:42 +0x52
github.com/ledgerwatch/turbo-geth/eth/stagedsync.DefaultStages.func14.1(0xc0128fc5c0, 0x1f4e520, 0xc01466c9c0, 0x1f5f4c0, 0xc00069c180)
        github.com/ledgerwatch/turbo-geth/eth/stagedsync/stagebuilder.go:356 +0x236
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).runStage(0xc01466c9c0, 0xc00152ca00, 0x1f5f4c0, 0xc00069c180, 0x7fed1c5c10f8, 0xc0004919c0, 0x0, 0x0)
        github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:226 +0x14c
github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).Run(0xc01466c9c0, 0x7fed1c5c10b8, 0xc00069c180, 0x1f6fd78, 0xc0004919c0, 0xc00097e210, 0xc00127b800)
        github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:198 +0x34b
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).syncWithPeer(0xc0002516c0, 0xc01301f950, 0x562bf72d3ab9279b, 0xede83e4595ec0df0, 0xf8f619010f2b1af4, 0x3f90ec85ea7b9cdc, 0xbbef40, 0xc00013cb40, 0x1d
f9068, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:515 +0xd94
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).synchronise(0xc0002516c0, 0xc0021a2b00, 0x40, 0x562bf72d3ab9279b, 0xede83e4595ec0df0, 0xf8f619010f2b1af4, 0x3f90ec85ea7b9cdc, 0xbbef40, 0xc00013cb40,
 0x1df9068, ...)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:367 +0x395
github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).Synchronise(0xc0002516c0, 0xc0021a2b00, 0x40, 0x562bf72d3ab9279b, 0xede83e4595ec0df0, 0xf8f619010f2b1af4, 0x3f90ec85ea7b9cdc, 0xbbef40, 0xc00013cb40,
 0x1df9068, ...)
        github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:285 +0x9e
github.com/ledgerwatch/turbo-geth/eth.(*handler).doSync(0xc0002a2100, 0xc007aa8900, 0x0, 0x4a9741)
        github.com/ledgerwatch/turbo-geth/eth/sync.go:280 +0xc5
github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).startSync.func1(0xc001cb06f0, 0xc007aa8900)
        github.com/ledgerwatch/turbo-geth/eth/sync.go:273 +0x38
created by github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).startSync
        github.com/ledgerwatch/turbo-geth/eth/sync.go:273 +0x76
```

**Comment by AskAlexSharov** [comment]
Must be fixed by https://github.com/ledgerwatch/turbo-geth/pull/1823
many thanks
