### ISSUE TITLE
Panic when closing LMDB KV

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon#1916]
#### Backtrace

````
INFO [05-11|17:51:37.715] [3/14 Bodies] DONE                       in=7m23.941431121s
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 33899 [running]:
sync.(*WaitGroup).Wait(0xc00069f770)
	sync/waitgroup.go:132 +0xae
github.com/ledgerwatch/turbo-geth/ethdb.(*LmdbKV).Close(0xc00003c100)
	github.com/ledgerwatch/turbo-geth/ethdb/kv_lmdb.go:295 +0x2a6
github.com/ledgerwatch/turbo-geth/ethdb.(*ObjectDatabase).Close(0xc0003e93d0)
	github.com/ledgerwatch/turbo-geth/ethdb/object_db.go:294 +0x33
github.com/ledgerwatch/turbo-geth/node.(*Node).doClose(0xc00024c3c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/node/node.go:231 +0x95
github.com/ledgerwatch/turbo-geth/node.(*Node).Close(0xc00024c3c0, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/node/node.go:216 +0x17d
created by github.com/ledgerwatch/turbo-geth/cmd/utils.StartNode.func1
	github.com/ledgerwatch/turbo-geth/cmd/utils/cmd.go:68 +0x16a
````

**Comment by AskAlexSharov** [comment]
Fast fix is: add atomic bool isClosed and check it in tx.begin
But long term solution probably: push all our goroutines to follow something like backend.go Start/Stop lifecycle. And wait all goroutines (stageloop, p2p, ...) finish, only then call db.Close(). Now we do cancel request but don't wait for goroutines finish. If this will be done, then we can remove waitgroup from KV.
