### ISSUE TITLE
[download.v2] Unwind on Goerli panicked

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon#1926]
#### Backtrace

````
INFO [05-13|07:10:36.446] [7/14 IntermediateHashes] Trie root       hash=0x42e15509aaaa4178ad98adf8fda3b1e0f97d0e2cc56febf34397cc1cf01470e5 in=30.220187ms
INFO [05-13|07:10:36.497] [11/14 CallTraces] disabled. Work In Progress
INFO [05-13|07:10:36.514] [13/14 TxPool] Read canonical hashes     hashes=3
INFO [05-13|07:10:36.515] [13/14 TxPool] Transaction stats         pending=1 queued=2
INFO [05-13|07:10:36.515] Memory                                   alloc=867.51MiB sys=1.86GiB
INFO [05-13|07:10:36.515] Timings                                  Headers=4.933298ms     BlockHashes="128.466µs"  Bodies=91.694206ms   Senders=5.832946ms   Execution=73.048722ms     HashState=14.811996ms  IntermediateHashes=37.908635ms   AccountHistoryIndex=9.200821ms    StorageHistoryIndex=17.442794ms    LogIndex=20.183064ms   TxLookup=16.296617ms     TxPool=1.18299ms   Finish="10.595µs"
INFO [05-13|07:10:37.821] Commit cycle                             in=1.306353015s
INFO [05-13|07:10:37.821] [1/14 Headers] Processing headers...     from=4782633
INFO [05-13|07:10:37.872] UnwindTo                                 block=4782632
INFO [05-13|07:10:37.872] [1/14 Headers] Processed                 highest=4782671 age=9s
INFO [05-13|07:10:37.872] Unwinding...                             stage=TxLookup
INFO [05-13|07:10:37.874] Unwinding...                             stage=LogIndex
INFO [05-13|07:10:37.882] Unwinding...                             stage=StorageHistoryIndex
INFO [05-13|07:10:37.895] Unwinding...                             stage=AccountHistoryIndex
INFO [05-13|07:10:37.902] Unwinding...                             stage=HashState
INFO [05-13|07:10:37.902] [6/14 HashState] Unwinding started       from=4782633 to=4782632 storage=false codes=true
INFO [05-13|07:10:37.903] [6/14 HashState] Unwinding started       from=4782633 to=4782632 storage=false codes=false
INFO [05-13|07:10:37.904] [6/14 HashState] Unwinding started       from=4782633 to=4782632 storage=true  codes=false
INFO [05-13|07:10:37.905] Unwinding...                             stage=IntermediateHashes
INFO [05-13|07:10:37.905] [7/14 IntermediateHashes] Unwinding of trie hashes from=4782633 to=4782632 csbucket=PLAIN-ACS
INFO [05-13|07:10:37.905] [7/14 IntermediateHashes] Unwinding of trie hashes from=4782633 to=4782632 csbucket=PLAIN-SCS
INFO [05-13|07:10:37.916] [7/14 IntermediateHashes] Trie root      hash=0x2cc01cdf2db14a4c15e22d113cb1c0d4e5ff79511aa2b61454da2d996360e801 in=9.990964ms
INFO [05-13|07:10:37.918] Unwinding...                             stage=Execution
INFO [05-13|07:10:37.918] [5/14 Execution] Unwind Execution        from=4782633 to=4782632
INFO [05-13|07:10:37.920] Unwinding...                             stage=Senders
INFO [05-13|07:10:37.920] Unwinding...                             stage=TxPool
INFO [05-13|07:10:37.920] [13/14 TxPool] Read canonical hashes     hashes=1
INFO [05-13|07:10:37.920] [13/14 TxPool] Injecting txs into the pool number=77
INFO [05-13|07:10:37.922] [13/14 TxPool] Injection complete
INFO [05-13|07:10:37.922] [13/14 TxPool] Transaction stats         pending=1 queued=3
INFO [05-13|07:10:37.936] Unwinding...                             stage=Bodies
INFO [05-13|07:10:37.936] Unwinding...                             stage=BlockHashes
INFO [05-13|07:10:37.936] Unwinding...                             stage=Headers
ERROR[05-13|07:10:37.936] ancestor nil                             height=4782671 hash="a581fb…5a86a6"
ERROR[05-13|07:10:37.936] Stage loop failure                       error="runtime error: invalid memory address or nil pointer dereference, trace: goroutine 126 [running]: runtime/debug.Stack(0x51a65a0, 0x5c0352a2900, 0x6) runtime/debug/stack.go:24 +0x9f github.com/ledgerwatch/turbo-geth/turbo/stages.StageLoopStep.func1(0x5c03185ff20) github.com/ledgerwatch/turbo-geth/turbo/stages/stageloop.go:88 +0x1d4 panic(0x50f6e80, 0x656fa70) runtime/panic.go:965 +0x1b9 github.com/ledgerwatch/turbo-geth/eth/stagedsync.fixCanonicalChain(0x5c0352a8530, 0xc, 0x48fa4f, 0x8c938ce0ffb81a5, 0x91d0a386146e4866, 0xffa48db6e7cd101e, 0xa6865aaab64bb75f, 0x9c3db800, 0x5c02c322e70, 0xc0001360c0, ...) github.com/ledgerwatch/turbo-geth/eth/stagedsync/stage_headers_new.go:266 +0x125 github.com/ledgerwatch/turbo-geth/eth/stagedsync.HeadersForward(0x5c02fd61ac0, 0x5ca5500, 0x5c01b212de0, 0x5cc5090, 0xc0002aab80, 0x5cd8d98, 0x5c02c322e70, 0x5cd0a58, 0xc00004c180, 0xc00050e200, ...) github.com/ledgerwatch/turbo-geth/eth/stagedsync/stage_headers_new.go:84 +0x260e github.com/ledgerwatch/turbo-geth/eth/stagedsync.ReplacementStages.func1.1(0x5c02fd61ac0, 0x5ca5500, 0x5c01b212de0, 0x336ec260, 0x5c0349dde00) github.com/ledgerwatch/turbo-geth/eth/stagedsync/replacement_stages.go.go:36 +0x15f github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).runStage(0x5c01b212de0, 0xc000232e60, 0x5cb7810, 0xc000507260, 0x336ec260, 0x5c0349dde00, 0xe, 0x0) github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:227 +0x14c github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).Run(0x5c01b212de0, 0xf044028, 0xc000507260, 0x5cc85b8, 0x5c0349dde00, 0x0, 0x5c0349dde80) github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:199 +0x34b github.com/ledgerwatch/turbo-geth/turbo/stages.StageLoopStep(0x5cc5090, 0xc0002aab80, 0x5cdac48, 0xc000507260, 0xc00013d3b0, 0x48fa4f, 0x6581900, 0x0, 0x0, 0x0) github.com/ledgerwatch/turbo-geth/turbo/stages/stageloop.go:125 +0x4c6 github.com/ledgerwatch/turbo-geth/turbo/stages.StageLoop(0x5cc5090, 0xc0002aab80, 0x5cdac48, 0xc000507260, 0xc00013d3b0, 0xc00050e200, 0x6581900) github.com/ledgerwatch/turbo-geth/turbo/stages/stageloop.go:66 +0xd4 github.com/ledgerwatch/turbo-geth/cmd/headers/download.Loop(0x5cc5090, 0xc0002aab80, 0x5cdac48, 0xc000507260, 0xc00013d3b0, 0xc0001dc000) github.com/ledgerwatch/turbo-geth/cmd/headers/download/downloader.go:271 +0x6d created by github.com/ledgerwatch/turbo-geth/eth.(*Ethereum).Start github.com/ledgerwatch/turbo-geth/eth/backend.go:799 +0x2e5 "
INFO [05-13|07:10:37.937] [1/14 Headers] Processing headers...     from=4782633
WARN [05-13|07:10:44.169] Verification failed for header           hash="0fca07…d99b7f" height=4782672 error="unknown ancestor"
INFO [05-13|07:11:07.939] [1/14 Headers] Wrote block headers       number=4782671 blk/second=1.267   batch=0.00B    alloc=919.45MiB sys=1.86GiB   numGC=81
INFO [05-13|07:11:37.938] [1/14 Headers] Wrote block headers       number=4782671 blk/second=0.000   batch=0.00B    alloc=950.52MiB sys=1.86GiB   numGC=81
INFO [05-13|07:12:07.939] [1/14 Headers] Wrote block headers       number=4782671 blk/second=0.000   batch=0.00B    alloc=986.83MiB sys=1.86GiB   numGC=81
INFO [05-13|07:12:37.938] [1/14 Headers] Wrote block headers       number=4782671 blk/second=0.000   batch=0.00B    alloc=536.52MiB sys=1.86GiB   numGC=82
INFO [05-13|07:13:07.938] [1/14 Headers] Wrote block headers       number=4782671 blk/second=0.000   batch=0.00B    alloc=577.11MiB sys=1.86GiB   numGC=82
````

**Comment by AlexeyAkhunov** [comment]
Caught it on the main net as well:
```
INFO [05-13|14:40:51.899] [5/14 Execution] Blocks execution        from=12426333 to=12426334
INFO [05-13|14:40:51.964] [5/14 Execution] Completed on            block=12426334
INFO [05-13|14:40:51.964] [6/14 HashState] Promoting plain state   from=12426333 to=12426334
INFO [05-13|14:40:51.964] [6/14 HashState] Incremental promotion started from=12426333 to=12426334 codes=true  csbucket=PLAIN-ACS
INFO [05-13|14:40:51.967] [6/14 HashState] Incremental promotion started from=12426333 to=12426334 codes=false csbucket=PLAIN-ACS
INFO [05-13|14:40:51.989] [6/14 HashState] Incremental promotion started from=12426333 to=12426334 codes=false csbucket=PLAIN-SCS
INFO [05-13|14:40:52.009] [7/14 IntermediateHashes] Generating intermediate hashes from=12426333 to=12426334
INFO [05-13|14:40:52.085] [7/14 IntermediateHashes] Trie root       hash=0xfd0b368682b76e72b8c3747df7fb0482a026c985444a0a5aa4602119ce51dbf2 in=73.812795ms
INFO [05-13|14:40:52.179] [11/14 CallTraces] disabled. Work In Progress
INFO [05-13|14:40:52.251] [13/14 TxPool] Read canonical hashes     hashes=1
INFO [05-13|14:40:52.253] [13/14 TxPool] Transaction stats         pending=3772 queued=1034
INFO [05-13|14:40:52.253] [14/14 Finish] Update current block for the RPC API to=12426333
INFO [05-13|14:40:52.253] Memory                                   alloc=770.50MiB  sys=1.53GiB
INFO [05-13|14:40:52.253] Timings                                  Headers=14.148658786s   BlockHashes=1.395555ms  Bodies="631.455µs"   Senders=14.354589ms  Execution=64.281964ms   HashState=45.302626ms   IntermediateHashes=85.112822ms   AccountHistoryIndex=30.169153ms   StorageHistoryIndex=33.50051ms    LogIndex=21.412551ms   TxLookup=49.86497ms   TxPool=23.757537ms  Finish="57.395µs"
INFO [05-13|14:40:55.156] Commit cycle                             in=2.903353371s
INFO [05-13|14:40:55.156] [1/14 Headers] Processing headers...     from=12426334
INFO [05-13|14:40:55.166] [1/14 Headers] Processed                 highest=12426335 age=3s
INFO [05-13|14:40:55.167] [3/14 Bodies] Processing bodies...       from=12426334 to=12426335
INFO [05-13|14:40:55.167] [3/14 Bodies] Processed                  highest=12426335
INFO [05-13|14:40:55.167] [4/14 Senders] Started                   from=12426334 to=12426335
INFO [05-13|14:40:55.167] [4/14 Senders] Read canonical hashes     amount=1
INFO [05-13|14:40:55.180] [5/14 Execution] Blocks execution        from=12426334 to=12426335
INFO [05-13|14:40:55.257] [5/14 Execution] Completed on            block=12426335
INFO [05-13|14:40:55.257] [6/14 HashState] Promoting plain state   from=12426334 to=12426335
INFO [05-13|14:40:55.257] [6/14 HashState] Incremental promotion started from=12426334 to=12426335 codes=true  csbucket=PLAIN-ACS
INFO [05-13|14:40:55.260] [6/14 HashState] Incremental promotion started from=12426334 to=12426335 codes=false csbucket=PLAIN-ACS
INFO [05-13|14:40:55.292] [6/14 HashState] Incremental promotion started from=12426334 to=12426335 codes=false csbucket=PLAIN-SCS
INFO [05-13|14:40:55.312] [7/14 IntermediateHashes] Generating intermediate hashes from=12426334 to=12426335
INFO [05-13|14:40:55.401] [7/14 IntermediateHashes] Trie root       hash=0x5609d8068840d991af58bcee699c902edba86b7c6365975cfe345da90309862a in=85.779346ms
INFO [05-13|14:40:55.515] [11/14 CallTraces] disabled. Work In Progress
INFO [05-13|14:40:55.581] [13/14 TxPool] Read canonical hashes     hashes=1
INFO [05-13|14:40:55.587] [13/14 TxPool] Transaction stats         pending=3851 queued=1025
INFO [05-13|14:40:55.587] [14/14 Finish] Update current block for the RPC API to=12426334
INFO [05-13|14:40:55.587] Memory                                   alloc=839.97MiB  sys=1.53GiB
INFO [05-13|14:40:55.587] Timings                                  Headers=9.355198ms      BlockHashes=1.201487ms  Bodies="534.995µs"   Senders=12.793924ms  Execution=76.325752ms   HashState=55.949983ms   IntermediateHashes=97.135821ms   AccountHistoryIndex=33.977263ms   StorageHistoryIndex=42.215863ms   LogIndex=29.234387ms   TxLookup=44.177217ms  TxPool=27.666046ms  Finish="58.141µs"
INFO [05-13|14:40:58.336] Commit cycle                             in=2.749470077s
INFO [05-13|14:40:58.337] [1/14 Headers] Processing headers...     from=12426335
INFO [05-13|14:40:58.349] UnwindTo                                 block=12426334
INFO [05-13|14:40:58.349] [1/14 Headers] Processed                 highest=12426337 age=2s
INFO [05-13|14:40:58.349] Unwinding...                             stage=TxLookup
INFO [05-13|14:40:58.354] Unwinding...                             stage=LogIndex
INFO [05-13|14:40:58.384] Unwinding...                             stage=StorageHistoryIndex
INFO [05-13|14:40:58.436] Unwinding...                             stage=AccountHistoryIndex
INFO [05-13|14:40:58.475] Unwinding...                             stage=HashState
INFO [05-13|14:40:58.475] [6/14 HashState] Unwinding started       from=12426335 to=12426334 storage=false codes=true
INFO [05-13|14:40:58.481] [6/14 HashState] Unwinding started       from=12426335 to=12426334 storage=false codes=false
INFO [05-13|14:40:58.485] [6/14 HashState] Unwinding started       from=12426335 to=12426334 storage=true  codes=false
INFO [05-13|14:40:58.490] Unwinding...                             stage=IntermediateHashes
INFO [05-13|14:40:58.490] [7/14 IntermediateHashes] Unwinding of trie hashes from=12426335 to=12426334 csbucket=PLAIN-ACS
INFO [05-13|14:40:58.493] [7/14 IntermediateHashes] Unwinding of trie hashes from=12426335 to=12426334 csbucket=PLAIN-SCS
INFO [05-13|14:40:58.534] [7/14 IntermediateHashes] Trie root      hash=0xfd0b368682b76e72b8c3747df7fb0482a026c985444a0a5aa4602119ce51dbf2 in=36.886503ms
INFO [05-13|14:40:58.541] Unwinding...                             stage=Execution
INFO [05-13|14:40:58.541] [5/14 Execution] Unwind Execution        from=12426335 to=12426334
INFO [05-13|14:40:58.545] Unwinding...                             stage=Senders
INFO [05-13|14:40:58.545] Unwinding...                             stage=TxPool
INFO [05-13|14:40:58.567] [13/14 TxPool] Read canonical hashes     hashes=1
INFO [05-13|14:40:58.568] [13/14 TxPool] Injecting txs into the pool number=246
INFO [05-13|14:40:58.573] [13/14 TxPool] Injection complete
INFO [05-13|14:40:58.573] [13/14 TxPool] Transaction stats         pending=4042 queued=1025
INFO [05-13|14:40:58.573] Unwinding...                             stage=Bodies
INFO [05-13|14:40:58.573] Unwinding...                             stage=BlockHashes
INFO [05-13|14:40:58.573] Unwinding...                             stage=Headers
ERROR[05-13|14:40:58.573] ancestor nil                             height=12426337 hash="8d055e…87b061"
ERROR[05-13|14:40:58.574] Stage loop failure                       error="runtime error: invalid memory address or nil pointer dereference, trace: goroutine 129 [running]: runtime/debug.Stack(0x51a6240, 0x3c0349fde80, 0x6) runtime/debug/stack.go:24 +0x9f github.com/ledgerwatch/turbo-geth/turbo/stages.StageLoopStep.func1(0x3c050a9bf20) github.com/ledgerwatch/turbo-geth/turbo/stages/stageloop.go:84 +0x1d4 panic(0x50f6b20, 0x656fa70) runtime/panic.go:965 +0x1b9 github.com/ledgerwatch/turbo-geth/eth/stagedsync.fixCanonicalChain(0x3c03a3fc8d0, 0xc, 0xbd9c61, 0x8fbb4e999b5e058d, 0x86b03329a73cc1e9, 0xb392f1645acf1fec, 0x61b08770cdfd99a2, 0x602e2868, 0x3c04d6833b0, 0xc00019e0c0, ...) github.com/ledgerwatch/turbo-geth/eth/stagedsync/stage_headers_new.go:266 +0x125 github.com/ledgerwatch/turbo-geth/eth/stagedsync.HeadersForward(0x3c044e683c0, 0x5ca5240, 0x3c02b6a8060, 0x5cc4dd0, 0xc00074cd80, 0x5cd8ad8, 0x3c04d6833b0, 0x5cd0798, 0xc00004a080, 0xc000130e00, ...) github.com/ledgerwatch/turbo-geth/eth/stagedsync/stage_headers_new.go:84 +0x260e github.com/ledgerwatch/turbo-geth/eth/stagedsync.ReplacementStages.func1.1(0x3c044e683c0, 0x5ca5240, 0x3c02b6a8060, 0x2f4a1160, 0x3c02b640c00) github.com/ledgerwatch/turbo-geth/eth/stagedsync/replacement_stages.go.go:36 +0x15f github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).runStage(0x3c02b6a8060, 0x3c02af0da90, 0x5cb7550, 0xc000351850, 0x2f4a1160, 0x3c02b640c00, 0xe, 0x0) github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:227 +0x14c github.com/ledgerwatch/turbo-geth/eth/stagedsync.(*State).Run(0x3c02b6a8060, 0x2ead3c70, 0xc000351850, 0x5cc82f8, 0x3c02b640c00, 0x0, 0x3c02b640c80) github.com/ledgerwatch/turbo-geth/eth/stagedsync/state.go:199 +0x34b github.com/ledgerwatch/turbo-geth/turbo/stages.StageLoopStep(0x5cc4dd0, 0xc00074cd80, 0x5cda988, 0xc000351850, 0xc0003987e0, 0xbd9c61, 0x6582080, 0x0, 0x0, 0x0) github.com/ledgerwatch/turbo-geth/turbo/stages/stageloop.go:121 +0x4c6 github.com/ledgerwatch/turbo-geth/turbo/stages.StageLoop(0x5cc4dd0, 0xc00074cd80, 0x5cda988, 0xc000351850, 0xc0003987e0, 0xc000130e00, 0x6582080) github.com/ledgerwatch/turbo-geth/turbo/stages/stageloop.go:62 +0xd4 github.com/ledgerwatch/turbo-geth/cmd/headers/download.Loop(0x5cc4dd0, 0xc00074cd80, 0x5cda988, 0xc000351850, 0xc0003987e0, 0xc0004c8f00) github.com/ledgerwatch/turbo-geth/cmd/headers/download/downloader.go:271 +0x6d created by github.com/ledgerwatch/turbo-geth/eth.(*Ethereum).Start github.com/ledgerwatch/turbo-geth/eth/backend.go:799 +0x2e5 "
INFO [05-13|14:40:58.574] [1/14 Headers] Processing headers...     from=12426335
ERROR[05-13|14:41:02.613] consensus.ErrUnknownAncestor             parentNum=12426337 hash=0xee2bb62be18684145658295015064beeaa0b4697617bb4eaf86cbea3a38ccfe2
WARN [05-13|14:41:02.613] Verification failed for header           hash="80e487…fa3d04" height=12426338 error="unknown ancestor"
INFO [05-13|14:41:28.574] [1/14 Headers] Wrote block headers       number=12426337 blk/second=0.067 batch=0.00B alloc=1.12GiB    sys=1.53GiB   numGC=150
INFO [05-13|14:41:58.573] [1/14 Headers] Wrote block headers       number=12426337 blk/second=0.000 batch=0.00B alloc=837.91MiB  sys=1.53GiB   numGC=151
INFO [05-13|14:42:28.572] [1/14 Headers] Wrote block headers       number=12426337 blk/second=0.000 batch=0.00B alloc=1.12GiB    sys=1.53GiB   numGC=151
INFO [05-13|14:42:58.571] [1/14 Headers] Wrote block headers       number=12426337 blk/second=0.000 batch=0.00B alloc=856.25MiB  sys=1.53GiB   numGC=152
INFO [05-13|14:43:28.570] [1/14 Headers] Wrote block headers       number=12426337 blk/second=0.000 batch=0.00B alloc=1.13GiB    sys=1.53GiB   numGC=152
INFO [05-13|14:43:58.570] [1/14 Headers] Wrote block headers       number=12426337 blk/second=0.000 batch=0.00B alloc=812.61MiB  sys=1.53GiB   numGC=153
```

**Comment by AlexeyAkhunov** [comment]
Fixed by https://github.com/ledgerwatch/erigon/pull/1959
