### ISSUE TITLE
RPC daemon does not handle receipts correctly

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon#1948]
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock": "0xb71b00", "toBlock": "0xb74274", "address": "0x98c32b59a0ac00cd33750427b1a317ebcf84d0f7", "topics": ["0x0000000000000000000000000000000000000000000000000000000000000000"]}],"id":13}' localhost:8545
```

It returns empty result, which is correct:
```
{"jsonrpc":"2.0","id":13,"result":[]}
```

but I see this in the RPC daemon logs:

````
ERROR[05-17|12:42:41.170] logs fetching failed                     hash="903668…4b9f82" err="receipt unmarshal failed: 903668e4aabdfe3afaf95bb93777b1b005f47fe9b3fcd3972065e470a04b9f82, EOF"
ERROR[05-17|12:42:41.869] logs fetching failed                     hash="f11bfc…f8b9f1" err="receipt unmarshal failed: f11bfc562ce1bec149befc0e9e034ccf0924b01292b15375aa634a25c5f8b9f1, EOF"
ERROR[05-17|12:42:42.493] logs fetching failed                     hash="8e0bc9…358c96" err="receipt unmarshal failed: 8e0bc953a684c1a08882c4c26622a8609b5dee1f4ce6d71a0719130e9e358c96, EOF"
ERROR[05-17|12:42:43.112] logs fetching failed                     hash="9aeff9…219017" err="receipt unmarshal failed: 9aeff9a2425554a3626382a390c6b5038f61c35d374cd90637c19c0d04219017, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:42:43.732] logs fetching failed                     hash="0585e5…0622e9" err="receipt unmarshal failed: 0585e58079c220dbf7bd3890a45d4c55581abc9baf71602977c5dd193e0622e9, cbor decode error [pos 6]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:42:44.332] logs fetching failed                     hash="51c0d5…29133a" err="receipt unmarshal failed: 51c0d52d8491a1bb2b50518ab52c510d2947b9edd19bccadbc66e556c929133a, EOF"
ERROR[05-17|12:42:44.939] logs fetching failed                     hash="732417…a5ffe8" err="receipt unmarshal failed: 7324174a8688d167d684bcd40e732e2d135cac11a866c5deea654ac2aba5ffe8, EOF"
ERROR[05-17|12:42:45.584] logs fetching failed                     hash="b511cc…5d56d1" err="receipt unmarshal failed: b511ccbd408aca845f45d97c786d18570cfbf266274e22d7c133fd64da5d56d1, EOF"
ERROR[05-17|12:42:46.199] logs fetching failed                     hash="225c00…85f0bf" err="receipt unmarshal failed: 225c00f18b16fd968b91dc2198658e2eedc0d12a8b63bb7c79f64ac15985f0bf, EOF"
ERROR[05-17|12:42:46.850] logs fetching failed                     hash="61cb83…1a6e97" err="receipt unmarshal failed: 61cb83c63d697c2ed7e3f7e0f1c5c9b79b2d225e5e26ebd194e2f0cdf01a6e97, EOF"
ERROR[05-17|12:42:47.557] logs fetching failed                     hash="f67e72…a62c2a" err="receipt unmarshal failed: f67e72a2e9756edc2f87a744914a21bc82df81dd2c8699a4156f9e10e7a62c2a, EOF"
ERROR[05-17|12:42:48.166] logs fetching failed                     hash="81ac60…e6b00a" err="receipt unmarshal failed: 81ac600f7f1c737071c08a17fc516b6201b93313cfb98f502e529ac1afe6b00a, EOF"
ERROR[05-17|12:42:48.658] logs fetching failed                     hash="365c56…77b7da" err="receipt unmarshal failed: 365c568f58127f78dc47a8d2c4d23aae0e569495e2c63dcb048b250a0777b7da, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:42:49.219] logs fetching failed                     hash="27a60c…c8e7c5" err="receipt unmarshal failed: 27a60c192fe490741ecb97b1d6057dbd0f9c3c8c6ece3ea01aac9fb1e4c8e7c5, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:42:49.859] logs fetching failed                     hash="51b308…1be7e7" err="receipt unmarshal failed: 51b308650e4f99e5df918c864baa0d7465bac58030c91b7fe8ce1dce201be7e7, EOF"
ERROR[05-17|12:42:50.441] logs fetching failed                     hash="a71326…5f12e8" err="receipt unmarshal failed: a71326f689c2e44c5793798f0b3635d348310403892db6130bc02ddf4e5f12e8, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:42:51.112] logs fetching failed                     hash="48ea80…d4ae42" err="receipt unmarshal failed: 48ea806ab9b721ef6d3161be9e36474649b51d4d82deead102788be429d4ae42, EOF"
ERROR[05-17|12:42:51.765] logs fetching failed                     hash="079592…502369" err="receipt unmarshal failed: 079592b7bd4db99e8c261cb6a3c7e71dba06b461b58753f9663ceb706a502369, EOF"
ERROR[05-17|12:42:52.361] logs fetching failed                     hash="c98ac7…fc0780" err="receipt unmarshal failed: c98ac7fdc11ff5e5043bd5e5842a1173b774dd08217fc16aa1aa2aef95fc0780, EOF"
ERROR[05-17|12:42:53.005] logs fetching failed                     hash="361afb…6944d3" err="receipt unmarshal failed: 361afbcf9b99bac62b08aa40f5f203703eee805591fe817a932cbbf8296944d3, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:42:53.599] logs fetching failed                     hash="2f256f…ea7fe8" err="receipt unmarshal failed: 2f256f5541a827481bbcc6edf0563c076b25fc17fdb44f5273fa04c270ea7fe8, EOF"
ERROR[05-17|12:42:54.217] logs fetching failed                     hash="154f96…0c46ec" err="receipt unmarshal failed: 154f960679b7444be0a225e3a6e873c588ee6072f47800fd34e173187d0c46ec, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:42:54.847] logs fetching failed                     hash="599ad4…140b8a" err="receipt unmarshal failed: 599ad41faff6199e3ff58b7b32be5586af302b052d13aca70e5f703522140b8a, EOF"
ERROR[05-17|12:42:55.507] logs fetching failed                     hash="cf924b…0eb6f9" err="receipt unmarshal failed: cf924b3812bfc80871b14d998044b8e8015a02cd65e3c3ce6b5a3b1c5c0eb6f9, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:42:56.212] logs fetching failed                     hash="8dd6e5…c8d3aa" err="receipt unmarshal failed: 8dd6e5a20746dcb9d922f2992c711b2afdc472819f261daf1b5e2151b8c8d3aa, EOF"
ERROR[05-17|12:42:56.813] logs fetching failed                     hash="b3eba0…eb4636" err="receipt unmarshal failed: b3eba0d2fb5c42bd6c79803c2b895f789ff8c3206e45b7781609937e9ceb4636, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:42:57.447] logs fetching failed                     hash="a29a5a…8d35cd" err="receipt unmarshal failed: a29a5ad3e60886f5b0cd380d349d047883d2fa6fe70ba10a9f2c59b1f18d35cd, EOF"
ERROR[05-17|12:42:58.022] logs fetching failed                     hash="452f13…6509b6" err="receipt unmarshal failed: 452f136872e29d043d6c570bb73eb5acae9465c9e68bb006766ab3c83c6509b6, EOF"
ERROR[05-17|12:42:58.701] logs fetching failed                     hash="9c8e9d…3215d4" err="receipt unmarshal failed: 9c8e9d27504ad96cd8aca986b0805d4b2afb75876ec942371d2e50f69e3215d4, EOF"
ERROR[05-17|12:42:59.235] logs fetching failed                     hash="1d51e4…74fca8" err="receipt unmarshal failed: 1d51e40b9479ed38f36863625eb49148e562e7cf816be2e6fcf1fdad3174fca8, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:42:59.884] logs fetching failed                     hash="3f4752…d1ee5c" err="receipt unmarshal failed: 3f47522161b3aba96c624665b36fe29af2f211b785898957a8a71f89cdd1ee5c, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:43:00.511] logs fetching failed                     hash="0b728d…7e7f08" err="receipt unmarshal failed: 0b728de311eb7e30afaacc7c2071c59d90dd1555c71d30cfcecd479c457e7f08, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:43:01.079] logs fetching failed                     hash="b0ef53…e21fcc" err="receipt unmarshal failed: b0ef53d8bdba0febb03c504920d400d60dfa038c317b1808db127da523e21fcc, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:43:01.730] logs fetching failed                     hash="0b1fb9…3c0c6b" err="receipt unmarshal failed: 0b1fb9a8f3e0bd524fdfb179ca028ad9392c848698818a208a3d1a1cd63c0c6b, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:43:02.383] logs fetching failed                     hash="1ae245…e0134f" err="receipt unmarshal failed: 1ae2455413b73705b78c1eac44ebadf261e92d865fc413bc3a2e1d0e7ee0134f, EOF"
ERROR[05-17|12:43:03.126] logs fetching failed                     hash="8b6a3b…65cf16" err="receipt unmarshal failed: 8b6a3b231c2b4f57f0868b5aa1d9543c5dee514c3e0203ad93ae9db39665cf16, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:43:03.972] logs fetching failed                     hash="88d262…c308cd" err="receipt unmarshal failed: 88d2627c72a3f85e2e47f9ce618cbf1d45077e8acd42dd9ebab596754cc308cd, EOF"
ERROR[05-17|12:43:04.778] logs fetching failed                     hash="8f2c8b…898298" err="receipt unmarshal failed: 8f2c8b8446be0f3bf03fd1504568eb46ac08de5ed5566216f9a0f913f5898298, EOF"
ERROR[05-17|12:43:05.539] logs fetching failed                     hash="853034…51f59f" err="receipt unmarshal failed: 8530342e9f0197aa7ce2756e001756e974e77ffd25f0e1356501e42a1651f59f, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:43:06.249] logs fetching failed                     hash="f2945a…a73e87" err="receipt unmarshal failed: f2945abfcd3a52b8bac86d4aa6ee1076da4ccb3d6b14584c6a5b92a377a73e87, EOF"
ERROR[05-17|12:43:07.049] logs fetching failed                     hash="07c87d…eae3fe" err="receipt unmarshal failed: 07c87de32e3c3a1f3cdff5f3d83b02cd9733df29dce61accc808e449cbeae3fe, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:43:07.813] logs fetching failed                     hash="84d796…5e1321" err="receipt unmarshal failed: 84d7967788ba57494025fbbcfa0191b10a53608eb30db458229237a3f45e1321, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:43:08.525] logs fetching failed                     hash="3c36d2…da2fda" err="receipt unmarshal failed: 3c36d2ffcf7d3a6fd44b02bf4aece928e8915c7a089f191cee47ca812ada2fda, cbor decode error [pos 5]: only encoded map or array can be decoded into a slice (0)"
ERROR[05-17|12:43:09.259] logs fetching failed                     hash="2a4243…0e7ec2" err="receipt unmarshal failed: 2a42434e6edce10e2441f42895b761de4a9753faa2dd20bf36fc1695be0e7ec2, EOF"
ERROR[05-17|12:43:09.535] ReadHeaderRLP failed                     err=EOF
WARN [05-17|12:43:09.537] received unexpected error from server after CloseSend err="rpc error: code = Canceled desc = context canceled"
ERROR[05-17|12:43:09.537] RPC method eth_getLogs crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 2941 [running]:
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call.func1(0xc005690b23, 0xb, 0xc00868fcb0)
	github.com/ledgerwatch/turbo-geth/rpc/service.go:219 +0xbd
panic(0x4e0ccc0, 0x57f6a70)
	runtime/panic.go:965 +0x1b9
github.com/ledgerwatch/turbo-geth/core.ApplyTransaction(0xc000152580, 0xc004861200, 0x50f6cb8, 0xc00551c600, 0x0, 0xc004b8a270, 0xc004b82a50, 0x50ec878, 0x586af38, 0x0, ...)
	github.com/ledgerwatch/turbo-geth/core/state_processor.go:151 +0x3a
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.getReceipts(0x50e9cf0, 0xc005531e00, 0x50f5fc0, 0xc0062993e0, 0xc000152580, 0xb72093, 0xee1dc6e4e43422a, 0xde61b79528f44124, 0xbf20dda2fa53974a, 0xc27e0ebe9516fc36, ...)
	github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/eth_receipts.go:50 +0x712
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*APIImpl).GetLogs(0xc0000a6690, 0x50e9cf0, 0xc005531e00, 0x0, 0xc00554d980, 0xc00554d9a0, 0xc00552bd40, 0x1, 0x1, 0xc00569e348, ...)
	github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/eth_receipts.go:147 +0x866
reflect.Value.call(0xc000040b80, 0xc000222a38, 0x13, 0x4f6b79b, 0x4, 0xc00553da90, 0x3, 0x3, 0xc00553dac0, 0xc00569e318, ...)
	reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc000040b80, 0xc000222a38, 0x13, 0xc00553da90, 0x3, 0x3, 0x0, 0xc003593ba0, 0x43dedb4)
	reflect/value.go:337 +0xb9
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call(0xc000195680, 0x50e9cf0, 0xc005531e00, 0xc005690b23, 0xb, 0xc00569e318, 0x1, 0x1, 0xc006299200, 0x0, ...)
	github.com/ledgerwatch/turbo-geth/rpc/service.go:225 +0x392
github.com/ledgerwatch/turbo-geth/rpc.(*handler).runMethod(0xc005569950, 0x50e9cf0, 0xc005531e00, 0xc0001b4230, 0xc000195680, 0xc00569e318, 0x1, 0x1, 0xc006299200, 0x0)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:440 +0x15cc
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCall(0xc005569950, 0xc0056a0330, 0xc0001b4230, 0xc006299200, 0x203001)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:349 +0x25f
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCallMsg(0xc005569950, 0xc0056a0330, 0xc0001b4230, 0xc006299200, 0xc00032c000)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:303 +0x1cb
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleMsg.func1(0xc0056a0330)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:144 +0x4f
github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc.func1(0xc005569950, 0xc00554d940)
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:231 +0xd2
created by github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc
	github.com/ledgerwatch/turbo-geth/rpc/handler.go:227 +0x66
````

**Comment by AlexeyAkhunov** [comment]
Actually, these blocks were pre-Berlin

**Comment by AlexeyAkhunov** [comment]
This is most likely due to the bug that caused logs (receipts) not being written
