### ISSUE TITLE
Missing method RwKV

### ISSUE THREAD

**Issue by pcko1** [ledgerwatch/erigon#1973]
#### System information

Geth version: `1.10.1-stable`
OS & Version: `Ubuntu 20.04.2 LTS`
Commit hash : `50934fa5d` (`main`)

#### Actual behaviour

Sync breaks with the following error.

#### Steps to reproduce the behaviour

`sudo ./build/bin/tg --datadir /my/data/dir`

#### Backtrace

````
panic: interface conversion: *ethdb.LmdbKV is not ethdb.HasRwKV: missing method RwKV

goroutine 96 [running]:
github.com/ledgerwatch/turbo-geth/cmd/headers/download.(*ControlServerImpl).getBlockBodies(0xc0005130e0, 0x209b310, 0xc001249e00, 0xc006304aa0, 0x20ab750, 0xc0011518b0, 0x0, 0x0)
	github.com/ledgerwatch/turbo-geth/cmd/headers/download/downloader.go:477 +0x1bf
github.com/ledgerwatch/turbo-geth/cmd/headers/download.(*ControlServerImpl).HandleInboundMessage(0xc0005130e0, 0x209b310, 0xc001249e00, 0xc006304aa0, 0x20ab750, 0xc0011518b0, 0xc006edde98, 0xc006304aa0)
	github.com/ledgerwatch/turbo-geth/cmd/headers/download/downloader.go:556 +0x1ef
github.com/ledgerwatch/turbo-geth/cmd/headers/download.RecvUploadMessage(0x209b310, 0xc001249e00, 0x20ab750, 0xc0011518b0, 0xc0001189e0)
	github.com/ledgerwatch/turbo-geth/cmd/headers/download/downloader.go:78 +0x21b
created by github.com/ledgerwatch/turbo-geth/eth.(*Ethereum).Start
	github.com/ledgerwatch/turbo-geth/eth/backend.go:723 +0x171
````

**Comment by AlexeyAkhunov** [comment]
Thanks for reporting! For now please use the latest release version, we'll update you here when master is fixed!
