### ISSUE TITLE
RPC method eth_gasPrice crashed

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#2031]
Latest release.

Node is currently re-syncing but rpcdaemon is throwing errors:

```
ERROR[05-27|08:34:14.467] RPC method eth_gasPrice crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 8198 [running]:
github.com/ledgerwatch/erigon/rpc.(*callback).call.func1(0xc0040ab6f0, 0xc, 0xc003599cb0)
	github.com/ledgerwatch/erigon/rpc/service.go:219 +0xbd
panic(0x10dc5c0, 0x19f9fe0)
	runtime/panic.go:965 +0x1b9
math/big.(*Int).Cmp(0x0, 0xc0002890c0, 0xc004048fc0)
	math/big/int.go:328 +0x41
github.com/ledgerwatch/erigon/eth/gasprice.(*Oracle).SuggestPrice(0xc0040bc2a0, 0x13b2a90, 0xc0040bb580, 0x0, 0x0, 0x0)
	github.com/ledgerwatch/erigon/eth/gasprice/gasprice.go:161 +0x8eb
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*APIImpl).GasPrice(0xc000297590, 0x13b2a90, 0xc0040bb580, 0x0, 0x0, 0x0)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_system.go:88 +0x8d
reflect.Value.call(0xc0001d35c0, 0xc000010a10, 0x13, 0x12385b6, 0x4, 0xc0040c86f0, 0x2, 0x2, 0xc003707b18, 0x49054c, ...)
	reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0001d35c0, 0xc000010a10, 0x13, 0xc0040c86f0, 0x2, 0x2, 0x0, 0x0, 0x8)
	reflect/value.go:337 +0xb9
github.com/ledgerwatch/erigon/rpc.(*callback).call(0xc0001d3620, 0x13b2a90, 0xc0040bb580, 0xc0040ab6f0, 0xc, 0x1b5b7e8, 0x0, 0x0, 0xc0040c2c60, 0x0, ...)
	github.com/ledgerwatch/erigon/rpc/service.go:225 +0x392
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc0040b8990, 0x13b2a90, 0xc0040bb580, 0xc0040bc230, 0xc0001d3620, 0x1b5b7e8, 0x0, 0x0, 0xc0040c2c60, 0x0)
	github.com/ledgerwatch/erigon/rpc/handler.go:440 +0x15cc
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc0040b8990, 0xc0040c8690, 0xc0040bc230, 0xc0040c2c60, 0x203001)
	github.com/ledgerwatch/erigon/rpc/handler.go:349 +0x25f
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc0040b8990, 0xc0040c8690, 0xc0040bc230, 0xc0040c2c60, 0xc001300000)
	github.com/ledgerwatch/erigon/rpc/handler.go:303 +0x1cb
github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1(0xc0040c8690)
	github.com/ledgerwatch/erigon/rpc/handler.go:144 +0x4f
github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1(0xc0040b8990, 0xc0040c61c0)
	github.com/ledgerwatch/erigon/rpc/handler.go:231 +0xd2
created by github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc
	github.com/ledgerwatch/erigon/rpc/handler.go:227 +0x66
```

**Comment by AlexeyAkhunov** [comment]
Oh, this code keeps crashing :)

**Comment by AlexeyAkhunov** [comment]
Should be fixed by https://github.com/ledgerwatch/erigon/pull/2036

I removed all those concurrencies. That function was launching 20 go-routines, each to retrieve a block, sort its transactions, and then pick 3 with lowest gas price. Code that assumes that no-one else is running on the server :)

**Comment by MysticRyuujin** [comment]
I don't think this is fixed.

Everything just returns `0x0` when I call `eth_gasPrice`

**Comment by AskAlexSharov** [comment]
I think it's fixed (i tested during sync and after sync)
