### ISSUE TITLE
Sync stuck after initial cycle (with 2 remote sentries)

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon#2106]
#### System information

Connected to 2 remove sentries

OS & Version: Ubuntu Linux

Commit hash : `c0e84111394197e4be76dfa1c4647b55cb93c7e0`

#### Backtrace

````
goroutine 44 [select, 87 minutes]:
google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc01127c600)
        google.golang.org/grpc@v1.36.0/internal/transport/transport.go:321 +0x99
google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
        google.golang.org/grpc@v1.36.0/internal/transport/transport.go:336
google.golang.org/grpc.(*csAttempt).recvMsg(0xc00ef06400, 0x1526520, 0xc000cc6720, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.36.0/stream.go:915 +0x731
google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc00ef06400, 0xc0c709c370, 0xa2)
        google.golang.org/grpc@v1.36.0/stream.go:780 +0x46
google.golang.org/grpc.(*clientStream).withRetry(0xc00ef0aa20, 0xc004027740, 0xc004027710, 0xc012a982d0, 0x2b7d370)
        google.golang.org/grpc@v1.36.0/stream.go:638 +0x9f
google.golang.org/grpc.(*clientStream).RecvMsg(0xc00ef0aa20, 0x1526520, 0xc000cc6720, 0x0, 0x0)
        google.golang.org/grpc@v1.36.0/stream.go:779 +0x105
google.golang.org/grpc.invoke(0x205d4f0, 0xc00084ddc0, 0x16779e4, 0x18, 0x159b420, 0xc0089800f0, 0x1526520, 0xc000cc6720, 0xc000354e00, 0xc014ac60e0, ...)
        google.golang.org/grpc@v1.36.0/call.go:73 +0x142
google.golang.org/grpc.(*ClientConn).Invoke(0xc000354e00, 0x205d4f0, 0xc00084ddc0, 0x16779e4, 0x18, 0x159b420, 0xc0089800f0, 0x1526520, 0xc000cc6720, 0xc00d15c230, ...)
        google.golang.org/grpc@v1.36.0/call.go:37 +0x1b3
github.com/ledgerwatch/erigon/gointerfaces/sentry.(*sentryClient).SetStatus(0xc000c99e10, 0x205d4f0, 0xc00084ddc0, 0xc0089800f0, 0xc00d15c230, 0x1, 0x1, 0xc00d15c230, 0x0, 0xc01fc6a400)
        github.com/ledgerwatch/erigon/gointerfaces/sentry/sentry_grpc.pb.go:96 +0xd4
github.com/ledgerwatch/erigon/turbo/remote.(*SentryClientRemote).SetStatus(0xc001478140, 0x205d4f0, 0xc00084ddc0, 0xc0089800f0, 0xc00d15c230, 0x1, 0x1, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/erigon/turbo/remote/sentry_client.go:56 +0xba
github.com/ledgerwatch/erigon/cmd/sentry/download.(*ControlServerImpl).UpdateHead(0xc00048d1d0, 0x205d4f0, 0xc00084ddc0, 0xbfdc59, 0x2d90abe8455ebd45, 0xdfb67886dc8603ea, 0x18572bbe4891bdbc, 0x6cfca731938fc31a, 
0xc00f4aaca0)
        github.com/ledgerwatch/erigon/cmd/sentry/download/sentry_api.go:33 +0x1d6
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep(0x205d4f0, 0xc00084ddc0, 0x20676a8, 0xc0003501c0, 0xc0000ce580, 0x0, 0x285ace0, 0x205da68, 0xc00084dd40, 0x1edff01, ...)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:220 +0xa02
github.com/ledgerwatch/erigon/turbo/stages.StageLoop(0x205d4f0, 0xc00084ddc0, 0x20676a8, 0xc0003501c0, 0xc0000ce580, 0xc00048d0e0, 0x285ace0, 0x205da68, 0xc00084dd40, 0xc00010e800, ...)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:85 +0x18f
github.com/ledgerwatch/erigon/eth.Loop(0x205d4f0, 0xc00084ddc0, 0x20676a8, 0xc0003501c0, 0xc0000ce580, 0xc00048d1d0, 0x205da68, 0xc00084dd40, 0xc000c68100, 0xc00012c2a0)
        github.com/ledgerwatch/erigon/eth/backend.go:670 +0xd9
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
        github.com/ledgerwatch/erigon/eth/backend.go:628 +0x208
````

**Comment by AskAlexSharov** [comment]
`SetStatus` inside UpdateHead has no parameter `grpc.WaitForReady(true)` - don't know why it's stuck. Probably because Sentry accepted request but didn't respond. We need add deadline/timeout to contexts which used in all remote calls.

**Comment by AskAlexSharov** [comment]
1 Idea how it can happen: sentry accepted request but then dead-locked on mutex.

**Comment by AskAlexSharov** [comment]
you fixed it
