### ISSUE TITLE
rpc daemon panics pretty often under heavy load

### ISSUE THREAD

**Issue by wizzard0** [ledgerwatch/erigon#2260]
#### System information
Erigon version: `erigon version 2021.06.5-alpha`

OS & Version: Ubuntu 20.04

Commit hash: cc360ec65854d724873bb5907d239adff1b10559

#### Expected behaviour
rpc calls are served

#### Actual behaviour
daemon randomly crashes, serves the same requests OK after restart
```
./build/bin/rpcdaemon --private.api.addr=127.0.0.1:9090 --http.api=eth,erigon,debug,net,web3 --ws --http.corsdomain '*' --http.vhosts '*'
INFO [06-30|21:14:37.325] rpc filters: subscribing to Erigon events
INFO [06-30|21:14:37.325] HTTP endpoint opened                     url=****:8545 ws=true ws.compression=false
INFO [06-30|21:14:37.326] interfaces compatible                    remote_db=127.0.0.1:9090 client=3.0.0 server=3.0.0
INFO [06-30|21:14:37.326] interfaces compatible                    remote_service=eth_backend client=2.1.0 server=2.1.0
INFO [06-30|21:14:37.326] interfaces compatible                    remote_service=mining      client=1.0.0 server=1.0.0
INFO [06-30|21:14:37.327] interfaces compatible                    remote_service=tx_pool     client=1.0.0 server=1.0.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb9906e]

goroutine 612 [running]:
github.com/json-iterator/go.(*Stream).WriteObjectStart(...)
	github.com/json-iterator/go@v1.1.11/stream.go:148
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc003767440, 0x13c0a70, 0xc005eaca00, 0xc000286620, 0xc0033fa900, 0xc0060a0f90, 0x2, 0x2, 0x0, 0x0)
	github.com/ledgerwatch/erigon/rpc/handler.go:445 +0x4e
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc003767440, 0xc0060a0f30, 0xc000286620, 0x0, 0x203001)
	github.com/ledgerwatch/erigon/rpc/handler.go:392 +0x25f
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc003767440, 0xc0060a0f30, 0xc000286620, 0x0, 0xc005080000)
	github.com/ledgerwatch/erigon/rpc/handler.go:346 +0x1cb
github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1(0xc0060a0f30)
	github.com/ledgerwatch/erigon/rpc/handler.go:187 +0x4f
github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1(0xc003767440, 0xc006418040)
	github.com/ledgerwatch/erigon/rpc/handler.go:274 +0xd2
created by github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc
	github.com/ledgerwatch/erigon/rpc/handler.go:270 +0x66
```

#### Steps to reproduce the behaviour
Batch query all receipts/logs sequentially + do batch eth_call/debug_traceTransaction. May crash after the first 2-3 requests, may run for as long as tens of minutes. debug_traceTransaction crashes most often.

**Comment by AskAlexSharov** [comment]
Can't reproduce. Do you have bigger stack trace? Can you reproduce if add `--datadir` option to rpcdaemon?

**Comment by wizzard0** [comment]
This is the entire stack trace, on every crash. Will check with —datadir today

**Comment by wizzard0** [comment]
Same crash with --datadir + --private.api.addr and with just --datadir.

**Comment by AskAlexSharov** [comment]
@wizzard0 take a look into folder `<datadir>/crashreports` and upload here some files from there. thank.

**Comment by wizzard0** [comment]
Um, it's empty. Permissions on the folder look fine.

**Comment by AskAlexSharov** [comment]
It's not easy to support streamable methods on WS because of WS nature and 100 layers of abstractions. I added good error message for now: https://github.com/ledgerwatch/erigon/pull/2268
thank you
