### ISSUE TITLE
rpcdaemon crashes when serving debug_traceTransaction via Websocket

### ISSUE THREAD

**Issue by Troublor** [ledgerwatch/erigon#2337]
#### System information

Erigon version: `erigon version 2021.07.2-alpha`

OS & Version: Linux

Commit hash : 95ab8506bc3f1b115d1bddb3f8e73c3474e1c7ad (tag: v2021.07.02)

#### Expected behaviour

The rpcdaemon does not crash.

#### Actual behaviour

The rpcdaemon process crash: `panic: runtime error: invalid memory address or nil pointer dereference`
Similar to #2206 but my erigon node does not stuck on block processing, and it is not fixed in latest release. 

#### Steps to reproduce the behaviour

1. start rpcdaemon
2. send RPC call via **websocket**:
```json
{
    "id": 1337,
    "jsonrpc":"2.0",
    "method":"debug_traceTransaction",
    "params": [
        "0x755e9f215ab7d11aedff6c4f82c519aa13414d7653a7f2241de7b388a6771def",
        {
            "disableStorage": false,
            "disableMemory": true,
            "disableStack": false
        }
    ]
}
```

Rpcdaemon works fine with http connection.

#### Backtrace

```
INFO [07-10|16:20:33.762] DB schemas compatible                    reader=3.0.0 database=3.0.0
INFO [07-10|16:20:33.763] rpc filters: subscribing to Erigon events 
DEBUG[07-10|16:20:33.763] Allowed origin(s) for WS RPC interface [*] 
INFO [07-10|16:20:33.763] HTTP endpoint opened                     url=0.0.0.0:8545 ws=true ws.compression=true
INFO [07-10|16:20:33.764] interfaces compatible                    remote_db=localhost:9090 client=3.0.0 server=3.0.0
INFO [07-10|16:20:33.765] interfaces compatible                    remote_service=eth_backend client=2.1.0 server=2.1.0
INFO [07-10|16:20:33.765] interfaces compatible                    remote_service=mining      client=1.0.0 server=1.0.0
INFO [07-10|16:20:33.765] interfaces compatible                    remote_service=tx_pool     client=1.0.0 server=1.0.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb9274e]

goroutine 119 [running]:
github.com/json-iterator/go.(*Stream).WriteObjectStart(...)
        github.com/json-iterator/go@v1.1.11/stream.go:148
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc0002f21e0, 0x1393350, 0xc003554ac0, 0xc0034b96c0, 0xc003578d80, 0xc0035a4a20, 0x2, 0x2, 0x0, 0x0)
        github.com/ledgerwatch/erigon/rpc/handler.go:453 +0x4e
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc0002f21e0, 0xc0035a49c0, 0xc0034b96c0, 0x0, 0x203000)
        github.com/ledgerwatch/erigon/rpc/handler.go:400 +0x25f
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc0002f21e0, 0xc0035a49c0, 0xc0034b96c0, 0x0, 0xc001300400)
        github.com/ledgerwatch/erigon/rpc/handler.go:354 +0x1cb
github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1(0xc0035a49c0)
        github.com/ledgerwatch/erigon/rpc/handler.go:195 +0x4f
github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1(0xc0002f21e0, 0xc00338dd40)
        github.com/ledgerwatch/erigon/rpc/handler.go:282 +0xd2
created by github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc
        github.com/ledgerwatch/erigon/rpc/handler.go:278 +0x66
```

**Comment by AskAlexSharov** [comment]
thank you for reporting
It was fixed in last release (or later), but methods which do streaming of json - can't be used by websocket. 
https://github.com/ledgerwatch/erigon/issues/2269
