### ISSUE TITLE
txpool_content method handler crashed

### ISSUE THREAD

**Issue by twilightrus** [ledgerwatch/erigon#2425]
#### System information

Erigon version: `erigon version 2021.07.3-alpha`

OS & Version: Ubuntu 18.04

Network: Rinkeby

#### Expected behaviour
txpool_content returns success result

#### Actual behaviour
returns jsonrpc error with text: "method handler crashed"
in logs stacktrace:

```
ERROR[07-22|12:20:59.103] RPC method txpool_content crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 27361339 [running]:
github.com/ledgerwatch/erigon/rpc.(*callback).call.func1(0xc00456b2d0, 0xe, 0xc000155c78)
        github.com/ledgerwatch/erigon/rpc/service.go:219 +0xbd
panic(0x10b8f00, 0x1bb22c0)
        runtime/panic.go:965 +0x1b9
math/big.(*Int).Bits(...)
        math/big/int.go:87
github.com/holiman/uint256.(*Int).SetFromBig(0xc0001550c0, 0x0, 0x44)
        github.com/holiman/uint256@v1.2.0/conversion.go:102 +0x4b
github.com/holiman/uint256.FromBig(...)
        github.com/holiman/uint256@v1.2.0/conversion.go:50
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.newRPCTransaction(0x139c150, 0xc0044b1200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc005a71ba0)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_api.go:250 +0x476
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.newRPCPendingTransaction(...)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_api.go:271
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*TxPoolAPIImpl).Content(0xc0031c0e40, 0x13896f0, 0xc005ba2f80, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/txpool_api.go:81 +0xc85
reflect.Value.call(0xc003266a80, 0xc0000fcbd0, 0x13, 0x12106af, 0x4, 0xc003fb9e90, 0x2, 0x2, 0xc000062ae0, 0x49b32c, ...)
        reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc003266a80, 0xc0000fcbd0, 0x13, 0xc003fb9e90, 0x2, 0x2, 0x0, 0x0, 0x0)
        reflect/value.go:337 +0xb9
github.com/ledgerwatch/erigon/rpc.(*callback).call(0xc003266ae0, 0x13896f0, 0xc005ba2f80, 0xc00456b2d0, 0xe, 0x1c74d90, 0x0, 0x0, 0xc000097e60, 0x0, ...)
        github.com/ledgerwatch/erigon/rpc/service.go:226 +0x392
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc003fba8c0, 0x13896f0, 0xc005ba2f80, 0xc0002675e0, 0xc003266ae0, 0x1c74d90, 0x0, 0x0, 0xc000097e60, 0x0)
        github.com/ledgerwatch/erigon/rpc/handler.go:522 +0x1893
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc003fba8c0, 0xc003fb9e30, 0xc0002675e0, 0xc000097e60, 0xc00455b208)
        github.com/ledgerwatch/erigon/rpc/handler.go:427 +0x25f
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc003fba8c0, 0xc003fb9e30, 0xc0002675e0, 0xc000097e60, 0x18)
        github.com/ledgerwatch/erigon/rpc/handler.go:381 +0x1cb
github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1(0xc003fb9e30)
        github.com/ledgerwatch/erigon/rpc/handler.go:216 +0x7b
github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1(0xc003fba8c0, 0xc004578880)
        github.com/ledgerwatch/erigon/rpc/handler.go:309 +0xd2
created by github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc
        github.com/ledgerwatch/erigon/rpc/handler.go:305 +0x66
```

#### Steps to reproduce the behaviour
Run node in rinkeby and retrieve txpool_content. I think it happened after the london update in rinkeby.

**Comment by AskAlexSharov** [comment]
hi, here is the fix https://github.com/ledgerwatch/erigon/pull/2426

**Comment by AskAlexSharov** [comment]
fix released
