### ISSUE TITLE
RPC method trace_filter crashed on block 7111822

### ISSUE THREAD

**Issue by culmore2015** [ledgerwatch/erigon#2522]
#### System information

Erigon version: 2021.08.2-alpha

OS & Version: Ubuntu 20.10

Commit hash : 155186ad3e5d1c08ca947b354a9cd0907fb83308

#### Expected behaviour

```
{"jsonrpc":"2.0","result":[{"action":{"callType":"call","from":"0x14972f2e4cfb2c1b254d0adfc2b14c144b94d8d2","gas":"0x6f7c","input":"0xa9059cbb000000000000000000000000d4683486536f0baef318967dc1dd4fe669052a33000000000000000000000000000000000000000000000000000000007bcc8140","to":"0xe251524df2bc0b83716749dc71975f173a5ef35c","value":"0x0"},"blockHash":"0x660b581d9d2dab57abfa7a5dbe8bf9c2c4e50ffdaacc4faa4a0ee8deb272c8a7","blockNumber":7111822,"result":{"gasUsed":"0x6f2a","output": ...
```

#### Actual behaviour

```
{"jsonrpc":"2.0","id":1,"result":[{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"method handler crashed"}}
```

#### Steps to reproduce the behaviour

```
curl --data '{"method":"trace_filter","params":[{"fromBlock":"0x6c848e","toBlock":"0x6c848e"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```

#### Backtrace

````
RPC method trace_filter crashed: runtime error: index out of range [-1]
goroutine 26200 [running]:
github.com/ledgerwatch/erigon/rpc.(*callback).call.func1(0xc00047d724, 0xc, 0xc000655cd8)
        github.com/ledgerwatch/erigon/rpc/service.go:219 +0xbd
panic(0x112c0e0, 0xc000ca78a8)
        runtime/panic.go:965 +0x1b9
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*OeTracer).CaptureEnd(0xc000cf2000, 0x0, 0xc000ccda00, 0x20, 0x20, 0x10d88, 0x10b30, 0x1d3c, 0x0, 0x0, ...)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/trace_adhoc.go:338 +0xd05
github.com/ledgerwatch/erigon/core/vm.(*EVM).Call.func1(0xc000ce91e0, 0xc0006540b0, 0xc000654098, 0xc0006540d0, 0x10d88, 0xc03da93b836c4b3a, 0x131a7b712ae, 0x1992f60)
        github.com/ledgerwatch/erigon/core/vm/evm.go:234 +0xd4
github.com/ledgerwatch/erigon/core/vm.(*EVM).Call(0xc000ce91e0, 0x1316240, 0xc000ca7800, 0x0, 0x0, 0x3000000, 0x19cc1f8, 0x0, 0x0, 0x10b30, ...)
        github.com/ledgerwatch/erigon/core/vm/evm.go:286 +0x439
github.com/ledgerwatch/erigon/core.(*StateTransition).TransitionDb(0xc001ff0480, 0x1330001, 0xc000cece10, 0xc005f30db8, 0xc001ff0480)
        github.com/ledgerwatch/erigon/core/state_transition.go:338 +0x52a
github.com/ledgerwatch/erigon/core.ApplyMessage(0xc000ce91e0, 0x13346d8, 0xc000cece10, 0xc005f30db8, 0xaa4fccaafd0f0001, 0xa7c872b2dee80e4a, 0xf5cf0605, 0x7a1200)
        github.com/ledgerwatch/erigon/core/state_transition.go:189 +0x6d
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*TraceAPIImpl).doCallMany(0xc000112690, 0x1328ed8, 0xc00549eac0, 0x1334128, 0xc000598510, 0xc0005ec000, 0xdc, 0xdc, 0xc000c00a80, 0xdc, ...)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/trace_adhoc.go:1152 +0xdb3
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*TraceAPIImpl).callManyTransactions(0xc000112690, 0x1328ed8, 0xc00549eac0, 0x1334128, 0xc000598510, 0xc000577000, 0xdc, 0xdc, 0xc0010e2c90, 0x1, ...)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/trace_filtering.go:433 +0x53a
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*TraceAPIImpl).Filter(0xc000112690, 0x1328ed8, 0xc00549eac0, 0xc00047d760, 0xc00047d768, 0x0, 0x0, 0x0, 0xc000769f20, 0x1, ...)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/trace_filtering.go:296 +0x1e35
reflect.Value.call(0xc00078a180, 0xc000110c10, 0x13, 0x11b5df0, 0x4, 0xc002926e10, 0x4, 0x6, 0x6, 0x48, ...)
        reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc00078a180, 0xc000110c10, 0x13, 0xc002926e10, 0x4, 0x6, 0x3, 0x6, 0x0)
        reflect/value.go:337 +0xb9
github.com/ledgerwatch/erigon/rpc.(*callback).call(0xc0004f9080, 0x1328ed8, 0xc00549eac0, 0xc00047d724, 0xc, 0xc002224cf0, 0x1, 0x1, 0xc00072aae0, 0x0, ...)
        github.com/ledgerwatch/erigon/rpc/service.go:226 +0x392
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc003dd86e0, 0x1328ed8, 0xc00549eac0, 0xc0001a64d0, 0xc0004f9080, 0xc002224cf0, 0x1, 0x1, 0xc00072aae0, 0x0)
        github.com/ledgerwatch/erigon/rpc/handler.go:488 +0x54f
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc003dd86e0, 0xc000598390, 0xc0001a64d0, 0xc00072aae0, 0xc002926d88)
        github.com/ledgerwatch/erigon/rpc/handler.go:428 +0x25f
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc003dd86e0, 0xc000598390, 0xc0001a64d0, 0xc00072aae0, 0x18)
        github.com/ledgerwatch/erigon/rpc/handler.go:382 +0x1cb
github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1(0xc000598390)
        github.com/ledgerwatch/erigon/rpc/handler.go:217 +0x7b
github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1(0xc003dd86e0, 0xc000769ee0)
        github.com/ledgerwatch/erigon/rpc/handler.go:310 +0xd2
created by github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc
        github.com/ledgerwatch/erigon/rpc/handler.go:306 +0x66
````

**Comment by AlexeyAkhunov** [comment]
thanks for the report, fixing

**Comment by culmore2015** [comment]
I just resync the block by adding ```--bad.block 7111822``` to sloved the problem. But it will takes another couple of days to sync.

**Comment by AlexeyAkhunov** [comment]
I don't think you needed to do resync, the problem was just in RPC daemon, regression introduced when I was adding `vmTrace` support this week

**Comment by culmore2015** [comment]
Great help,  thanks !
