### ISSUE TITLE
trace_block report error on block 146675

### ISSUE THREAD

**Issue by alexlee85** [ledgerwatch/erigon#2571]
#### System information

Erigon version: 
```
erigon version 2021.08.2-alpha
```

OS & Version: Windows/Linux/OSX

Commit hash : 
```
commit 155186ad3e5d1c08ca947b354a9cd0907fb83308 (HEAD -> v2021.08.02, tag: v2021.08.02, origin/stable)
```

#### Expected behaviour
get block trace result

#### Actual behaviour
report error:
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "method handler crashed"
  }
}
```

#### Steps to reproduce the behaviour
```
send a trace_block request
{
    "method": "trace_block",
    "params": ["0x23cf3"],
    "id": 1,
    "jsonrpc": "2.0"
}
```

#### Backtrace

````
[backtrace]
EROR[08-23|19:42:30] RPC method trace_block crashed: runtime error: index out of range [-1]
goroutine 9297011 [running]:
github.com/ledgerwatch/erigon/rpc.(*callback).call.func1(0xc000a78560, 0xb, 0xc0002ddcd8)
        github.com/ledgerwatch/erigon/rpc/service.go:219 +0xbd
panic(0x111b020, 0xc000dc2a50)
        runtime/panic.go:965 +0x1b9
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*OeTracer).CaptureEnd(0xc001026680, 0x0, 0x0, 0x0, 0x0, 0x39348, 0x38790, 0x4798, 0x0, 0x0, ...)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/trace_adhoc.go:338 +0xd05
github.com/ledgerwatch/erigon/core/vm.(*EVM).Call.func1(0xc00081c2c0, 0xc0002dc3a0, 0xc0002dc388, 0xc0002dc3c0, 0x39348, 0xc04100499229783f, 0x31b504352d5, 0x1b7bf60)
        github.com/ledgerwatch/erigon/core/vm/evm.go:234 +0xd4
github.com/ledgerwatch/erigon/core/vm.(*EVM).Call(0xc00081c2c0, 0x1305180, 0xc000dc29d8, 0x0, 0x0, 0x1000000, 0xc000dd2380, 0x314, 0x314, 0x38790, ...)
        github.com/ledgerwatch/erigon/core/vm/evm.go:286 +0x439
github.com/ledgerwatch/erigon/core.(*StateTransition).TransitionDb(0xc00174b4d0, 0x1320001, 0xc000808d20, 0xc000a78ae0, 0xc00174b4d0)
        github.com/ledgerwatch/erigon/core/state_transition.go:338 +0x52a
github.com/ledgerwatch/erigon/core.ApplyMessage(0xc00081c2c0, 0x1323618, 0xc000808d20, 0xc000a78ae0, 0xeb2b8044cbf00001, 0xbf0b4357b50a1b2f, 0xca6b47d5, 0x2fefd8)
        github.com/ledgerwatch/erigon/core/state_transition.go:189 +0x6d
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*TraceAPIImpl).doCallMany(0xc000290ba0, 0x1317e18, 0xc0007a8640, 0x1323068, 0xc000ad2ae0, 0xc00023ca80, 0xa, 0xa, 0xc000210f00, 0xa, ...)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/trace_adhoc.go:1152 +0xdb3
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*TraceAPIImpl).callManyTransactions(0xc000290ba0, 0x1317e18, 0xc0007a8640, 0x1323068, 0xc000ad2ae0, 0xc0005c7e00, 0xa, 0xa, 0xc000fb0550, 0x1, ...)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/trace_filtering.go:433 +0x53a
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*TraceAPIImpl).Block(0xc000290ba0, 0x1317e18, 0xc0007a8640, 0x23cf3, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/trace_filtering.go:145 +0x472
reflect.Value.call(0xc0005d5c00, 0xc0002988c0, 0x13, 0x11a4d30, 0x4, 0xc0008563c0, 0x3, 0x3, 0xc0008563f0, 0xc000ece408, ...)
        reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0005d5c00, 0xc0002988c0, 0x13, 0xc0008563c0, 0x3, 0x3, 0x102b2a0, 0x12e9840, 0x0)
        reflect/value.go:337 +0xb9
github.com/ledgerwatch/erigon/rpc.(*callback).call(0xc0001f2a80, 0x1317e18, 0xc0007a8640, 0xc000a78560, 0xb, 0xc000ece408, 0x1, 0x1, 0xc0009e4ae0, 0x0, ...)
        github.com/ledgerwatch/erigon/rpc/service.go:226 +0x392
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc0005c7d60, 0x1317e18, 0xc0007a8640, 0xc0004c20e0, 0xc0001f2a80, 0xc000ece408, 0x1, 0x1, 0xc0009e4ae0, 0x0)
        github.com/ledgerwatch/erigon/rpc/handler.go:523 +0xb2c
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc0005c7d60, 0xc000ad2a50, 0xc0004c20e0, 0xc0009e4ae0, 0xc00174aa28)
        github.com/ledgerwatch/erigon/rpc/handler.go:428 +0x25f
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc0005c7d60, 0xc000ad2a50, 0xc0004c20e0, 0xc0009e4ae0, 0x18)
        github.com/ledgerwatch/erigon/rpc/handler.go:382 +0x1cb
github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1(0xc000ad2a50)
        github.com/ledgerwatch/erigon/rpc/handler.go:217 +0x7b
github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1(0xc0005c7d60, 0xc0005ae4e0)
        github.com/ledgerwatch/erigon/rpc/handler.go:310 +0xd2
created by github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc
        github.com/ledgerwatch/erigon/rpc/handler.go:306 +0x66
````

**Comment by AskAlexSharov** [comment]
Do you use —prune flag?

**Comment by alexlee85** [comment]
no, my start cmd is:
```
./bin/erigon --port=30305 --datadir=/opt/ethnode/erigon/data --private.api.addr=localhost:9090
```

**Comment by alexlee85** [comment]
after upgrade to v2021.08.03 problem resolved.
