### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by jsvisa** [ledgerwatch/erigon#2631]
#### System information

Erigon version: `./erigon --version`

```bash
$ ./bin/erigon --version
erigon version 2021.09.2-alpha
```

OS & Version: Windows/Linux/OSX

Commit hash : 

#### Expected behaviour

no panic occured

#### Actual behaviour

```bash
panic: runtime error: index out of range [1] with length 1

goroutine 110 [running]:
encoding/binary.bigEndian.Uint16(...)
        encoding/binary/binary.go:101
github.com/ledgerwatch/erigon/turbo/trie.UnmarshalTrieNode({0x7d68bd41613c, 0x28, 0x28})
        github.com/ledgerwatch/erigon/turbo/trie/trie_root.go:1429 +0x1ec
github.com/ledgerwatch/erigon/turbo/trie.(*StorageTrieCursor)._unmarshal(0xc00053e438, {0x7d68bd416114, 0xb4f236b9aa5f8542, 0x8601eae92ae0a3c0}, {0x7d68bd41613c, 0x56323311a8fe57b4, 0xf236b9aa5f8542})
        github.com/ledgerwatch/erigon/turbo/trie/trie_root.go:1300 +0x179
github.com/ledgerwatch/erigon/turbo/trie.(*StorageTrieCursor)._seek(0xc00053e438, {0xc0828c53a8, 0xa83bbe, 0x7e77dac2eed0}, {0xc00053d077, 0x0, 0x40})
        github.com/ledgerwatch/erigon/turbo/trie/trie_root.go:1156 +0x20f
github.com/ledgerwatch/erigon/turbo/trie.(*StorageTrieCursor).SeekToAccount(0xc00053e438, {0xc0828c53a8, 0x28, 0x28})
        github.com/ledgerwatch/erigon/turbo/trie/trie_root.go:1035 +0x2ce
github.com/ledgerwatch/erigon/turbo/trie.(*FlatDBTrieLoader).CalcTrieRoot(0xc0828c5380, {0x1e34748, 0xc05099bbc0}, {0x2b4b520, 0x41, 0x
0}, 0xc000578000)
        github.com/ledgerwatch/erigon/turbo/trie/trie_root.go:256 +0xd45
github.com/ledgerwatch/erigon/eth/stagedsync.incrementIntermediateHashes({0xc003fa0a68, 0xc01c196960}, 0xc01c19ee20, {0x1e41230, 0xc05099bbc0}, 0x0, {{0x1e1ed20, 0xc000368540}, 0x1, {0xc000334240, ...}, ...}, ...)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_interhashes.go:366 +0x631
github.com/ledgerwatch/erigon/eth/stagedsync.SpawnIntermediateHashesStage(0xc01c19ee20, {0x1df5d20, 0xc0002e96b0}, {0x0, 0x0}, {{0x1e1ed20, 0xc000368540}, 0x1, {0xc000334240, 0x15}, ...}, ...)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_interhashes.go:85 +0x7ed
github.com/ledgerwatch/erigon/eth/stagedsync.DefaultStages.func31(0xb0, 0x96, 0x13adf71, {0x1df5d20, 0xc0002e96b0}, {0x0, 0x0})
        github.com/ledgerwatch/erigon/eth/stagedsync/default_stages.go:178 +0x85
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc0002e96b0, 0xc000534640, {0x1e1ed20, 0xc000368540}, {0x0, 0x0}, 0x0, 0x0)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:316 +0x14d
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc0002e96b0, {0x1e1ed20, 0xc000368540}, {0x0, 0x0}, 0xf0)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:233 +0x2a5
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x1e16fd8, 0xc00020f480}, {0x1e1ed20, 0xc000368540}, 0xc0002e96b0, 0x0, 0xc00082e920, 0x1, 0xc00037b4e0, 0x0)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:127 +0x42b
github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x1e16fd8, 0xc00020f480}, {0x1e1ed20, 0xc000368540}, 0x0, 0xc0000ebd90, 0xc0000ebfd0, 0xc45426, 0xc0000e4f00, 0x0)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:54 +0x15f
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
        github.com/ledgerwatch/erigon/eth/backend.go:660 +0x3d8
```

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
@jsvisa - did restart help you? Will try to check it tomorrow.

**Comment by jsvisa** [comment]
I'm sorry, not the restart didn't solve this issue.

**Comment by AskAlexSharov** [comment]
@jsvisa as a hotfix you can do:
```
stop erigon

./build/bin/integration stage_trie --datadir=<your_datadir> --reset

start erigon
```

Is it mainnet?

**Comment by jsvisa** [comment]
Thanks for your advice, I'll give it a try.

It's the mainnet

**Comment by jsvisa** [comment]
> @jsvisa as a hotfix you can do:
> 
> ```
> 
> stop erigon
> 
> 
> 
> ./build/bin/integration stage_trie --datadir=<your_datadir> --reset
> 
> 
> 
> start erigon
> 
> ```
> 
> 
> 
> Is it mainnet?

After stage_trie, the panic issue solved
