### ISSUE TITLE
Recovering a node that got stuck after the London hard fork

### ISSUE THREAD

**Issue by alcuadrado** [ledgerwatch/erigon#2647]
Hi,

I forgot to update my Erigon instance before the London HF. I did it yesterday, but the it seems to be stuck now. 

It hasn't progressed from block number 13107517, and and the logs always look like this:

```
Sep 08 13:09:10 puc erigon[57953]: [INFO] [09-08|13:09:10.928] Regenerated local transaction journal    transactions=0 accounts=0
Sep 08 13:09:14 puc erigon[57953]: [INFO] [09-08|13:09:14.062] [1/18 Headers] Wrote block headers       number=13107517 blk/second=0.000 alloc="662.51 MiB" sys="5.20 GiB"
Sep 08 13:09:44 puc erigon[57953]: [INFO] [09-08|13:09:44.061] [1/18 Headers] Wrote block headers       number=13107517 blk/second=0.000 alloc="749.37 MiB" sys="5.20 GiB"
Sep 08 13:09:44 puc erigon[57953]: [INFO] [09-08|13:09:44.062] [1/18 Headers] Processed                 highest inserted=0 age=52y5mo1w
Sep 08 13:09:44 puc erigon[57953]: [INFO] [09-08|13:09:44.062] [1/18 Headers] DONE                      in=2m30.001269265s
Sep 08 13:09:44 puc erigon[57953]: [INFO] [09-08|13:09:44.064] Update current block for the RPC API     from=13107518 to=13107517
Sep 08 13:09:44 puc erigon[57953]: [INFO] [09-08|13:09:44.064] [1/18 Headers] Waiting for headers...    from=13107517
Sep 08 13:09:54 puc erigon[57953]: [INFO] [09-08|13:09:54.154] [p2p] GoodPeers                          eth66=30 eth65=26
Sep 08 13:10:14 puc erigon[57953]: [INFO] [09-08|13:10:14.066] [1/18 Headers] Wrote block headers       number=13107517 blk/second=0.000 alloc="823.32 MiB" sys="5.20 GiB"
```

Is there a way to recover it? Or do I have to resync?

Thanks

**Comment by AskAlexSharov** [comment]
- Upgrade
- Start with --bad.block=0xcabd9194507f1d4305f510d9b6a51d0816abca1290050d0f575c9301c357021a 
- Wait and see if it will sync well 
- Restart without  --bad.block parameter

**Comment by alcuadrado** [comment]
I'm getting this error with 2021.09.02

```
EROR[09-09|16:51:19.781] catch panic                              err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 1 [running]: runtime/debug.Stack(0xc000027fd0, 0x1452940, 0x284ae50) runtime/debug/stack.go:24 +0x9f github.com/ledgerwatch/erigon/common/debug.LogPanic() github.com/ledgerwatch/erigon/common/debug/log_panic.go:63 +0x6a panic(0x1452940, 0x284ae50) runtime/panic.go:965 +0x1b9 github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).UnwindTo(0x0, 0xc8013d, 0x431d7f509491bdca, 0x81da5b6d910f505, 0xf0d059012caab16, 0x1a0257c301935c57) github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:109 +0x17c github.com/ledgerwatch/erigon/eth.New(0xc0002d4370, 0x285fec0, 0x209f8f8, 0xc0002a2fc0, 0xc000cd5b00, 0x11fcd9f, 0xc00013a160) github.com/ledgerwatch/erigon/eth/backend.go:372 +0x312b github.com/ledgerwatch/erigon/turbo/node.RegisterEthService(...) github.com/ledgerwatch/erigon/turbo/node/node.go:107 github.com/ledgerwatch/erigon/turbo/node.New(0xc000168300, 0x285fec0, 0x209f8f8, 0xc0002a2fc0, 0x6, 0x6, 0x7f6d48629428) github.com/ledgerwatch/erigon/turbo/node/node.go:98 +0x65 main.runErigon(0xc00013a160) github.com/ledgerwatch/erigon/cmd/erigon/main.go:31 +0x233 github.com/urfave/cli.HandleAction(0x13dc2e0, 0x1f171c8, 0xc00013a160, 0xc00013a160, 0x0) github.com/urfave/cli@v1.22.5/app.go:526 +0x59 github.com/urfave/cli.(*App).Run(0xc0001ea700, 0xc00003c080, 0x4, 0x4, 0x0, 0x0) github.com/urfave/cli@v1.22.5/app.go:286 +0x675 main.main() github.com/ledgerwatch/erigon/cmd/erigon/main.go:18 +0xa9 "
```

**Comment by AskAlexSharov** [comment]
ouch. this is merge-conflict. fixed by https://github.com/ledgerwatch/erigon/pull/2657

**Comment by alcuadrado** [comment]
Thanks, my node is now on sync, using 2021.09.03.
