### ISSUE TITLE
RPC method web3_clientVersion crashed

### ISSUE THREAD

**Issue by quickchase** [ledgerwatch/erigon#2753]
web3_clientVersion is crashing - Alexey confirmed on his end - and I confirmed on 2 different servers:

Latest Stable Release:

```
curl -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' localhost:8545

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"method handler crashed"}}

[EROR] [09-30|09:29:30.673] RPC method web3_clientVersion crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 168 [running]:
github.com/ledgerwatch/erigon/rpc.(*callback).call.func1(0xc000125f98, 0x12, 0xc00006fd28)
	github.com/ledgerwatch/erigon/rpc/service.go:219 +0xbd
panic(0x10803e0, 0x192f1b0)
	runtime/panic.go:965 +0x1b9
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*Web3APIImpl).ClientVersion(0xc00000e078, 0x1340618, 0xc000043e40, 0x0, 0x0, 0x0, 0x0)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/web3_api.go:32 +0x2a
reflect.Value.call(0xc0005808a0, 0xc0000108c0, 0x13, 0x11caf4b, 0x4, 0xc0006b7200, 0x2, 0x2, 0xc00006fb90, 0x4b1fcc, ...)
	reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0005808a0, 0xc0000108c0, 0x13, 0xc0006b7200, 0x2, 0x2, 0x104d500, 0x1311dd8, 0x0)
	reflect/value.go:337 +0xb9
github.com/ledgerwatch/erigon/rpc.(*callback).call(0xc000580900, 0x1340618, 0xc000043e40, 0xc000125f98, 0x12, 0x19f2a58, 0x0, 0x0, 0xc000581c80, 0x0, ...)
	github.com/ledgerwatch/erigon/rpc/service.go:226 +0x392
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc000197c20, 0x1340618, 0xc000043e40, 0xc00068ed90, 0xc000580900, 0x19f2a58, 0x0, 0x0, 0xc000581c80, 0x0)
	github.com/ledgerwatch/erigon/rpc/handler.go:491 +0xb2c
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc000197c20, 0xc0006b71a0, 0xc00068ed90, 0xc000581c80, 0x203000)
	github.com/ledgerwatch/erigon/rpc/handler.go:396 +0x25f
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc000197c20, 0xc0006b71a0, 0xc00068ed90, 0xc000581c80, 0x18)
	github.com/ledgerwatch/erigon/rpc/handler.go:350 +0x1a5
github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1(0xc0006b71a0)
	github.com/ledgerwatch/erigon/rpc/handler.go:185 +0x7b
github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1(0xc000197c20, 0xc00048fe20)
	github.com/ledgerwatch/erigon/rpc/handler.go:278 +0xd2
created by github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc
	github.com/ledgerwatch/erigon/rpc/handler.go:274 +0x66
```

**Comment by briancolecoinmetrics** [comment]
We're seeing the same problem in logs on  2021.09.05, but also this trailing warning line:
```
[EROR] [09-30|20:46:27.500] RPC method web3_clientVersion crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 160 [running]:
github.com/ledgerwatch/erigon/rpc.(*callback).call.func1(0xc000039ce0, 0x12, 0xc0000b8d28)
        github.com/ledgerwatch/erigon/rpc/service.go:219 +0xbd
panic(0x1089400, 0x1938bb0)
        runtime/panic.go:965 +0x1b9
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*Web3APIImpl).ClientVersion(0xc0001286d8, 0x1349798, 0xc0002a0540, 0x0, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/web3_api.go:32 +0x2a
reflect.Value.call(0xc0004b4600, 0xc000110920, 0x13, 0x11d408b, 0x4, 0xc000d96e10, 0x2, 0x2, 0xc0000b8b90, 0x4aa4ac, ...)
        reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0004b4600, 0xc000110920, 0x13, 0xc000d96e10, 0x2, 0x2, 0x10565e0, 0x131af58, 0x0)
        reflect/value.go:337 +0xb9
github.com/ledgerwatch/erigon/rpc.(*callback).call(0xc0004b4660, 0x1349798, 0xc0002a0540, 0xc000039ce0, 0x12, 0x19fc498, 0x0, 0x0, 0xc0004b5740, 0x0, ...)
        github.com/ledgerwatch/erigon/rpc/service.go:226 +0x392
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc0007c6640, 0x1349798, 0xc0002a0540, 0xc0007bc1c0, 0xc0004b4660, 0x19fc498, 0x0, 0x0, 0xc0004b5740, 0x0)
        github.com/ledgerwatch/erigon/rpc/handler.go:491 +0xb2c
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc0007c6640, 0xc000d96db0, 0xc0007bc1c0, 0xc0004b5740, 0x203000)
        github.com/ledgerwatch/erigon/rpc/handler.go:396 +0x25f
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc0007c6640, 0xc000d96db0, 0xc0007bc1c0, 0xc0004b5740, 0x18)
        github.com/ledgerwatch/erigon/rpc/handler.go:350 +0x1a5
github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1(0xc000d96db0)
        github.com/ledgerwatch/erigon/rpc/handler.go:185 +0x7b
github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1(0xc0007c6640, 0xc0008f8420)
        github.com/ledgerwatch/erigon/rpc/handler.go:278 +0xd2
created by github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc
        github.com/ledgerwatch/erigon/rpc/handler.go:274 +0x66
 
[WARN] [09-30|20:46:27.500] Served                                   conn=10.0.1.103:41424 method=web3_clientVersion reqid=56465 t=325.254µs err="method handler crashed"
```
Not sure if that means anything or not.

**Comment by AskAlexSharov** [comment]
fixed in devel I think

**Comment by briancolecoinmetrics** [comment]
We can confirm that 2021.10.01 appears to have resolved this.
