### ISSUE TITLE
Erigon crashing after 10.01 upgrade, "erigon: mdbx:9683: mdbx_page_alloc: Assertion `((re_list)[((re_list)[0])]) < txn->mt_geo.next && ((re_list)[1]) < txn->mt_geo.next' failed."

### ISSUE THREAD

**Issue by NessDan** [ledgerwatch/erigon#2777]
#### System information

Erigon version: `erigon version 2021.10.1-alpha`

OS & Version: Ubuntu Linux 21.04

Commit hash : `ef80fd54b1c6c82aae92f5fa24cbd381e8577b50`

#### Expected behaviour

Erigon loads and properly runs

#### Actual behaviour

Erigon loads, starts to "event subscription channel established with the RPC daemon", and then promptly crashes with a key error:

```
erigon: mdbx:9683: mdbx_page_alloc: Assertion `((re_list)[((re_list)[0])]) < txn->mt_geo.next && ((re_list)[1]) < txn->mt_geo.next' failed.`
```

#### Steps to reproduce the behaviour

1. Update Erigon to the latest version,
2. Run the RPC Client, `./rpcdaemon --datadir /home/erigon/data/ --private.api.addr=localhost:9090`
2. Run Erigon, `./erigon --datadir /home/erigon/data --private.api.addr=localhost:9090`
3. Observe the logs.

#### Backtrace

[Full stack trace attached to the issue.](https://github.com/ledgerwatch/erigon/files/7281152/erigon-stacktrace-10.04-error.txt)

````
Oct 04 20:22:35 beafy erigon[22602]: [INFO] [10-04|20:22:35.993] Build info                               git_branch=HEAD git_tag=v2021.10.01 git_commit=ef80fd54b1c6c82aae92f5fa24cbd381e8577b50
Oct 04 20:22:35 beafy erigon[22602]: [INFO] [10-04|20:22:35.993] Starting Erigon on Ethereum mainnet...
Oct 04 20:22:35 beafy erigon[22602]: [INFO] [10-04|20:22:35.994] Maximum peer count                       ETH=100 total=100
Oct 04 20:22:35 beafy erigon[22602]: [INFO] [10-04|20:22:35.994] Set global gas cap                       cap=50000000
Oct 04 20:22:36 beafy erigon[22602]: [INFO] [10-04|20:22:36.043] Opening Database                         label=chaindata path=/home/erigon/data/chaindata
Oct 04 20:22:36 beafy erigon[22602]: mdbx_ipclock_failed:29740 wlock owner died, recovering
Oct 04 20:22:36 beafy erigon[22602]: [INFO] [10-04|20:22:36.044] Initialised chain configuration          config="{ChainID: 1  1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Engine: ethash}"
Oct 04 20:22:36 beafy erigon[22602]: [INFO] [10-04|20:22:36.044] Disk storage enabled for ethash DAGs     dir=/home/erigon/data/ethash-dags count=2
Oct 04 20:22:36 beafy erigon[22602]: [INFO] [10-04|20:22:36.044] Initialising Ethereum protocol           network=1
Oct 04 20:22:36 beafy erigon[22602]: [INFO] [10-04|20:22:36.044] Effective                                prune="--prune="
Oct 04 20:22:36 beafy erigon[22602]: [INFO] [10-04|20:22:36.672] Starting private RPC server              on=localhost:9090
Oct 04 20:22:36 beafy erigon[22602]: [INFO] [10-04|20:22:36.673] [1/18 Headers] Waiting for headers...    from=13354674
Oct 04 20:22:36 beafy erigon[22602]: [INFO] [10-04|20:22:36.686] Mapped network port                      proto=tcp extport=30303 intport=30303 interface=NAT-PMP(192.168.1.1)
Oct 04 20:22:36 beafy erigon[22602]: [INFO] [10-04|20:22:36.689] Mapped network port                      proto=udp extport=30303 intport=30303 interface=NAT-PMP(192.168.1.1)
Oct 04 20:22:36 beafy erigon[22602]: [INFO] [10-04|20:22:36.694] Mapped network port                      proto=tcp extport=30304 intport=30304 interface=NAT-PMP(192.168.1.1)
Oct 04 20:22:36 beafy erigon[22602]: [INFO] [10-04|20:22:36.698] Mapped network port                      proto=udp extport=30304 intport=30304 interface=NAT-PMP(192.168.1.1)
Oct 04 20:22:36 beafy erigon[22602]: [INFO] [10-04|20:22:36.731] Started P2P networking                   version=66 self=enode://11411322e260a7454774ec32b66450e31b87a6879a61b0359841a44d2c17babf65171744529c24c6ae10f1859f7d02d1c3ac06e6e6b6abb0cae0ac5ea660673c@67.149.151.142:30303 name=erigon/v2021.10.1-alpha-ef80fd54/linux-amd64/go1.16.4
Oct 04 20:22:36 beafy erigon[22602]: [INFO] [10-04|20:22:36.753] Started P2P networking                   version=65 self=enode://11411322e260a7454774ec32b66450e31b87a6879a61b0359841a44d2c17babf65171744529c24c6ae10f1859f7d02d1c3ac06e6e6b6abb0cae0ac5ea660673c@67.149.151.142:30304 name=erigon/v2021.10.1-alpha-ef80fd54/linux-amd64/go1.16.4
Oct 04 20:22:37 beafy erigon[22602]: [INFO] [10-04|20:22:37.515] event subscription channel established with the RPC daemon
Oct 04 20:22:55 beafy erigon[22602]: erigon: mdbx:9683: mdbx_page_alloc: Assertion `((re_list)[((re_list)[0])]) < txn->mt_geo.next && ((re_list)[1]) < txn->mt_geo.next' failed.
Oct 04 20:22:55 beafy erigon[22602]: SIGABRT: abort
Oct 04 20:22:55 beafy erigon[22602]: PC=0x7f4c66229fbb m=30 sigcode=18446744073709551610
Oct 04 20:22:55 beafy erigon[22602]: signal arrived during cgo execution
Oct 04 20:22:55 beafy erigon[22602]: goroutine 191 [syscall, locked to thread]:
Oct 04 20:22:55 beafy erigon[22602]: runtime.cgocall(0x1219bd0, 0xc0023c0b78, 0xc00b0b1f00)
Oct 04 20:22:55 beafy erigon[22602]:         runtime/cgocall.go:154 +0x5b fp=0xc0023c0b48 sp=0xc0023c0b10 pc=0x44953b
Oct 04 20:22:55 beafy erigon[22602]: github.com/torquem-ch/mdbx-go/mdbx._Cfunc_mdbxgo_cursor_put2(0x7d4bac0018e0, 0xc006158780, 0x28, 0xc0037f8fc0, 0x21f, 0xc000000000, 0xc000000000)
Oct 04 20:22:55 beafy erigon[22602]:         _cgo_gotypes.go:1021 +0x48 fp=0xc0023c0b78 sp=0xc0023c0b48 pc=0x98c728
Oct 04 20:22:55 beafy erigon[22602]: github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).Put.func1(0xc00b572420, 0xc006158780, 0x28, 0x28, 0xc0037f8fc0, 0x21f, 0x21f, 0x0, 0xc000032000)
````

**Comment by AskAlexSharov** [comment]
1. what version of Erigon you had before?
2. please run 
```
make db-tools
./build/bin/mdbx_chk -v -d <datadir>/chaindata
```
and show output

**Comment by NessDan** [comment]
> 1. what version of Erigon you had before?

I can't say, it was one of the last 3 releases but that's as specific as I can get :(

> 2. please run
> 
> ```
> make db-tools
> ./build/bin/mdbx_chk -v -d <datadir>/chaindata
> ```

Output:

```
~/git$ ./build/bin/mdbx_chk -v -d ~/data/chaindata
mdbx_chk v0.10.1-15-g63e7276 (2021-06-18T15:13:51+03:00, T-1c2ca15627c5c4e72657c00530c8a9a71ccd5128)
Running for /home/erigon/data/chaindata in 'read-only' mode...
 - monopolistic mode
 - current boot-id a98c597a17115145-06e45e92b9c54e1f
 - pagesize 4096 (4096 system), max keysize 1980..2022, max readers 118
 - mapsize 2199023255552 (2.00 Tb)
 - dynamic datafile: 12288 (12.00 Kb) .. 2199023255552 (2.00 Tb), +2147483648 (2.00 Gb), -4096 (4.00 Kb)
 - current datafile: 1372242051072 (1.25 Tb), 335020032 pages
 - meta-0: steady txn#356176, tail
 - meta-1: steady txn#356177, stay
 - meta-2: steady txn#356178, head
 - transactions: recent 356178, latter reader 356178, lag 0
Skipping b-tree walk...
Processing '@MAIN'...
 - key-value kind: usual-key => single-value
 - summary: 52 records, 0 dups, 640 key's bytes, 2496 data's bytes, 0 problems
Processing '@GC'...
 - key-value kind: ordinal-key => single-value
 - last modification txn#356178
 - fixed key-size 8
 - problems: wrong idl entry (4)
 - summary: 3 records, 0 dups, 24 key's bytes, 608 data's bytes, 4 problems
 - space: 536870912 total pages, backed 335020032 (62.4%), allocated 334665058 (62.3%), available 202205986 (37.7%)
Total 4 errors are detected, elapsed 0.001 seconds.
```

> 1. What is your FileSystem? What is your Disk model? Is it server-grade or desktop Disk?

Default filesystem for Ubuntu server installations (ext4?) I have an NVMe RAID for my disks. They are consumer NVMes.

> 2. How much free space left on Disk?
291GB Left

**Comment by AskAlexSharov** [comment]
@NessDan what type of RAID?

**Comment by erthink** [comment]
Corresponding libmdbx' assertion is [here](https://github.com/erthink/libmdbx/blob/c81226906afe0e3758ac9143bcbe6a672b6c1b57/src/core.c#L6293-L6294).

For such cases DB should be checked without `-d` option.

**Comment by AskAlexSharov** [comment]
@NessDan please run `./build/bin/mdbx_chk -v <datadir>/chaindata`

**Comment by erthink** [comment]
@NessDan, in your case, the database is definitely damaged. As a libmdbx developer, I am interested to understand the cause and fix it if one is the result of an libmdbx' bug.

If you already run the `mdbx_chk -vvv` then wait it for completeness.
Otherwise, you can get the initial amount of information for me much quicker.
Please:
1. run `./build/bin/mdbx_chk -0 -d -vvvvv <datadir>/chaindata`
2. run `./build/bin/mdbx_chk -1 -d -vvvvv <datadir>/chaindata`
3. run `./build/bin/mdbx_chk -2 -d -vvvvv <datadir>/chaindata`
4. and provide the output.

**Comment by erthink** [comment]
@NessDan, seems you got RAM glitches. Suggesting run the [memtestx86](https://www.memtest86.com/).

In details:
- all three MVCC snapshots (pointed by each of the three meta-pages) have the same problem;
- the problem is the GC' record #356176 has the four wrong entries (32-bit numbers) in the data;
- each GC' record is a sorted list of page numbers which could be reused in corresponding conditions;
- these four bad values seems like a good values with a single bit error:
  ```
         ...
   304916243 = 0x122CA713
  2452399876 = 0x122CA704 | 0x8000000
   297390424 = 0x11B9D158
         ...
   297388963 = 0x11B9CBA4
  1371130778 = 0x11B9CB9A | 0x4000000
   296860409 = 0x11B1BAF9
         ...
   296859945 = 0x11B1B929
  1370601768 = 0x11B1B928 | 0x4000000
   285674439 = 0x11070BC7
         ...
   285674321 = 0x11070B51
  1359416077 = 0x11070B0D | 0x4000000
   334665057 = 0x13F29561

Moreover, in three cases (except the last one), the values were correctly sorted before the distortion. The last fourth case also confirms my assumption, since the observed order of values corresponds to the situation when the `334665057` is added to the list after these data in RAM is distorted.

For now I have no idea how such corruption could happen due to an error in _libmdbx_ or _Erigon_, except for RAM failures.
@AskAlexSharov, FYI.

**Comment by NessDan** [comment]
@erthink thank you, I ran memtest and you were correct! 

I removed the faulty sticks, in the meantime is there anything I can do to repair the damage here?

**Comment by NessDan** [comment]
Thank you for your help! I'll look into ECC Memory :)
