### ISSUE TITLE
`rpcdaemon` crashes on `eth_call` occasionally after v2021.10.01

### ISSUE THREAD

**Issue by zzh1996** [ledgerwatch/erigon#2778]
#### System information

Erigon version: erigon version 2021.10.1-alpha

OS & Version: Linux Ubuntu 21.04

Commit hash: ef80fd54b

#### Expected behaviour

`rpcdaemon` doesn't crash, just like v2021.09.05 and previous versions.

Return data should be:

`[{"jsonrpc":"2.0","id":0,"result":"0x"},{"jsonrpc":"2.0","id":1,"result":"0x"},{"jsonrpc":"2.0","id":2,"result":"0x"},{"jsonrpc":"2.0","id":3,"result":"0x"},{"jsonrpc":"2.0","id":4,"result":"0x"}]`

#### Actual behaviour

`rpcdaemon` crashes sometimes.

`[{"jsonrpc":"2.0","id":0,"error":{"code":-32000,"message":"method handler crashed"}},{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"method handler crashed"}},{"jsonrpc":"2.0","id":2,"result":"0x"
},{"jsonrpc":"2.0","id":3,"result":"0x"},{"jsonrpc":"2.0","id":4,"result":"0x"}]`

In addition, sometimes wrong results are returned.

`[{"jsonrpc":"2.0","id":0,"result":"0x"},{"jsonrpc":"2.0","id":1,"result":"0x"},{"jsonrpc":"2.0","id":2,"error":{"code":-32000,"message":"insufficient funds for gas * price + value: address 0xBE0eB53F46cd790
Cd13851d5EFf43D12404d33E8 have 116 want 100000000000000000"}},{"jsonrpc":"2.0","id":3,"result":"0x"},{"jsonrpc":"2.0","id":4,"result":"0x"}]`

`[{"jsonrpc":"2.0","id":0,"result":"0x"},{"jsonrpc":"2.0","id":1,"result":"0x"},{"jsonrpc":"2.0","id":2,"error":{"code":-32000,"message":"invalid jump destination"}},{"jsonrpc":"2.0","id":3,"result":"0x"},{"
jsonrpc":"2.0","id":4,"result":"0x"}]`

#### Steps to reproduce the behaviour

```
curl http://127.0.0.1:8545/ -H "Content-Type: application/json" --data '[{"method": "eth_call", "params": [{"from": "0xBE0eB53F46cd790Cd13851d5EFf43D12404d33E8", "to": "0xbaa54d6e90c3f4d7ebec11bd180134c7ed8ebb52", "gas": "0xe4e1c0", "value": "0x16345785d8a0000", "data": "0x"}, "latest"], "id": 0, "jsonrpc": "2.0"}, {"method": "eth_call", "params": [{"from": "0xBE0eB53F46cd790Cd13851d5EFf43D12404d33E8", "to": "0xbaa54d6e90c3f4d7ebec11bd180134c7ed8ebb52", "gas": "0xe4e1c0", "value": "0x16345785d8a0000", "data": "0x"}, "latest"], "id": 1, "jsonrpc": "2.0"}, {"method": "eth_call", "params": [{"from": "0xBE0eB53F46cd790Cd13851d5EFf43D12404d33E8", "to": "0xbaa54d6e90c3f4d7ebec11bd180134c7ed8ebb52", "gas": "0xe4e1c0", "value": "0x16345785d8a0000", "data": "0x"}, "latest"], "id": 2, "jsonrpc": "2.0"}, {"method": "eth_call", "params": [{"from": "0xBE0eB53F46cd790Cd13851d5EFf43D12404d33E8", "to": "0xbaa54d6e90c3f4d7ebec11bd180134c7ed8ebb52", "gas": "0xe4e1c0", "value": "0x16345785d8a0000", "data": "0x"}, "latest"], "id": 3, "jsonrpc": "2.0"}, {"method": "eth_call", "params": [{"from": "0xBE0eB53F46cd790Cd13851d5EFf43D12404d33E8", "to": "0xbaa54d6e90c3f4d7ebec11bd180134c7ed8ebb52", "gas": "0xe4e1c0", "value": "0x16345785d8a0000", "data": "0x"}, "latest"], "id": 4, "jsonrpc": "2.0"}]'
```

#### Backtrace

````
EROR[10-05|06:54:44.870] RPC method eth_call crashed: runtime error: index out of range [1] with length 1
goroutine 571766 [running]:
github.com/ledgerwatch/erigon/rpc.(*callback).call.func1(0xc00398a430, 0x8, 0xc0006ddd60)
        github.com/ledgerwatch/erigon/rpc/service.go:219 +0xbd
panic(0x113f960, 0xc0040a4750)
        runtime/panic.go:965 +0x1b9
github.com/ledgerwatch/erigon/core/types/accounts.(*Account).DecodeForStorage(0xc000547980, 0xc0033212c8, 0x1, 0x1, 0xc0033212c8, 0x1)
        github.com/ledgerwatch/erigon/core/types/accounts/account.go:468 +0x837
github.com/ledgerwatch/erigon/core/state.(*CachedReader2).ReadAccountData(0xc001942540, 0xc79cd463fb50ebe, 0x123df4efd55138d1, 0xe8334d40, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/erigon/core/state/cached_reader2.go:36 +0xf9
github.com/ledgerwatch/erigon/core/state.(*IntraBlockState).getStateObject(0xc000a3b260, 0xc79cd463fb50ebe, 0x123df4efd55138d1, 0xe8334d40, 0x0)
        github.com/ledgerwatch/erigon/core/state/intra_block_state.go:548 +0xf6
github.com/ledgerwatch/erigon/core/state.(*IntraBlockState).GetBalance(0xc000a3b260, 0xc79cd463fb50ebe, 0x123df4efd55138d1, 0xc0e8334d40, 0xe4e1c0)
        github.com/ledgerwatch/erigon/core/state/intra_block_state.go:260 +0x56
github.com/ledgerwatch/erigon/core.(*StateTransition).buyGas(0xc000033710, 0x0, 0xc00225ff48, 0x1)
        github.com/ledgerwatch/erigon/core/state_transition.go:210 +0x10c
github.com/ledgerwatch/erigon/core.(*StateTransition).preCheck(0xc000033710, 0x20300000000000, 0x7f284d687fff, 0x7f2848762090)
        github.com/ledgerwatch/erigon/core/state_transition.go:264 +0x490
github.com/ledgerwatch/erigon/core.(*StateTransition).TransitionDb(0xc000033710, 0x1340001, 0xc0008e6a50, 0xc00225ff60, 0xc000033710)
        github.com/ledgerwatch/erigon/core/state_transition.go:292 +0x4f
github.com/ledgerwatch/erigon/core.ApplyMessage(0xc0008f6000, 0x134bc58, 0xc0008e6a50, 0xc00225ff60, 0xc0008f0001, 0x62581d100901a8f8, 0xc9b72352, 0x1caa85f)
        github.com/ledgerwatch/erigon/core/state_transition.go:189 +0x6d
github.com/ledgerwatch/erigon/turbo/transactions.DoCall(0x1340498, 0xc0031504e0, 0xc00408e2b8, 0xc00408e2e8, 0xc003321828, 0x0, 0x0, 0x0, 0xc002d0eea0, 0xc0005aec78, ...)
        github.com/ledgerwatch/erigon/turbo/transactions/call.go:133 +0xe49
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*APIImpl).Call(0xc0002a02d0, 0x1340498, 0xc00462f240, 0xc00408e2b8, 0xc00408e2e8, 0xc003321828, 0x0, 0x0, 0x0, 0xc002d0eea0, ...)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_call.go:44 +0x289
reflect.Value.call(0xc0005ba380, 0xc000294100, 0x13, 0x11caf4b, 0x4, 0xc0002cf980, 0x5, 0x5, 0xc0002cf9b0, 0xc002b80dc0, ...)
        reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0005ba380, 0xc000294100, 0x13, 0xc0002cf980, 0x5, 0x5, 0x104d500, 0x1311c58, 0x0)
        reflect/value.go:337 +0xb9
github.com/ledgerwatch/erigon/rpc.(*callback).call(0xc00028e7e0, 0x1340498, 0xc00462f240, 0xc00398a430, 0x8, 0xc002b80dc0, 0x3, 0x3, 0xc0038076e0, 0x0, ...)
        github.com/ledgerwatch/erigon/rpc/service.go:226 +0x392
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc00066ae60, 0x1340498, 0xc00462f240, 0xc00059aa80, 0xc00028e7e0, 0xc002b80dc0, 0x3, 0x3, 0xc0038076e0, 0x0)
        github.com/ledgerwatch/erigon/rpc/handler.go:491 +0xb2c
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc00066ae60, 0xc0002911a0, 0xc00059aa80, 0xc0038076e0, 0x60)
        github.com/ledgerwatch/erigon/rpc/handler.go:396 +0x25f
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc00066ae60, 0xc0002911a0, 0xc00059aa80, 0xc0038076e0, 0x4)
        github.com/ledgerwatch/erigon/rpc/handler.go:350 +0x1a5
github.com/ledgerwatch/erigon/rpc.(*handler).handleBatch.func2.1(0xc00398a4b4, 0xc003a5ac00, 0xc0002911a0, 0xc00066ae60, 0xc0002910b0, 0x5, 0x5, 0xc0037820f0, 0x5, 0x5, ...)
        github.com/ledgerwatch/erigon/rpc/handler.go:148 +0x1e5
created by github.com/ledgerwatch/erigon/rpc.(*handler).handleBatch.func2
        github.com/ledgerwatch/erigon/rpc/handler.go:134 +0x1dc
````

**Comment by AskAlexSharov** [comment]
I will take a look today

**Comment by AskAlexSharov** [comment]
@zzh1996 hi, can you help me to test - if `state_stream_default` branch solves your problem

**Comment by zzh1996** [comment]
> @zzh1996 hi, can you help me to test - if `state_stream_default` branch solves your problem (rebuild erigon and rpcdaemon)

It's not working. The same error message.
