### ISSUE TITLE
erigon 2021.10.02 crashing / restart loop 

### ISSUE THREAD

**Issue by briancolecoinmetrics** [ledgerwatch/erigon#2797]
#### System information

Erigon version: 2021.10.02

OS & Version: Linux (Alpine 3.14 based Docker image; https://gitlab.com/coinmetrics/fullnodes/erigon/-/blob/main/Dockerfile)

Commit hash : 8b4d31f6617a051285e62ef065d4a9de2a439fb2

This is the startup message:
```
[INFO] [10-07|17:12:53.186] Build info                               git_branch=HEAD git_tag=v2021.10.02 git_commit=8b4d31f6617a051285e62ef065d4a9de2a439fb2
```

#### Expected behaviour

Erigon fullnode should continue running once started until manually stopped or something external breaks it (running out of disk space, hard fork, whatever), and even then the node should stay up and recover once the situation is resolved.

#### Actual behaviour
Node runs for ~21 minutes and then it dies and gets restarted by docker.

#### Steps to reproduce the behaviour

Run erigon for a bit? Sorry, I don't think we're doing anything unusual; it's a somewhat long-lived instance (data directory is over a month old now) that we periodically update with the newest version of the software. I'm quite happy to provide any additional info needed, although sharing the whole data directory is probably impractical (there's no nice way to transfer 1.5T around).

#### Backtrace
```
[INFO] [10-07|17:12:41.011] [10/18 HashState] ETL [1/2] Extracting   from=StorageChangeSet current key=0000000000cb984f08650bb9dc722c9c8c62e79c2bafa2d3fc5b32930000000000000001 alloc="816.3 MiB" sys="1.8 GiB"
panic: runtime error: slice bounds out of range [:32] with capacity 20

goroutine 76 [running]:
github.com/ledgerwatch/erigon/common/changeset.DecodeStorage(0x7ec5899dbfac, 0x24, 0x24, 0x7ec5899e2fe2, 0x14, 0x14, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/ledgerwatch/erigon/common/changeset/storage_changeset.go:51 +0x1f5
github.com/ledgerwatch/erigon/eth/stagedsync.getExtractFunc.func1(0x7ec5899dbfac, 0x24, 0x24, 0x7ec5899e2fe2, 0x14, 0x14, 0xc03f420040, 0x0, 0x0)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_hashstate.go:281 +0x9d
github.com/ledgerwatch/erigon-lib/etl.extractBucketIntoFiles(0xc004de8fc0, 0xf, 0x20efcb8, 0xc0078252c0, 0x164c891, 0x10, 0xc014f240f8, 0x8, 0x8, 0x0, ...)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20211006142856-240f7f121273/etl/etl.go:164 +0x2f7
github.com/ledgerwatch/erigon-lib/etl.Transform(0xc004de8fc0, 0xf, 0x20f7178, 0xc0078252c0, 0x164c891, 0x10, 0x1648b7f, 0xd, 0xc0001ae060, 0x12, ...)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20211006142856-240f7f121273/etl/etl.go:109 +0x225
github.com/ledgerwatch/erigon/eth/stagedsync.(*Promoter).Promote(0xc007825380, 0xc004de8fc0, 0xf, 0xc007a5eb60, 0xcb799e, 0xcc0e68, 0x1, 0x0, 0x0)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_hashstate.go:437 +0x238
github.com/ledgerwatch/erigon/eth/stagedsync.promoteHashedStateIncrementally(0xc004de8fc0, 0xf, 0xc007a5eb60, 0xcb799e, 0xcc0e68, 0x20f7178, 0xc0078252c0, 0x20e7498, 0xc00021c180, 0xc0001ae060, ...)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_hashstate.go:520 +0x185
github.com/ledgerwatch/erigon/eth/stagedsync.SpawnHashStateStage(0xc007a5eb60, 0x0, 0xc0078252c0, 0x20e7498, 0xc00021c180, 0xc0001ae060, 0x12, 0x20de998, 0xc0000e11c0, 0x0, ...)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_hashstate.go:65 +0x52b
github.com/ledgerwatch/erigon/eth/stagedsync.DefaultStages.func28(0xc0002a0001, 0xc007a5eb60, 0x20bfaa0, 0xc0002a31e0, 0x0, 0x0, 0xc00021c180, 0xc007a5eb60)
        github.com/ledgerwatch/erigon/eth/stagedsync/default_stages.go:165 +0x7f
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc0002a31e0, 0xc00018f4a0, 0x20e7498, 0xc00021c180, 0x0, 0x0, 0x1, 0x0, 0x0)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:316 +0x1b0
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc0002a31e0, 0x20e7498, 0xc00021c180, 0x0, 0x0, 0x1, 0x0, 0x0)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:233 +0x428
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep(0x20de998, 0xc0000e11c0, 0x20e7498, 0xc00021c180, 0xc0002a31e0, 0x0, 0xc000ce8760, 0x1, 0xc0002d8770, 0x0, ...)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:129 +0x285
github.com/ledgerwatch/erigon/turbo/stages.StageLoop(0x20de998, 0xc0000e11c0, 0x20e7498, 0xc00021c180, 0xc0002a31e0, 0xc000030ff0, 0xc000ce8760, 0xc0002d8770, 0xc000190240, 0x0)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:56 +0x15c
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
        github.com/ledgerwatch/erigon/eth/backend.go:781 +0x1b4
```

**Comment by AskAlexSharov** [comment]
@briancolecoinmetrics because commands didn't run: `unknown command "state_hash_state" for "integration"`
show me `integration --help`

**Comment by AskAlexSharov** [comment]
It even advising you 
```
Did you mean this?
        stage_hash_state
```

:-)

**Comment by briancolecoinmetrics** [comment]
Just this?
```
host$ docker exec -ti erigoncontainer ash
~ $ integration --help
long and heavy integration tests for Erigon

Usage:
  integration [command]

Available Commands:
  compare_bucket    compare bucket to the same bucket in '--chaindata.reference'
  compare_states    compare state buckets to buckets in '--chaindata.reference'
  completion        generate the autocompletion script for the specified shell
  f_to_mdbx         copy data from '--chaindata' to '--chaindata.to'
  help              Help about any command
  loop_exec         
  loop_ih           
  mdbx_to_mdbx      copy data from '--chaindata' to '--chaindata.to'
  print_migrations  
  print_stages      
  remove_migration  
  reset_state       Reset StateStages (5,6,7,8,9,10) and buckets
  run_migrations    
  set_prune         Override existing --prune flag value (if you know what you are doing)
  stage_bodies      
  stage_call_traces 
  stage_exec        
  stage_hash_state  
  stage_headers     
  stage_history     
  stage_log_index   
  stage_senders     
  stage_trie        
  stage_tx_lookup   
  state_stages      Run all StateStages (which happen after senders) in loop.
Examples: 
--unwind=1 --unwind.every=10  # 10 blocks forward, 1 block back, 10 blocks forward, ...
--unwind=10 --unwind.every=1  # 1 block forward, 10 blocks back, 1 blocks forward, ...
--unwind=10  # 10 blocks back, then stop
--integrity.fast=false --integrity.slow=false # Performs DB integrity checks each step. You can disable slow or fast checks.
--block # Stop at exact blocks
--chaindata.reference # When finish all cycles, does comparison to this db file.

  test_cons         Integration test for consensus engine
  test_core         Test server for testing core of Erigon or equivalent component

Flags:
      --backtrace string             Request a stack trace at a specific logging statement (e.g. "block.go:271")
      --debug                        Prepends log messages with call-site location (file and line number)
  -h, --help                         help for integration
      --log.json                     Format logs with JSON
      --metrics                      Enable metrics collection and reporting
      --metrics.addr string          Enable stand-alone metrics HTTP server listening interface (default "127.0.0.1")
      --metrics.expensive            Enable expensive metrics collection and reporting
      --metrics.port int             Metrics HTTP server listening port (default 6060)
      --pprof                        Enable the pprof HTTP server
      --pprof.addr string            pprof HTTP server listening interface (default "127.0.0.1")
      --pprof.blockprofilerate int   Turn on block profiling with the given rate
      --pprof.cpuprofile string      Write CPU profile to the given file
      --pprof.memprofilerate int     Turn on memory profiling with the given rate (default 524288)
      --pprof.port int               pprof HTTP server listening port (default 6060)
      --trace string                 Write execution trace to the given file
      --verbosity int                Logging verbosity: 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail (default 3)
      --vmodule string               Per-module verbosity: comma-separated list of <pattern>=<level> (e.g. eth/*=5,p2p=4)

Use "integration [command] --help" for more information about a command.
```

And yes, I copy-pasted the command you provided, saw the error, and replaced the command as it suggested (it's the very next command in the typescript); given that it ran that without complaining about the command I assumed I'd substituted correctly?

**Comment by AskAlexSharov** [comment]
you did correct. but by some reason command was killed.
please try smaller command:
```
integration state_stages --datadir=/opt/data --unwind=100
integration stage_hash_state --datadir=/opt/data
```

**Comment by briancolecoinmetrics** [comment]
We are running erigon 2021.10.02 built from `git clone --depth 1 -b v2021.10.02 https://github.com/ledgerwatch/erigon` (using https://gitlab.com/coinmetrics/fullnodes/erigon/-/blob/main/Dockerfile in https://gitlab.com/coinmetrics/fullnodes/erigon/-/jobs/1658975756). We're composing the final image with `COPY --from=build /opt/erigon/build/bin/* /usr/local/bin/` so that exact path doesn't make it but the `integration` command ends up in the shell's PATH (so I just run it directly).

Running with that flag appears to reproduce the error:
```
~ $ integration state_stages --datadir=/opt/data --unwind=100 --integrity.fast=false
INFO[10-13|05:13:50.008] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Engine: ethash}"
INFO[10-13|05:13:54.384] [10/18 HashState] Promoting plain state  from=13334942 to=13408117
INFO[10-13|05:13:54.384] [10/18 HashState] Incremental promotion started from=13334942 to=13408117 codes=true csbucket=AccountChangeSet
INFO[10-13|05:14:24.389] [10/18 HashState] ETL [1/2] Extracting   from=AccountChangeSet current key=0000000000cbd1ed alloc="167.4 MiB" sys="279.8 MiB"
INFO[10-13|05:14:54.386] [10/18 HashState] ETL [1/2] Extracting   from=AccountChangeSet current key=0000000000cc32e1 alloc="116.9 MiB" sys="280.2 MiB"
INFO[10-13|05:15:24.386] [10/18 HashState] ETL [1/2] Extracting   from=AccountChangeSet current key=0000000000cc96c1 alloc="130.4 MiB" sys="280.6 MiB"
INFO[10-13|05:15:27.469] [10/18 HashState] Incremental promotion started from=13334942 to=13408117 codes=false csbucket=AccountChangeSet
INFO[10-13|05:15:57.471] [10/18 HashState] ETL [1/2] Extracting   from=AccountChangeSet current key=0000000000cbce05 alloc="344.2 MiB" sys="616.0 MiB"
INFO[10-13|05:16:27.470] [10/18 HashState] ETL [1/2] Extracting   from=AccountChangeSet current key=0000000000cc1a73 alloc="512.6 MiB" sys="953.7 MiB"
INFO[10-13|05:16:57.470] [10/18 HashState] ETL [1/2] Extracting   from=AccountChangeSet current key=0000000000cc6c7a alloc="563.5 MiB" sys="954.9 MiB"
INFO[10-13|05:17:53.455] [10/18 HashState] ETL [2/2] Loading      into=HashedAccount current key=e3e07055... alloc="1.8 GiB" sys="2.2 GiB"
INFO[10-13|05:17:55.623] [10/18 HashState] Incremental promotion started from=13334942 to=13408117 codes=false csbucket=StorageChangeSet
INFO[10-13|05:18:28.313] database closed                          label=chaindata
panic: runtime error: slice bounds out of range [:32] with capacity 20

goroutine 1 [running]:
github.com/ledgerwatch/erigon/common/changeset.DecodeStorage(0x7f56cd087fac, 0x24, 0x24, 0x7f56cd08efe2, 0x14, 0x14, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/ledgerwatch/erigon/common/changeset/storage_changeset.go:51 +0x1f5
github.com/ledgerwatch/erigon/eth/stagedsync.getExtractFunc.func1(0x7f56cd087fac, 0x24, 0x24, 0x7f56cd08efe2, 0x14, 0x14, 0xc084e90540, 0x0, 0x0)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_hashstate.go:281 +0x9d
github.com/ledgerwatch/erigon-lib/etl.extractBucketIntoFiles(0xc005edb8c0, 0xf, 0x203b638, 0xc005ecf770, 0x159f31d, 0x10, 0xc02d11c0b8, 0x8, 0x8, 0x0, ...)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20211006142856-240f7f121273/etl/etl.go:164 +0x2f7
github.com/ledgerwatch/erigon-lib/etl.Transform(0xc005edb8c0, 0xf, 0x2042a18, 0xc005ecf770, 0x159f31d, 0x10, 0x159b791, 0xd, 0xc00011ee40, 0x29, ...)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20211006142856-240f7f121273/etl/etl.go:109 +0x225
github.com/ledgerwatch/erigon/eth/stagedsync.(*Promoter).Promote(0xc005ecf860, 0xc005edb8c0, 0xf, 0xc005ee5e60, 0xcb799e, 0xcc9775, 0x1, 0x0, 0x0)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_hashstate.go:437 +0x238
github.com/ledgerwatch/erigon/eth/stagedsync.promoteHashedStateIncrementally(0xc005edb8c0, 0xf, 0xc005ee5e60, 0xcb799e, 0xcc9775, 0x2042a18, 0xc005ecf770, 0x2033ad8, 0xc000126d00, 0xc00011ee40, ...)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_hashstate.go:520 +0x185
github.com/ledgerwatch/erigon/eth/stagedsync.SpawnHashStateStage(0xc005ee5e60, 0x2042a18, 0xc005ecf770, 0x2033ad8, 0xc000126d00, 0xc00011ee40, 0x29, 0x202b8b0, 0xc000042060, 0x0, ...)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_hashstate.go:65 +0x52b
github.com/ledgerwatch/erigon/eth/stagedsync.DefaultStages.func28(0xc0001e0000, 0xc005ee5e60, 0x200e160, 0xc0001e24d0, 0x2042a18, 0xc005ecf770, 0xc000126d00, 0xc005ee5e60)
        github.com/ledgerwatch/erigon/eth/stagedsync/default_stages.go:165 +0x7f
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc0001e24d0, 0xc00003c690, 0x2033ad8, 0xc000126d00, 0x2042a18, 0xc005ecf770, 0x0, 0x0, 0x0)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:316 +0x1b0
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc0001e24d0, 0x2033ad8, 0xc000126d00, 0x2042a18, 0xc005ecf770, 0x0, 0x0, 0xc00011def0)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:233 +0x428
github.com/ledgerwatch/erigon/cmd/integration/commands.syncBySmallSteps(0x2033ad8, 0xc000126d00, 0x0, 0x0, 0x0, 0x0, 0x2a698c0, 0x0, 0x0, 0x2a698c0, ...)
        github.com/ledgerwatch/erigon/cmd/integration/commands/state_stages.go:278 +0xc39
github.com/ledgerwatch/erigon/cmd/integration/commands.glob..func24(0x27bcc40, 0xc000283170, 0x0, 0x3, 0x0, 0x0)
        github.com/ledgerwatch/erigon/cmd/integration/commands/state_stages.go:63 +0x258
github.com/spf13/cobra.(*Command).execute(0x27bcc40, 0xc000283110, 0x3, 0x3, 0x27bcc40, 0xc000283110)
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x27be040, 0xc000119340, 0xc00029bcd0, 0x18)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.2.1/command.go:895
main.main()
        github.com/ledgerwatch/erigon/cmd/integration/main.go:15 +0x129
~ $
```

Unless you're suggesting that I try from a newer version than is released? It'd take a little work, but I should be able to try master or an arbitrary commit if you think it'd help. We are on v2021.10.02, though.

**Comment by AskAlexSharov** [comment]
Show plz: integration print_stages

**Comment by AskAlexSharov** [comment]
@briancolecoinmetrics and if add `--datadir=/opt/data`?

**Comment by mandrigin** [comment]
please reopen is still relevant @briancolecoinmetrics
