### ISSUE TITLE
MDBX_PROBLEM: Transaction should be aborted

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/erigon#2985]
#### System information

Erigon version: `2021.11.03-beta`

OS & Version: Linux - Docker

I updated my docker image to latest version and I got this, interestingly I have another identical server, exact same setup, working fine.

```
[INFO] [11-17|20:06:56.523] Build info                               git_branch=stable git_tag=v2021.11.03 git_commit=a37afc5b1546c1ee4c3056fec1315060d03442bd
[INFO] [11-17|20:06:56.523] Starting Erigon on Ethereum mainnet...
[INFO] [11-17|20:06:56.524] Maximum peer count                       ETH=100 total=100
[INFO] [11-17|20:06:56.524] Set global gas cap                       cap=50000000
[INFO] [11-17|20:06:56.561] Opening Database                         label=chaindata path=/home/erigon/.local/share/erigon/chaindata
mdbx_ipclock_failed:30047 wlock owner died, recovering
[INFO] [11-17|20:06:56.562] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Engine: ethash}"
[INFO] [11-17|20:06:56.562] Disk storage enabled for ethash DAGs     dir=/home/erigon/.local/share/erigon/ethash-dags count=2
[INFO] [11-17|20:06:56.562] Initialising Ethereum protocol           network=1
[INFO] [11-17|20:06:56.562] Effective                                prune="--prune="
[INFO] [11-17|20:06:57.261] Starting private RPC server              on=0.0.0.0:9090
[INFO] [11-17|20:06:57.261] [1/15 Headers] Waiting for headers...    from=13634911
[WARN] [11-17|20:06:57.264] [RecvMessage] sentry not ready yet       err="could not start server: mdbx_env_open: MDBX_PROBLEM: Unexpected internal error, transaction should be aborted, label: sentry, trace: [kv_mdbx.go:217 nodedb.go:130 nodedb.go:104 server.go:518 server.go:491 sentry.go:814 sentry_client.go:193 downloader.go:338 downloader.go:252 backend.go:679 asm_amd64.s:1581]"
[WARN] [11-17|20:06:57.264] [RecvUploadMessage] sentry not ready yet err="could not start server: mdbx_env_open: MDBX_PROBLEM: Unexpected internal error, transaction should be aborted, label: sentry, trace: [kv_mdbx.go:217 nodedb.go:130 nodedb.go:104 server.go:518 server.go:491 sentry.go:814 sentry_client.go:193 downloader.go:338 downloader.go:64 backend.go:682 asm_amd64.s:1581]"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8dd63d]

goroutine 103 [running]:
github.com/ledgerwatch/erigon/p2p/enode.(*LocalNode).Set(0xf8ae76f84067e5d4, {0x1be65e0, 0xc005c94f00})
        github.com/ledgerwatch/erigon/p2p/enode/localnode.go:118 +0x3d
github.com/ledgerwatch/erigon/cmd/sentry/download.(*SentryServerImpl).SetStatus(0xc000364ea0, {0xc0000cb630, 0xc0006be880}, 0xc0000cb630)
        github.com/ledgerwatch/erigon/cmd/sentry/download/sentry.go:818 +0x592
github.com/ledgerwatch/erigon-lib/direct.(*SentryClientDirect).SetStatus(0xc000145a40, {0x1c02078, 0xc000323100}, 0xc000364ea0, {0x10, 0xfe5a40, 0xc0006d1e01})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20211116105337-347396fb51eb/direct/sentry_client.go:193 +0x2c
github.com/ledgerwatch/erigon/cmd/sentry/download.SentrySetStatus({0x1c02078, 0xc000323100}, {0x1c1eda0, 0xc000320480}, 0xc0006d1f38)
        github.com/ledgerwatch/erigon/cmd/sentry/download/downloader.go:338 +0x5b
github.com/ledgerwatch/erigon/cmd/sentry/download.RecvMessageLoop({0x1c02078, 0xc000323100}, {0x1c1eda0, 0xc000320480}, 0xc000145a40, 0x0)
        github.com/ledgerwatch/erigon/cmd/sentry/download/downloader.go:252 +0x292
github.com/ledgerwatch/erigon/eth.(*Ethereum).Start.func1(0x0)
        github.com/ledgerwatch/erigon/eth/backend.go:679 +0x58
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
        github.com/ledgerwatch/erigon/eth/backend.go:678 +0x10f
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8dd63d]

goroutine 105 [running]:
github.com/ledgerwatch/erigon/p2p/enode.(*LocalNode).Set(0xf8ae76f84067e5d4, {0x1be65e0, 0xc001598540})
        github.com/ledgerwatch/erigon/p2p/enode/localnode.go:118 +0x3d
github.com/ledgerwatch/erigon/cmd/sentry/download.(*SentryServerImpl).SetStatus(0xc000364ea0, {0xc000884050, 0xc00073a180}, 0xc000884050)
        github.com/ledgerwatch/erigon/cmd/sentry/download/sentry.go:818 +0x592
github.com/ledgerwatch/erigon-lib/direct.(*SentryClientDirect).SetStatus(0xc000145a40, {0x1c02078, 0xc000323100}, 0xc000364ea0, {0x10, 0xfe5a40, 0xc000127e01})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20211116105337-347396fb51eb/direct/sentry_client.go:193 +0x2c
github.com/ledgerwatch/erigon/cmd/sentry/download.SentrySetStatus({0x1c02078, 0xc000323100}, {0x1c1eda0, 0xc000320480}, 0x0)
        github.com/ledgerwatch/erigon/cmd/sentry/download/downloader.go:338 +0x5b
github.com/ledgerwatch/erigon/cmd/sentry/download.RecvUploadHeadersMessageLoop({0x1c02078, 0xc000323100}, {0x1c1eda0, 0xc000320480}, 0xc000145a40, 0x0)
        github.com/ledgerwatch/erigon/cmd/sentry/download/downloader.go:159 +0x288
github.com/ledgerwatch/erigon/eth.(*Ethereum).Start.func3(0x0)
        github.com/ledgerwatch/erigon/eth/backend.go:685 +0x58
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
        github.com/ledgerwatch/erigon/eth/backend.go:684 +0x48
```

**Comment by AlexeyAkhunov** [comment]
You should be able to solve this by removing your `nodes` directory. I did not figure out why this is happening though

**Comment by MysticRyuujin** [comment]
Confirmed! Deleting `nodes` directory fixed it.
