### ISSUE TITLE
RPC Daemon panic on eth_getBlockByNumber

### ISSUE THREAD

**Issue by splix** [ledgerwatch/erigon#3173]
RPC Daemon stopped to work for _some block numbers_. May be caused by db corruption, though no other evidences of db corruption.

#### System information

erigon version 2021.12.3-beta
Debian

#### Expected behaviour

Return JSON for block or error

#### Actual behaviour

RPC Daemon panic

#### Steps to reproduce the behaviour

Request `{"jsonrpc":"2.0", "method":"eth_getBlockByNumber", "id":1, "params":["0xc9ef50", false]}`
Once the daemon receives the request it immediately panics.

NOTE: happens only for some blocks, for other block numbers it works fine

#### Backtrace

````
fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x2 addr=0x7d73e752e010 pc=0x440e57]

runtime stack:
runtime.throw(0x11e1a0c, 0x2a)
	runtime/panic.go:1117 +0x72
runtime.sigpanic()
	runtime/signal_unix.go:718 +0x2e5

goroutine 117 [syscall]:
runtime.cgocall(0xe0f840, 0xc00054ee80, 0xe0f700)
	runtime/cgocall.go:154 +0x5b fp=0xc00054ee50 sp=0xc00054ee18 pc=0x44d37b
github.com/torquem-ch/mdbx-go/mdbx._Cfunc_mdbxgo_cursor_get1(0x7f1e50002870, 0xc000678090, 0x28, 0xc000073f90, 0xc000073fb0, 0xf, 0x7f1e00000000)
	_cgo_gotypes.go:966 +0x48 fp=0xc00054ee80 sp=0xc00054ee50 pc=0x991608
github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).getVal1.func1(0xc000073ff0, 0xc000678090, 0x28, 0x28, 0xf, 0xc00054efb8)
	github.com/torquem-ch/mdbx-go@v0.22.2/mdbx/cursor.go:195 +0xf9 fp=0xc00054eee0 sp=0xc00054ee80 pc=0x999db9
github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).getVal1(0xc000073ff0, 0xc000678090, 0x28, 0x28, 0xf, 0x0, 0x5)
	github.com/torquem-ch/mdbx-go@v0.22.2/mdbx/cursor.go:195 +0x57 fp=0xc00054ef30 sp=0xc00054eee0 pc=0x992cf7
github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).Get(0xc000073ff0, 0xc000678090, 0x28, 0x28, 0x0, 0x0, 0x0, 0xf, 0x202fb2087676eb58, 0x0, ...)
	github.com/torquem-ch/mdbx-go@v0.22.2/mdbx/cursor.go:142 +0x86 fp=0xc00054efb0 sp=0xc00054ef30 pc=0x992766
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).set(...)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20211217093552-7d82c6ac76e6/kv/mdbx/kv_mdbx.go:1017
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).SeekExact(0xc000638540, 0xc000678090, 0x28, 0x28, 0xc000638540, 0x0, 0x0, 0xc000678098, 0xc00054f130, 0x20, ...)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20211217093552-7d82c6ac76e6/kv/mdbx/kv_mdbx.go:1381 +0x3b6 fp=0xc00054f0b8 sp=0xc00054efb0 pc=0x9a6a36
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).GetOne(0xc000597a10, 0x11bd3a8, 0x9, 0xc000678090, 0x28, 0x28, 0x28, 0x28, 0xc00054f258, 0xa66a2a, ...)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20211217093552-7d82c6ac76e6/kv/mdbx/kv_mdbx.go:873 +0xc4 fp=0xc00054f128 sp=0xc00054f0b8 pc=0x9a1a84
github.com/ledgerwatch/erigon/core/rawdb.ReadStorageBodyRLP(0x7f1e5c255238, 0xc000597a10, 0x1bd8238282b002b6, 0x23f6a883888dfb5f, 0xb1f79ac13432b687, 0x81223da7a0f8561c, 0xc9ef50, 0x121d0c8, 0xc00054f290, 0x4c6625)
	github.com/ledgerwatch/erigon/core/rawdb/accessors_chain.go:255 +0xa7 fp=0xc00054f1c8 sp=0xc00054f128 pc=0xc08087
github.com/ledgerwatch/erigon/core/rawdb.ReadBody(0x7f1e5c255238, 0xc000597a10, 0x1bd8238282b002b6, 0x23f6a883888dfb5f, 0xb1f79ac13432b687, 0x81223da7a0f8561c, 0xc9ef50, 0x0, 0x0, 0xc9ef50)
	github.com/ledgerwatch/erigon/core/rawdb/accessors_chain.go:416 +0x74 fp=0xc00054f2b8 sp=0xc00054f1c8 pc=0xc08b34
github.com/ledgerwatch/erigon/core/rawdb.ReadBodyWithTransactions(0x7f1e5c255238, 0xc000597a10, 0x1bd8238282b002b6, 0x23f6a883888dfb5f, 0xb1f79ac13432b687, 0x81223da7a0f8561c, 0xc9ef50, 0xc00051a780)
	github.com/ledgerwatch/erigon/core/rawdb/accessors_chain.go:364 +0x74 fp=0xc00054f3c0 sp=0xc00054f2b8 pc=0xc08814
github.com/ledgerwatch/erigon/core/rawdb.ReadBlock(0x7f1e5c255238, 0xc000597a10, 0x1bd8238282b002b6, 0x23f6a883888dfb5f, 0xb1f79ac13432b687, 0x81223da7a0f8561c, 0xc9ef50, 0x112f140)
	github.com/ledgerwatch/erigon/core/rawdb/accessors_chain.go:757 +0xba fp=0xc00054f438 sp=0xc00054f3c0 pc=0xc0a09a
github.com/ledgerwatch/erigon/core/rawdb.ReadBlockWithSenders(0x133a638, 0xc000597a10, 0x1bd8238282b002b6, 0x23f6a883888dfb5f, 0xb1f79ac13432b687, 0x81223da7a0f8561c, 0xc9ef50, 0xc000696250, 0x8, 0x8, ...)
	github.com/ledgerwatch/erigon/core/rawdb/accessors_chain.go:773 +0x98 fp=0xc00054f4c8 sp=0xc00054f438 pc=0xc0a1f8
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*BaseAPI).blockWithSenders(0xc00010e820, 0x133a638, 0xc000597a10, 0x1bd8238282b002b6, 0x23f6a883888dfb5f, 0xb1f79ac13432b687, 0x81223da7a0f8561c, 0xc9ef50, 0x0, 0x0, ...)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_api.go:163 +0x8b fp=0xc00054f590 sp=0xc00054f4c8 pc=0xddf96b
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*BaseAPI).blockByNumberWithSenders(0xc00010e820, 0x133a638, 0xc000597a10, 0xc9ef50, 0x0, 0x0, 0x121c8a8)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_api.go:143 +0x136 fp=0xc00054f638 sp=0xc00054f590 pc=0xddf696
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*BaseAPI).blockByRPCNumber(0xc00010e820, 0xc9ef50, 0x133a638, 0xc000597a10, 0xc000597a10, 0x0, 0x0)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_api.go:215 +0x9e fp=0xc00054f680 sp=0xc00054f638 pc=0xddff7e
github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands.(*APIImpl).GetBlockByNumber(0xc00010e8c0, 0x132ec98, 0xc0006741c0, 0xc9ef50, 0x0, 0x0, 0x0, 0x0)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/commands/eth_block.go:181 +0x108 fp=0xc00054f8d0 sp=0xc00054f680 pc=0xde3048
runtime.call64(0xc000597950, 0xc000110340, 0xc000674200, 0x2800000040)
	runtime/asm_amd64.s:552 +0x3e fp=0xc00054f920 sp=0xc00054f8d0 pc=0x4ba47e
reflect.Value.call(0xc00011e900, 0xc000110340, 0x13, 0x11b818d, 0x4, 0xc000638420, 0x4, 0x4, 0xc000638450, 0xc0005978f0, ...)
	reflect/value.go:476 +0x8e7 fp=0xc00054fb28 sp=0xc00054f920 pc=0x528c07
reflect.Value.Call(0xc00011e900, 0xc000110340, 0x13, 0xc000638420, 0x4, 0x4, 0x1038340, 0x13003b0, 0x0)
	reflect/value.go:337 +0xb9 fp=0xc00054fba8 sp=0xc00054fb28 pc=0x5280d9
github.com/ledgerwatch/erigon/rpc.(*callback).call(0xc000505080, 0x132ec98, 0xc0006741c0, 0xc00003a3c0, 0x14, 0xc0005978f0, 0x2, 0x2, 0xc0006383c0, 0x0, ...)
	github.com/ledgerwatch/erigon/rpc/service.go:226 +0x392 fp=0xc00054fcd8 sp=0xc00054fba8 pc=0xa41bb2
github.com/ledgerwatch/erigon/rpc.(*handler).runMethod(0xc0001245a0, 0x132ec98, 0xc0006741c0, 0xc0000ec2a0, 0xc000505080, 0xc0005978f0, 0x2, 0x2, 0xc0006383c0, 0x0)
	github.com/ledgerwatch/erigon/rpc/handler.go:484 +0xb2c fp=0xc00054fd90 sp=0xc00054fcd8 pc=0xa3b72c
github.com/ledgerwatch/erigon/rpc.(*handler).handleCall(0xc0001245a0, 0xc000597890, 0xc0000ec2a0, 0xc0006383c0, 0x60)
	github.com/ledgerwatch/erigon/rpc/handler.go:389 +0x25f fp=0xc00054fe48 sp=0xc00054fd90 pc=0xa3a05f
github.com/ledgerwatch/erigon/rpc.(*handler).handleCallMsg(0xc0001245a0, 0xc000597890, 0xc0000ec2a0, 0xc0006383c0, 0x28)
	github.com/ledgerwatch/erigon/rpc/handler.go:343 +0x1a5 fp=0xc00054fed0 sp=0xc00054fe48 pc=0xa39305
github.com/ledgerwatch/erigon/rpc.(*handler).handleMsg.func1(0xc000597890)
	github.com/ledgerwatch/erigon/rpc/handler.go:181 +0x132 fp=0xc00054ff68 sp=0xc00054fed0 pc=0xa46fd2
github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc.func1(0xc0001245a0, 0xc000634360)
	github.com/ledgerwatch/erigon/rpc/handler.go:271 +0xd2 fp=0xc00054ffd0 sp=0xc00054ff68 pc=0xa47272
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc00054ffd8 sp=0xc00054ffd0 pc=0x4bbda1
created by github.com/ledgerwatch/erigon/rpc.(*handler).startCallProc
	github.com/ledgerwatch/erigon/rpc/handler.go:267 +0x66
````

**Comment by AskAlexSharov** [comment]
optimistically closing. if it's still an issue - feel free to reopen
