### ISSUE TITLE
Panic on graceful shutdown

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon#3499]
Commit hash : git_commit=7261215e6e25520cae5aad1e1b1ccebd875d021e

#### Steps to reproduce the behaviour

Press Ctrl-C after having just downloaded headers

#### Backtrace

````
WARN[02-12|16:20:50.434] [direct] stream returns                  err="context canceled"
WARN[02-12|16:20:50.434] [direct] stream returns                  err="context canceled"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x522affc]

goroutine 89 [running]:
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.(*Filters).HandlePendingBlock(0xc001b2ab40, 0x0)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:226 +0x5c
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.(*Filters).subscribeToPendingBlocks(0xc001b2ab40, 0x6738158, 0xc001b2a180, 0x674acd8, 0xc0012e91c0, 0x0, 0x0)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:219 +0x15a
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.New.func3(0x6738158, 0xc001b2a180, 0xc001b2ab40, 0x674acd8, 0xc0012e91c0)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:121 +0x98
created by github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.New
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:114 +0x2b4
````

**Comment by AlexeyAkhunov** [comment]
Probably related to the internal RPC Daemon work

**Comment by AskAlexSharov** [comment]
fixed in devel
