### ISSUE TITLE
Panic while restarting erigon (devel)

### ISSUE THREAD

**Issue by geomad** [ledgerwatch/erigon#3511]
#### System information

Erigon version: devel v2022.02.02
OS & Version: Linux debian
Commit hash : Restarting after updating from ef6013faff0d10cfb2d4b9afbee8f0a1fe73fb94 to dffcc57ecc7fa64ea207cc9075a29e8874669327

#### Issue

Erigon panicked while restarting after updating. systemd service is set up with `KillSignal=SIGINT`
After the restart erigon is working properly.

```
[INFO] [p2p] GoodPeers                          eth66=20
[INFO] [txpool] stat                            block=14200283 pending=764 baseFee=30000 queued=30000 alloc_mb=1051 sys_mb=1438
[INFO] [1/16 Headers] Processed                 highest inserted=14200284 age=24s
Stopping Erigon client daemon...
[INFO] Got interrupt, shutting down...
[WARN] [direct] stream returns                  err="context canceled"
[WARN] subscription to newHeaders closed        reason="context canceled"
[WARN] subscription to newHeaders closed        reason="context canceled"
[WARN] Messages returned                        err="context canceled"
[WARN] [direct] stream returns                  err="context canceled"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x140d586]
goroutine 106 [running]:
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.(*Filters).OnNewEvent(0xc000e41180, 0x0)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:344 +0xa6
github.com/ledgerwatch/erigon/cmd/rpcdaemon/services.(*RemoteBackend).Subscribe(0xc000170730, {0x278f938, 0xc000e40980}, 0xc000282010)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/services/eth_backend.go:155 +0x1c8
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.New.func1()
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:65 +0xe2
created by github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.New
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:54 +0x1de
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x140d972]
goroutine 107 [running]:
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.(*Filters).OnNewTx(0xc000e41180, 0x0)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:395 +0xb2
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.(*Filters).subscribeToPendingTransactions(0x0, {0x278f938, 0xc000e40980}, {0x27acdd0, 0xc001f0aa20})
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:193 +0x125
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.New.func2()
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:94 +0x95
created by github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.New
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:87 +0x28f
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x140c101]
goroutine 108 [running]:
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.(*Filters).HandlePendingBlock(0xc000e41180, 0x0)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:226 +0x61
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.(*Filters).subscribeToPendingBlocks(0x0, {0x278f938, 0xc000e40980}, {0x27acd70, 0xc001f0aa30})
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:219 +0x129
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.New.func3()
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:121 +0x95
created by github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.New
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:114 +0x446
erigon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
erigon.service: Failed with result 'exit-code'.
Stopped Erigon client daemon.
erigon.service: Consumed 1h 6min 47.564s CPU time.
Started Erigon client daemon.
[INFO] Build info                               git_branch=devel git_tag=v2022.02.02 git_commit=dffcc57ecc7fa64ea207cc9075a29e8874669327
[INFO] Starting Erigon on Ethereum mainnet...
[INFO] Maximum peer count                       ETH=20 total=20
[INFO] Set global gas cap                       cap=50000000
[INFO] Opening Database                         label=chaindata path=/erigon/chaindata
mdbx_ipclock_failed:30346 wlock owner died, recovering
[INFO] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Terminal Total Difficulty: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
[INFO] Disk storage enabled for ethash DAGs     dir=/erigon/erigon-ethash count=2
[INFO] Initialising Ethereum protocol           network=1
[INFO] Effective                                prune_flags="--prune=" snapshot_flags=
[INFO] Starting private RPC server              on=localhost:9090
```

**Comment by AskAlexSharov** [comment]
thank you. fixed in latest devel
