### ISSUE TITLE
Panic on shutdown (devel)

### ISSUE THREAD

**Issue by geomad** [ledgerwatch/erigon#3549]
#### System information

Erigon version: devel v2022.02.02
OS & Version: Linux debian
Commit hash : Restarting after updating from e74b9ef9ffea340798c9c6ca439e707efa444cbf to 5db869236a295938647bdd255e1c7899ca7ba9a2

#### Issue

Erigon panicked while restarting after updating. systemd service is set up with `KillSignal=SIGINT`
After the restart erigon is working properly.
```
erigon --txpool.disable --datadir /erigon --maxpeers 25 --ethash.dagdir /erigon/erigon-ethash --port 30305 --private.api.addr=localhost:9090
```

```
[INFO] Got interrupt, shutting down...
Stopping Erigon client daemon...
[WARN] subscription to newHeaders closed        reason="context canceled"
[WARN] subscription to newHeaders closed        reason="context canceled"
[INFO] Exiting...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x140ed81]
goroutine 32 [running]:
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.(*Filters).HandlePendingBlock(0xc00035f180, 0x0)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:227 +0x61
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.(*Filters).subscribeToPendingBlocks(0x0, {0x27caa38, 0xc00035ec40}, {0x27e7f70, 0xc00115c580})
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:220 +0x129
github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.New.func3()
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:122 +0x95
created by github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters.New
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/filters/filters.go:115 +0x446
erigon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
erigon.service: Failed with result 'exit-code'.
Stopped Erigon client daemon.
erigon.service: Consumed 1h 9min 51.811s CPU time.
Started Erigon client daemon.
[INFO] Build info                               git_branch=devel git_tag=v2022.02.03 git_commit=5db869236a295938647bdd255e1c7899ca7ba9a2
[INFO] Starting Erigon on Ethereum mainnet...
[INFO] Maximum peer count                       ETH=20 total=20
[INFO] Set global gas cap                       cap=50000000
[INFO] Opening Database                         label=chaindata path=/erigon/chaindata
```

**Comment by AskAlexSharov** [comment]
We fixed it in later versions, but there is one more similar issue: https://github.com/ledgerwatch/erigon/issues/3559
