### ISSUE TITLE
`debug_traceTransaction` call calls `rpcdaemon` for large gas transaction

### ISSUE THREAD

**Issue by riordant** [ledgerwatch/erigon#3864]
#### System information

Erigon version: `./erigon --version`
erigon version 2022.02.3-beta

OS & Version: Windows/Linux/OSX
Linux Mint 20

Commit hash : 
```
commit 227bb7368937ba408da82fddcacc02d27153d4fe (HEAD, tag: v2022.02.03)
Author: Alex Sharov <AskAlexSharov@gmail.com>
Date:   Thu Feb 17 14:37:26 2022 +0700

    save (#3533)
```

#### Expected behaviour
calling the following:
`curl -s --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x00a516e3401db12dc3d9beacf746f269290a7092e105072f27b3a852a202309e"],"id":"1"}' -H "Content-Type: application/json" -X POST http://localhost:8545`

Causes `rpcdaemon` to be killed with the following:
`[1]    1056550 killed     ./rpcdaemon --datadir=/mnt/lv/erigon --private.api.addr=localhost:9090   "*"`

#### Actual behaviour
Should return the data for `debug_traceTransaction` without killing the daemon

#### Steps to reproduce the behaviour
`./erigon --datadir=/mnt/lv/erigon --private.api.addr=localhost:9090`
`./rpcdaemon --datadir=/mnt/lv/erigon --private.api.addr=localhost:9090 --http.api=eth,erigon,web3,net,debug,trace,txpool --http.corsdomain "*" --rpc.gascap 0`
then executing the above `cURL` command.

Also, I understand from reading the docs that it is possible to 'stream' the output of this call. How is that achieved? I cannot find anything else about it in the docs.

**Comment by victordeleau** [comment]
Using the commit you provided I have a panic due to a segmentation violation when starting erigon with `--mine`. Will try on mainnet once my node is synced.

I tried reproduce the issue on `devel` using the dev chain. `debug_traceTransaction` seems to work correctly in that case.

As for streaming the output of the call, I don't know how that works, but I would be interested to know.

**Comment by AskAlexSharov** [comment]
@victordeleau show top 20 lines of panic.

**Comment by victordeleau** [comment]
Here is the first stacktrace

```
INFO[05-29|14:55:27.219] [1/5 MiningCreateBlock] Start mine       block=1 baseFee=875000000 gasLimit=11511229
unexpected fault address 0x1b79a30
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1b79a30 pc=0x43b1a3]

goroutine 60 [running, locked to thread]:
runtime.throw({0x11a1734?, 0x0?})
        runtime/panic.go:992 +0x71 fp=0xc00071b580 sp=0xc00071b550 pc=0x461bd1
runtime.sigpanic()
        runtime/signal_unix.go:825 +0x305 fp=0xc00071b5d0 sp=0xc00071b580 pc=0x477f85
runtime.mapiterinit(0x400?, 0x112d160?, 0xc00017eeb0?)
        runtime/map.go:821 +0x23 fp=0xc00071b5f0 sp=0xc00071b5d0 pc=0x43b1a3
reflect.mapiterinit(0x0?, 0xc0000ddc00?, 0xc0000ddc00?)
        runtime/map.go:1373 +0x19 fp=0xc00071b618 sp=0xc00071b5f0 pc=0x48e619
github.com/goccy/go-json/internal/encoder/vm.Run(0xc000014d00, {0xc0000ddc00?, 0x0?, 0x400?}, 0xc00062c880?)
        github.com/goccy/go-json@v0.7.4/internal/encoder/vm/vm.go:410 +0x1fb7 fp=0xc00071ea78 sp=0xc00071b618 pc=0xc72af7
github.com/goccy/go-json.encodeRunCode(0x110f420?, {0xc0000ddc00?, 0x2659688?, 0xc00062c7c0?}, 0xc0005b4c00?)
        github.com/goccy/go-json@v0.7.4/encode.go:307 +0x68 fp=0xc00071eab0 sp=0xc00071ea78 pc=0xca1ae8
github.com/goccy/go-json.encode(0xc000014d00, {0x110f420, 0xc00017eea0})
        github.com/goccy/go-json@v0.7.4/encode.go:232 +0x21c fp=0xc00071eb30 sp=0xc00071eab0 pc=0xca19dc
github.com/goccy/go-json.marshal({0x110f420, 0xc00017eea0}, {0x0, 0x0, 0xf8007ff46a727108?})
        github.com/goccy/go-json@v0.7.4/encode.go:147 +0xba fp=0xc00071eb90 sp=0xc00071eb30 pc=0xca169a
github.com/goccy/go-json.MarshalWithOption(...)
        github.com/goccy/go-json@v0.7.4/json.go:186
github.com/goccy/go-json.Marshal({0x110f420?, 0xc00017eea0?})
        github.com/goccy/go-json@v0.7.4/json.go:171 +0x2a fp=0xc00071ebc8 sp=0xc00071eb90 pc=0xca1b6a
github.com/ledgerwatch/erigon/consensus/clique.(*Snapshot).store(0xc00017eea0, {0x1cc68b8, 0xc0001a4f80})
        github.com/ledgerwatch/erigon/consensus/clique/snapshot.go:142 +0x39 fp=0xc00071ec18 sp=0xc00071ebc8 pc=0xd420d9
github.com/ledgerwatch/erigon/consensus/clique.(*Clique).Snapshot(0xc00020e240, {0x1cc6648, 0xc0005180f0}, 0x25d32c0?, {0x50, 0x47, 0x42, 0x2d, 0xb8, 0x6d, ...}, ...)
        github.com/ledgerwatch/erigon/consensus/clique/verifier.go:190 +0xb12 fp=0xc00071eeb8 sp=0xc00071ec18 pc=0xd45892
github.com/ledgerwatch/erigon/consensus/clique.(*Clique).Prepare(0xc00020e240, {0x1cc6648, 0xc0005180f0}, 0xc000202780)
        github.com/ledgerwatch/erigon/consensus/clique/clique.go:308 +0xda fp=0xc00071f0b8 sp=0xc00071eeb8 pc=0xd3ea7a
github.com/ledgerwatch/erigon/eth/stagedsync.SpawnMiningCreateBlockStage(_, {_, _}, {{0x1cc68b8, 0xc0001a4c00}, {0x2388428, 0xc00028f500, 0xc00028f560, 0xc000364150}, {{0x0, ...}, ...}, ...}, ...)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_mining_create_block.go:237 +0x1342 fp=0xc00071fbb0 sp=0xc00071f0b8 pc=0xe41582
github.com/ledgerwatch/erigon/eth/stagedsync.MiningStages.func1(0x10?, 0x6d?, 0x11ae426?, {0x11?, 0x1cc9b78?}, {0x1ccd188, 0xc0002904b0})
        github.com/ledgerwatch/erigon/eth/stagedsync/stagebuilder.go:37 +0xb3 fp=0xc00071fd38 sp=0xc00071fbb0 pc=0xe53193
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc0000d6d10, 0xc00010eeb0, {0x0?, 0x0}, {0x1ccd188?, 0xc0002904b0}, 0x0?, 0x0?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:316 +0x14c fp=0xc00071fe38 sp=0xc00071fd38 pc=0xe5582c
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc0000d6d10, {0x0, 0x0}, {0x1ccd188, 0xc0002904b0}, 0x0?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:233 +0x2a5 fp=0xc00071fee8 sp=0xc00071fe38 pc=0xe54ae5
github.com/ledgerwatch/erigon/turbo/stages.MiningStep({0x1cc46a0?, 0xc000036098?}, {0x1cc68b8?, 0xc0001a4c00?}, 0x0?)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:209 +0x10c fp=0xc00071ff90 sp=0xc00071fee8 pc=0xe5f76c
github.com/ledgerwatch/erigon/eth.(*Ethereum).StartMining.func3.1()
        github.com/ledgerwatch/erigon/eth/backend.go:640 +0x36 fp=0xc00071ffe0 sp=0xc00071ff90 pc=0xe66656
runtime.goexit()
        runtime/asm_amd64.s:1571 +0x1 fp=0xc00071ffe8 sp=0xc00071ffe0 pc=0x494e41
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).StartMining.func3
        github.com/ledgerwatch/erigon/eth/backend.go:640 +0x3d8
```

**Comment by mandrigin** [comment]
I assume it is a duplicate of #4637

Mining issue seems to be different. I will close this issue for now, but please reopen @victordeleau if it reproduces on the latest release.
