### ISSUE TITLE
Erigon crash on Goerli test net

### ISSUE THREAD

**Issue by JuliusDegesys** [ledgerwatch/erigon#3912]
#### System information

Erigon version: `./erigon --version`
erigon version 2022.99.99-dev-0a5ce152

OS & Version: Linux

Commit hash : 0a5ce152a

#### Expected behaviour
Erigon runs without crashing.

#### Actual behaviour
Erigon crashes.

#### Steps to reproduce the behaviour
Start erigon & rpcdaemon for goerli test net.
```
./build/bin/erigon --datadir /mnt/md0/goerli --chain goerli --private.api.addr=localhost:9091 --port 30304
./build/bin/rpcdaemon --datadir=/mnt/md0/goerli --txpool.api.addr=localhost:9091 --private.api.addr=localhost:9091 --http.api=eth,erigon,web3,net,debug,trace,txpool --http.port 8546
```
`erigon` crashes, but `rpcdaemon` doesn't. I was able to reproduce the following error several times, just by trying to start `erigon`. Eventually, after closing `rpcdaemon`, I was able to restart `erigon` without an exception.

If it matters, I was also running the mainnet at the same time. However, no issues on these two processes:
```
./build/bin/erigon --datadir /mnt/md0/mainnet --chain mainnet --private.api.addr=localhost:9090 --port 30303
./build/bin/rpcdaemon --datadir=/mnt/md0/mainnet --txpool.api.addr=localhost:9090 --private.api.addr=localhost:9090 --http.api=eth,erigon,web3,net,debug,trace,txpool --http.port 8545
```
#### Backtrace
```
$ ./build/bin/erigon --datadir /mnt/md0/goerli --chain goerli --private.api.addr=localhost:9091 --port 30304
INFO[04-18|03:41:27.441] Build info                               git_branch=devel git_tag=v2022.04.02 git_commit=0a5ce152a4b4e5fb997eb317e5a2c0dfe444c1bc
INFO[04-18|03:41:27.442] Starting Erigon on Görli testnet... 
INFO[04-18|03:41:27.443] Maximum peer count                       ETH=100 total=100
INFO[04-18|03:41:27.444] [torrent] Public IP                      ip=70.19.93.60
INFO[04-18|03:41:27.444] Set global gas cap                       cap=50000000
INFO[04-18|03:41:27.446] Opening Database                         label=chaindata path=/mnt/md0/goerli/chaindata
erigon: ../nptl/pthread_mutex_lock.c:428: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.
SIGABRT: abort
PC=0x7f4bf6dbc03b m=8 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x13d2970, 0xc000d5f260)
	runtime/cgocall.go:157 +0x5c fp=0xc000d5f238 sp=0xc000d5f200 pc=0x449e9c
github.com/torquem-ch/mdbx-go/mdbx._Cfunc_mdbx_txn_begin(0x7f4bac000b60, 0x0, 0x0, 0xc001188108)
	_cgo_gotypes.go:879 +0x4c fp=0xc000d5f260 sp=0xc000d5f238 pc=0x914fec
github.com/torquem-ch/mdbx-go/mdbx.beginTxn.func1(0x7?, 0x0, 0x0, 0xc001188100)
	github.com/torquem-ch/mdbx-go@v0.23.2/mdbx/txn.go:109 +0xb9 fp=0xc000d5f2a8 sp=0xc000d5f260 pc=0x91be59
github.com/torquem-ch/mdbx-go/mdbx.beginTxn(0xc0011de750, 0x0, 0x0)
	github.com/torquem-ch/mdbx-go@v0.23.2/mdbx/txn.go:109 +0x18b fp=0xc000d5f2f0 sp=0xc000d5f2a8 pc=0x91bc4b
github.com/torquem-ch/mdbx-go/mdbx.(*Env).BeginTxn(...)
	github.com/torquem-ch/mdbx-go@v0.23.2/mdbx/env.go:526
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).BeginRw(0xc00026c000, {0xc0011f8cb0?, 0x7?})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220415104858-ee6e50ab671d/kv/mdbx/kv_mdbx.go:424 +0xc5 fp=0xc000d5f3d8 sp=0xc000d5f2f0 pc=0x9220e5
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).Update(0xc00026c000, {0x287b400, 0xc0000401d8}, 0xc000d5f490)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220415104858-ee6e50ab671d/kv/mdbx/kv_mdbx.go:650 +0xcf fp=0xc000d5f470 sp=0xc000d5f3d8 pc=0x92398f
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).openDBIs(0xc0011de780?, {0xc0011f2400?, 0x17b59a1?, 0xe?})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220415104858-ee6e50ab671d/kv/mdbx/kv_mdbx.go:349 +0xd0 fp=0xc000d5f4c8 sp=0xc000d5f470 pc=0x921690
github.com/ledgerwatch/erigon-lib/kv/mdbx.MdbxOpts.Open({0x2698b28, {0xc000406400, 0x19}, 0x0, 0x0, 0x2, 0x60000000000, 0x2800000, {0x2882fd8, 0xc000d690e0}, ...})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220415104858-ee6e50ab671d/kv/mdbx/kv_mdbx.go:271 +0x94f fp=0xc000d5f6a8 sp=0xc000d5f4c8 pc=0x92100f
github.com/ledgerwatch/erigon/node.OpenDatabase.func1(0x60?)
	github.com/ledgerwatch/erigon/node/node.go:532 +0x285 fp=0xc000d5fa18 sp=0xc000d5f6a8 pc=0x120a8a5
github.com/ledgerwatch/erigon/node.OpenDatabase(0xc000204a00, {0x2882fd8, 0xc000d690e0}, 0x0)
	github.com/ledgerwatch/erigon/node/node.go:535 +0x31c fp=0xc000d5fbc0 sp=0xc000d5fa18 pc=0x120a21c
github.com/ledgerwatch/erigon/eth.New(0xc0000e0000, 0x32c89a0, {{0xc0011d8528, 0x16}, 0x1bf08eb000, 0x5f5e100, 0x45d964b800, 0xdf8475800, 0x2710, 0x7530, ...}, ...)
	github.com/ledgerwatch/erigon/eth/backend.go:155 +0x47f fp=0xc000d615e0 sp=0xc000d5fbc0 pc=0x13a4d5f
github.com/ledgerwatch/erigon/turbo/node.RegisterEthService(0xc0000e0000, 0x32c89a0, {0x2882fd8, 0xc000d690e0})
	github.com/ledgerwatch/erigon/turbo/node/node.go:121 +0x19c fp=0xc000d61840 sp=0xc000d615e0 pc=0x13afe9c
github.com/ledgerwatch/erigon/turbo/node.New(0x2876120?, 0x17af8c4?, {0x2882fd8, 0xc000d690e0})
	github.com/ledgerwatch/erigon/turbo/node/node.go:109 +0x45 fp=0xc000d61888 sp=0xc000d61840 pc=0x13afc45
main.runErigon(0xc000d7c9a0?)
	github.com/ledgerwatch/erigon/cmd/erigon/main.go:41 +0x1e5 fp=0xc000d61938 sp=0xc000d61888 pc=0x13b65c5
github.com/urfave/cli.HandleAction({0x1521c20?, 0x269b508?}, 0xc00014e540?)
	github.com/urfave/cli@v1.22.5/app.go:526 +0x50 fp=0xc000d61950 sp=0xc000d61938 pc=0x7808b0
github.com/urfave/cli.(*App).Run(0xc00014e540, {0xc00003c080, 0x8, 0x8})
	github.com/urfave/cli@v1.22.5/app.go:286 +0x7c5 fp=0xc000d61f28 sp=0xc000d61950 pc=0x77de85
main.main()
	github.com/ledgerwatch/erigon/cmd/erigon/main.go:28 +0x75 fp=0xc000d61f80 sp=0xc000d61f28 pc=0x13b6355
runtime.main()
	runtime/proc.go:250 +0x212 fp=0xc000d61fe0 sp=0xc000d61f80 pc=0x47ee92
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc000d61fe8 sp=0xc000d61fe0 pc=0x4afba1

goroutine 6 [sleep]:
time.Sleep(0x22ecb25c00)
	runtime/time.go:194 +0x12e
github.com/VictoriaMetrics/metrics.summariesSwapCron(0x45d964b800)
	github.com/VictoriaMetrics/metrics@v1.18.1/summary.go:237 +0x36
created by github.com/VictoriaMetrics/metrics.registerSummaryLocked
	github.com/VictoriaMetrics/metrics@v1.18.1/summary.go:211 +0x125

goroutine 50 [semacquire]:
sync.runtime_Semacquire(0xc000582340?)
	runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc000226401?)
	sync/waitgroup.go:136 +0x52
golang.org/x/sync/errgroup.(*Group).Wait(0xc000d744c0)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x27
github.com/huin/goupnp/httpu.(*MultiClient).Do(0xc000156108, 0xc0001a1e00, 0x7d2b7500, 0x3)
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/httpu/multiclient.go:48 +0x15c
github.com/huin/goupnp/ssdp.SSDPRawSearch({0x7f4bcc3b5018, 0xc000156108}, {0x17fb87e, 0x31}, 0x2, 0x157eb00?)
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/ssdp/ssdp.go:68 +0x42a
github.com/huin/goupnp.DiscoverDevices({0x17fb87e, 0x31})
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/goupnp.go:82 +0xb9
github.com/ledgerwatch/erigon/p2p/nat.discover(0xc0004f6480, {0x17fb87e?, 0x738926?}, 0x2699270)
	github.com/ledgerwatch/erigon/p2p/nat/natupnp.go:186 +0x6b
created by github.com/ledgerwatch/erigon/p2p/nat.discoverUPnP
	github.com/ledgerwatch/erigon/p2p/nat/natupnp.go:152 +0x76

goroutine 20 [chan receive]:
github.com/ledgerwatch/erigon/p2p/nat.discoverUPnP()
	github.com/ledgerwatch/erigon/p2p/nat/natupnp.go:174 +0x10d
github.com/ledgerwatch/erigon/p2p/nat.Any.func1.1()
	github.com/ledgerwatch/erigon/p2p/nat/nat.go:155 +0x25
created by github.com/ledgerwatch/erigon/p2p/nat.Any.func1
	github.com/ledgerwatch/erigon/p2p/nat/nat.go:155 +0x6b

goroutine 51 [semacquire]:
sync.runtime_Semacquire(0xc000582d00?)
	runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc000226301?)
	sync/waitgroup.go:136 +0x52
golang.org/x/sync/errgroup.(*Group).Wait(0xc000d74240)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x27
github.com/huin/goupnp/httpu.(*MultiClient).Do(0xc000156078, 0xc0001a1800, 0x7d2b7500, 0x3)
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/httpu/multiclient.go:48 +0x15c
github.com/huin/goupnp/ssdp.SSDPRawSearch({0x7f4bcc3b5018, 0xc000156078}, {0x17fb8af, 0x31}, 0x2, 0xc0003da060?)
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/ssdp/ssdp.go:68 +0x42a
github.com/huin/goupnp.DiscoverDevices({0x17fb8af, 0x31})
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/goupnp.go:82 +0xb9
github.com/ledgerwatch/erigon/p2p/nat.discover(0xc0004f6480, {0x17fb8af?, 0xc0003da438?}, 0x2699278)
	github.com/ledgerwatch/erigon/p2p/nat/natupnp.go:186 +0x6b
created by github.com/ledgerwatch/erigon/p2p/nat.discoverUPnP
	github.com/ledgerwatch/erigon/p2p/nat/natupnp.go:162 +0xc5

goroutine 52 [semacquire]:
sync.runtime_Semacquire(0xc000582ea0?)
	runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc0003da001?)
	sync/waitgroup.go:136 +0x52
golang.org/x/sync/errgroup.(*Group).Wait(0xc000d74500)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x27
github.com/huin/goupnp/httpu.(*MultiClient).sendRequests(0xc000156078, 0xc0001520c0, 0xc0001a1800, 0x7d2b7500, 0x3)
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/httpu/multiclient.go:69 +0x65
github.com/huin/goupnp/httpu.(*MultiClient).Do.func1()
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/httpu/multiclient.go:37 +0x6e
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d

goroutine 53 [chan receive]:
github.com/huin/goupnp/httpu.(*MultiClient).Do.func2()
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/httpu/multiclient.go:42 +0x4a
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d

goroutine 54 [semacquire]:
sync.runtime_Semacquire(0xc0005831e0?)
	runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x157eb01?)
	sync/waitgroup.go:136 +0x52
golang.org/x/sync/errgroup.(*Group).Wait(0xc000d74580)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x27
github.com/huin/goupnp/httpu.(*MultiClient).sendRequests(0xc000156108, 0xc000152120, 0xc0001a1e00, 0x7d2b7500, 0x3)
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/httpu/multiclient.go:69 +0x65
github.com/huin/goupnp/httpu.(*MultiClient).Do.func1()
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/httpu/multiclient.go:37 +0x6e
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d

goroutine 55 [chan receive]:
github.com/huin/goupnp/httpu.(*MultiClient).Do.func2()
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/httpu/multiclient.go:42 +0x4a
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d

goroutine 56 [sleep]:
time.Sleep(0x4c4b40)
	runtime/time.go:194 +0x12e
github.com/huin/goupnp/httpu.(*HTTPUClient).Do(0xc000156060, 0xc0001a1800, 0xc0003d3b60?, 0x3)
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/httpu/httpu.go:116 +0x525
github.com/huin/goupnp/httpu.(*MultiClient).sendRequests.func1()
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/httpu/multiclient.go:61 +0x4a
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d

goroutine 57 [sleep]:
time.Sleep(0x4c4b40)
	runtime/time.go:194 +0x12e
github.com/huin/goupnp/httpu.(*HTTPUClient).Do(0xc0001560f0, 0xc0001a1e00, 0xc0003d3b60?, 0x3)
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/httpu/httpu.go:116 +0x525
github.com/huin/goupnp/httpu.(*MultiClient).sendRequests.func1()
	github.com/huin/goupnp@v1.0.1-0.20210626160114-33cdcbb30dda/httpu/multiclient.go:61 +0x4a
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d

rax    0x0
rbx    0x7f4bccd14700
rcx    0x7f4bf6dbc03b
rdx    0x0
rdi    0x2
rsi    0x7f4bccd139e0
rbp    0x7f4bf6f31588
rsp    0x7f4bccd139e0
r8     0x0
r9     0x7f4bccd139e0
r10    0x8
r11    0x246
r12    0x7f4bf72ce5fa
r13    0x1ac
r14    0x7f4bf72ce617
r15    0x7f4bd028f40a
rip    0x7f4bf6dbc03b
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

```

**Comment by AskAlexSharov** [comment]
Plz: OS, FS, cc -v

**Comment by AskAlexSharov** [comment]
closing due to inactivity. feel free to switch to newer release and create new issue if need

**Comment by brandoncurtis** [comment]
For anyone who finds this issue while searching for this error: try disabling the RPC daemon before restarting Erigon.  This allowed me to bypass the error and recover successfully from the crash.

- Erigon version v2022.06.03
