### ISSUE TITLE
erigon2 stuck at block 14826995

### ISSUE THREAD

**Issue by changwilling** [ledgerwatch/erigon#4268]
#### System information

Erigon version: `./erigon --version`

Erigon version: erigon version 2022.05.7-alpha-327e7d9

OS & Version: linux

Commit hash : 327e7d969cf4448153d54761b4f160faf306d0ad

#### Expected behaviour
Everything works ok

#### Actual behaviour
Execution failed on block 14826995

#### Steps to reproduce the behaviour
1. I synced erigon on ethereum mainnet via  ./build/bin/erigon --datadir=/data/erigon --private.api.addr=0.0.0.0:9090
2. the the node exist the error log:
    ```
    Execution failed        block=14826995 hash=0xbdb29f71505b70bcdc19fc0220e7303e1d4a2a52885807cb9251706ad2ccde43 err="could not apply tx 1 from block 14826995 [0x029d011a51368917f2c79a5ca3c8ea1f5da88847de0eabc8c938a4c32d5ae7f3]: nonce too low: address 0x0000f079e68BbCC79AB9600ace786B0a4dB1c83c, tx: 132397 state: 132398"
    ```
3.then eth block stuck with logs:
   ```
  INFO[05-26|02:30:36.238] [1/16 Headers] Wrote block headers       number=14826994 blk/second=0.000 alloc=3.6Gb sys=11.5Gb
INFO[05-26|02:30:36.238] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=51 respMin=14832538 respMax=14845406
INFO[05-26|02:30:36.238] {14832538-14845406 links=12870 (14832538-14845401-14845406)} => f5b6a387681f23b6f9477d4a84b7524d5ea83609584631726f49e0239b5921d6
INFO[05-26|02:30:56.227] [snapshots] Dumping txs                  block num=14602250 alloc=4.6Gb sys=11.5Gb
INFO[05-26|02:30:56.237] [1/16 Headers] Wrote block headers       number=14826994 blk/second=0.000 alloc=4.6Gb sys=11.5Gb
INFO[05-26|02:30:56.237] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=34 respMin=14827162 respMax=14845407
INFO[05-26|02:30:56.238] {14827162-14845407 links=18247 (14827162-14845401-14845407)} => c7dd9e13c171ffb33627a5595105466da724dab4905e2363f3d2c69bf7636d9b
INFO[05-26|02:31:16.238] [1/16 Headers] Wrote block headers       number=14826994 blk/second=0.000 alloc=3.6Gb sys=11.5Gb
INFO[05-26|02:31:16.238] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=9 respMin=14826970 respMax=14828505
INFO[05-26|02:31:16.238] [snapshots] Dumping txs                  block num=14603005 alloc=3.6Gb sys=11.5Gb
INFO[05-26|02:31:36.230] [snapshots] Dumping txs                  block num=14603691 alloc=2.9Gb sys=11.6Gb
INFO[05-26|02:31:36.238] [1/16 Headers] Wrote block headers       number=14826994 blk/second=0.000 alloc=2.9Gb sys=11.6Gb
INFO[05-26|02:31:36.238] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=13 respMin=14843488 respMax=14845408
INFO[05-26|02:31:36.238] {14843488-14845408 links=1921 (14843488-14845408)} => 4c86c71151a54e83b11dff6ee22150110561a60a9353a8d621d3ffcb3e3b3722
INFO[05-26|02:31:56.224] [snapshots] Dumping txs                  block num=14604399 alloc=3.9Gb sys=11.6Gb
INFO[05-26|02:31:56.237] [1/16 Headers] Wrote block headers       number=14826994 blk/second=0.000 alloc=3.9Gb sys=11.6Gb
INFO[05-26|02:31:56.237] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=45 respMin=14837152 respMax=14845411
INFO[05-26|02:31:56.237] {14837152-14845411 links=8260 (14837152-14845411)} => c76dcdece75e4eea87c146282872dddd33909753b7fd8e25ca35698bf9699beb
INFO[05-26|02:32:07.392] [p2p] GoodPeers                          eth66=32
INFO[05-26|02:32:16.235] [snapshots] Dumping txs                  block num=14605090 alloc=4.9Gb sys=11.6Gb
INFO[05-26|02:32:16.237] [1/16 Headers] Wrote block headers       number=14826994 blk/second=0.000 alloc=4.9Gb sys=11.6Gb
INFO[05-26|02:32:16.237] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=33 respMin=14832352 respMax=14845412
INFO[05-26|02:32:16.238] {14832352-14845412 links=13061 (14832352-14845412)} => 6b38f5f6a7162b202016799abaa742e3c7531a87ddff61ccf3c741637812c2ea
INFO[05-26|02:32:36.237] [1/16 Headers] Wrote block headers       number=14826994 blk/second=0.000 alloc=3.4Gb sys=11.7Gb
INFO[05-26|02:32:36.237] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=29 respMin=14826976 respMax=14832351
INFO[05-26|02:32:36.487] [snapshots] Dumping txs                  block num=14605731 alloc=3.4Gb sys=11.7Gb
   ```
3.I try to fix use command bellow:
```
./build/bin/integration stage_headers --reset --datadir=/data/erigon
```
but it appears the same fault. 
now i use command : ./build/bin/integration print_stages --datadir=/data/erigon, logs bellow:
```
                         stage_at        prune_at
Headers                  14826994        0
BlockHashes              14826994        0
Bodies                   14826994        0
Senders                  14826994        0
Execution                14826994        14826994
Translation              0               0
HashState                14826994        0
IntermediateHashes       14826994        14826994
AccountHistoryIndex      14826994        0
StorageHistoryIndex      14826994        0
LogIndex                 14826994        0
CallTraces               14826994        14826994
TxLookup                 14826994        14700000
Finish                   14826994        0
--
prune distance:

sequence: EthTx=1612315500, NonCanonicalTx=1615623551

first header in db: 14600000
```
Any help to fix this issue would be appreciated.

**Comment by AlexeyAkhunov** [comment]
There was one more fix after the last release, it will be included into the next release, or alternatively you can try from `devel`

**Comment by AskAlexSharov** [comment]
If you still see this error try:
`./build/bin/integration state_stages --unwind=1000 --datadir=<your_datadir>`

**Comment by changwilling** [comment]
> INFO[05-26|02:31:56.237] [1/16 Headers] Wrote block headers       number=14826994 blk/second=0.000 alloc=3.9Gb sys=11.6Gb


> There was one more fix after the last release, it will be included into the next release, or alternatively you can try from `devel`

Thanks for the new release so fast, but it still stuck by logs bellow:
```
INFO[05-28|14:25:07.733] [1/16 Headers] Wrote block headers       number=14599999 blk/second=0.000 alloc=3.0Gb sys=4.9Gb
INFO[05-28|14:25:07.733] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=0 respMin=0 respMax=0
INFO[05-28|14:25:07.740] {14626361-14860772 links=234474 (14626361-14859656-14859677-14859701-14859743-14859755-14859758-14859762-14859765-14859773-14859821-14859842-14859899-14859932-14859934-14859943-14859944-14859954-14859978-14859993-14860019-14860030-14860033-14860043-14860056-14860057-14860075-14860086-14860096-14860128-14860143-14860191-14860198-14860217-14860220-14860238-14860258-14860316-14860324-14860330-14860334-14860365-14860385-14860414-14860418-14860430-14860438-14860450-14860451-14860508-14860580-14860613-14860666-14860673-14860681-14860700-14860705-14860712-14860723-14860734-14860761-14860769-14860772)} => 6c4e246787cb634a8a06ac346a5cda503584b4f5c0c7a58eb07dfff7dbdbda50
INFO[05-28|14:25:07.740] {14871533-14871533 links=1 (14871533)} => 23457f0afaaa08afbe58a032a0886ff7653cd8b16c04b327a4a6f0921f8c2d84
INFO[05-28|14:25:07.740] {14871572-14871572 links=1 (14871572)} => 715de0808528214736cb6d635b429f6ee7e2a6b6e9c867a859d8ce3273684a5e
INFO[05-28|14:25:27.733] [1/16 Headers] Wrote block headers       number=14599999 blk/second=0.000 alloc=3.2Gb sys=4.9Gb
INFO[05-28|14:25:27.733] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=2 respMin=14860773 respMax=14860773
INFO[05-28|14:25:27.740] {14626361-14860773 links=234475 (14626361-14859656-14859677-14859701-14859743-14859755-14859758-14859762-14859765-14859773-14859821-14859842-14859899-14859932-14859934-14859943-14859944-14859954-14859978-14859993-14860019-14860030-14860033-14860043-14860056-14860057-14860075-14860086-14860096-14860128-14860143-14860191-14860198-14860217-14860220-14860238-14860258-14860316-14860324-14860330-14860334-14860365-14860385-14860414-14860418-14860430-14860438-14860450-14860451-14860508-14860580-14860613-14860666-14860673-14860681-14860700-14860705-14860712-14860723-14860734-14860761-14860769-14860773)} => 6c4e246787cb634a8a06ac346a5cda503584b4f5c0c7a58eb07dfff7dbdbda50
INFO[05-28|14:25:27.740] {14871533-14871533 links=1 (14871533)} => 23457f0afaaa08afbe58a032a0886ff7653cd8b16c04b327a4a6f0921f8c2d84
INFO[05-28|14:25:27.740] {14871572-14871572 links=1 (14871572)} => 715de0808528214736cb6d635b429f6ee7e2a6b6e9c867a859d8ce3273684a5e
INFO[05-28|14:25:47.732] [1/16 Headers] Wrote block headers       number=14599999 blk/second=0.000 alloc=2.5Gb sys=4.9Gb
INFO[05-28|14:25:47.732] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=8 respMin=14860774 respMax=14860774
INFO[05-28|14:25:47.739] {14626361-14860774 links=234476 (14626361-14859656-14859677-14859701-14859743-14859755-14859758-14859762-14859765-14859773-14859821-14859842-14859899-14859932-14859934-14859943-14859944-14859954-14859978-14859993-14860019-14860030-14860033-14860043-14860056-14860057-14860075-14860086-14860096-14860128-14860143-14860191-14860198-14860217-14860220-14860238-14860258-14860316-14860324-14860330-14860334-14860365-14860385-14860414-14860418-14860430-14860438-14860450-14860451-14860508-14860580-14860613-14860666-14860673-14860681-14860700-14860705-14860712-14860723-14860734-14860761-14860769-14860774)} => 6c4e246787cb634a8a06ac346a5cda503584b4f5c0c7a58eb07dfff7dbdbda50
INFO[05-28|14:25:47.739] {14871533-14871533 links=1 (14871533)} => 23457f0afaaa08afbe58a032a0886ff7653cd8b16c04b327a4a6f0921f8c2d84
INFO[05-28|14:25:47.739] {14871572-14871572 links=1 (14871572)} => 715de0808528214736cb6d635b429f6ee7e2a6b6e9c867a859d8ce3273684a5e
INFO[05-28|14:26:07.733] [1/16 Headers] Wrote block headers       number=14599999 blk/second=0.000 alloc=2.7Gb sys=4.9Gb
INFO[05-28|14:26:07.733] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=9 respMin=14860775 respMax=14860776
INFO[05-28|14:26:07.740] {14626361-14860776 links=234478 (14626361-14859656-14859677-14859701-14859743-14859755-14859758-14859762-14859765-14859773-14859821-14859842-14859899-14859932-14859934-14859943-14859944-14859954-14859978-14859993-14860019-14860030-14860033-14860043-14860056-14860057-14860075-14860086-14860096-14860128-14860143-14860191-14860198-14860217-14860220-14860238-14860258-14860316-14860324-14860330-14860334-14860365-14860385-14860414-14860418-14860430-14860438-14860450-14860451-14860508-14860580-14860613-14860666-14860673-14860681-14860700-14860705-14860712-14860723-14860734-14860761-14860769-14860776)} => 6c4e246787cb634a8a06ac346a5cda503584b4f5c0c7a58eb07dfff7dbdbda50
INFO[05-28|14:26:07.740] {14871533-14871533 links=1 (14871533)} => 23457f0afaaa08afbe58a032a0886ff7653cd8b16c04b327a4a6f0921f8c2d84
INFO[05-28|14:26:07.740] {14871572-14871572 links=1 (14871572)} => 715de0808528214736cb6d635b429f6ee7e2a6b6e9c867a859d8ce3273684a5e
```

**Comment by changwilling** [comment]
> If you still see this error try: `./build/bin/integration state_stages --unwind=1000 --datadir=<your_datadir>`

I has tried the command:
```
./build/bin/integration state_stages --datadir=/data/erigon --unwind=1000
```
but exist the error logs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x54 pc=0x10a76e2]

goroutine 1 [running]:
github.com/ledgerwatch/erigon/eth/stagedsync.UnwindIntermediateHashesStage(0xc082186000, 0xc092baa0a0, {0x19faa88, 0xc004542180}, {{0x19f2140, 0xc000550000}, 0x1, {0xc0004d4d20, 0x15}, 0x1, ...}, ...)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_interhashes.go:409 +0x202
github.com/ledgerwatch/erigon/eth/stagedsync.DefaultStages.func26(0x80?, 0x145bc9c?, 0x12?, {0x19faa88?, 0xc004542180?})
        github.com/ledgerwatch/erigon/eth/stagedsync/default_stages.go:130 +0x65
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).unwindStage(0xc000269080, 0x28?, 0xc08fc3bea0, {0x19f2140?, 0xc000550000}, {0x19faa88?, 0xc004542180})
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:351 +0x2eb
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc000269080, {0x19f2140, 0xc000550000}, {0x19faa88, 0xc004542180}, 0xa?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:204 +0x32f
github.com/ledgerwatch/erigon/cmd/integration/commands.syncBySmallSteps({0x19f2140, 0xc000550000}, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...)
        github.com/ledgerwatch/erigon/cmd/integration/commands/state_stages.go:278 +0xb05
github.com/ledgerwatch/erigon/cmd/integration/commands.glob..func24(0x2479340?, {0x1446a91?, 0x2?, 0x2?})
        github.com/ledgerwatch/erigon/cmd/integration/commands/state_stages.go:65 +0x208
github.com/spf13/cobra.(*Command).execute(0x2479340, {0xc0004cd300, 0x2, 0x2})
        github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x247a740)
        github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.4.0/command.go:895
main.main()
        github.com/ledgerwatch/erigon/cmd/integration/main.go:15 +0x112
```
Any suggestions for the issues would be appreciated.

**Comment by AskAlexSharov** [comment]
show: `integration print_stages`

**Comment by AskAlexSharov** [comment]
what if `./build/bin/integration state_stages --datadir=/data/erigon --unwind=1000 --syncmode=snap`
?

**Comment by changwilling** [comment]
> 

Thanks for your suggestion，but still not work. It stuck at this block:
```
INFO[05-29|10:16:16.035] [p2p] GoodPeers                          eth66=33
INFO[05-29|10:16:33.352] [1/16 Headers] Wrote block headers       number=14826994 blk/second=0.000 alloc=13.3Gb sys=21.4Gb
INFO[05-29|10:16:33.352] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=22474 skelMin=14828530 skelMax=14865370 resp=22476 respMin=14828530 respMax=14865891

INFO[05-29|10:16:53.352] [1/16 Headers] Wrote block headers       number=14826994 blk/second=0.000 alloc=7.8Gb sys=21.4Gb
INFO[05-29|10:16:53.352] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=23818 skelMin=14828530 skelMax=14865370 resp=23840 respMin=14828530 respMax=14865893

INFO[05-29|10:17:13.352] [1/16 Headers] Wrote block headers       number=14826994 blk/second=0.000 alloc=9.7Gb sys=21.4Gb
INFO[05-29|10:17:13.352] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=22782 skelMin=14828530 skelMax=14865370 resp=22783 respMin=14828530 respMax=14865894
```

**Comment by changwilling** [comment]
> what if `./build/bin/integration state_stages --datadir=/data/erigon --unwind=1000 --syncmode=snap` ?

The command worked,and no errors happens when i run ./build/bin/integration state_stages --datadir=/data/erigon --unwind=1000 --syncmode=snap, but still stuck at block 14825996. logs bellow:
```
INFO[05-30|00:28:09.103] [1/16 Headers] Wrote block headers       number=14825996 blk/second=0.000 alloc=5.1Gb sys=9.6Gb
INFO[05-30|00:28:09.103] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=11 respMin=14869555 respMax=14869555
INFO[05-30|00:28:29.103] [1/16 Headers] Wrote block headers       number=14825996 blk/second=0.000 alloc=5.2Gb sys=9.6Gb
INFO[05-30|00:28:29.103] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=8 respMin=14869556 respMax=14869556
INFO[05-30|00:28:37.175] [p2p] GoodPeers                          eth66=33
INFO[05-30|00:28:49.103] [1/16 Headers] Wrote block headers       number=14825996 blk/second=0.000 alloc=5.3Gb sys=9.6Gb
INFO[05-30|00:28:49.103] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=12 respMin=14869557 respMax=14869557
INFO[05-30|00:29:09.103] [1/16 Headers] Wrote block headers       number=14825996 blk/second=0.000 alloc=5.5Gb sys=9.6Gb
INFO[05-30|00:29:09.103] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=6 respMin=14869558 respMax=14869558
```

**Comment by changwilling** [comment]
> what if `./build/bin/integration state_stages --datadir=/data/erigon --unwind=1000 --syncmode=snap` ?

and also i noticed the errors logs：
```
Handling incoming message                stream=RecvMessage err="decode BlockBodiesPacket66: rlp: input list has too many elements for eth.BlockRawBodiesPacket66"
```

**Comment by changwilling** [comment]
> > what if `./build/bin/integration state_stages --datadir=/data/erigon --unwind=1000 --syncmode=snap` ?
> 
> The command worked,and no errors happens when i run ./build/bin/integration state_stages --datadir=/data/erigon --unwind=1000 --syncmode=snap, but still stuck at block 14825996. logs bellow:
> 
> ```
> INFO[05-30|00:28:09.103] [1/16 Headers] Wrote block headers       number=14825996 blk/second=0.000 alloc=5.1Gb sys=9.6Gb
> INFO[05-30|00:28:09.103] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=11 respMin=14869555 respMax=14869555
> INFO[05-30|00:28:29.103] [1/16 Headers] Wrote block headers       number=14825996 blk/second=0.000 alloc=5.2Gb sys=9.6Gb
> INFO[05-30|00:28:29.103] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=8 respMin=14869556 respMax=14869556
> INFO[05-30|00:28:37.175] [p2p] GoodPeers                          eth66=33
> INFO[05-30|00:28:49.103] [1/16 Headers] Wrote block headers       number=14825996 blk/second=0.000 alloc=5.3Gb sys=9.6Gb
> INFO[05-30|00:28:49.103] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=12 respMin=14869557 respMax=14869557
> INFO[05-30|00:29:09.103] [1/16 Headers] Wrote block headers       number=14825996 blk/second=0.000 alloc=5.5Gb sys=9.6Gb
> INFO[05-30|00:29:09.103] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=6 respMin=14869558 respMax=14869558
> ```

and alse I noticed exists the error logs : 
```
Handling incoming message                stream=RecvMessage err="decode BlockBodiesPacket66: rlp: input list has too many elements for eth.BlockRawBodiesPacket66"
```

**Comment by changwilling** [comment]
> > > what if `./build/bin/integration state_stages --datadir=/data/erigon --unwind=1000 --syncmode=snap` ?
> > 
> > 
> > The command worked,and no errors happens when i run ./build/bin/integration state_stages --datadir=/data/erigon --unwind=1000 --syncmode=snap, but still stuck at block 14825996. logs bellow:
> > ```
> > INFO[05-30|00:28:09.103] [1/16 Headers] Wrote block headers       number=14825996 blk/second=0.000 alloc=5.1Gb sys=9.6Gb
> > INFO[05-30|00:28:09.103] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=11 respMin=14869555 respMax=14869555
> > INFO[05-30|00:28:29.103] [1/16 Headers] Wrote block headers       number=14825996 blk/second=0.000 alloc=5.2Gb sys=9.6Gb
> > INFO[05-30|00:28:29.103] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=8 respMin=14869556 respMax=14869556
> > INFO[05-30|00:28:37.175] [p2p] GoodPeers                          eth66=33
> > INFO[05-30|00:28:49.103] [1/16 Headers] Wrote block headers       number=14825996 blk/second=0.000 alloc=5.3Gb sys=9.6Gb
> > INFO[05-30|00:28:49.103] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=12 respMin=14869557 respMax=14869557
> > INFO[05-30|00:29:09.103] [1/16 Headers] Wrote block headers       number=14825996 blk/second=0.000 alloc=5.5Gb sys=9.6Gb
> > INFO[05-30|00:29:09.103] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=6 respMin=14869558 respMax=14869558
> > ```
> 
> and alse I noticed exists the error logs :
> 
> ```
> Handling incoming message                stream=RecvMessage err="decode BlockBodiesPacket66: rlp: input list has too many elements for eth.BlockRawBodiesPacket66"
> ```

finally the error is not matter. The erigon works normally.Thanks for your reply.
