### ISSUE TITLE
Goerli: snapshot.store() segfault

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#4298]
```
INFO[05-29|14:55:27.219] [1/5 MiningCreateBlock] Start mine       block=1 baseFee=875000000 gasLimit=11511229
unexpected fault address 0x1b79a30
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1b79a30 pc=0x43b1a3]

goroutine 60 [running, locked to thread]:
runtime.throw({0x11a1734?, 0x0?})
        runtime/panic.go:992 +0x71 fp=0xc00071b580 sp=0xc00071b550 pc=0x461bd1
runtime.sigpanic()
        runtime/signal_unix.go:825 +0x305 fp=0xc00071b5d0 sp=0xc00071b580 pc=0x477f85
runtime.mapiterinit(0x400?, 0x112d160?, 0xc00017eeb0?)
        runtime/map.go:821 +0x23 fp=0xc00071b5f0 sp=0xc00071b5d0 pc=0x43b1a3
reflect.mapiterinit(0x0?, 0xc0000ddc00?, 0xc0000ddc00?)
        runtime/map.go:1373 +0x19 fp=0xc00071b618 sp=0xc00071b5f0 pc=0x48e619
[github.com/goccy/go-json/internal/encoder/vm.Run(0xc000014d00](http://github.com/goccy/go-json/internal/encoder/vm.Run(0xc000014d00), {0xc0000ddc00?, 0x0?, 0x400?}, 0xc00062c880?)
        [github.com/goccy/go-json@v0.7.4/internal/encoder/vm/vm.go:410](http://github.com/goccy/go-json@v0.7.4/internal/encoder/vm/vm.go:410) +0x1fb7 fp=0xc00071ea78 sp=0xc00071b618 pc=0xc72af7
[github.com/goccy/go-json.encodeRunCode(0x110f420](http://github.com/goccy/go-json.encodeRunCode(0x110f420)?, {0xc0000ddc00?, 0x2659688?, 0xc00062c7c0?}, 0xc0005b4c00?)
        [github.com/goccy/go-json@v0.7.4/encode.go:307](http://github.com/goccy/go-json@v0.7.4/encode.go:307) +0x68 fp=0xc00071eab0 sp=0xc00071ea78 pc=0xca1ae8
[github.com/goccy/go-json.encode(0xc000014d00](http://github.com/goccy/go-json.encode(0xc000014d00), {0x110f420, 0xc00017eea0})
        [github.com/goccy/go-json@v0.7.4/encode.go:232](http://github.com/goccy/go-json@v0.7.4/encode.go:232) +0x21c fp=0xc00071eb30 sp=0xc00071eab0 pc=0xca19dc
[github.com/goccy/go-json.marshal({0x110f420](http://github.com/goccy/go-json.marshal(%7B0x110f420), 0xc00017eea0}, {0x0, 0x0, 0xf8007ff46a727108?})
        [github.com/goccy/go-json@v0.7.4/encode.go:147](http://github.com/goccy/go-json@v0.7.4/encode.go:147) +0xba fp=0xc00071eb90 sp=0xc00071eb30 pc=0xca169a
[github.com/goccy/go-json.MarshalWithOption(..](http://github.com/goccy/go-json.MarshalWithOption(..).)
        [github.com/goccy/go-json@v0.7.4/json.go:186](http://github.com/goccy/go-json@v0.7.4/json.go:186)
[github.com/goccy/go-json.Marshal({0x110f420](http://github.com/goccy/go-json.Marshal(%7B0x110f420)?, 0xc00017eea0?})
        [github.com/goccy/go-json@v0.7.4/json.go:171](http://github.com/goccy/go-json@v0.7.4/json.go:171) +0x2a fp=0xc00071ebc8 sp=0xc00071eb90 pc=0xca1b6a
[github.com/ledgerwatch/erigon/consensus/clique.(*Snapshot).store(0xc00017eea0](http://github.com/ledgerwatch/erigon/consensus/clique.(*Snapshot).store(0xc00017eea0), {0x1cc68b8, 0xc0001a4f80})
        [github.com/ledgerwatch/erigon/consensus/clique/snapshot.go:142](http://github.com/ledgerwatch/erigon/consensus/clique/snapshot.go:142) +0x39 fp=0xc00071ec18 sp=0xc00071ebc8 pc=0xd420d9
[github.com/ledgerwatch/erigon/consensus/clique.(*Clique).Snapshot(0xc00020e240](http://github.com/ledgerwatch/erigon/consensus/clique.(*Clique).Snapshot(0xc00020e240), {0x1cc6648, 0xc0005180f0}, 0x25d32c0?, {0x50, 0x47, 0x42, 0x2d, 0xb8, 0x6d, ...}, ...)
        [github.com/ledgerwatch/erigon/consensus/clique/verifier.go:190](http://github.com/ledgerwatch/erigon/consensus/clique/verifier.go:190) +0xb12 fp=0xc00071eeb8 sp=0xc00071ec18 pc=0xd45892
[github.com/ledgerwatch/erigon/consensus/clique.(*Clique).Prepare(0xc00020e240](http://github.com/ledgerwatch/erigon/consensus/clique.(*Clique).Prepare(0xc00020e240), {0x1cc6648, 0xc0005180f0}, 0xc000202780)
        [github.com/ledgerwatch/erigon/consensus/clique/clique.go:308](http://github.com/ledgerwatch/erigon/consensus/clique/clique.go:308) +0xda fp=0xc00071f0b8 sp=0xc00071eeb8 pc=0xd3ea7a
[github.com/ledgerwatch/erigon/eth/stagedsync.SpawnMiningCreateBlockStage(_](http://github.com/ledgerwatch/erigon/eth/stagedsync.SpawnMiningCreateBlockStage(_), {_, _}, {{0x1cc68b8, 0xc0001a4c00}, {0x2388428, 0xc00028f500, 0xc00028f560, 0xc000364150}, {{0x0, ...}, ...}, ...}, ...)
        [github.com/ledgerwatch/erigon/eth/stagedsync/stage_mining_create_block.go:237](http://github.com/ledgerwatch/erigon/eth/stagedsync/stage_mining_create_block.go:237) +0x1342 fp=0xc00071fbb0 sp=0xc00071f0b8 pc=0xe41582
[github.com/ledgerwatch/erigon/eth/stagedsync.MiningStages.func1(0x10](http://github.com/ledgerwatch/erigon/eth/stagedsync.MiningStages.func1(0x10)?, 0x6d?, 0x11ae426?, {0x11?, 0x1cc9b78?}, {0x1ccd188, 0xc0002904b0})
        [github.com/ledgerwatch/erigon/eth/stagedsync/stagebuilder.go:37](http://github.com/ledgerwatch/erigon/eth/stagedsync/stagebuilder.go:37) +0xb3 fp=0xc00071fd38 sp=0xc00071fbb0 pc=0xe53193
[github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc0000d6d10](http://github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc0000d6d10), 0xc00010eeb0, {0x0?, 0x0}, {0x1ccd188?, 0xc0002904b0}, 0x0?, 0x0?)
        [github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:316](http://github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:316) +0x14c fp=0xc00071fe38 sp=0xc00071fd38 pc=0xe5582c
[github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc0000d6d10](http://github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc0000d6d10), {0x0, 0x0}, {0x1ccd188, 0xc0002904b0}, 0x0?)
        [github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:233](http://github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:233) +0x2a5 fp=0xc00071fee8 sp=0xc00071fe38 pc=0xe54ae5
[github.com/ledgerwatch/erigon/turbo/stages.MiningStep({0x1cc46a0](http://github.com/ledgerwatch/erigon/turbo/stages.MiningStep(%7B0x1cc46a0)?, 0xc000036098?}, {0x1cc68b8?, 0xc0001a4c00?}, 0x0?)
        [github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:209](http://github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:209) +0x10c fp=0xc00071ff90 sp=0xc00071fee8 pc=0xe5f76c
[github.com/ledgerwatch/erigon/eth.(*Ethereum).StartMining.func3.1()](http://github.com/ledgerwatch/erigon/eth.(*Ethereum).StartMining.func3.1())
        [github.com/ledgerwatch/erigon/eth/backend.go:640](http://github.com/ledgerwatch/erigon/eth/backend.go:640) +0x36 fp=0xc00071ffe0 sp=0xc00071ff90 pc=0xe66656
runtime.goexit()
        runtime/asm_amd64.s:1571 +0x1 fp=0xc00071ffe8 sp=0xc00071ffe0 pc=0x494e41
created by [github.com/ledgerwatch/erigon/eth.(*Ethereum).StartMining.func3](http://github.com/ledgerwatch/erigon/eth.(*Ethereum).StartMining.func3)
        [github.com/ledgerwatch/erigon/eth/backend.go:640](http://github.com/ledgerwatch/erigon/eth/backend.go:640) +0x3d8
```

**Comment by drunkirishcoder** [comment]
any idea what's causing this? I am running into this problem as well.

```
+ exec erigon '--datadir=/var/lib/erigon' '--private.api.addr=127.0.0.1:9090' --metrics --metrics.expensive '--metrics.addr=0.0.0.0' '--metrics.port=6060' '--chain=rinkeby' '--txpool.globalslots=1' '--txpool.globalqueue=1' '--txpool.lifetime=1s'
[INFO] [06-02|13:32:46.085] Starting metrics server                  addr=http://0.0.0.0:6060/debug/metrics/prometheus
[INFO] [06-02|13:32:46.085] Build info                               git_branch=HEAD git_tag=v2022.05.09 git_commit=d139c750cba2d9ce03e4677d6700b21246c6813f
[INFO] [06-02|13:32:46.085] Starting Erigon on Rinkeby testnet...
[INFO] [06-02|13:32:46.086] Maximum peer count                       ETH=100 total=100
[INFO] [06-02|13:32:46.086] Set global gas cap                       cap=50000000
[INFO] [06-02|13:32:46.087] Opening Database                         label=chaindata path=/var/lib/erigon/chaindata
mdbx_ipclock_failed:30668 wlock owner died, recovering
[INFO] [06-02|13:32:46.088] Initialised chain configuration          config="{ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: true EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1035301 Constantinople: 3660663 Petersburg: 4321234 Istanbul: 5435345, Muir Glacier: <nil>, Berlin: 8290928, London: 8897988, Arrow Glacier: <nil>, Engine: clique}"
[INFO] [06-02|13:32:46.096] Initialising Ethereum protocol           network=4
[INFO] [06-02|13:32:46.096] Effective                                prune="--prune="
[WARN] [06-02|13:32:46.548] Preverified hashes not found for         chain=rinkeby
[INFO] [06-02|13:32:46.558] Starting private RPC server              on=127.0.0.1:9090
[INFO] [06-02|13:32:46.558] new subscription to logs established
[INFO] [06-02|13:32:46.558] [1/16 Headers] Waiting for headers...    from=10335204
[INFO] [06-02|13:32:46.575] Started P2P networking                   version=66 self=enode://d39bbb7e923d58254ffeecef94718183dfe334fedfa071bbaaed3f5842c525eaea32b18272c40175192b48743387e915d32a2f61512ab1483d30edfd32f427bf@127.0.0.1:30303 name=erigon/v2022.04.2-beta-d139c750/linux-amd64/go1.18.2
[INFO] [06-02|13:32:47.402] new subscription to newHeaders established
[INFO] [06-02|13:32:49.359] New txs subscriber joined
unexpected fault address 0x1bca540
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1bca540 pc=0x439983]

goroutine 59 [running, locked to thread]:
runtime.throw({0x11af2f4?, 0x325e00400424000?})
	runtime/panic.go:992 +0x71 fp=0xc00bd6b598 sp=0xc00bd6b568 pc=0x4603b1
runtime.sigpanic()
	runtime/signal_unix.go:825 +0x305 fp=0xc00bd6b5e8 sp=0xc00bd6b598 pc=0x476765
runtime.mapiterinit(0x400?, 0x113a8a0?, 0xc00bd0cb50?)
	runtime/map.go:821 +0x23 fp=0xc00bd6b608 sp=0xc00bd6b5e8 pc=0x439983
reflect.mapiterinit(0x0?, 0xc00bd54000?, 0xc00bd54000?)
	runtime/map.go:1373 +0x19 fp=0xc00bd6b630 sp=0xc00bd6b608 pc=0x48ce59
github.com/goccy/go-json/internal/encoder/vm.Run(0xc00bd26270, {0xc00bd54000?, 0x0?, 0x400?}, 0xc009114900?)
	github.com/goccy/go-json@v0.7.4/internal/encoder/vm/vm.go:410 +0x1fb7 fp=0xc00bd6ea90 sp=0xc00bd6b630 pc=0xc71bf7
github.com/goccy/go-json.encodeRunCode(0x111c6c0?, {0xc00bd54000?, 0x26bcfe8?, 0xc009114840?}, 0xc00bd54400?)
	github.com/goccy/go-json@v0.7.4/encode.go:307 +0x68 fp=0xc00bd6eac8 sp=0xc00bd6ea90 pc=0xca0be8
github.com/goccy/go-json.encode(0xc00bd26270, {0x111c6c0, 0xc00bd0cb40})
	github.com/goccy/go-json@v0.7.4/encode.go:232 +0x21c fp=0xc00bd6eb48 sp=0xc00bd6eac8 pc=0xca0adc
github.com/goccy/go-json.marshal({0x111c6c0, 0xc00bd0cb40}, {0x0, 0x0, 0xc00bd46440?})
	github.com/goccy/go-json@v0.7.4/encode.go:147 +0xba fp=0xc00bd6eba8 sp=0xc00bd6eb48 pc=0xca079a
github.com/goccy/go-json.MarshalWithOption(...)
	github.com/goccy/go-json@v0.7.4/json.go:186
github.com/goccy/go-json.Marshal({0x111c6c0?, 0xc00bd0cb40?})
	github.com/goccy/go-json@v0.7.4/json.go:171 +0x2a fp=0xc00bd6ebe0 sp=0xc00bd6eba8 pc=0xca0c6a
github.com/ledgerwatch/erigon/consensus/clique.(*Snapshot).store(0xc00bd0cb40, {0x1d17e58, 0xc000120980})
	github.com/ledgerwatch/erigon/consensus/clique/snapshot.go:142 +0x39 fp=0xc00bd6ec30 sp=0xc00bd6ebe0 pc=0xd411b9
github.com/ledgerwatch/erigon/consensus/clique.(*Clique).Snapshot(0xc00001aab0, {0x1d17480, 0xc00726e018}, 0x13501f75bc6922be?, {0x61, 0xbf, 0x1a, 0x59, 0xef, 0x3f, ...}, ...)
	github.com/ledgerwatch/erigon/consensus/clique/verifier.go:228 +0x7a8 fp=0xc00bd6eed0 sp=0xc00bd6ec30 pc=0xd44608
github.com/ledgerwatch/erigon/consensus/clique.(*Clique).verifyCascadingFields(0xc00001aab0, {0x1d17480, 0xc00726e018}, 0xc00bbcf900, {0x0?, 0x0, 0x0})
	github.com/ledgerwatch/erigon/consensus/clique/verifier.go:134 +0x469 fp=0xc00bd6f070 sp=0xc00bd6eed0 pc=0xd43ae9
github.com/ledgerwatch/erigon/consensus/clique.(*Clique).verifyHeader(0xc00001aab0, {0x1d17480, 0xc00726e018}, 0xc00bbcf900, {0x0, 0x0, 0x0})
	github.com/ledgerwatch/erigon/consensus/clique/verifier.go:85 +0x459 fp=0xc00bd6f120 sp=0xc00bd6f070 pc=0xd434f9
github.com/ledgerwatch/erigon/consensus/clique.(*Clique).VerifyHeader(0x10559a0?, {0x1d17480?, 0xc00726e018?}, 0x1db689f0e08157c8?, 0x80?)
	github.com/ledgerwatch/erigon/consensus/clique/clique.go:251 +0x2b fp=0xc00bd6f168 sp=0xc00bd6f120 pc=0xd3d24b
github.com/ledgerwatch/erigon/turbo/stages/headerdownload.(*HeaderDownload).InsertHeaders(0xc000228a00, 0xc00bbd4440, {0xc001184e64, 0xc}, 0x0?)
	github.com/ledgerwatch/erigon/turbo/stages/headerdownload/header_algos.go:691 +0x750 fp=0xc00bd6f380 sp=0xc00bd6f168 pc=0xda5c30
github.com/ledgerwatch/erigon/eth/stagedsync.HeadersForward(_, {_, _}, {_, _}, {_, _}, {{0x1d17e58, 0xc000120880}, 0xc000228a00, ...}, ...)
	github.com/ledgerwatch/erigon/eth/stagedsync/stage_headers.go:158 +0xc4a fp=0xc00bd6f890 sp=0xc00bd6f380 pc=0xe2c58a
github.com/ledgerwatch/erigon/eth/stagedsync.DefaultStages.func1(0x10?, 0x58?, 0x11b133e?, {0x1d0d720?, 0xc000155810?}, {0x0?, 0x0?})
	github.com/ledgerwatch/erigon/eth/stagedsync/default_stages.go:38 +0xb5 fp=0xc00bd6f9f8 sp=0xc00bd6f890 pc=0xe15475
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc000155810, 0xc00010eb40, {0x1d17e58?, 0xc000120880}, {0x0?, 0x0}, 0x20?, 0x41?)
	github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:316 +0x150 fp=0xc00bd6fb00 sp=0xc00bd6f9f8 pc=0xe57630
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc000155810, {0x1d17e58, 0xc000120880}, {0x0, 0x0}, 0x0?)
	github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:233 +0x2a5 fp=0xc00bd6fbb0 sp=0xc00bd6fb00 pc=0xe568e5
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x1d15be8?, 0xc00011b280}, {0x1d17e58, 0xc000120880}, 0xc000155810, 0x0, 0xc000018b40, 0x1, 0xc000704e60, 0x0)
	github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:129 +0x432 fp=0xc00bd6fe18 sp=0xc00bd6fbb0 pc=0xe60652
github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x1d15be8, 0xc00011b280}, {0x1d17e58?, 0xc000120880}, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0)
	github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:55 +0x166 fp=0xc00bd6ff80 sp=0xc00bd6fe18 pc=0xe5fdc6
github.com/ledgerwatch/erigon/eth.(*Ethereum).Start.func7()
	github.com/ledgerwatch/erigon/eth/backend.go:717 +0x4e fp=0xc00bd6ffe0 sp=0xc00bd6ff80 pc=0xe6928e
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc00bd6ffe8 sp=0xc00bd6ffe0 pc=0x493681
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
	github.com/ledgerwatch/erigon/eth/backend.go:717 +0x3c5
```

**Comment by AskAlexSharov** [comment]
No, we don’t have ideas about it. Maybe it’s write to journal after closing it, but no evidence.

**Comment by mandrigin** [comment]
@drunkirishcoder please retry on the latest alpha and see if it persists

**Comment by mandrigin** [comment]
I and all my team synced goerli just fine on the latest release w/o this issue. Closing for now, if it repeats on the latest release @drunkirishcoder feel free to reopen/comment.
