### ISSUE TITLE
Need to sanitise p2p request to prevent panic

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon#4363]
#### Backtrace

````
INFO[06-03|18:10:35.805] [6/16 Execution] Executed blocks         number=14677002 blk/s=27.2 tx/s=5515.0 Mgas/s=412.6 gasState=0.82 estimated duration=3h35m29.424s batch=878.8Mb alloc=6.5Gb sys=10.0Gb
INFO[06-03|18:10:55.812] [6/16 Execution] Executed blocks         number=14677552 blk/s=27.5 tx/s=4849.8 Mgas/s=422.6 gasState=0.83 estimated duration=3h35m22.886s batch=896.5Mb alloc=6.4Gb sys=10.0Gb
INFO[06-03|18:11:15.854] [6/16 Execution] Executed blocks         number=14678091 blk/s=26.9 tx/s=5038.8 Mgas/s=417.1 gasState=0.85 estimated duration=3h35m17.317s batch=913.7Mb alloc=6.2Gb sys=10.0Gb
INFO[06-03|18:11:35.844] [6/16 Execution] Executed blocks         number=14678641 blk/s=27.5 tx/s=5015.2 Mgas/s=423.5 gasState=0.86 estimated duration=3h35m10.773s batch=931.8Mb alloc=6.0Gb sys=10.0Gb
INFO[06-03|18:11:55.784] [6/16 Execution] Executed blocks         number=14679174 blk/s=26.7 tx/s=4828.1 Mgas/s=413.0 gasState=0.88 estimated duration=3h35m6.036s batch=949.9Mb alloc=5.8Gb sys=10.0Gb
INFO[06-03|18:12:03.009] [p2p] GoodPeers                          eth66=98
INFO[06-03|18:12:15.806] [6/16 Execution] Executed blocks         number=14679718 blk/s=27.2 tx/s=5225.3 Mgas/s=424.5 gasState=0.89 estimated duration=3h34m59.454s batch=967.9Mb alloc=5.6Gb sys=10.0Gb
INFO[06-03|18:12:35.814] [6/16 Execution] Executed blocks         number=14680258 blk/s=27.0 tx/s=5558.7 Mgas/s=417.0 gasState=0.91 estimated duration=3h34m54.150s batch=985.4Mb alloc=5.6Gb sys=10.0Gb
INFO[06-03|18:12:55.787] [6/16 Execution] Executed blocks         number=14680871 blk/s=30.7 tx/s=5211.0 Mgas/s=472.8 gasState=0.93 estimated duration=3h34m39.989s batch=1002.7Mb alloc=5.7Gb sys=10.0Gb
INFO[06-03|18:13:15.807] [6/16 Execution] Executed blocks         number=14681416 blk/s=27.2 tx/s=4832.3 Mgas/s=419.4 gasState=0.94 estimated duration=3h34m34.458s batch=1020.9Mb alloc=5.5Gb sys=10.0Gb
INFO[06-03|18:13:35.780] [6/16 Execution] Executed blocks         number=14681943 blk/s=26.4 tx/s=4706.8 Mgas/s=406.4 gasState=0.96 estimated duration=3h34m31.062s batch=1.0Gb alloc=5.3Gb sys=10.0Gb
INFO[06-03|18:13:55.845] [6/16 Execution] Executed blocks         number=14682495 blk/s=27.5 tx/s=4693.0 Mgas/s=421.2 gasState=0.97 estimated duration=3h34m25.349s batch=1.0Gb alloc=5.1Gb sys=10.0Gb
INFO[06-03|18:14:03.009] [p2p] GoodPeers                          eth66=96
INFO[06-03|18:14:15.838] [6/16 Execution] Executed blocks         number=14683030 blk/s=26.8 tx/s=5000.6 Mgas/s=417.8 gasState=0.99 estimated duration=3h34m20.238s batch=1.0Gb alloc=4.9Gb sys=10.0Gb
INFO[06-03|18:14:34.143] Committed State                          gas reached=549757599869 gasTarget=549755813888
INFO[06-03|18:14:40.030] Flushed buffer file                      name=/home/mainnet/etl-temp/erigon-sortable-buf-1595170366 alloc=5.9Gb sys=10.0Gb
INFO[06-03|18:14:44.670] Flushed buffer file                      name=/home/mainnet/etl-temp/erigon-sortable-buf-44472864 alloc=6.0Gb sys=10.0Gb
INFO[06-03|18:14:49.279] Flushed buffer file                      name=/home/mainnet/etl-temp/erigon-sortable-buf-4274026040 alloc=6.2Gb sys=10.0Gb
INFO[06-03|18:14:49.602] Flushed buffer file                      name=/home/mainnet/etl-temp/erigon-sortable-buf-2550773389 alloc=6.2Gb sys=10.0Gb
INFO[06-03|18:15:19.602] [] ETL [2/2] Loading                     into=PlainState current key=34f0915a... alloc=6.9Gb sys=10.0Gb
INFO[06-03|18:15:49.603] [] ETL [2/2] Loading                     into=PlainState current key=5d0f4298... alloc=4.1Gb sys=10.0Gb
panic: runtime error: index out of range [0] with length 0

goroutine 4102 [running]:
github.com/ledgerwatch/erigon/core/types.(*Block).SendersToTxs(...)
	github.com/ledgerwatch/erigon/core/types/block.go:1233
github.com/ledgerwatch/erigon/core/rawdb.ReadReceipts({0x1ea60c0?, 0xc0f645b2f0?}, 0xc0adc2bcb0, {0x2b99940?, 0x0, 0x0})
	github.com/ledgerwatch/erigon/core/rawdb/accessors_chain.go:888 +0x4de
github.com/ledgerwatch/erigon/core/rawdb.ReadReceiptsByHash({0x1ea60c0?, 0xc0f645b2f0}, {0x8, 0xe2, 0x5d, 0xcb, 0x58, 0x2, 0x9b, 0xae, ...})
	github.com/ledgerwatch/erigon/core/rawdb/accessors_chain.go:912 +0x166
github.com/ledgerwatch/erigon/eth/protocols/eth.AnswerGetReceiptsQuery({0x1ea60c0?, 0xc0f645b2f0}, {0xc07eb44600?, 0x80, 0xc0c8970fc0?})
	github.com/ledgerwatch/erigon/eth/protocols/eth/handlers.go:180 +0x14f
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).getReceipts66(0xc090e61100, {0x1e9b828, 0xc000a83240}, 0xc170e0ab90, {0x1ea8958, 0xc0001284c8})
	github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:587 +0x21a
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).handleInboundMessage(0x1e904a0?, {0x1e9b828?, 0xc000a83240?}, 0x4688b6?, {0x1ea8958?, 0xc0001284c8?})
	github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:657 +0xb4
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).HandleInboundMessage(0xc095139ee0?, {0x1e9b828, 0xc000a83240}, 0xc170e0ab90, {0x1ea8958?, 0xc0001284c8?})
	github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:622 +0x5d
github.com/ledgerwatch/erigon/cmd/sentry/sentry.pumpStreamLoop[...].func2()
	github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:209 +0xde
created by github.com/ledgerwatch/erigon/cmd/sentry/sentry.pumpStreamLoop[...]
	github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:207 +0x2ce
````

**Comment by AskAlexSharov** [comment]
Fixed in devel. But without sanitizing

**Comment by mandrigin** [comment]
@AskAlexSharov do we still need to sanitize the request?

**Comment by AskAlexSharov** [comment]
let's close it for now
