### ISSUE TITLE
panic: interface is nil, not simplelru.entry

### ISSUE THREAD

**Issue by battlmonstr** [ledgerwatch/erigon#4396]
#### System information

Erigon devel commit

OS & Version: Linux

Commit hash : e13e21228893d5ccda5e24d578ab8618d63ff559

#### Actual behaviour

panic

#### Steps to reproduce the behaviour

The node was running for a several days on mainnet, then crashed. Portion of the log above this doesn't seem related:

```
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:45:51.843547821Z","top seen height":14913295}
{"err":"rlp parse transaction: transaction must be either 1 list or 1 string","lvl":"dbug","msg":"TRANSACTIONS_66","t":"2022-06-06T05:45:52.176437141Z"}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:45:53.562843466Z","top seen height":14913295}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:45:54.645497085Z","top seen height":14913295}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:45:55.718942174Z","top seen height":14913295}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:45:56.791970688Z","top seen height":14913295}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:45:58.309839252Z","top seen height":14913295}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:46:00.266938821Z","top seen height":14913295}
{"alloc":"3.7Gb","blk/second":0,"lvl":"info","msg":"[1/16 Headers] Wrote block headers","number":14894000,"sys":"10.4Gb","t":"2022-06-06T05:46:01.316511832Z"}
{"lvl":"info","msg":"Req/resp stats","req":0,"reqMax":0,"reqMin":0,"resp":49,"respMax":14913295,"respMin":14895536,"skel":16,"skelMax":15190256,"skelMin":14895536,"t":"2022-06-06T05:46:01.316580177Z"}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:46:02.316690936Z","top seen height":14913295}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:46:03.608503111Z","top seen height":14913295}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:46:05.120243196Z","top seen height":14913295}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:46:06.613334117Z","top seen height":14913295}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:46:07.686272304Z","top seen height":14913295}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:46:08.88416941Z","top seen height":14913295}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:46:09.936544237Z","top seen height":14913295}
{"anchors":0,"highestInDb":14894000,"lvl":"dbug","msg":"Request skeleton","t":"2022-06-06T05:46:11.399734627Z","top seen height":14913295}
```

#### Backtrace

```
panic: interface conversion: interface {} is nil, not *simplelru.entry

goroutine 6667 [running]:
github.com/hashicorp/golang-lru/simplelru.(*LRU).removeElement(0x17777a0?, 0xc07ca6f660?)
	github.com/hashicorp/golang-lru@v0.5.5-0.20210104140557-80c98217689d/simplelru/lru.go:172 +0x107
github.com/hashicorp/golang-lru/simplelru.(*LRU).removeOldest(0x1656260?)
	github.com/hashicorp/golang-lru@v0.5.5-0.20210104140557-80c98217689d/simplelru/lru.go:165 +0x34
github.com/hashicorp/golang-lru/simplelru.(*LRU).Add(0xc0a1f36a00, {0x15dd700?, 0xc0f42c81f0}, {0x1627a60?, 0x29d4668})
	github.com/hashicorp/golang-lru@v0.5.5-0.20210104140557-80c98217689d/simplelru/lru.go:67 +0x394
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).discardLocked(0xc09eb5e600, 0xc09c93a1e0, 0xd)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220530021709-f5c973d4c534/txpool/pool.go:1068 +0x15a
github.com/ledgerwatch/erigon-lib/txpool.promote(0xc09eb6e8c0, 0xc09eb6e900, 0xc09eb6e940, 0x15867687d9, 0xc07ca6fbe8)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220530021709-f5c973d4c534/txpool/pool.go:1296 +0x354
github.com/ledgerwatch/erigon-lib/txpool.addTxs(0xe343b0, {0x1e98340, 0xc077c331d0}, 0x218038?, {{0xc0911d6298, 0x1, 0x1}, {0xc040229c98, 0x14, 0x18}, ...}, ...)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220530021709-f5c973d4c534/txpool/pool.go:928 +0x787
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).processRemoteTxs(0xc09eb5e600, {0x1ea1208, 0xc0004ea9c0?})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220530021709-f5c973d4c534/txpool/pool.go:510 +0x48d
github.com/ledgerwatch/erigon-lib/txpool.MainLoop({0x1ea1208?, 0xc0004ea9c0}, {0x1ea5440, 0xc09c8bd2c0}, {0x2b61e40?, 0xc09dee5fa0?}, 0xc09eb5e600, 0xc09eb4daa0, 0xc09eb6e980, 0xc09eb76a68, ...)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220530021709-f5c973d4c534/txpool/pool.go:1334 +0x54e
created by github.com/ledgerwatch/erigon/eth.New
	github.com/ledgerwatch/erigon/eth/backend.go:461 +0x3031
```

**Comment by JekaMas** [comment]
It might worth it to use the same package with generics and forget about golang interfaces - https://github.com/hashicorp/golang-lru/pull/101
