### ISSUE TITLE
Panic: send on closed channel

### ISSUE THREAD

**Issue by alexlee85** [ledgerwatch/erigon#4458]
#### System information

Erigon version: 
```
2022.99.99-dev-ff5cbcb7
git_branch=devel
```

OS & Version: 
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

Commit hash :  `ff5cbcb75dd9156e0917406fdf2fb126de629583`

#### Expected behaviour
do not panic

#### Actual behaviour
panic: send on closed channel

#### Backtrace

````
INFO[06-15|04:49:00.088] [p2p] GoodPeers                          eth66=12
INFO[06-15|04:49:18.511] [4/16 Bodies] Wrote block bodies         block_num=18569136 delivery/sec=1.7MB wasted/sec=0B alloc=3.4GB sys=6.5GB
INFO[06-15|04:49:38.511] [4/16 Bodies] Wrote block bodies         block_num=18569292 delivery/sec=1.2MB wasted/sec=0B alloc=3.5GB sys=6.5GB
INFO[06-15|04:49:58.511] [4/16 Bodies] Wrote block bodies         block_num=18569292 delivery/sec=1.8MB wasted/sec=0B alloc=3.8GB sys=6.5GB
INFO[06-15|04:50:18.511] [4/16 Bodies] Wrote block bodies         block_num=18569292 delivery/sec=778.2KB wasted/sec=0B alloc=3.9GB sys=6.5GB
panic: send on closed channel

goroutine 525703 [running]:
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*PeerInfo).Async(0xc07765a240, 0xc0e4184b90)
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_grpc_server.go:147 +0x12f
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*GrpcServer).writePeer(0xc00123c480, {0x18d6547, 0xf}, 0xc07765a240, 0x3, {0xc079fdf050, 0x2f, 0x2f}, 0x0)
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_grpc_server.go:609 +0x112
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*GrpcServer).SendMessageById(0xc00123c480, {0xc0959acd40?, 0x30?}, 0xc17d437df0)
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_grpc_server.go:733 +0x25d
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*GrpcServer).startSync(0xc00123c480, {0x1ef6688, 0xc000110e80}, {0x1e, 0x64, 0x34, 0x33, 0x7f, 0xbb, 0xd, ...}, ...)
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_grpc_server.go:640 +0x24b
github.com/ledgerwatch/erigon/cmd/sentry/sentry.NewGrpcServer.func1.1({0x1e, 0x64, 0x34, 0x33, 0x7f, 0xbb, 0xd, 0xb0, 0x50, 0x34, ...})
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_grpc_server.go:511 +0x196
github.com/ledgerwatch/erigon/cmd/sentry/sentry.handShake.func2()
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_grpc_server.go:241 +0x8f
created by github.com/ledgerwatch/erigon/cmd/sentry/sentry.handShake
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_grpc_server.go:237 +0x34a

````

**Comment by nand2** [comment]
Same on
`git_branch=heads/v2022.06.03 git_tag=v2022.06.03-dirty git_commit=2a570ad599014c3bc522287967c778792a4eb4f4`
Twice so far in 1 hour.

**Comment by alexlee85** [comment]
seems this commit [#4467](https://github.com/ledgerwatch/erigon/pull/4467) already fixed this problem
