### ISSUE TITLE
panic: slice bounds out of range

### ISSUE THREAD

**Issue by du5** [ledgerwatch/erigon#4553]
Erigon version: `./erigon --version` git_tag: v2022.06.06 git_commit: 7724089985bf9cb8bb7d1bde92892256a6af859f

can not reproduce bug,

command:
```
erigon --chain=bsc --prune=hrtc --prune.h.older=5000 --prune.r.older=5000 --prune.t.older=5000 --prune.c.older=5000 --datadir=erigon --db.pagesize=16k
```

logs:
```
INFO[06-28|00:05:20.935] RPC Daemon notified of new headers       from=19057612 to=19058636 header sending=756.31µs log sending=230ns
INFO[06-28|00:05:20.938] [1/16 Headers] Waiting for headers...    from=19058636
INFO[06-28|00:05:20.952] [1/16 Headers] Processed                 highest inserted=19058705 age=2s
INFO[06-28|00:05:20.977] [4/16 Bodies] Processing bodies...       from=19058636 to=19058705
INFO[06-28|00:05:21.037] [4/16 Bodies] Processed                  highest=19058705
INFO[06-28|00:05:21.037] [5/16 Senders] Started                   from=19058636 to=19058705
INFO[06-28|00:05:21.111] [6/16 Execution] Blocks execution        from=19058636 to=19058705
INFO[06-28|00:05:28.351] [6/16 Execution] Completed on            block=19058705
INFO[06-28|00:05:28.351] [8/16 HashState] Promoting plain state   from=19058636 to=19058705
INFO[06-28|00:05:28.351] [8/16 HashState] Incremental promotion started from=19058636 to=19058705 codes=true csbucket=AccountChangeSet
INFO[06-28|00:05:28.707] [8/16 HashState] Incremental promotion started from=19058636 to=19058705 codes=false csbucket=AccountChangeSet
INFO[06-28|00:05:28.974] [snapshots] Dumping txs                  block num=18707481 alloc=3.3GB sys=9.2GB
INFO[06-28|00:05:28.975] [8/16 HashState] Incremental promotion started from=19058636 to=19058705 codes=false csbucket=StorageChangeSet
INFO[06-28|00:05:30.394] [9/16 IntermediateHashes] Generating intermediate hashes from=19058636 to=19058705
INFO[06-28|00:05:35.516] Timings (slower than 50ms)               Bodies=60ms Senders=73ms Execution=7.24s HashState=2.042s IntermediateHashes=2.991s CallTraces=229ms AccountHistoryIndex=141ms StorageHistoryIndex=468ms LogIndex=189ms TxLookup=115ms Prune TxLookup=95ms Prune LogIndex=52ms Prune StorageHistoryIndex=81ms Prune CallTraces=51ms Prune Senders=657ms
INFO[06-28|00:05:35.516] Tables                                   PlainState=162.1GB AccountChangeSet=131.8MB StorageChangeSet=284.1MB BlockTransaction=61.4GB TransactionLog=496.5MB FreeList=14.2MB ReclaimableSpace=56.6GB
INFO[06-28|00:05:38.796] Commit cycle                             in=3.280474723s
INFO[06-28|00:05:38.798] RPC Daemon notified of new headers       from=19058636 to=19058705 header sending=57.73µs log sending=250ns
INFO[06-28|00:05:38.799] [1/16 Headers] Waiting for headers...    from=19058705
INFO[06-28|00:05:38.800] [1/16 Headers] Processed                 highest inserted=19058711 age=2s
INFO[06-28|00:05:39.345] [6/16 Execution] Completed on            block=19058711
panic: runtime error: slice bounds out of range [648:610]

goroutine 5884 [running]:
github.com/ledgerwatch/erigon-lib/compress.(*Getter).Next(0xc185065738, {0xc0c3142900, 0x0, 0x80})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220620073929-46bebb3317d9/compress/decompress.go:411 +0x4ad
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockReaderWithSnapshots).headerFromSnapshotByHash(0x16?, {0x50, 0x41, 0xac, 0xc3, 0xb5, 0xde, 0xa0, 0x5f, 0x94, ...}, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_reader.go:517 +0x26c
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockReaderWithSnapshots).HeaderByHash.func1({0xc0b3be6800, 0xc0c3142900?, 0x0?})
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_reader.go:273 +0xa7
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*headerSegments).View(0x5fa0deb5c3ac4150?, 0x8fd103c71fa58394?)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:184 +0xa3
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockReaderWithSnapshots).HeaderByHash(0xc0006868f8, {0x300000002?, 0x0?}, {0x7f99b45142c8?, 0xc100bfe6f0?}, {0x50, 0x41, 0xac, 0xc3, 0xb5, ...})
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_reader.go:267 +0x14e
github.com/ledgerwatch/erigon/eth/protocols/eth.AnswerGetBlockHeadersQuery({0x1f21880?, 0xc100bfe6f0}, 0xc0b5eee200, {0x7f99b441e878, 0xc0006868f8})
        github.com/ledgerwatch/erigon/eth/protocols/eth/handlers.go:54 +0x21b
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).getBlockHeaders66.func1({0x1f21880?, 0xc100bfe6f0?})
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:519 +0x4a
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).View(0xc0d9dbe840?, {0x1f167a8?, 0xc000770300?}, 0xc0eff154a0)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220620073929-46bebb3317d9/kv/mdbx/kv_mdbx.go:643 +0xbe
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).getBlockHeaders66(0xc091dee400, {0x1f167a8, 0xc000770300}, 0xc182064690, {0x1f23bf8, 0xc0007322d0})
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:518 +0x1dd
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).handleInboundMessage(0xc125e0d638?, {0x1f167a8?, 0xc000770300?}, 0x45cb96?, {0x1f23bf8?, 0xc0007322d0?})
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:663 +0x86
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).HandleInboundMessage(0x0?, {0x1f167a8, 0xc000770300}, 0xc182064690, {0x1f23bf8?, 0xc0007322d0?})
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:634 +0x5d
github.com/ledgerwatch/erigon/cmd/sentry/sentry.pumpStreamLoop[...].func2()
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:210 +0xde
created by github.com/ledgerwatch/erigon/cmd/sentry/sentry.pumpStreamLoop[...]
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:208 +0x2ce
```

**Comment by AskAlexSharov** [comment]
Handled crash by: https://github.com/ledgerwatch/erigon/pull/4557
