### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by du5** [ledgerwatch/erigon#4619]
version info `git_branch=HEAD git_tag=v2022.07.01 git_commit=0977639431fe520fc77399d03cdeba36526d2d52`

flags ` --prune= --prune.h.older=5000 --prune.r.older=5000 --prune.t.older=5000 --prune.c.older=5000 --chain=bsc --db.pagesize=16k `
```bash
INFO[07-03|17:35:57.338] Commit cycle                             in=4.84372221s
INFO[07-03|17:35:57.340] RPC Daemon notified of new headers       from=19229693 to=19230190 header sending=256.965µs log sending=170ns
INFO[07-03|17:35:57.341] [1/16 Headers] Waiting for headers...    from=19230190
INFO[07-03|17:35:57.349] [1/16 Headers] Processed                 highest inserted=19230264 age=19m12s
INFO[07-03|17:35:57.377] [4/16 Bodies] Processing bodies...       from=19230190 to=19230264
INFO[07-03|17:36:15.674] [snapshots] Dumping txs                  block num=18797137 alloc=4.3GB sys=10.4GB
INFO[07-03|17:36:17.377] [4/16 Bodies] Wrote block bodies         block_num=19230190 delivery/sec=0B wasted/sec=0B alloc=4.4GB sys=10.4GB
INFO[07-03|17:36:27.500] [4/16 Bodies] Processed                  highest=19230264
INFO[07-03|17:36:27.500] [5/16 Senders] Started                   from=19230190 to=19230264
INFO[07-03|17:36:27.545] [6/16 Execution] Blocks execution        from=19230190 to=19230264
INFO[07-03|17:36:35.609] [6/16 Execution] Completed on            block=19230264
INFO[07-03|17:36:35.609] [8/16 HashState] Promoting plain state   from=19230190 to=19230264
INFO[07-03|17:36:35.609] [8/16 HashState] Incremental promotion started from=19230190 to=19230264 codes=true csbucket=AccountChangeSet
INFO[07-03|17:36:35.950] [snapshots] Dumping txs                  block num=18798551 alloc=5.8GB sys=10.4GB
INFO[07-03|17:36:35.989] [8/16 HashState] Incremental promotion started from=19230190 to=19230264 codes=false csbucket=AccountChangeSet
INFO[07-03|17:36:37.162] [8/16 HashState] Incremental promotion started from=19230190 to=19230264 codes=false csbucket=StorageChangeSet
INFO[07-03|17:36:40.652] [9/16 IntermediateHashes] Generating intermediate hashes from=19230190 to=19230264
INFO[07-03|17:36:49.417] Timings (slower than 50ms)               Bodies=30.123s Execution=8.063s HashState=5.043s IntermediateHashes=5.528s CallTraces=275ms AccountHistoryIndex=110ms StorageHistoryIndex=1.692s LogIndex=131ms TxLookup=67ms Prune TxLookup=122ms Prune LogIndex=209ms Prune StorageHistoryIndex=170ms Prune AccountHistoryIndex=77ms Prune CallTraces=274ms Prune Execution=53ms
INFO[07-03|17:36:49.417] Tables                                   PlainState=163.3GB AccountChangeSet=90.0MB StorageChangeSet=231.1MB BlockTransaction=27.6GB TransactionLog=393.6MB FreeList=19.5MB ReclaimableSpace=78.0GB
INFO[07-03|17:36:52.907] Commit cycle                             in=3.489859841s
INFO[07-03|17:36:52.908] RPC Daemon notified of new headers       from=19230190 to=19230264 header sending=40.296µs log sending=171ns
INFO[07-03|17:36:52.908] [1/16 Headers] Waiting for headers...    from=19230264
INFO[07-03|17:36:52.947] [1/16 Headers] Processed                 highest inserted=19230666 age=1s
INFO[07-03|17:36:53.070] [4/16 Bodies] Processing bodies...       from=19230264 to=19230666
panic: runtime error: slice bounds out of range [:-1]

goroutine 4482 [running]:
github.com/ledgerwatch/erigon-lib/compress.(*Getter).Next(0xc06b125738, {0xc0bc32c380, 0x0, 0x80})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220620073929-46bebb3317d9/compress/decompress.go:406 +0x4b5
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockReaderWithSnapshots).headerFromSnapshotByHash(0x16?, {0x48, 0x4, 0xe3, 0x19, 0xec, 0xa1, 0xea, 0x16, 0x11, ...}, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_reader.go:517 +0x26c
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockReaderWithSnapshots).HeaderByHash.func1({0xc05643e200, 0xc0bc32c380?, 0x0?})
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_reader.go:273 +0xa7
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*headerSegments).View(0x16eaa1ec19e30448?, 0x443c447ebf00ae11?)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:184 +0xa3
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockReaderWithSnapshots).HeaderByHash(0xc0001a7200, {0x300000002?, 0x0?}, {0x7fd07c07f2e0?, 0xc15f8c5da0?}, {0x48, 0x4, 0xe3, 0x19, 0xec, ...})
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_reader.go:267 +0x14e
github.com/ledgerwatch/erigon/eth/protocols/eth.AnswerGetBlockHeadersQuery({0x1f2c860?, 0xc15f8c5da0}, 0xc076742180, {0x744365c61bb8, 0xc0001a7200})
        github.com/ledgerwatch/erigon/eth/protocols/eth/handlers.go:54 +0x21b
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).getBlockHeaders66.func1({0x1f2c860?, 0xc15f8c5da0?})
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:519 +0x4a
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).View(0xc078fb10b0?, {0x1f21788?, 0xc001290340?}, 0xc13b39c2a0)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220620073929-46bebb3317d9/kv/mdbx/kv_mdbx.go:643 +0xbe
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).getBlockHeaders66(0xc061020800, {0x1f21788, 0xc001290340}, 0xc09d05f1d0, {0x1f2ebd8, 0xc00051a2e8})
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:518 +0x1dd
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).handleInboundMessage(0x0?, {0x1f21788?, 0xc001290340?}, 0x0?, {0x1f2ebd8?, 0xc00051a2e8?})
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:663 +0x86
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).HandleInboundMessage(0x7778565d10a1?, {0x1f21788, 0xc001290340}, 0xc09d05f1d0, {0x1f2ebd8?, 0xc00051a2e8?})
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:634 +0x5d
github.com/ledgerwatch/erigon/cmd/sentry/sentry.pumpStreamLoop[...].func2()
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:210 +0xde
created by github.com/ledgerwatch/erigon/cmd/sentry/sentry.pumpStreamLoop[...]
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:208 +0x2ce
```

**Comment by leonardchinonso** [comment]
@du5 can you try running `downloader verify_hashes`? Your snapshots files might be corrupted.

**Comment by AskAlexSharov** [comment]
@du5 no, he mean `downloader torrent_hashes --verify`

**Comment by leonardchinonso** [comment]
@du5 sorry for the confusion, I meant `downloader torrent_hashes --verify`. You can pass the directory of the torrent files with the 'datadir' option (`downloader torrent_hashes --verify --datadir=<data_dir>`) so it verifies them if you have `.torrent` files.
