### ISSUE TITLE
MDBX_PAGE_FULL when syncing Polygon mainnet

### ISSUE THREAD

**Issue by dafky2000** [ledgerwatch/erigon#4716]
#### System information

Erigon version: 2022.06.6-alpha-77240899

OS & Version: Linux

Commit hash : 7724089985bf9cb8bb7d1bde92892256a6af859f

#### Expected behaviour
Move to the next  sync stage (14)

#### Actual behaviour
Restarts current stage 13 (LogIndex 1/2) after failing LogIndex 2/2

#### Steps to reproduce the behaviour
./erigon --chain=bor-mainnet --bor.heimdall=https://heimdall.api.matic.network --db.pagesize 64kb --snapshots=true --datadir=/home/erigon/.local/share/erigon/ --ethash.dagdir=/home/erigon/.local/share/ethash/ --metrics --port="31303" --pprof.addr="0.0.0.0" --pprof.port="6060" --private.api.addr="0.0.0.0:9090" --http.addr=0.0.0.0 --http.port=8547 --http.api=eth,debug,net,web3,trace --trace.maxtraces=10000

#### Backtrace

The data directory is currently 3174165492 bytes

````
[INFO] [07-14|04:49:38.412] [13/16 LogIndex] etl: temp files removed total size=1.2GB                      
[EROR] [07-14|04:49:41.258] Staged Sync                              err="[13/16 LogIndex] 13/16 LogIndex: put: k=311434160d7537be358930def317afb606c0d737017f9bcb, table: LogAddressIndex, err: mdbx_cursor_put: MDBX_PAGE_FULL: Internal erro
r - Page has no more space"                                                                                            
[INFO] [07-14|04:50:05.911] [p2p] GoodPeers                          eth66=100                             
[INFO] [07-14|04:50:12.294] [13/16 LogIndex] Progress                number=7619791 alloc=4.3GB sys=12.0GB 
[INFO] [07-14|04:50:42.167] [13/16 LogIndex] Progress                number=8332057 alloc=5.2GB sys=12.0GB
````

**Comment by AskAlexSharov** [comment]
Your db size now?

**Comment by dafky2000** [comment]
It was about 3.1 TB yesterday, right now in the process it is 2.6TB (at block 28970000 of LogIndex 1/2).

I got this error during my first sync attempt but thought I may have omitted `db.pagesize` during initialization. This time around I'm 100% certain it was there from the first run.

**Comment by AskAlexSharov** [comment]
@dafky2000 can you try branch `mdbx_64_page_full`?

**Comment by dafky2000** [comment]
Done, will report back!

**Comment by dafky2000** [comment]
@AskAlexSharov, I've received a different error during the same stage transition. mdbx.dat is 3134732012 kb

```
[INFO] [07-17|16:13:04.605] [13/16 LogIndex] ETL [2/2] Loading       into=LogTopicIndex current key=e6f99566... alloc=6.3GB sys=11.4GB                                                                                                         
[INFO] [07-17|16:13:06.966] [txpool] stat                            block=0 pending=10000 baseFee=0 queued=30000 alloc=5.7GB sys=11.4GB                                                                                                       
[INFO] [07-17|16:13:34.619] [13/16 LogIndex] ETL [2/2] Loading       into=LogTopicIndex current key=f658eab3... alloc=6.2GB sys=11.4GB                                                                                                         
[INFO] [07-17|16:14:00.960] [13/16 LogIndex] etl: temp files removed total size=32.0GB                                                                                                                                                         
[INFO] [07-17|16:14:03.257] Flushed buffer file                      name=/home/erigon/.local/share/erigon/etl-temp/erigon-sortable-buf-3058471017 alloc=4.1GB sys=11.4GB                                                                      
[INFO] [07-17|16:14:07.186] [txpool] stat                            block=0 pending=10000 baseFee=0 queued=30000 alloc=5.3GB sys=11.4GB                                                                                                       
Assertion failed: page_room(mp) >= leaf_size(mc->mc_txn->mt_env, key, data) (mdbx: mdbx_node_add_leaf: 19633)                                                                                                                                  
SIGABRT: abort                                                                                                                                                                                                                                 
PC=0x7f67f773f3f1 m=16 sigcode=18446744073709551610                                                                                                                                                                                            
signal arrived during cgo execution                                                                                                                                                                                                            
                                                                                                                                                                                                                                               
goroutine 3142 [syscall, locked to thread]:                                                                                                                                                                                                    
runtime.cgocall(0x152a560, 0xc03c3cf000)                                                                                                                                                                                                       
        runtime/cgocall.go:157 +0x5c fp=0xc03c3cefd8 sp=0xc03c3cefa0 pc=0x43447c                                                                                                                                                               
github.com/torquem-ch/mdbx-go/mdbx._Cfunc_mdbxgo_cursor_put2(0x7767cb42bc20, 0xc10fe8a1b0, 0x18, 0xc160f11600, 0x790, 0x0)                                                                                                                     
        _cgo_gotypes.go:1030 +0x4c fp=0xc03c3cf000 sp=0xc03c3cefd8 pc=0xa96f2c                                                                                                                                                                 
github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).Put.func1(0xc03c3cf0a8?, {0xc10fe8a1b0, 0x18, 0x0?}, {0xc160f11600, 0x790, 0x448073?}, 0x0)                                                                                                       
        github.com/torquem-ch/mdbx-go@v0.24.3-0.20220614090901-342411560dde/mdbx/cursor.go:238 +0xb3 fp=0xc03c3cf050 sp=0xc03c3cf000 pc=0xa99153                                                                                               
github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).Put(0x27f67cb9f8df8?, {0xc10fe8a1b0?, 0xc03c3cf108?, 0x301287a51?}, {0xc160f11600?, 0x0?, 0x8?}, 0xa80?)                                                                                          
        github.com/torquem-ch/mdbx-go@v0.24.3-0.20220614090901-342411560dde/mdbx/cursor.go:238 +0x91 fp=0xc03c3cf0c0 sp=0xc03c3cf050 pc=0xa98f31                                                                                               
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).put(...)                                                                                                                                                                               
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220714160525-21aa65c1c383/kv/mdbx/kv_mdbx.go:1090                                                                                                                                           
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).Put(0xc1584342a0, {0xc10fe8a1b0?, 0x448073?, 0x6db40e4e1f48?}, {0xc160f11600?, 0xa80?, 0x64?})                                                                                         
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220714160525-21aa65c1c383/kv/mdbx/kv_mdbx.go:1378 +0xa7 fp=0xc03c3cf178 sp=0xc03c3cf0c0 pc=0xaa9bc7                                                                                         
github.com/ledgerwatch/erigon-lib/etl.loadFilesIntoBucket.func1({0xc193532140?, 0x1f4be20?, 0xc1484dddd0?}, {0xc10fe8a1b0, 0x18, 0x18}, {0xc160f11600, 0x790, 0x8d4})                                                                          
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220714160525-21aa65c1c383/etl/collector.go:252 +0xb6c fp=0xc03c3cf3b0 sp=0xc03c3cf178 pc=0xe4e9ec                                                                                           
github.com/ledgerwatch/erigon/eth/stagedsync.promoteLogIndex.func1.1({0xc10fe8a1b0, 0x18, 0x18}, 0xc1aade20a8?)                                                                                                                                
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_log_index.go:211 +0xf8 fp=0xc03c3cf430 sp=0xc03c3cf3b0 pc=0x1231158                                                                                                                 
github.com/ledgerwatch/erigon/ethdb/bitmapdb.WalkChunkWithKeys.func1(0xc1605c0d20?, 0x0)                                                                                                                                                       
        github.com/ledgerwatch/erigon/ethdb/bitmapdb/dbutils.go:75 +0xc3 fp=0xc03c3cf488 sp=0xc03c3cf430 pc=0xe649a3                                                                                                                           
github.com/ledgerwatch/erigon/ethdb/bitmapdb.WalkChunks(0xc1605c0d20, 0x0?, 0xc03c3cf500)                                                                                                                                                      
        github.com/ledgerwatch/erigon/ethdb/bitmapdb/dbutils.go:59 +0x99 fp=0xc03c3cf4e8 sp=0xc03c3cf488 pc=0xe64719                                                                                                                           
github.com/ledgerwatch/erigon/ethdb/bitmapdb.WalkChunkWithKeys({0xc1aade20a8?, 0xc03c3cf5e8?, 0xb8ec?}, 0x293f0?, 0xc03c3cf5c8?, 0xc0c2171140?)                                                                                                
        github.com/ledgerwatch/erigon/ethdb/bitmapdb/dbutils.go:67 +0x5b fp=0xc03c3cf538 sp=0xc03c3cf4e8 pc=0xe6487b                                                                                                                           
github.com/ledgerwatch/erigon/eth/stagedsync.promoteLogIndex.func1({0xc1aade20a8, 0x14, 0x14}, {0xc080930000, 0xb8ec, 0x293f0}, {0x1f4d6c0?, 0xc14087a080?}, 0xc085deea50)                                                                     
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_log_index.go:206 +0x36c fp=0xc03c3cf648 sp=0xc03c3cf538 pc=0x1230fac                                                                                                                
github.com/ledgerwatch/erigon-lib/etl.loadFilesIntoBucket({0xc099d8a970, 0xe}, {0x1f70f10, 0xc0ece1b7a0}, {0x18fa853, 0xf}, 0x0, {0xc022386480, 0x6, 0x8}, ...)                                                                                
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220714160525-21aa65c1c383/etl/collector.go:265 +0x8df fp=0xc03c3cf908 sp=0xc03c3cf648 pc=0xe4d87f                                                                                           
github.com/ledgerwatch/erigon-lib/etl.(*Collector).Load(0xc0de5389b0?, {0x1f70f10?, 0xc0ece1b7a0?}, {0x18fa853?, 0xf?}, 0xc0f3f69f40?, {{0x0, 0x0, 0x0}, {0x0, ...}, ...})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220714160525-21aa65c1c383/etl/collector.go:265 +0x8df fp=0xc03c3cf908 sp=0xc03c3cf648 pc=0xe4d87f                                                                                           
github.com/ledgerwatch/erigon-lib/etl.(*Collector).Load(0xc0de5389b0?, {0x1f70f10?, 0xc0ece1b7a0?}, {0x18fa853?, 0xf?}, 0xc0f3f69f40?, {{0x0, 0x0, 0x0}, {0x0, ...}, ...})                                                                     
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220714160525-21aa65c1c383/etl/collector.go:140 +0x190 fp=0xc03c3cfa08 sp=0xc03c3cf908 pc=0xe4cc70
github.com/ledgerwatch/erigon/eth/stagedsync.promoteLogIndex({0xc099d8a970, 0xe}, {0x1f70f10, 0xc0ece1b7a0}, 0x0, {{0xc000593c20, 0x29}, {0x1f66a70, 0xc000e10000}, {0x1, ...}, ...}, ...)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_log_index.go:219 +0xdd1 fp=0xc03c3d1758 sp=0xc03c3cfa08 pc=0x1230811
github.com/ledgerwatch/erigon/eth/stagedsync.SpawnLogIndex(0xc12b06c8e0, {0x0, 0x0?}, {{0xc000593c20, 0x29}, {0x1f66a70, 0xc000e10000}, {0x1, {0x1f62ce0, 0xc0008c9830}, ...}, ...}, ...)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_log_index.go:77 +0x325 fp=0xc03c3d1898 sp=0xc03c3d1758 pc=0x122f765
github.com/ledgerwatch/erigon/eth/stagedsync.DefaultStages.func37(0x90?, 0x52?, 0x18efb7e?, {0x8?, 0x0?}, {0x0?, 0x0?})
        github.com/ledgerwatch/erigon/eth/stagedsync/default_stages.go:180 +0x6e fp=0xc03c3d1950 sp=0xc03c3d1898 pc=0x11f6c0e
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc099d65290, 0xc099db00a0, {0x1f66a70?, 0xc000e10000}, {0x0?, 0x0}, 0x0?, 0x0?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:327 +0x150 fp=0xc03c3d1a58 sp=0xc03c3d1950 pc=0x1247250
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc099d65290, {0x1f66a70?, 0xc000e10000}, {0x0, 0x0}, 0x0?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:235 +0x265 fp=0xc03c3d1b10 sp=0xc03c3d1a58 pc=0x1246225
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x1f5efc8, 0xc000530400}, {0x1f66a70?, 0xc000e10000?}, 0xc099d65290, 0x0, 0xc000200b80, 0x1, 0xc08138e4e0, 0x0)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:161 +0x445 fp=0xc03c3d1db8 sp=0xc03c3d1b10 pc=0x1501585
github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x1f5efc8, 0xc000530400}, {0x1f66a70?, 0xc000e10000}, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:82 +0x145 fp=0xc03c3d1f80 sp=0xc03c3d1db8 pc=0x1500c85
github.com/ledgerwatch/erigon/eth.(*Ethereum).Start.func1()                                                            
        github.com/ledgerwatch/erigon/eth/backend.go:855 +0x4e fp=0xc03c3d1fe0 sp=0xc03c3d1f80 pc=0x150d66e
runtime.goexit()                                           
        runtime/asm_amd64.s:1571 +0x1 fp=0xc03c3d1fe8 sp=0xc03c3d1fe0 pc=0x499cc1
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start                                                         
        github.com/ledgerwatch/erigon/eth/backend.go:855 +0x1e5                                                        

goroutine 1 [chan receive, 1645 minutes]:                  
github.com/ledgerwatch/erigon/node.(*Node).Wait(...)                                                                   
        github.com/ledgerwatch/erigon/node/node.go:259                                                                 
github.com/ledgerwatch/erigon/turbo/node.(*ErigonNode).Serve(0xc099d63820)                                             
        github.com/ledgerwatch/erigon/turbo/node/node.go:33 +0x7c                                                      
main.runErigon(0xc0003f26e0?)                              
        github.com/ledgerwatch/erigon/cmd/erigon/main.go:46 +0x27a                                                     
github.com/urfave/cli.HandleAction({0x1631620?, 0x1d545f0?}, 0xc00030fdc0?)                                            
        github.com/urfave/cli@v1.22.9/app.go:526 +0x50                                                                 
github.com/urfave/cli.(*App).Run(0xc00030fdc0, {0xc000156000, 0x11, 0x12})                                             
        github.com/urfave/cli@v1.22.9/app.go:286 +0x7c5                                                                
main.main()                                                
        github.com/ledgerwatch/erigon/cmd/erigon/main.go:28 +0x75
```

**Comment by AskAlexSharov** [comment]
hi. here is branch with fix: https://github.com/ledgerwatch/erigon/pull/4847

**Comment by dafky2000** [comment]
This appears to be fixed and has moved on to the next stages. Currently, approx 3.7TB, thank you!!
