### ISSUE TITLE
Erigon is crashing on Mumbai testnet

### ISSUE THREAD

**Issue by mikolajsobolewski** [ledgerwatch/erigon#4764]
#### System information

Erigon version: `2022.06.6-alpha-77240899`

OS & Version: Alpine Linux v3.15

#### Steps to reproduce the behaviour

Sync heimdall and sync erigon. Try to request latest block by
````
curl -s -X POST --header "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", true],"id":1}' http://127.0.0.1:8545/
````
the first request returns latest block, the following requests return block 0

#### Backtrace

````
[INFO] [07-20|09:43:37.726] Timings (slower than 50ms)               Headers=8m4.41s BlockHashes=3.077s Bodies=1m57.225s Senders=2m54.745s Execution=11.064s Unwind Headers=47.951s HashState=90ms Unwind Headers=2.836s Unwind Headers=2.752s Unwind Headers=2.74s Unwind Headers=2.65s Unwind Headers=2.731s Unwind Headers=2.662s Unwind Headers=2.717s Unwind Headers=2.647s Unwind Headers=2.728s Unwind Headers=2.651s Unwind Headers=2.71s Unwind Headers=2.674s Unwind Headers=2.737s Unwind Headers=2.664s Unwind Headers=2.721s Unwind Headers=2.688s Unwind Headers=2.747s Unwind Headers=2.726s
[INFO] [07-20|09:43:37.726] [snapshots] Retire Blocks                range=26000k-26500k
[INFO] [07-20|09:43:37.726] [1/16 Headers] Waiting for headers...    from=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe37ce9]

goroutine 305391 [running]:
github.com/ledgerwatch/erigon-lib/compress.(*Getter).nextPos(0xc048841770?, 0x4e?)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220620073929-46bebb3317d9/compress/decompress.go:312 +0x29
github.com/ledgerwatch/erigon-lib/compress.(*Getter).Next(0xc060c77840, {0x0, 0x0, 0x0})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220620073929-46bebb3317d9/compress/decompress.go:389 +0x59
github.com/ledgerwatch/erigon/turbo/snapshotsync.expectedTxsAmount({0xc04a617680, 0x32}, 0x18cba80, 0x1945ba0)
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1367 +0x1e5
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs({0x1f19828?, 0xc001198580}, {0x7f2759969dd8?, 0xc0011c2000}, {0xc04a617680, 0x53}, {0xc000647a70, 0x30}, 0x18cba80, 0x1945ba0, ...)
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1217 +0xbc5
github.com/ledgerwatch/erigon/turbo/snapshotsync.dumpBlocksRange({0x1f19828, 0xc001198580}, 0x64cec5?, 0xc0000a6220?, {0xc000647a70, 0x30}, {0xc0000fab00, 0x31}, {0x7f2759969dd8, 0xc0011c2000}, ...)
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1049 +0x365
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpBlocks({0x1f19828, 0xc001198580}, 0x1?, 0x1945ba0, 0x7a120, {0xc000647a70, 0x30}, {0xc0000fab00, 0x31}, {0x7f2759969dd8, ...}, ...)
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1031 +0x165
github.com/ledgerwatch/erigon/turbo/snapshotsync.retireBlocks({0x1f19828, 0xc001198580}, 0x18cba80, 0x1945ba0, {0x13881, 0x0, 0x0, 0x0}, {0xc000647a70, 0x30}, ...)
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:978 +0x205
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocks(...)
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:939
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground.func1()
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:962 +0x1c8
created by github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:952 +0xf1
[INFO] [07-20|09:43:39.756] Build info                               git_branch=heads/v2022.06.06 git_tag=v2022.06.06-dirty git_commit=7724089985bf9cb8bb7d1bde92892256a6af859f
````

**Comment by AskAlexSharov** [comment]
Try update erigon version
