### ISSUE TITLE
Goerli - panic: no gaps in tx ids are allowed: block 7000000 does jump from 90141651 to 91003027

### ISSUE THREAD

**Issue by PeaStew** [ledgerwatch/erigon#4788]
#### System information

Erigon version: v2022.07.02
Chain: Goerli
OS & Version: Linux

Commit hash : 

#### Expected behaviour
not panic

#### Actual behaviour
panic

#### Steps to reproduce the behaviour
This started today, after initial error

`panic: no gaps in tx ids are allowed: block 7021910 does jump from 89324096 to 4914836`

Rewound to before this block on headers and blocks, then resync, got to chaintip and it ran for about 30 mins before crashing with below error

#### Backtrace

````
[INFO] [07-22|07:32:25.387] [1/16 Headers] Waiting for headers...    from=7269758
Jul 22 07:32:33 <servername>8 erigon[2581316]: panic: no gaps in tx ids are allowed: block 7000000 does jump from 90141651 to 91003027
Jul 22 07:32:33 <servername>8 erigon[2581316]: goroutine 237256 [running]:
Jul 22 07:32:33 <servername>8 erigon[2581316]: github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs.func3.1({0x778e7c499f48?, 0xc024fbc630?, 0x8?}, {0x778e7c499f50?, 0x717b80a33288?, 0x60?})
Jul 22 07:32:33 <servername>8 erigon[2581316]:         github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1171 +0x314
Jul 22 07:32:33 <servername>8 erigon[2581316]: github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).ForAmount(0x1f4e0c0?, {0x18e6c26?, 0xa9b37672ba8c7e9b?}, {0xc024fbc630, 0x8, 0xa}, 0x10, 0xc03ff3e540)
Jul 22 07:32:33 <servername>8 erigon[2581316]:         github.com/ledgerwatch/erigon-lib@v0.0.0-20220707065230-95e361fa1ed7/kv/mdbx/kv_mdbx.go:533 +0x1a8
Jul 22 07:32:33 <servername>8 erigon[2581316]: github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs.func3({0x1f4e0c0, 0xc0174d7170}, {0x77a7f7a02fa8?, 0x8?, 0x778b82c24c00?}, {0x77a7f7a02fb0?, 0xc036d50300?, 0x1f4e0c0?})
Jul 22 07:32:33 <servername>8 erigon[2581316]:         github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1168 +0x824
Jul 22 07:32:33 <servername>8 erigon[2581316]: github.com/ledgerwatch/erigon-lib/kv.BigChunks.func1({0x1f4e0c0, 0xc0174d7170})
Jul 22 07:32:33 <servername>8 erigon[2581316]:         github.com/ledgerwatch/erigon-lib@v0.0.0-20220707065230-95e361fa1ed7/kv/helpers.go:40 +0x1eb
Jul 22 07:32:33 <servername>8 erigon[2581316]: github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).View(0xdf8475800?, {0x1f41a80?, 0xc000138000?}, 0xc036d502c0)
Jul 22 07:32:33 <servername>8 erigon[2581316]:         github.com/ledgerwatch/erigon-lib@v0.0.0-20220707065230-95e361fa1ed7/kv/mdbx/kv_mdbx.go:648 +0xbe
Jul 22 07:32:33 <servername>8 erigon[2581316]: github.com/ledgerwatch/erigon-lib/kv.BigChunks({0x7f8e6404d8f8, 0xc000220b40}, {0x18e51b3, 0xf}, {0xc024fbc650, 0x8, 0x8}, 0xc0174dab60)
Jul 22 07:32:33 <servername>8 erigon[2581316]:         github.com/ledgerwatch/erigon-lib@v0.0.0-20220707065230-95e361fa1ed7/kv/helpers.go:18 +0x192
Jul 22 07:32:33 <servername>8 erigon[2581316]: github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs({0x1f41a48?, 0xc000aa4b80}, {0x7f8e6404d8f8?, 0xc000220b40}, {0xc017014af0, 0x6d}, {0xc000042960, 0x4a}, 0x6acfc0, 0x6c5660, ...)
Jul 22 07:32:33 <servername>8 erigon[2581316]:         github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1123 +0x948
Jul 22 07:32:33 <servername>8 erigon[2581316]: github.com/ledgerwatch/erigon/turbo/snapshotsync.dumpBlocksRange({0x1f41a48, 0xc000aa4b80}, 0x64d265?, 0xc000146200?, {0xc000042960, 0x4a}, {0xc0000429b0, 0x4b}, {0x7f8e6404d8f8, 0xc000220b40}, ...)
Jul 22 07:32:33 <servername>8 erigon[2581316]:         github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1049 +0x365
Jul 22 07:32:33 <servername>8 erigon[2581316]: github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpBlocks({0x1f41a48, 0xc000aa4b80}, 0x0?, 0x6c5660, 0x7a120, {0xc000042960, 0x4a}, {0xc0000429b0, 0x4b}, {0x7f8e6404d8f8, ...}, ...)
Jul 22 07:32:33 <servername>8 erigon[2581316]:         github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1031 +0x165
Jul 22 07:32:33 <servername>8 erigon[2581316]: github.com/ledgerwatch/erigon/turbo/snapshotsync.retireBlocks({0x1f41a48, 0xc000aa4b80}, 0x6acfc0, 0x6c5660, {0x5, 0x0, 0x0, 0x0}, {0xc000042960, 0x4a}, ...)
Jul 22 07:32:33 <servername>8 erigon[2581316]:         github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:978 +0x205
Jul 22 07:32:33 <servername>8 erigon[2581316]: github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocks(...)
Jul 22 07:32:33 <servername>8 erigon[2581316]:         github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:939
Jul 22 07:32:33 <servername>8 erigon[2581316]: github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground.func1()
Jul 22 07:32:33 <servername>8 erigon[2581316]:         github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:962 +0x1c8
Jul 22 07:32:33 <servername>8 erigon[2581316]: created by github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground
Jul 22 07:32:33 <servername>8 erigon[2581316]:         github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:952 +0xf1
````

**Comment by AskAlexSharov** [comment]
Workaround: add —snap.stop

**Comment by suspended** [comment]
Just got the same on Goerli after restarting

**Comment by 3cl1ps** [comment]
just got it on mainnet, snap.stop made it working

**Comment by banteg** [comment]
got the same on mainnet https://gist.github.com/banteg/9a2946a7e3809c91aaafc3fc5019dbaf
