### ISSUE TITLE
erigon crash: invalid memory address or nil pointer dereference when run erigon as a validator in bsc network

### ISSUE THREAD

**Issue by fynn-0xc** [ledgerwatch/erigon#4972]
#### System information

Erigon version: `./erigon --version`

[root@xxx bin]# ./erigon --version
erigon version 2022.08.1-alpha-7dabdc32

OS & Version: Linux

Commit hash : 

7dabdc3269f1e3b098fee5ab4d96ec843823a6fd

#### Expected behaviour
it can mining block and catch up the latest block

#### Actual behaviour
During executing one round of mining stage sync, it crash when commit block

#### Steps to reproduce the behaviour
1. deploy bsc local private network
2. replace one of the validator from bsc client to erigon client
3. run erigon  then core dump

#### Backtrace

````
[root@xxx bin]# ./erigon --datadir=/server/erigon_dev --private.api.addr=localhost:9090 --mine --miner.sigfile /server/gethPriKey/private.key
INFO[08-09|08:59:32.990] Build info                               git_branch=HEAD git_tag=v2022.08.01 git_commit=7dabdc3269f1e3b098fee5ab4d96ec843823a6fd
INFO[08-09|08:59:32.990] Starting Erigon on Ethereum mainnet...
INFO[08-09|08:59:32.991] Maximum peer count                       ETH=100 total=100
INFO[08-09|08:59:32.991] starting HTTP APIs                       APIs=eth,erigon,engine
INFO[08-09|08:59:32.991] torrent verbosity                        level=WRN
INFO[08-09|08:59:35.092] Set global gas cap                       cap=50000000
INFO[08-09|08:59:35.125] Opening Database                         label=chaindata path=/server/erigon_dev/chaindata
INFO[08-09|08:59:35.127] Initialised chain configuration          config="{ChainID: 714, Homestead: 0, DAO: <nil>, DAO Support: false, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 0, Muir Glacier: 0, Berlin: <nil>, London: <nil>, Arrow Glacier: <nil>, Gray Glacier: <nil>, Terminal Total Difficulty: <nil>, Merge Netsplit: <nil>, Engine: parlia}" genesis=0x9cd9a43b76857523bb3d5c0869eeeabcbbe4a162dac3dac3140bc0cc4e7198cf
INFO[08-09|08:59:35.127] Effective                                prune_flags= snapshot_flags=
INFO[08-09|08:59:35.127] Using snapshots                          on=false
INFO[08-09|08:59:35.127] Initialising Ethereum protocol           network=1
INFO[08-09|08:59:35.134] Starting private RPC server              on=localhost:9090
INFO[08-09|08:59:35.134] new subscription to logs established
INFO[08-09|08:59:35.135] rpc filters: subscribing to Erigon events
INFO[08-09|08:59:35.135] New txs subscriber joined
INFO[08-09|08:59:35.135] new subscription to newHeaders established
INFO[08-09|08:59:35.135] Reading JWT secret                       path=/server/erigon_dev/jwt.hex
INFO[08-09|08:59:35.135] Generated JWT secret                     path=/server/erigon_dev/jwt.hex
INFO[08-09|08:59:35.135] HTTP endpoint opened for Engine API      url=localhost:8551 ws=true ws.compression=true
INFO[08-09|08:59:35.135] HTTP endpoint opened                     url=localhost:8545 ws=false ws.compression=true grpc=false
INFO[08-09|08:59:35.145] [txpool] Started
INFO[08-09|08:59:35.145] [1/16 Headers] Waiting for headers...    from=0
INFO[08-09|08:59:35.146] Started P2P networking                   version=66 self=enode://b7ac4b161141433d1dd954ca4a5c08c270ac553881659d58dea314b12392c894e2fe4e7d70175b59195377803b23323daf42b41bf1bb54c8901bf8460ff8c084@127.0.0.1:30303 name=erigon/v2022.08.1-alpha-7dabdc32/linux-amd64/go1.18.5
INFO[08-09|08:59:38.139] [1/5 MiningCreateBlock] Start mine       block=1 baseFee=<nil> gasLimit=39843751
INFO[08-09|08:59:38.140] [parlia] init contract                   block hash=0xe76b0a35f2ef105d8fb55ecc259feba9fa492b099b9cde60a85053cb995f38e1 contract=0x0000000000000000000000000000000000001000
INFO[08-09|08:59:38.140] [parlia] init contract                   block hash=0x825c888193cd9bd8320804ceaee4920c7fc62c3b33ea583d31b17850c46ebe5c contract=0x0000000000000000000000000000000000001001
INFO[08-09|08:59:38.140] [parlia] init contract                   block hash=0x8ca389c8505504297b1ca0ad94e1cb5eb8c2d40d8e18a70f40e7d73bc8a255f8 contract=0x0000000000000000000000000000000000001003
INFO[08-09|08:59:38.140] [parlia] init contract                   block hash=0x7a2b2647767af394e6678ddb5c6d0def1dee1de002cb62674d9097bf37722485 contract=0x0000000000000000000000000000000000001006
INFO[08-09|08:59:38.140] [parlia] init contract                   block hash=0xb14668516390fe0047fd10a6945192d6b88442cb34eecd76bae7a0ba5529c3d7 contract=0x0000000000000000000000000000000000001004
INFO[08-09|08:59:38.141] [parlia] init contract                   block hash=0x86bc837c0d40b1b2f5b0e68665559fe726006fc29d60c65a368f37da0a6ddc72 contract=0x0000000000000000000000000000000000001005
INFO[08-09|08:59:38.141] [parlia] init contract                   block hash=0xe61039dfba261cdc3f578c617abf61d3bdd2a7cfa220358154db0588519f9580 contract=0x0000000000000000000000000000000000002000
INFO[08-09|08:59:38.143] [4/5 IntermediateHashes] Regeneration trie hashes started
INFO[08-09|08:59:38.143] [4/5 IntermediateHashes] Trie root       hash=0xf95252bc1a5018cf95d6f33466948fcddf930c16d9cc461b66fd4e7665aec537
INFO[08-09|08:59:38.143] [4/5 IntermediateHashes] Regeneration ended
INFO[08-09|08:59:38.144] Sealing block with                       number=1 delay=-144.011821ms headerDifficulty=1 val=0xeE06551B99525B8C3ef93f6472caC2F79Aa584AF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8ac163]

goroutine 695 [running]:
github.com/torquem-ch/mdbx-go/mdbx.openCursor.func1(0xc00093f8c0?, 0x93f8b8?, 0xc002396000)
	github.com/torquem-ch/mdbx-go@v0.25.2/mdbx/cursor.go:67 +0x23
github.com/torquem-ch/mdbx-go/mdbx.openCursor(0x0, 0x241aa20?)
	github.com/torquem-ch/mdbx-go@v0.25.2/mdbx/cursor.go:67 +0x65
github.com/torquem-ch/mdbx-go/mdbx.(*Txn).OpenCursor(...)
	github.com/torquem-ch/mdbx-go@v0.25.2/mdbx/txn.go:611
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).stdCursor(0xc00241aa80, {0x1938828, 0xa})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220804053117-2be46669d514/kv/mdbx/kv_mdbx.go:1087 +0x13f
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).RwCursor(0xc00241aa80, {0x1938828, 0xa})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220804053117-2be46669d514/kv/mdbx/kv_mdbx.go:1074 +0xdb
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).Cursor(...)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220804053117-2be46669d514/kv/mdbx/kv_mdbx.go:1078
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).statelessCursor(0xc00241aa80, {0x1938828, 0xa})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220804053117-2be46669d514/kv/mdbx/kv_mdbx.go:909 +0x9f
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).GetOne(0x1010000000007?, {0x1938828?, 0x0?}, {0xc0023c4000, 0xa, 0xa})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220804053117-2be46669d514/kv/mdbx/kv_mdbx.go:935 +0x2d
github.com/ledgerwatch/erigon-lib/kv/memdb.(*MemoryMutation).getMem(0xc001bc0000?, {0x1938828?, 0x42fee7?}, {0xc0023c4000?, 0x167d4a0?, 0x1?})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220804053117-2be46669d514/kv/memdb/memory_mutation.go:82 +0x2e
github.com/ledgerwatch/erigon-lib/kv/memdb.(*MemoryMutation).GetOne(0xc002422280, {0x1938828, 0xa}, {0xc0023c4000, 0xa, 0xa})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220804053117-2be46669d514/kv/memdb/memory_mutation.go:136 +0x3b
github.com/ledgerwatch/erigon/core/rawdb.ReadHeadHeaderHash({0x1fad6c0, 0xc002422280})
	github.com/ledgerwatch/erigon/core/rawdb/accessors_chain.go:117 +0x95
github.com/ledgerwatch/erigon/eth/stagedsync.ChainReader.CurrentHeader({{{0x0, 0x0}, 0xc001afe1e0, {0x0, 0x0}, 0xc001afe200, 0x0, 0x0, 0xc001afe240, {0x0, ...}, ...}, ...})
	github.com/ledgerwatch/erigon/eth/stagedsync/chain_reader.go:28 +0x2d
github.com/ledgerwatch/erigon/consensus/parlia.(*Parlia).shouldWaitForCurrentBlockProcess(0xc0006f77b0?, {0x1fb08c8, 0xc000558b00}, 0xc0001da780, 0xc0022a9f20?)
	github.com/ledgerwatch/erigon/consensus/parlia/parlia.go:940 +0x55
github.com/ledgerwatch/erigon/consensus/parlia.(*Parlia).Seal.func1()
	github.com/ledgerwatch/erigon/consensus/parlia/parlia.go:848 +0x125
created by github.com/ledgerwatch/erigon/consensus/parlia.(*Parlia).Seal
	github.com/ledgerwatch/erigon/consensus/parlia/parlia.go:842 +0x85d
````

**Comment by fynn-z** [comment]
fix https://github.com/ledgerwatch/erigon/pull/4984

**Comment by enriavil1** [comment]
@fynn-z has it been fixed?

**Comment by fynn-z** [comment]
> @fynn-z has it been fixed?

Yes, it fixed.
