### ISSUE TITLE
build/bin/integrations print_headers crashes with incorrect --datadir

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/erigon#5038]
I ran `./build/bin/integrations print_headers` with an incorrect `--datadir` (actually an empty `--datadir`). It crashes as below:

```
Print stages crashes:

jrush@web3:~/D/erigon|devel⚡*?➤ build/bin/integration print_stages
panic: fail to open mdbx: mdbx_env_open: no such file or directory, label: chaindata, trace: [kv_mdbx.go:213 kv_mdbx.go:338 root.go:53 stages.go:222 command.go:872 command.go:990 command.go:918 command.go:911 main.go:15 proc.go:250 asm_arm64.s:1263]

goroutine 1 [running]:
github.com/ledgerwatch/erigon-lib/kv/mdbx.MdbxOpts.MustOpen({0x101d7ad10, {0x140004190e0, 0x25}, 0x0, 0x0, 0x2, 0x80000000000, 0x42820000, {0x101d9a740, 0x140003ce820}, ...})
    github.com/ledgerwatch/erigon-lib@v0.0.0-20220811075528-55fa5d700637/kv/mdbx/kv_mdbx.go:340 +0xcc
github.com/ledgerwatch/erigon/cmd/integration/commands.openDB({0x101d7ad10, {0x140004190e0, 0x25}, 0x0, 0x0, 0x2, 0x80000000000, 0x42820000, {0x101d9a740, 0x140003ce820}, ...}, ...)
    github.com/ledgerwatch/erigon/cmd/integration/commands/root.go:53 +0xe0
github.com/ledgerwatch/erigon/cmd/integration/commands.glob..func18(0x10269d6a0?, {0x10147b971?, 0x0?, 0x0?})
    github.com/ledgerwatch/erigon/cmd/integration/commands/stages.go:222 +0x13c
github.com/spf13/cobra.(*Command).execute(0x10269d6a0, {0x1026fce80, 0x0, 0x0})
    github.com/spf13/cobra@v1.5.0/command.go:872 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x1026a0620)
    github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
    github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
    github.com/spf13/cobra@v1.5.0/command.go:911
main.main()
    github.com/ledgerwatch/erigon/cmd/integration/main.go:15 +0x12c
```

**Comment by tjayrush** [comment]
Also, the word `snapsthos` is misspelled. Should be `snapshots`.

**Comment by AskAlexSharov** [comment]
It ysing same defaults as erigon, but looks like need to break defaults and make datadir required. Zillion users already did it.

**Comment by AskAlexSharov** [comment]
done https://github.com/ledgerwatch/erigon/pull/5041
