### ISSUE TITLE
crash during DB migration

### ISSUE THREAD

**Issue by SCBuergel** [ledgerwatch/erigon#5095]
#### System information

Erigon version: 2022.08.02-alpha (unzipped from GitHub release and `make erigon` following instructions)

OS & Version: Ubuntu20.04

#### Expected behaviour
When starting my erigon node with `./erigon` I expect it to sync my DB to the new format and start operating normally.

#### Actual behaviour
It crashed at 59%:
![Screenshot from 2022-08-17 22-49-23](https://user-images.githubusercontent.com/11379673/185241260-57f74eba-63bf-43f9-b1b3-7358d59b5c3f.png)

Every time I start it again, it crashes immediately:
```
$ /home/seb/erigon-2022.08.02/build/bin/erigon
INFO[08-17|22:49:37.885] Build info                               git_branch= git_tag= git_commit=
INFO[08-17|22:49:37.886] Starting Erigon on Ethereum mainnet... 
INFO[08-17|22:49:37.887] Maximum peer count                       ETH=100 total=100
INFO[08-17|22:49:37.888] starting HTTP APIs                       APIs=eth,erigon,engine
INFO[08-17|22:49:37.888] torrent verbosity                        level=WRN
INFO[08-17|22:49:40.261] [torrent] Public IP                      ip=178.195.164.159
INFO[08-17|22:49:40.261] Set global gas cap                       cap=50000000
INFO[08-17|22:49:40.307] Opening Database                         label=chaindata path=/home/seb/.local/share/erigon/chaindata
INFO[08-17|22:49:40.309] Re-Opening DB in exclusive mode to apply migrations 
INFO[08-17|22:49:40.310] Apply migration                          name=txs_begin_end
INFO[08-17|22:49:40.310] [database version migration] Continue migration from_block=6020000
fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x2 addr=0x7721ebaeb010 pc=0x424b6c]

runtime stack:
runtime.throw({0x19e4b63?, 0x7f1258003c50?})
	runtime/panic.go:992 +0x71
runtime.sigpanic()
	runtime/signal_unix.go:802 +0x3a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x15a9790, 0xc001b75fb0)
	runtime/cgocall.go:157 +0x5c fp=0xc001b75f88 sp=0xc001b75f50 pc=0x4293bc
github.com/torquem-ch/mdbx-go/mdbx._Cfunc_mdbx_cursor_get(0x7f125bfff6c0, 0x7f1258003c50, 0x7f1258003c70, 0x8)
	_cgo_gotypes.go:447 +0x4c fp=0xc001b75fb0 sp=0xc001b75f88 pc=0x8b09cc
github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).getVal0.func1(0xc001b76078?, 0x8)
	github.com/torquem-ch/mdbx-go@v0.25.2/mdbx/cursor.go:184 +0xb0 fp=0xc001b76000 sp=0xc001b75fb0 pc=0x8b4950
github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).getVal0(0xc00003f000?, 0xc0020d4000?)
	github.com/torquem-ch/mdbx-go@v0.25.2/mdbx/cursor.go:184 +0x1d fp=0xc001b76030 sp=0xc001b76000 pc=0x8b477d
github.com/torquem-ch/mdbx-go/mdbx.(*Cursor).Get(0xc00088e190, {0x0, 0x0, 0x0}, {0x0?, 0xaa?, 0xc00088e190?}, 0x8)
	github.com/torquem-ch/mdbx-go@v0.25.2/mdbx/cursor.go:140 +0x65 fp=0xc001b760a0 sp=0xc001b76030 pc=0x8b44a5
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).next(...)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220814135647-e160c1ad9ca1/kv/mdbx/kv_mdbx.go:1123
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).Next(0xc0005f2960)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220814135647-e160c1ad9ca1/kv/mdbx/kv_mdbx.go:1272 +0x50 fp=0xc001b76178 sp=0xc001b760a0 pc=0xa9b550
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).ForAmount(0xc00088a680?, {0x19ab43d?, 0xc0005b0180?}, {0xc00097e6a8, 0x8, 0x8}, 0x5e, 0xc0005b01b0)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220814135647-e160c1ad9ca1/kv/mdbx/kv_mdbx.go:557 +0x176 fp=0xc001b76210 sp=0xc001b76178 pc=0xa96ff6
github.com/ledgerwatch/erigon/core/rawdb.CanonicalTransactions({0x7f12782a9e68, 0xc00071a0f0}, 0x10664f44, 0x5e)
	github.com/ledgerwatch/erigon/core/rawdb/accessors_chain.go:409 +0x1f0 fp=0xc001b76290 sp=0xc001b76210 pc=0x110ebd0
github.com/ledgerwatch/erigon/migrations.glob..func3({0x2026c90, 0xc000906160}, {{0xc0001169a0, 0x1d}, {0xc0001169a0, 0x1d}, {0xc0005abaa0, 0x27}, {0xc0008924c0, 0x36}, ...}, ...)
	github.com/ledgerwatch/erigon/migrations/txs_begin_end.go:91 +0x7ee fp=0xc001b77bb8 sp=0xc001b76290 pc=0x129e04e
github.com/ledgerwatch/erigon/migrations.(*Migrator).Apply(0xc0004183a8, {0x2026c90, 0xc000906160}, {0xc0001169a0?, 0x0?})
	github.com/ledgerwatch/erigon/migrations/migrations.go:205 +0x772 fp=0xc001b77ef8 sp=0xc001b77bb8 pc=0x129c392
github.com/ledgerwatch/erigon/node.OpenDatabase(0xc0002a8000, {0x20291c0, 0xc0000c7b00}, 0x0)
	github.com/ledgerwatch/erigon/node/node.go:354 +0x3b3 fp=0xc001b78020 sp=0xc001b77ef8 pc=0x12a49f3
github.com/ledgerwatch/erigon/eth.New(0xc00088a000, 0x2b74e20, {0x20291c0?, 0xc0000c7b00})
	github.com/ledgerwatch/erigon/eth/backend.go:158 +0x43c fp=0xc001b797d8 sp=0xc001b78020 pc=0x155575c
github.com/ledgerwatch/erigon/turbo/node.New(0x200234a?, 0x199a4df?, {0x20291c0, 0xc0000c7b00})
	github.com/ledgerwatch/erigon/turbo/node/node.go:115 +0x85 fp=0xc001b79838 sp=0xc001b797d8 pc=0x1562145
main.runErigon(0xc000386580?)
	github.com/ledgerwatch/erigon/cmd/erigon/main.go:58 +0x28e fp=0xc001b79908 sp=0xc001b79838 pc=0x15a812e
github.com/urfave/cli.HandleAction({0x16cd080?, 0x1e008a0?}, 0xc00075a000?)
	github.com/urfave/cli@v1.22.9/app.go:526 +0x50 fp=0xc001b79920 sp=0xc001b79908 pc=0x5f3c70
github.com/urfave/cli.(*App).Run(0xc00075a000, {0xc0001981e0, 0x1, 0x1})
	github.com/urfave/cli@v1.22.9/app.go:286 +0x7c5 fp=0xc001b79ef8 sp=0xc001b79920 pc=0x5f1245
main.main()
	github.com/ledgerwatch/erigon/cmd/erigon/main.go:34 +0x75 fp=0xc001b79f80 sp=0xc001b79ef8 pc=0x15a7db5
runtime.main()
	runtime/proc.go:250 +0x212 fp=0xc001b79fe0 sp=0xc001b79f80 pc=0x45e032
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc001b79fe8 sp=0xc001b79fe0 pc=0x48ec01

goroutine 19 [sleep]:
time.Sleep(0x22ecb25c00)
	runtime/time.go:194 +0x12e
github.com/VictoriaMetrics/metrics.summariesSwapCron(0x45d964b800)
	github.com/VictoriaMetrics/metrics@v1.22.1/summary.go:237 +0x36
created by github.com/VictoriaMetrics/metrics.registerSummaryLocked
	github.com/VictoriaMetrics/metrics@v1.22.1/summary.go:211 +0x125
```
#### Steps to reproduce the behaviour
Start erigon with the last release of 2021, then install latest version and wait for DB migration to crash

**Comment by AskAlexSharov** [comment]
SIGBUS on MMAP may be because of hardware failure: Please use tools like https://www.memtest86.com to test RAM and tools like https://www.smartmontools.org to test Disk
