### ISSUE TITLE
Polygon node crashing with out-of-control RAM usage

### ISSUE THREAD

**Issue by Petter-s** [ledgerwatch/erigon#5126]
#### System information

Erigon version: version 2022.99.99-dev-c1eef706

OS & Version: Windows 11 (Build 22000.856)

Commit hash : c1eef706b37334f8d6d98d3c73fc8a5377214cc8

PC: i9-11900H processor, 32 GB RAM, 2 TB M.2 disk

#### Expected behaviour

Successfully syncing a Polygon node with RAM usage not exceeding 16 GB as stated in the Erigon system requirements.

#### Actual behaviour

What I’m trying to do:
Run a Polygon node locally with Erigon on Windows 11.

What I have done:
I downloaded the latest Bor full node snapshot from https://snapshots.matic.today/ and extracted it into a folder: E:\polygon_bor_data.

I then start Erigon using these flags (following [this guide](https://polygontechnology.notion.site/Erigon-Usage-Guide-64be30e49b894ed8b3c6b3da8300acfb)):

`erigon.exe chain=bor-mainnet --bor.heimdall=https://heimdall.api.matic.network --datadir=E:\polygon_bor_data --port=30304 --http.port=8546 --authrpc.port=8552 --torrent.port=42068 --private.api.addr=127.0.0.1:9091 --http --ws --http.api=eth,debug,net,trace,web3,erigon`

When starting Erigon RAM usage quickly explodes to 100 % of my available 32 GB. Then Erigon starts to also fill my ~130 GB available paged memory space.

As this happens I repeatedly get a warning from Erigon saying that missing snapshots are being downloaded and also an error saying “="[1/16 Headers] BuildMissedIndices: compressed file is too short: 0"”.

Here is an excerpt of the terminal during this phase:

```
INFO[08-21|03:00:56.023] Build info                               git_branch=devel git_tag=v2021.10.03-1694-gc1eef706b git_commit=c1eef706b37334f8d6d98d3c73fc8a5377214cc8
INFO[08-21|03:00:56.026] Starting Erigon on Ethereum mainnet...
INFO[08-21|03:00:56.027] Maximum peer count                       ETH=100 total=100
INFO[08-21|03:00:56.027] starting HTTP APIs                       APIs=eth,erigon,engine
INFO[08-21|03:00:56.028] torrent verbosity                        level=WRN
INFO[08-21|03:00:58.488] [torrent] Public IP                      ip=100.94.137.159
INFO[08-21|03:00:58.587] Set global gas cap                       cap=50000000
INFO[08-21|03:00:58.692] Opening Database                         label=chaindata path=C:\\Users\\i9laptop\\AppData\\Local\\Erigon\\chaindata
INFO[08-21|03:00:58.743] Initialised chain configuration          config="{ChainID: 1, Homestead: 1150000, DAO: 1920000, DAO Support: true, Tangerine Whistle: 2463000, Spurious Dragon: 2675000, Byzantium: 4370000, Constantinople: 7280000, Petersburg: 7280000, Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Gray Glacier: 15050000, Terminal Total Difficulty: 58750000000000000000000, Merge Netsplit: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
INFO[08-21|03:00:58.745] Effective                                prune_flags= snapshot_flags="--snapshots=true" history.v2=false
INFO[08-21|03:00:59.090] Initialising Ethereum protocol           network=1
INFO[08-21|03:00:59.090] Disk storage enabled for ethash DAGs     dir=C:\\Users\\i9laptop\\AppData\\Local\\Erigon\\ethash-dags count=2
INFO[08-21|03:00:59.182] new subscription to logs established
INFO[08-21|03:00:59.182] Starting private RPC server              on=127.0.0.1:9090
INFO[08-21|03:00:59.187] rpc filters: subscribing to Erigon events
INFO[08-21|03:00:59.188] New txs subscriber joined
INFO[08-21|03:00:59.189] new subscription to newHeaders established
INFO[08-21|03:00:59.193] Reading JWT secret                       path=C:\\Users\\i9laptop\\AppData\\Local\\Erigon/jwt.hex
INFO[08-21|03:00:59.195] HTTP endpoint opened for Engine API      url=localhost:8551 ws=true ws.compression=true
INFO[08-21|03:00:59.196] HTTP endpoint opened                     url=localhost:8545 ws=false ws.compression=true grpc=false
INFO[08-21|03:00:59.208] [txpool] Started
WARN[08-21|03:00:59.210] [Snapshots] downloading missing snapshots
INFO[08-21|03:00:59.210] [Snapshots] Fetching torrent files metadata
INFO[08-21|03:00:59.210] [snapshots] seeding a new snapshot
INFO[08-21|03:00:59.211] [snapshots] seeding a new snapshot
INFO[08-21|03:00:59.211] [snapshots] seeding a new snapshot
INFO[08-21|03:00:59.216] [Snapshots] Stat                         blocks=0k indices=0k alloc=72.3MB sys=108.3MB
EROR[08-21|03:00:59.224] Staged Sync                              err="[1/16 Headers] BuildMissedIndices: compressed file is too short: 0"
INFO[08-21|03:00:59.443] Started P2P networking                   version=66 self=enode://6de2e64a9e85324ccf48c19c3ee636ead8fda0a5bce99b9e452f0587bae3321b4c7163a06fa9b7b831dc48403fcac411f31f35a40ed64786d20ef293f9df63ca@100.94.137.159:30303 name=erigon/v2022.99.99-dev-c1eef706/windows-amd64/go1.18.2
WARN[08-21|03:00:59.736] [Snapshots] downloading missing snapshots
INFO[08-21|03:00:59.738] [Snapshots] Fetching torrent files metadata
INFO[08-21|03:00:59.738] [snapshots] seeding a new snapshot
INFO[08-21|03:00:59.738] [snapshots] seeding a new snapshot
INFO[08-21|03:00:59.738] [snapshots] seeding a new snapshot
INFO[08-21|03:00:59.747] [Snapshots] Stat                         blocks=0k indices=0k alloc=265.3MB sys=331.8MB
EROR[08-21|03:00:59.758] Staged Sync                              err="[1/16 Headers] BuildMissedIndices: compressed file is too short: 0"
INFO[08-21|03:00:59.891] Mapped network port                      proto=udp extport=30303 intport=30303 interface="UPNP IGDv1-IP1"
WARN[08-21|03:01:00.270] [Snapshots] downloading missing snapshots
INFO[08-21|03:01:00.270] [Snapshots] Fetching torrent files metadata
INFO[08-21|03:01:00.270] [snapshots] seeding a new snapshot
INFO[08-21|03:01:00.270] [snapshots] seeding a new snapshot
INFO[08-21|03:01:00.270] [snapshots] seeding a new snapshot
INFO[08-21|03:01:00.298] [Snapshots] Stat                         blocks=0k indices=0k alloc=642.6MB sys=728.4MB
INFO[08-21|03:01:00.314] Mapped network port                      proto=tcp extport=30303 intport=30303 interface="UPNP IGDv1-IP1"
EROR[08-21|03:01:00.314] Staged Sync                              err="[1/16 Headers] BuildMissedIndices: compressed file is too short: 0"

```

After a few minutes of running, Erigon has consumed all of my RAM + ~130 GB paged memory and then crashes with an error that is too long to be fully shown in my terminal, but the part I can see looks something like this:
```

        github.com/anacrolix/torrent@v1.46.1-0.20220808053819-61302332cfc5/tracker_scraper.go:207 +0xca
created by github.com/anacrolix/torrent.(*trackerScraper).Run
        github.com/anacrolix/torrent@v1.46.1-0.20220808053819-61302332cfc5/tracker_scraper.go:205 +0x12e

goroutine 1060 [select, 12 minutes]:
github.com/anacrolix/torrent.(*trackerScraper).Run(0xc002e8b260)
        github.com/anacrolix/torrent@v1.46.1-0.20220808053819-61302332cfc5/tracker_scraper.go:249 +0x49c
created by github.com/anacrolix/torrent.(*Torrent).startScrapingTracker.func1
        github.com/anacrolix/torrent@v1.46.1-0.20220808053819-61302332cfc5/torrent.go:1687 +0x254

goroutine 1061 [select, 12 minutes]:
github.com/anacrolix/torrent.(*trackerScraper).Run(0xc002e8b340)
        github.com/anacrolix/torrent@v1.46.1-0.20220808053819-61302332cfc5/tracker_scraper.go:249 +0x49c
created by github.com/anacrolix/torrent.(*Torrent).startScrapingTracker.func1
        github.com/anacrolix/torrent@v1.46.1-0.20220808053819-61302332cfc5/torrent.go:1687 +0x254

goroutine 1028 [select, 12 minutes]:
github.com/anacrolix/torrent.(*trackerScraper).Run.func1()
        github.com/anacrolix/torrent@v1.46.1-0.20220808053819-61302332cfc5/tracker_scraper.go:207 +0xca
created by github.com/anacrolix/torrent.(*trackerScraper).Run
        github.com/anacrolix/torrent@v1.46.1-0.20220808053819-61302332cfc5/tracker_scraper.go:205 +0x12e

goroutine 1062 [select, 2 minutes]:
github.com/anacrolix/torrent.(*trackerScraper).Run(0xc002e8b420)
        github.com/anacrolix/torrent@v1.46.1-0.20220808053819-61302332cfc5/tracker_scraper.go:249 +0x49c
created by github.com/anacrolix/torrent.(*Torrent).startScrapingTracker.func1
        github.com/anacrolix/torrent@v1.46.1-0.20220808053819-61302332cfc5/torrent.go:1687 +0x254
```
*...continues 100s of times with similar messages*

**Comment by AskAlexSharov** [comment]
Try start with —downloader.verify flag

**Comment by Petter-s** [comment]
> —downloader.verify

I have tried adding --downloader.verify now but the Erigon behaviour seems identical to the way it was without the flag. Same RAM usage, same warnings + error + crash.

This is the full startup configuration I used:

`erigon.exe chain=bor-mainnet --bor.heimdall=https://heimdall.api.matic.network --datadir=E:\polygon_bor_data --downloader.verify --port=30304 --http.port=8546 --authrpc.port=8552 --torrent.port=42068 --private.api.addr=127.0.0.1:9091 --http --ws --http.api=eth,debug,net,trace,web3,erigon`
