### ISSUE TITLE
Panic - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Texnomic** [ledgerwatch/erigon#5206]
#### System information

Erigon version: v2022.08.02-alpha

OS & Version: Ubuntu Server

Commit hash : 35c4faa

#### CMD

````bash
./erigon --config /mnt/data/Erigon.yaml
````

#### Config

````yaml
# -----------------
# Basics
# -----------------
chain: mainnet
datadir: /mnt/data
http.api: "eth,erigon,engine,web3,net,debug,trace,txpool,db,parity"
nat: "any"

# -----------------
# Memory Pool
# -----------------
txpool.globalslots: 1000000
txpool.globalbasefeeslots: 1000000
txpool.globalqueue: 1000000
txpool.lifetime: 720h
maxpeers: 200

# -----------------
# IPs
# -----------------
authrpc.addr: 0.0.0.0
metrics.addr: 0.0.0.0
private.api.addr: "0.0.0.0:9090"
pprof.addr: 0.0.0.0
http.addr: 0.0.0.0

# -----------------
# Ports
# -----------------
port: 30303
http.port: 8545
authrpc.port: 8551
pprof.port: 6060
metrics.port: 6070

# -----------------
# Hosts
# -----------------
http.vhosts: "*"
authrpc.vhosts: "*"
http.corsdomain: "*"

# -----------------
# Flags
# -----------------
history.v2: false
watch-the-burn: true
metrics: true
metrics.expensive: true
pprof: true
ws: true
http: true
snapshots: true
no-downloader: true
healthcheck: true
http.compression: true
http.trace: true
v5disc: true
````

#### Logs

````bash
INFO[08-27|09:04:34.000] [Snapshots] Stat                         blocks=15330k indices=15330k alloc=7.3GB sys=10.0GB
INFO[08-27|09:04:35.036] [snapshots] Merge done                   from=15320000
INFO[08-27|09:04:35.045] [Snapshots] Stat                         blocks=15330k indices=15330k alloc=7.3GB sys=10.0GB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11cb100]

goroutine 6418626 [running]:
github.com/ledgerwatch/erigon/turbo/snapshotsync.RequestSnapshotsDownload({0x201e1c8, 0xc00070aa00}, {0xc188febdd0?, 0xc00070aa00?, 0x201e1c8?}, {0x0, 0x0})
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:2084 +0x40
github.com/ledgerwatch/erigon/turbo/snapshotsync.retireBlocks({0x201e1c8, 0xc00070aa00}, 0xe9e6e8, 0xe9ead0, {0x1, 0x0, 0x0, 0x0}, {0xc0001360f0, 0x12}, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1127 +0x645
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocks(0xc09aa32150, {0x201e1c8, 0xc00070aa00}, 0x200d2a0?, 0xc1bebe8280?, 0x3?)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1037 +0x125
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground.func1()
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1079 +0x107
created by github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1069 +0xdf

````

**Comment by AskAlexSharov** [comment]
set `no-downloader: false`

**Comment by Texnomic** [comment]
I intentionally wanted to disable the `downloader` component, Is it possible ?

**Comment by AskAlexSharov** [comment]
> I intentionally wanted to disable the `downloader` component, Is it possible ?

why?

**Comment by Texnomic** [comment]
> why?

Two reasons: total bandwidth consumption and number of concurrent connections, since, at least in my case, Erigon is used with internet speed of `< 30 Mbps` and limited monthly quote of `< 400 GB`. Also BitTorrent Peers + DevP2P Peers are over `200+` active connections by default.

**Comment by AskAlexSharov** [comment]
See —torrent.upload.rate,  —torrent.download.rate, —torrent.cons.perfile flags

**Comment by Texnomic** [comment]
Thanks, got it.
