### ISSUE TITLE
Panic on devel

### ISSUE THREAD

**Issue by geomad** [ledgerwatch/erigon#5289]
#### System information

Erigon version: ` git_branch=devel git_tag=v2021.10.03-1812-g488121f66-dirty`
OS & Version: Linux
Commit hash : 488121f669825939e494a04cc0dd840869ebf7f4
Network: mainnet

after upgrading to latest devel erigon panics on startup.

startup arguments:
`--snap.stop --snapshots=true --datadir /erigon --http=false --txpool.disable --maxpeers 15 --ethash.dagdir /erigon/erigon-ethash --port 30305 --trustedpeers=enode://xxxx`

startup log:
```
[INFO] Initialising Ethereum protocol           network=1
[INFO] Disk storage enabled for ethash DAGs     dir=/chain/erigon/erigon-ethash count=2
[INFO] Starting private RPC server              on=127.0.0.1:9090
[INFO] new subscription to logs established
[INFO] rpc filters: subscribing to Erigon events
[INFO] new subscription to newHeaders established
[INFO] Reading JWT secret                       path=/erigon/jwt.hex
[EROR] could not start RPC api for engine: could not start RPC api: listen tcp 127.0.0.1:8551: bind: address already in use
[INFO] Started P2P networking                   version=66 self=enode://xxxx
[INFO] [Snapshots] Fetching torrent files metadata
[INFO] new subscription to newHeaders established
[INFO] [Snapshots] Stat                         blocks=14000k indices=14000k alloc=2.0GB sys=2.2GB
[INFO] [1/16 Snapshots] Writing total difficulty index for snapshots block_num=835272
[INFO] new subscription to newHeaders established
[INFO] [1/16 Snapshots] Writing total difficulty index for snapshots block_num=1712258
[INFO] [1/16 Snapshots] Writing total difficulty index for snapshots block_num=2856302
[INFO] [1/16 Snapshots] Writing total difficulty index for snapshots block_num=3728270
[INFO] [1/16 Snapshots] Writing total difficulty index for snapshots block_num=4777727
[INFO] [p2p] GoodPeers                          eth66=8
[INFO] [1/16 Snapshots] Writing total difficulty index for snapshots block_num=6228068
[INFO] [1/16 Snapshots] Writing total difficulty index for snapshots block_num=7456541
[INFO] [1/16 Snapshots] Writing total difficulty index for snapshots block_num=9369733
[INFO] [1/16 Snapshots] Writing total difficulty index for snapshots block_num=10939305
[INFO] [1/16 Snapshots] Writing total difficulty index for snapshots block_num=12069181
[INFO] [1/16 Snapshots] Writing total difficulty index for snapshots block_num=13695291
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe8ebc9]
goroutine 71178 [running]:
github.com/ledgerwatch/erigon-lib/compress.(*Getter).nextPos(0x176a240?, 0xd0?)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220905084759-b1c6dac7321d/compress/decompress.go:394 +0x29
github.com/ledgerwatch/erigon-lib/compress.(*Getter).Next(0xc006a5be70, {0xc006a5adf0, 0x0, 0x1000})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220905084759-b1c6dac7321d/compress/decompress.go:506 +0x59
github.com/ledgerwatch/erigon/turbo/snapshotsync.forEachAsync.func1.1()
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1775 +0x16e
github.com/ledgerwatch/erigon-lib/compress.(*Decompressor).WithReadAhead(0xc001923900, 0xc0032cc768)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220905084759-b1c6dac7321d/compress/decompress.go:369 +0xa2
github.com/ledgerwatch/erigon/turbo/snapshotsync.forEachAsync.func1()
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1770 +0xb4
created by github.com/ledgerwatch/erigon/turbo/snapshotsync.forEachAsync
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1768 +0xc5
erigon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by enriavil1** [comment]
can you run `--downloader.verify`

**Comment by geomad** [comment]
Thanks! after downloading snapshots and syncing for a few hours it finally worked! Think that has anything to do with --snap.stop? I was thinking to remove that after doing the full resync for erigon2-2
