### ISSUE TITLE
Panic: no gaps in tx ids are allowed

### ISSUE THREAD

**Issue by breezytm** [ledgerwatch/erigon#5301]
What could be the root cause of this issue? I am running the devel branch image. 

```
eth-node-000            | [INFO] [09-07|03:53:10.324] [2/16 Headers] Waiting for headers...    from=15488122
eth-node-000            | panic: no gaps in tx ids are allowed: block 15397000 does jump from 1717457216 to 1717457219
eth-node-000            | 
eth-node-000            | goroutine 182108 [running]:
eth-node-000            | github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs.func3.1({0x772f9fc72ac4?, 0xc0d7c8eac0?, 0x8?}, {0x772f9fc72acc?, 0x70ac6875f2c0?, 0x60?})
eth-node-000            |    github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1308 +0x314
eth-node-000            | github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).ForAmount(0x2020040?, {0x199c211?, 0x17fc93a52c996a99?}, {0xc0d7c8eac0, 0x8, 0xa}, 0x22, 0xc0d7cb6360)
eth-node-000            |    github.com/ledgerwatch/erigon-lib@v0.0.0-20220905084759-b1c6dac7321d/kv/mdbx/kv_mdbx.go:560 +0x1a8
eth-node-000            | github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs.func3({0x2020040, 0xc0d7b30660}, {0x77264744fcd8?, 0x8?, 0x1?}, {0x77264744fce0?, 0x203035?, 0x7?})
eth-node-000            |    github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1305 +0x824
eth-node-000            | github.com/ledgerwatch/erigon-lib/kv.BigChunks.func1({0x2020040, 0xc0d7b30660})
eth-node-000            |    github.com/ledgerwatch/erigon-lib@v0.0.0-20220905084759-b1c6dac7321d/kv/helpers.go:53 +0x1eb
eth-node-000            | github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).View(0xdf8475800?, {0x2011e00?, 0xc0003ac000?}, 0xc0d7cc8040)
eth-node-000            |    github.com/ledgerwatch/erigon-lib@v0.0.0-20220905084759-b1c6dac7321d/kv/mdbx/kv_mdbx.go:633 +0xbe
eth-node-000            | github.com/ledgerwatch/erigon-lib/kv.BigChunks({0x7f257b313ee0, 0xc0006858c0}, {0x199a716, 0xf}, {0xc0d7c8eae0, 0x8, 0x8}, 0xc0d7cb4340)
eth-node-000            |    github.com/ledgerwatch/erigon-lib@v0.0.0-20220905084759-b1c6dac7321d/kv/helpers.go:31 +0x192
eth-node-000            | github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs({0x2011dc8?, 0xc000cc87c0}, {0x7f257b313ee0?, 0xc0006858c0}, {0xc0d453fd60, 0x45}, {0xc000798240, 0x22}, 0xeaf088, 0xeaf470, ...)
eth-node-000            |    github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1260 +0x948
eth-node-000            | github.com/ledgerwatch/erigon/turbo/snapshotsync.dumpBlocksRange({_, _}, _, _, {_, _}, {_, _}, {0x7f257b313ee0, 0xc0006858c0}, ...)
eth-node-000            |    github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1149 +0x5c9
eth-node-000            | github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpBlocks({0x2011dc8, 0xc000cc87c0}, 0xeaf088, 0xeaf470, 0x7a120, {0xc000798240, 0x22}, {0xc000798270, 0x23}, {0x7f257b313ee0, ...}, ...)
eth-node-000            |    github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1117 +0x225
eth-node-000            | github.com/ledgerwatch/erigon/turbo/snapshotsync.retireBlocks({0x2011dc8, 0xc000cc87c0}, 0xeaf088, 0xeaf470, {0x1, 0x0, 0x0, 0x0}, {0xc000798240, 0x22}, ...)
eth-node-000            |    github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1076 +0x205
eth-node-000            | github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocks(0xc00c868bd0, {0x2011dc8, 0xc000cc87c0}, 0x2d3c1a0?, 0xc00f4ae780?, 0xcfd1c5?)
eth-node-000            |    github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1018 +0x125
eth-node-000            | github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground.func1()
eth-node-000            |    github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1060 +0x107
eth-node-000            | created by github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground
eth-node-000            |    github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1050 +0xdf
eth-node-000            | [INFO] [09-07|03:53:30.780] Build info                               git_branch=devel git_tag=v2021.10.03-1812-g488121f66-dirty git_commit=488121f669825939e494a04cc0dd840869ebf7f4

```

**Comment by AskAlexSharov** [comment]
Temporary workaround: —snap.stop

**Comment by breezytm** [comment]
That works. Thanks for the prompt response.

**Comment by banteg** [comment]
duplicate of #4788
