### ISSUE TITLE
Erigon fails to shut down on sigterm & sigint if beacon chain not answering

### ISSUE THREAD

**Issue by kaiwetlesen** [ledgerwatch/erigon#5433]
#### System information

Erigon version: 2022.09.1-alpha-4067b7c4

OS & Version: Rocky Linux 8, kernel 4.18.0-372.19.1 x64

Commit hash : 4067b7c4da6c5d741d3027d95ae2afdf6b7a943a

#### Expected behaviour

Erigon will issue a shutdown message, then perform full graceful shutdown within 20s.

#### Actual behaviour

  Erigon issues shutdown message, partially shuts down, but does not until 10 sigints or sigterms received, then prints a stack trace.

#### Steps to reproduce the behaviour

1. Start up Erigon stack with no beacon chain connected.
2. Attempt to shut down with sigint or sigterm.

#### Backtrace

````
$ /usr/bin/erigon2 --datadir=/var/lib/erigon2 --http=false --metrics --metrics.port=6060 --db.pagesize=64kb --batchSize=2GB --etl.bufferSize=4GB
INFO[09-19|18:11:20.636] Starting metrics server                  addr=http://127.0.0.1:6060/debug/metrics/prometheus
INFO[09-19|18:11:20.637] Build info                               git_branch=erigon-v2022.09.01 git_tag=v2022.09.01 git_commit=4067b7c4da6c5d741d3027d95ae2afdf6b7a943a
INFO[09-19|18:11:20.637] Starting Erigon on Ethereum mainnet... 
INFO[09-19|18:11:20.638] Maximum peer count                       ETH=100 total=100
INFO[09-19|18:11:20.638] starting HTTP APIs                       APIs=eth,erigon,engine
INFO[09-19|18:11:20.638] torrent verbosity                        level=WRN
INFO[09-19|18:11:22.741] Set global gas cap                       cap=50000000
INFO[09-19|18:11:22.793] Opening Database                         label=chaindata path=/var/lib/erigon2/chaindata
INFO[09-19|18:11:22.795] Initialised chain configuration          config="{ChainID: 1, Homestead: 1150000, DAO: 1920000, DAO Support: true, Tangerine Whistle: 2463000, Spurious Dragon: 2675000, Byzantium: 4370000, Constantinople: 7280000, Petersburg: 7280000, Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Gray Glacier: 15050000, Terminal Total Difficulty: 58750000000000000000000, Merge Netsplit: <nil>, Shanghai: <nil>, Cancun: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
INFO[09-19|18:11:22.795] Effective                                prune_flags= snapshot_flags="--snapshots=true" history.v2=false
INFO[09-19|18:11:23.542] Initialising Ethereum protocol           network=1
INFO[09-19|18:11:23.542] Disk storage enabled for ethash DAGs     dir=/var/lib/erigon2/ethash-dags count=2
INFO[09-19|18:11:24.064] Starting private RPC server              on=127.0.0.1:9090
INFO[09-19|18:11:24.065] new subscription to logs established 
INFO[09-19|18:11:24.065] rpc filters: subscribing to Erigon events 
INFO[09-19|18:11:24.065] New txs subscriber joined 
INFO[09-19|18:11:24.065] new subscription to newHeaders established 
INFO[09-19|18:11:24.065] Reading JWT secret                       path=/var/lib/erigon2/jwt.hex
INFO[09-19|18:11:24.067] HTTP endpoint opened for Engine API      url=localhost:8551 ws=true ws.compression=true
INFO[09-19|18:11:24.079] [Snapshots] Fetching torrent files metadata 
INFO[09-19|18:11:24.205] Started P2P networking                   version=66 self=enode://{client_hash}@127.0.0.1:30303 name=erigon/v2022.09.1-alpha-4067b7c4/linux-amd64/go1.19
INFO[09-19|18:11:26.934] [txpool] Started 
INFO[09-19|18:11:29.746] [Snapshots] Stat                         blocks=15451k indices=15451k alloc=2.8GB sys=3.0GB
INFO[09-19|18:11:29.747] Timings (slower than 50ms)               Headers=5.67s
INFO[09-19|18:11:29.747] RPC Daemon notified of new headers       from=15541157 to=15541158 header sending=15.571µs log sending=520ns
INFO[09-19|18:11:29.747] [1/15 Headers] Waiting for Beacon Chain... 
^CINFO[09-19|18:11:46.646] Got interrupt, shutting down... 
INFO[09-19|18:11:46.646] Exiting Engine... 
INFO[09-19|18:11:46.646] RPC server shutting down 
INFO[09-19|18:11:46.646] RPC server shutting down 
WARN[09-19|18:11:46.646] Failed to serve http endpoint            err="http: Server closed"
INFO[09-19|18:11:46.646] Engine HTTP endpoint close               url=localhost:8551
INFO[09-19|18:11:46.647] Timings (slower than 50ms)               Headers=16.898s
INFO[09-19|18:11:46.647] Tables                                   PlainState=73.6GB AccountChangeSet=162.8GB StorageChangeSet=240.8GB BlockTransaction=7.7GB TransactionLog=447.2GB FreeList=584.0KB ReclaimableSpace=584.0MB
INFO[09-19|18:11:46.647] Commit cycle                             in=9.34µs
INFO[09-19|18:11:46.647] RPC Daemon notified of new headers       from=15541157 to=15541158 header sending=4.31µs log sending=360ns
INFO[09-19|18:11:46.647] [1/15 Headers] Waiting for Beacon Chain... 
^CWARN[09-19|18:13:24.523] Already shutting down, interrupt more to panic. times=9
^CWARN[09-19|18:14:12.405] Already shutting down, interrupt more to panic. times=8
^CWARN[09-19|18:14:22.523] Already shutting down, interrupt more to panic. times=7
^CWARN[09-19|18:14:26.409] Already shutting down, interrupt more to panic. times=6
^CWARN[09-19|18:14:28.537] Already shutting down, interrupt more to panic. times=5
^CWARN[09-19|18:14:29.288] Already shutting down, interrupt more to panic. times=4
^CWARN[09-19|18:14:29.910] Already shutting down, interrupt more to panic. times=3
^CWARN[09-19|18:14:30.812] Already shutting down, interrupt more to panic. times=2
^CWARN[09-19|18:14:32.648] Already shutting down, interrupt more to panic. times=1
^Cpanic: boom

goroutine 3467 [running]:
github.com/ledgerwatch/erigon/internal/debug.LoudPanic(...)
	github.com/ledgerwatch/erigon/internal/debug/loudpanic.go:26
github.com/ledgerwatch/erigon/internal/debug.ListenSignals({0x2027be0?, 0xc0004aa080})
	github.com/ledgerwatch/erigon/internal/debug/signal.go:38 +0x34f
created by github.com/ledgerwatch/erigon/cmd/utils.StartNode
	github.com/ledgerwatch/erigon/cmd/utils/cmd.go:58 +0xaa

goroutine 1 [chan receive, 3 minutes]:
github.com/ledgerwatch/erigon/node.(*Node).Wait(...)
	github.com/ledgerwatch/erigon/node/node.go:265
github.com/ledgerwatch/erigon/turbo/node.(*ErigonNode).Serve(0xc001a07120)
	github.com/ledgerwatch/erigon/turbo/node/node.go:32 +0x7c
main.runErigon(0xc00047db80?)
	github.com/ledgerwatch/erigon/cmd/erigon/main.go:64 +0x33a
github.com/urfave/cli.HandleAction({0x16db400?, 0x1e0ff78?}, 0xc000355500?)
	github.com/urfave/cli@v1.22.9/app.go:526 +0x7f
github.com/urfave/cli.(*App).Run(0xc000355500, {0xc000040090, 0x9, 0x9})
	github.com/urfave/cli@v1.22.9/app.go:286 +0x7ca
main.main()
	github.com/ledgerwatch/erigon/cmd/erigon/main.go:35 +0x75

goroutine 6 [sleep]:
time.Sleep(0x22ecb25c00)
	runtime/time.go:195 +0x135
github.com/VictoriaMetrics/metrics.summariesSwapCron(0x45d964b800)
	github.com/VictoriaMetrics/metrics@v1.22.2/summary.go:237 +0x36
created by github.com/VictoriaMetrics/metrics.registerSummaryLocked
	github.com/VictoriaMetrics/metrics@v1.22.2/summary.go:211 +0x128

goroutine 36 [IO wait, 3 minutes]:
internal/poll.runtime_pollWait(0x7f78b506b308, 0x72)
	runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc0004aa000?, 0x4?, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc0004aa000)
	internal/poll/fd_unix.go:614 +0x234
net.(*netFD).accept(0xc0004aa000)
	net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc000012df8)
	net/tcpsock_posix.go:142 +0x28
net.(*TCPListener).Accept(0xc000012df8)
	net/tcpsock.go:288 +0x3d
net/http.(*Server).Serve(0xc0004a6000, {0x2037060, 0xc000012df8})
	net/http/server.go:3070 +0x385
net/http.(*Server).ListenAndServe(0xc0004a6000)
	net/http/server.go:2999 +0x7d
net/http.ListenAndServe(...)
	net/http/server.go:3255
github.com/ledgerwatch/erigon/metrics/exp.Setup.func2()
	github.com/ledgerwatch/erigon/metrics/exp/exp.go:26 +0x69
created by github.com/ledgerwatch/erigon/metrics/exp.Setup
	github.com/ledgerwatch/erigon/metrics/exp/exp.go:25 +0x145

goroutine 4031 [chan receive, 3 minutes]:
github.com/ledgerwatch/erigon-lib/direct.(*SubscribeLogsStreamS).Recv(0xc0033ac410?)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220902083702-215695f9392d/direct/eth_backend_client.go:154 +0x2b
github.com/ledgerwatch/erigon/ethdb/privateapi.(*LogsFilterAggregator).subscribeLogs(0xc0033ac410, {0x2044a58, 0xc006c30570})
	github.com/ledgerwatch/erigon/ethdb/privateapi/logsfilter.go:131 +0xbc
github.com/ledgerwatch/erigon/ethdb/privateapi.(*EthBackendServer).SubscribeLogs(0x0?, {0x2044a58?, 0xc006c30570?})
	github.com/ledgerwatch/erigon/ethdb/privateapi/ethbackend.go:677 +0x2c
github.com/ledgerwatch/erigon-lib/direct.(*EthBackendClientDirect).SubscribeLogs.func1()
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220902083702-215695f9392d/direct/eth_backend_client.go:121 +0x9b
created by github.com/ledgerwatch/erigon-lib/direct.(*EthBackendClientDirect).SubscribeLogs
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220902083702-215695f9392d/direct/eth_backend_client.go:118 +0x15b

goroutine 3460 [chan receive]:
github.com/ledgerwatch/erigon/metrics.(*meterArbiter).tick(0x2f849a0)
	github.com/ledgerwatch/erigon/metrics/meter.go:230 +0x87
created by github.com/ledgerwatch/erigon/metrics.NewMeterForced
	github.com/ledgerwatch/erigon/metrics/meter.go:34 +0xc5

goroutine 3439 [sleep]:
time.Sleep(0x6fc23ac00)
	runtime/time.go:195 +0x135
github.com/ledgerwatch/erigon/cmd/downloader/downloader.MainLoop.func1()
	github.com/ledgerwatch/erigon/cmd/downloader/downloader/downloader.go:355 +0x4d
created by github.com/ledgerwatch/erigon/cmd/downloader/downloader.MainLoop
	github.com/ledgerwatch/erigon/cmd/downloader/downloader/downloader.go:333 +0x11e

goroutine 4064 [IO wait]:
internal/poll.runtime_pollWait(0x7f788473c270, 0x72)
	runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc0030e0380?, 0xc000012108?, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc0030e0380)
	internal/poll/fd_unix.go:614 +0x234
net.(*netFD).accept(0xc0030e0380)
	net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc0018fd398)
	net/tcpsock_posix.go:142 +0x28
net.(*TCPListener).Accept(0xc0018fd398)
	net/tcpsock.go:288 +0x3d
github.com/ledgerwatch/erigon/p2p.(*Server).listenLoop(0xc000241b80, {0x2039128, 0xc0016ecb80})
	github.com/ledgerwatch/erigon/p2p/server.go:892 +0x753
github.com/ledgerwatch/erigon/p2p.(*Server).setupListening.func2()
	github.com/ledgerwatch/erigon/p2p/server.go:721 +0x74
created by github.com/ledgerwatch/erigon/p2p.(*Server).setupListening
	github.com/ledgerwatch/erigon/p2p/server.go:718 +0x27a

goroutine 4078 [chan receive, 3 minutes]:
github.com/ledgerwatch/erigon-lib/direct.(*SubscribeLogsStreamC).Recv(0xc004ae65c8?)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220902083702-215695f9392d/direct/eth_backend_client.go:181 +0x2b
github.com/ledgerwatch/erigon/cmd/rpcdaemon/rpcservices.(*RemoteBackend).SubscribeLogs(0xc0033ad1d0, {0x2039128, 0xc0004ae440}, 0xc0004a8890, 0xd2044b?)
	github.com/ledgerwatch/erigon/cmd/rpcdaemon/rpcservices/eth_backend.go:156 +0x1e2
github.com/ledgerwatch/erigon/turbo/rpchelper.New.func2()
	github.com/ledgerwatch/erigon/turbo/rpchelper/filters.go:108 +0xef
created by github.com/ledgerwatch/erigon/turbo/rpchelper.New
	github.com/ledgerwatch/erigon/turbo/rpchelper/filters.go:98 +0x3d9

goroutine 3466 [chan send, 3 minutes, locked to thread]:
github.com/ledgerwatch/erigon/eth/stagedsync.handleInterrupt(_, {{0x2043200, 0xc000267130}, 0xc009c6eb40, 0xc0001f00c0, {{0xc000458a58, 0x7}, 0xc0002b46e0, {0xc000458a68, 0x6}, ...}, ...}, ...)
	github.com/ledgerwatch/erigon/eth/stagedsync/stage_headers.go:729 +0xf9
github.com/ledgerwatch/erigon/eth/stagedsync.HeadersPOS(_, {_, _}, {_, _}, {_, _}, {{0x2043200, 0xc000267130}, 0xc009c6eb40, ...}, ...)
	github.com/ledgerwatch/erigon/eth/stagedsync/stage_headers.go:195 +0x3de
github.com/ledgerwatch/erigon/eth/stagedsync.SpawnStageHeaders(_, {_, _}, {_, _}, {_, _}, {{0x2043200, 0xc000267130}, 0xc009c6eb40, ...}, ...)
	github.com/ledgerwatch/erigon/eth/stagedsync/stage_headers.go:163 +0x44a
github.com/ledgerwatch/erigon/eth/stagedsync.DefaultStages.func1(0x10?, 0xe2?, 0x19aaa1a?, {0x2027b80?, 0xc00152e210?}, {0x20554d0?, 0xc0bcf48930?})
	github.com/ledgerwatch/erigon/eth/stagedsync/default_stages.go:20 +0xb5
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc00152e210, 0xc0033ac460, {0x2043200?, 0xc000267130}, {0x20554d0?, 0xc0bcf48930}, 0xa0?, 0x9a?)
	github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:352 +0x150
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc00152e210, {0x2043200?, 0xc000267130}, {0x20554d0, 0xc0bcf48930}, 0xf0?)
	github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:255 +0x265
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x2039128, 0xc0004ae440}, {0x2043200?, 0xc000267130?}, 0xc00152e210, 0x0, 0xc0016d4f00, 0x0, 0xc003900b30, 0x0)
	github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:163 +0x44c
github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x2039128, 0xc0004ae440}, {0x2043200?, 0xc000267130}, 0x1000001?, 0x0?, 0x0?, 0xc000f04330?, 0x0?, 0x0)
	github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:84 +0x145
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
	github.com/ledgerwatch/erigon/eth/backend.go:883 +0x1e5

goroutine 3469 [syscall]:
os/signal.signal_recv()
	runtime/sigqueue.go:152 +0x2f
os/signal.loop()
	os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2a

goroutine 15255 [chan receive, 3 minutes]:
github.com/ledgerwatch/erigon/eth.(*Ethereum).Stop(0xc0004b0180)
	github.com/ledgerwatch/erigon/eth/backend.go:911 +0x1a5
github.com/ledgerwatch/erigon/node.(*Node).stopServices(0xc0b8c0ff30?, {0xc001a07110, 0x1, 0x7137b2393060?})
	github.com/ledgerwatch/erigon/node/node.go:219 +0xb2
github.com/ledgerwatch/erigon/node.(*Node).Close(0xc0004aa080)
	github.com/ledgerwatch/erigon/node/node.go:162 +0x18b
created by github.com/ledgerwatch/erigon/internal/debug.ListenSignals
	github.com/ledgerwatch/erigon/internal/debug/signal.go:29 +0x26a
$ 
````

**Comment by alysak6075** [comment]
Same here. The force shutdown corrupted the DB to a point that none of the usual tricks work. Resyncing now

**Comment by mandrigin** [comment]
try 2022.09.02

**Comment by alysak6075** [comment]
Will do after resync. Thanks

**Comment by megalepozy** [comment]
Just add this issue myself, I made a pastebin with the log if anyone is interested (erigon version 2.55.1)
[https://pastebin.com/xbRjCTTv](https://pastebin.com/xbRjCTTv)

**Comment by megalepozy** [comment]
Just restarted the process and I had to re-do only 8k blocks, so all good :)
