### ISSUE TITLE
Finished unwinding with panic

### ISSUE THREAD

**Issue by DaraDoyoung** [ledgerwatch/erigon#5651]
#### System information

Erigon version: `erigon version 2022.10.1-dev-d566d4af`

OS & Version: Ubuntu 22.04 LTS

I unwinded my erigon node with this scirpt:
`build/bin/integration state_stages --unwind=10 --datadir ~/data --chain mainnet`
but got error and ended with panic.

````
INFO[10-07|02:20:59.005] [Snapshot Txs] Replacement preprocessing processed=87.15% ch=0
INFO[10-07|02:21:14.678] [14/16 TxLookup Prune] ETL [1/2] Extracting from=CanonicalHeader block=15563320 alloc=4.6GB sys=6.5GB
INFO[10-07|02:21:29.008] [Snapshot Txs] Replacement preprocessing processed=99.00% ch=0
INFO[10-07|02:21:32.046] [Snapshot Txs] Replacement preprocessing took=4m2.937666862s
INFO[10-07|02:21:32.051] [Snapshot Txs] Effective dictionary      patternList.Len=7150 patternsSize=248.0KB 5=191 6=154 7=119 8=168 9=134 10=118 11=127 12=113 13=261 14=341 15=230 16=152 17=147 18=86 19=87 20=848 32=1713 64=2152 128=9
INFO[10-07|02:21:32.062] [Snapshot Txs] Positional dictionary     positionList.len=9480 posSize=30.3KB
INFO[10-07|02:21:35.568] [Snapshot Txs] Compress                  took=4m6.565225789s ratio=1.90 file=v1-015460-015470-transactions.seg
INFO[10-07|02:21:35.568] [snapshots] Compression                  ratio=1.90 file=v1-015460-015470-transactions
INFO[10-07|02:21:43.956] [index] calculating                      file=v1-015460-015470-transactions.idx
INFO[10-07|02:21:44.659] [14/16 TxLookup Prune] ETL [1/2] Extracting from=CanonicalHeader block=15565634 alloc=4.4GB sys=6.5GB
INFO[10-07|02:21:55.128] [index] write                            file=v1-015460-015470-transactions.idx
INFO[10-07|02:22:06.511] [Snapshots] Blocks Stat                  blocks=15470k indices=15470k alloc=5.4GB sys=6.5GB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdf2222]

goroutine 24 [running]:
github.com/ledgerwatch/erigon/turbo/shards.(*Events).OnNewSnapshot(0x0)
	github.com/ledgerwatch/erigon/turbo/shards/events.go:108 +0x42
github.com/ledgerwatch/erigon/turbo/snapshotsync.retireBlocks({0x1be7e20, 0xc000044078}, 0xebe6a0, 0xec0db0, {0x1, 0x0, 0x0, 0x0}, {0xc0021e0bc0, 0x1a}, ...)
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1149 +0x2e4
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocks(0xc0004e9380, {0x1be7e20, 0xc000044078}, 0x0?, 0x0?, 0x0?)
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1085 +0x125
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground.func1()
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1125 +0xc7
created by github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1117 +0xd6
````

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/5656

**Comment by revitteth** [comment]
Closing as fixed.
