### ISSUE TITLE
rpcdaemon panic: mkdir : no such file or directory

### ISSUE THREAD

**Issue by beejiujitsu** [ledgerwatch/erigon#5663]
#### System information

Erigon version: https://github.com/ledgerwatch/erigon/releases/tag/v2.27.0

OS & Version: Google Kubernetes Engine running 

Commit hash : 6d8b304eae78cef7aa3f3eb7ed584559bdfe7dbb

#### Expected behaviour

rpcdaemon successfully starts and serves traffic.

#### Actual behaviour

rpcdaemon Pod crashes with the following output:

```
[INFO] [10-07|14:56:08.769] Starting metrics server                  addr=http://0.0.0.0:6060/debug/metrics/prometheus
│ [INFO] [10-07|14:56:08.769] Starting pprof server                    cpu="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/profile?seconds=20" heap="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/heap"
│ panic: mkdir : no such file or directory
```

#### Steps to reproduce the behaviour

1. Update thorax/erigon image tag from v2022.10.01 to v2.27.0
2. Redeploy rpcdaemon with new tag

#### Backtrace

````
│ goroutine 1 [running]:
│ github.com/ledgerwatch/erigon-lib/common/dir.MustExist(...)
│     github.com/ledgerwatch/erigon-lib@v0.0.0-20221006052028-22049904649b/common/dir/rw_dir.go:11
│ github.com/ledgerwatch/erigon/cmd/rpcdaemon/cli.RemoteServices({_, _}, {0x1, {0x7ffc67770bc1, 0x10}, 0x0, {0x0, 0x0}, {{0x0, 0x0}, ...}, ...}, ...)
│     github.com/ledgerwatch/erigon/cmd/rpcdaemon/cli/config.go:250 +0x228b
│ main.main.func1(0x263d2e0?, {0x1712e3c?, 0x16?, 0x17?})
│     github.com/ledgerwatch/erigon/cmd/rpcdaemon/main.go:19 +0xf6
│ github.com/spf13/cobra.(*Command).execute(0x263d2e0, {0xc000040190, 0x16, 0x17})
│     github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
│ github.com/spf13/cobra.(*Command).ExecuteC(0x263d2e0)
│     github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
│ github.com/spf13/cobra.(*Command).Execute(...)
│     github.com/spf13/cobra@v1.5.0/command.go:918
│ github.com/spf13/cobra.(*Command).ExecuteContext(...)
│     github.com/spf13/cobra@v1.5.0/command.go:911
│ main.main()
│     github.com/ledgerwatch/erigon/cmd/rpcdaemon/main.go:38 +0xfe
│ Stream closed EOF for int/rpcdaemon-d6fb6878b-5d8nq (rpcdaemon)
````
#### Additional details

Reverting the version used allows rpcdaemon to successfully start.

**Comment by AlexeyAkhunov** [comment]
Will be fixed here, thank you: https://github.com/ledgerwatch/erigon/pull/5686

**Comment by revitteth** [comment]
Should be fixed, closing.
