### ISSUE TITLE
runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by beejiujitsu** [ledgerwatch/erigon#5815]
#### System information

Erigon version: `./erigon --version` 

```
<<K9s-Shell>> Pod: int/erigon-1 | Container: erigon
/ $ erigon --version
erigon version 2.28.1-stable-9711af6d
/ $
```

OS & Version: Windows/Linux/OSX

Linux

Commit hash : 

#### Expected behaviour

Erigon proceeds past stage 2/16.

#### Actual behaviour

```
erigon {"err":"runtime error: slice bounds out of range [:-1], snapshot: 15000000-15500000, trace: [block_reader.go:509 panic.go:884 panic.go:139 decompress.go:535 block_reader.go:524 block_reader.go:281 block_snapshots
│ .go:268 block_reader.go:275 stage_headers.go:481 stage_headers.go:207 stage_headers.go:140 default_stages.go:36 sync.go:345 sync.go:255 stageloop.go:173 stageloop.go:93 asm_amd64.s:1594], trace: [stageloop.go:139 panic.
│ go:890 block_reader.go:509 panic.go:884 panic.go:139 decompress.go:535 block_reader.go:524 block_reader.go:281 block_snapshots.go:268 block_reader.go:275 stage_headers.go:481 stage_headers.go:207 stage_headers.go:140 de
│ fault_stages.go:36 sync.go:345 sync.go:255 stageloop.go:173 stageloop.go:93 asm_amd64.s:1594]","lvl":"eror","msg":"Staged Sync","t":"2022-10-20T18:29:46.7628831Z"}
```

#### Steps to reproduce the behaviour

Not reproducible; only happening on one of five erigon archive nodes.

All five archive nodes are configured with the same flags, env vars, etc.

#### Backtrace

````
trace: [block_reader.go:509 panic.go:884 panic.go:139 decompress.go:535 block_reader.go:524 block_reader.go:281 block_snapshots
│ .go:268 block_reader.go:275 stage_headers.go:481 stage_headers.go:207 stage_headers.go:140 default_stages.go:36 sync.go:345 sync.go:255 stageloop.go:173 stageloop.go:93 asm_amd64.s:1594], trace: [stageloop.go:139 panic.
│ go:890 block_reader.go:509 panic.go:884 panic.go:139 decompress.go:535 block_reader.go:524 block_reader.go:281 block_snapshots.go:268 block_reader.go:275 stage_headers.go:481 stage_headers.go:207 stage_headers.go:140 de
│ fault_stages.go:36 sync.go:345 sync.go:255 stageloop.go:173 stageloop.go:93 asm_amd64.s:1594]"
````

**Comment by beejiujitsu** [comment]
Related troubleshooting thread: https://discord.com/channels/687972960811745322/738982866670714901/1031568427086774385

**Comment by beejiujitsu** [comment]
Error with context:

```
│ erigon {"lvl":"info","msg":"[2/16 Headers] Waiting for Consensus Layer...","t":"2022-10-20T18:34:07.481058324Z"}
│ erigon {"hash":"0xe88882dec4c9293a72181d99ecfd8e2807298e438ec1475c0d7a12b4bba1a0a4","height":15770646,"lvl":"info","msg":"[2/16 Headers] Handling new payload","t":"2022-10-20T18:34:07.481154925Z"}
│ erigon {"err":"runtime error: slice bounds out of range [:-1], snapshot: 15000000-15500000, trace: [block_reader.go:509 panic.go:884 panic.go:139 decompress.go:535 block_reader.go:524 block_reader.go:281 block_snapshots
│ .go:268 block_reader.go:275 stage_headers.go:481 stage_headers.go:207 stage_headers.go:140 default_stages.go:36 sync.go:345 sync.go:255 stageloop.go:173 stageloop.go:93 asm_amd64.s:1594], trace: [stageloop.go:139 panic.
│ go:890 block_reader.go:509 panic.go:884 panic.go:139 decompress.go:535 block_reader.go:524 block_reader.go:281 block_snapshots.go:268 block_reader.go:275 stage_headers.go:481 stage_headers.go:207 stage_headers.go:140 de
│ fault_stages.go:36 sync.go:345 sync.go:255 stageloop.go:173 stageloop.go:93 asm_amd64.s:1594]","lvl":"eror","msg":"Staged Sync","t":"2022-10-20T18:34:07.481428022Z"}
```

**Comment by beejiujitsu** [comment]
Now I'm seeing the error on another erigon instance, erigon-1, after restarting it.

Error with context:

```
erigon-1 erigon {"lvl":"info","msg":"[2/16 Headers] Waiting for Consensus Layer...","t":"2022-10-20T19:47:09.820258462Z"}
erigon-1 erigon {"hash":"0x92b07cb513b4b35af79052761162ad2d230935185a23b1e997853ad6b86b7899","height":15771349,"lvl":"info","msg":"[2/16 Headers] Handling new payload","t":"2022-10-20T19:47:09.820354342Z"}
erigon-1 erigon {"err":"runtime error: slice bounds out of range [641:401], snapshot: 15000000-15500000, trace: [block_reader.go:509 panic.go:884 panic.go:153 decompress.go:541 block_reader.go:524 block_reader.go:281 block_snapshots.go:268 block_reader.go:275 stage_headers.go:481 stage_headers.go:207 stage_headers.go:140 default_stages.go:36 sync.go:345 sync.go:255 stageloop.go:173 stageloop.go:93 asm_amd64.s:1594], trace: [stageloop.go:139 panic.go:890 block_reader.go:509 panic.go:884 panic.go:153 decompress.go:541 block_reader.go:524 block_reader.go:281 block_snapshots.go:268 block_reader.go:275 stage_headers.go:481 stage_headers.go:207 stage_headers.go:140 default_stages.go:36 sync.go:345 sync.go:255 stageloop.go:173 stageloop.go:93 asm_amd64.s:1594]","lvl":"eror","msg":"Staged Sync","t":"2022-10-20T19:47:09.820589335Z"}
erigon-1 erigon {"lvl":"info","msg":"[2/16 Headers] Waiting for Consensus Layer...","t":"2022-10-20T19:47:10.809075216Z"}
```

**Comment by AskAlexSharov** [comment]
Try: 
- stop erigon 
- remove `v1-015000-015500-*` files from <your_datadir>/snapshots folder
- Remove <datadir>/snapshots/db 
- do `./build/bin/integration stage_headers --reset`
- start erigon as usually with --snap.stop flag 
- in future, when you update erigon verison - can remove --snap.stop flag

**Comment by beejiujitsu** [comment]
Thanks @AskAlexSharov, I'll give that a try.

**Comment by beejiujitsu** [comment]
I ran your steps on the broken archive node, erigon-1.

The `stage_headers --reset` step ended with:

```
erigon-1 sre-25-stage-headers-reset [INFO] [10-21|16:18:10.498] [fillind_db_from_snapshots] Total difficulty index: 15261k/15635k
erigon-3 erigon {"alloc":"2.6GB","baseFee":26406,"block":15698999,"lvl":"info","msg":"[txpool] stat","pending":9188,"queued":30000,"sys":"5.0GB","t":"2022-10-21T16:18:14.829325729Z"}
erigon-2 erigon {"alloc":"2.5GB","block_num":15692514,"lvl":"info","msg":"[5/16 Bodies] Writing block bodies","remaining":90516,"sys":"5.8GB","t":"2022-10-21T16:18:16.598487924Z"}
erigon-1 sre-25-stage-headers-reset panic: runtime error: slice bounds out of range [36:11]
erigon-1 sre-25-stage-headers-reset
erigon-1 sre-25-stage-headers-reset goroutine 1 [running]:
erigon-1 sre-25-stage-headers-reset github.com/ledgerwatch/erigon-lib/compress.(*Getter).Next(0xc0adcf9368, {0xc06dd36000, 0x0, 0x2000})
erigon-1 sre-25-stage-headers-reset     github.com/ledgerwatch/erigon-lib@v0.0.0-20221015011442-b896e9470d90/compress/decompress.go:541 +0x4b0
erigon-1 sre-25-stage-headers-reset github.com/ledgerwatch/erigon/turbo/snapshotsync.ForEachHeader.func1.1()
erigon-1 sre-25-stage-headers-reset     github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1882 +0x11e
erigon-1 sre-25-stage-headers-reset github.com/ledgerwatch/erigon-lib/compress.(*Decompressor).WithReadAhead(0xc00446f380, 0xc0adcf9468)
erigon-1 sre-25-stage-headers-reset     github.com/ledgerwatch/erigon-lib@v0.0.0-20221015011442-b896e9470d90/compress/decompress.go:366 +0xa2
erigon-1 sre-25-stage-headers-reset github.com/ledgerwatch/erigon/turbo/snapshotsync.ForEachHeader.func1({0xc004a71e00, 0x29, 0x0?})
erigon-1 sre-25-stage-headers-reset     github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1879 +0xc5
erigon-1 sre-25-stage-headers-reset github.com/ledgerwatch/erigon/turbo/snapshotsync.(*headerSegments).View(0x7fef83a1f108?, 0x20?)
erigon-1 sre-25-stage-headers-reset     github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:268 +0xa3
erigon-1 sre-25-stage-headers-reset github.com/ledgerwatch/erigon/turbo/snapshotsync.ForEachHeader({0xc03ad0d780?, 0x0?}, 0xc000407440, 0xc077da97f8)
erigon-1 sre-25-stage-headers-reset     github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1877 +0xc8
erigon-1 sre-25-stage-headers-reset github.com/ledgerwatch/erigon/eth/stagedsync.FillDBFromSnapshots({0x15eb73e, 0x19}, {0x1c1fda0, 0xc00012e000}, {0x1c36ef0?, 0xc03acec720?}, {0xc0006d2510, 0x25}, 0xc000407440, {0x77ac22719a98, ...})
erigon-1 sre-25-stage-headers-reset     github.com/ledgerwatch/erigon/eth/stagedsync/stage_snapshots.go:203 +0x70d
erigon-1 sre-25-stage-headers-reset github.com/ledgerwatch/erigon/core/rawdb/rawdbreset.ResetBlocks({0x1c36ef0?, 0xc03acec720}, {0x7fef5acdeb78?, 0xc000277290}, 0xc000407440, {0x77ac22719a98, 0xc000128038}, {0xc0006d2510, 0x25})
erigon-1 sre-25-stage-headers-reset     github.com/ledgerwatch/erigon/core/rawdb/rawdbreset/reset_stages.go:115 +0x5e5
erigon-1 sre-25-stage-headers-reset github.com/ledgerwatch/erigon/cmd/integration/commands.stageHeaders.func1({0x1c36ef0?, 0xc03acec720})
erigon-1 sre-25-stage-headers-reset     github.com/ledgerwatch/erigon/cmd/integration/commands/stages.go:493 +0x1cf
erigon-1 sre-25-stage-headers-reset github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).Update(0x7fef5acdeb78?, {0x1c1fd68?, 0xc00070e640?}, 0xc03a70db40)
erigon-1 sre-25-stage-headers-reset     github.com/ledgerwatch/erigon-lib@v0.0.0-20221015011442-b896e9470d90/kv/mdbx/kv_mdbx.go:659 +0xbd
erigon-1 sre-25-stage-headers-reset github.com/ledgerwatch/erigon/cmd/integration/commands.stageHeaders({0x1c27bc0?, 0xc000277290}, {0x1c1fd68?, 0xc00070e640})
erigon-1 sre-25-stage-headers-reset     github.com/ledgerwatch/erigon/cmd/integration/commands/stages.go:486 +0x13a
erigon-1 sre-25-stage-headers-reset github.com/ledgerwatch/erigon/cmd/integration/commands.glob..func9(0x25632c0?, {0x15c83a6?, 0x5?, 0x5?})
erigon-1 sre-25-stage-headers-reset     github.com/ledgerwatch/erigon/cmd/integration/commands/stages.go:73 +0x14c
erigon-1 sre-25-stage-headers-reset github.com/spf13/cobra.(*Command).execute(0x25632c0, {0xc00013e4b0, 0x5, 0x5})
erigon-1 sre-25-stage-headers-reset     github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
erigon-1 sre-25-stage-headers-reset github.com/spf13/cobra.(*Command).ExecuteC(0x2565ac0)
erigon-1 sre-25-stage-headers-reset     github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
erigon-1 sre-25-stage-headers-reset github.com/spf13/cobra.(*Command).Execute(...)
erigon-1 sre-25-stage-headers-reset     github.com/spf13/cobra@v1.5.0/command.go:918
erigon-1 sre-25-stage-headers-reset github.com/spf13/cobra.(*Command).ExecuteContext(...)
erigon-1 sre-25-stage-headers-reset     github.com/spf13/cobra@v1.5.0/command.go:911
erigon-1 sre-25-stage-headers-reset main.main()
erigon-1 sre-25-stage-headers-reset     github.com/ledgerwatch/erigon/cmd/integration/main.go:15 +0x11b
```

Due to the nature the system I'm using (kubernetes), the process terminated and restarted:

```
k logs erigon-1 -c sre-25-stage-headers-reset
[INFO] [10-21|16:18:26.240] [Snapshots] Blocks Stat                  blocks=15636k indices=15636k alloc=2.3GB sys=2.4GB
[INFO] [10-21|16:18:46.242] TruncateBlocks                           block=15667379
[INFO] [10-21|16:19:06.241] TruncateBlocks                           block=15605533
[INFO] [10-21|16:19:26.242] TruncateBlocks                           block=15543809
[INFO] [10-21|16:19:46.242] TruncateBlocks                           block=15486050
[INFO] [10-21|16:20:06.241] TruncateBlocks                           block=15427388
[INFO] [10-21|16:20:26.241] TruncateBlocks                           block=15370376
[INFO] [10-21|16:20:46.242] TruncateBlocks                           block=15312051
```


Here are the initContainer commands used prior to starting erigon pulled from `k get pod erigon-1 -o jsonpath='{.spec.initContainers}' | jq -C '.[].command[]' -r | grep -ve '^sh$' -e '^-c$' | grep -v chown`:

```
find /home/erigon/.local/share/erigon/snapshots -type f -name 'snapshots/v1-015000-015500-*' -delete
rm -rf /home/erigon/.local/share/erigon/snapshots/db
integration stage_headers --reset --datadir /home/erigon/.local/share/erigon --chain mainnet
```

**Comment by beejiujitsu** [comment]
It appears https://github.com/ledgerwatch/erigon/commit/af46c3c069f4b7213f34f6599be75431bdd2717e , which pulls in https://github.com/ledgerwatch/erigon-lib/pull/690 ,  would fix this bug. Is that correct? If so, do I need to wait for a newer version to be released before trying that to fix this bug?

**Comment by beejiujitsu** [comment]
I just realized my find command has a bad name; I included the `snapshots` path.

Will fix and try again.

**Comment by AskAlexSharov** [comment]
`ls snapshots | grep v1-015`

**Comment by beejiujitsu** [comment]
There are a lot:


```
v1-015633-015634-transactions.idx
v1-015633-015634-transactions.seg
v1-015634-015635-bodies.idx
v1-015634-015635-bodies.seg
v1-015634-015635-headers.idx
v1-015634-015635-headers.seg
v1-015634-015635-transactions-to-block.idx
v1-015634-015635-transactions.idx
v1-015634-015635-transactions.seg
v1-015635-015636-bodies.idx
v1-015635-015636-bodies.seg
v1-015635-015636-headers.idx
v1-015635-015636-headers.seg
v1-015635-015636-transactions-to-block.idx
v1-015635-015636-transactions.idx
v1-015635-015636-transactions.seg
~/.local/share/erigon $ ls snapshots | grep v1-015 -c
70
~/.local/share/erigon $
```

**Comment by beejiujitsu** [comment]
re: https://discord.com/channels/687972960811745322/1030873853783719946/1033225974009057361

Per your Discord reply, I am removing all torrent files and all db files under snapshots.

**Comment by AskAlexSharov** [comment]
We understand better the problem now, and seems right solution is to remove `v1-015000-015500-*.idx` files only

**Comment by beejiujitsu** [comment]
Thanks @AskAlexSharov. 

Does that seem like something that should be codified into erigon's snapshot process?

That is, does it seem reasonable to ignore the index on error and refetch/generate it? That seems like a good self-healing property to have.

**Comment by AskAlexSharov** [comment]
> Thanks @AskAlexSharov.
> 
> Does that seem like something that should be codified into erigon's snapshot process?
> 
> That is, does it seem reasonable to ignore the index on error and refetch/generate it? That seems like a good self-healing property to have.

No magic: to generate snapshot you need old data, erigon db doesn’t have it - because it storing such data in snapshot. So, need download it, store it, and maybe even re-execute that old blocks. All this is expensive, slow and hiding real error - if you got this error once, you can get it again after snapshot re-creation. Also Erigon can’t distinguish “broken index” vs “broken snapshot” errors. 

Also It’s broken not because it’s “somehow broken” - but because Erigon has a bug which need to fix.

**Comment by beejiujitsu** [comment]
got it, thanks

**Comment by beejiujitsu** [comment]
Error is gone and has not resurfaced, so closing issue.

Thank you for your help, @AskAlexSharov.

**Comment by AskAlexSharov** [comment]
@savhappy as a workaround reduce GOMAXPROCS
