### ISSUE TITLE
The program panic if --downloader.verify is added

### ISSUE THREAD

**Issue by du5** [ledgerwatch/erigon#5823]
#### System information

Erigon version: `erigon version 2.28.1-stable-9711af6d`

OS & Version: Linux

Commit hash : 9711af6d

````
root@Ubuntu-2204-jammy-amd64-base ~ # erigon --chain=bsc --port=30411 --http.api=eth,web3,net --v5disc --torrent.upload.rate=32mb --torrent.download.rate=25000mb  --db.pagesize=16k --prune= --prune.r.before=16000000 --prune.h.older=5000 --prune.t.older=5000 --prune.c.older=5000 --verbosity 3 --downloader.verify
INFO[10-21|23:26:50.700] Build info                               git_branch=HEAD git_tag=v2.28.1 git_commit=9711af6ddf01f1eb96c9dfb7bf33c5d69e6f648a
INFO[10-21|23:26:50.700] Starting Erigon on BSC mainnet... 
INFO[10-21|23:26:50.704] Maximum peer count                       ETH=100 total=100
INFO[10-21|23:26:50.704] starting HTTP APIs                       APIs=eth,web3,net
INFO[10-21|23:26:50.704] torrent verbosity                        level=WRN
INFO[10-21|23:26:52.807] Set global gas cap                       cap=50000000
INFO[10-21|23:26:52.815] Opening Database                         label=chaindata path=/root/.local/share/erigon/chaindata
INFO[10-21|23:26:52.817] Initialised chain configuration          config="{ChainID: 56 Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Euler: 18907621, Gibbs: <nil>, Nano: 21962149, Moran: 22107423, Engine: parlia}" genesis=0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b
INFO[10-21|23:26:52.817] Effective                                prune_flags="--prune.h.older=5000 --prune.r.before=16000000 --prune.t.older=5000 --prune.c.older=5000" snapshot_flags="--snapshots=true" history.v3=false
INFO[10-21|23:26:53.895] Initialising Ethereum protocol           network=56
INFO[10-21|23:26:54.287] Starting private RPC server              on=127.0.0.1:9090
INFO[10-21|23:26:54.287] new subscription to logs established 
INFO[10-21|23:26:54.287] rpc filters: subscribing to Erigon events 
INFO[10-21|23:26:54.288] New txs subscriber joined 
INFO[10-21|23:26:54.288] new subscription to newHeaders established 
INFO[10-21|23:26:54.288] Reading JWT secret                       path=/root/.local/share/erigon/jwt.hex
INFO[10-21|23:26:54.288] HTTP endpoint opened for Engine API      url=localhost:8551 ws=true ws.compression=true
INFO[10-21|23:26:54.288] HTTP endpoint opened                     url=localhost:8545 ws=false ws.compression=true grpc=false
INFO[10-21|23:26:54.302] [1/16 Snapshots] Fetching torrent files metadata 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13932f6]

goroutine 4913 [running]:
github.com/anacrolix/torrent/metainfo.(*Info).NumPieces(...)
        github.com/anacrolix/torrent@v1.47.0/metainfo/info.go:134
github.com/anacrolix/torrent.(*Torrent).numPieces(...)
        github.com/anacrolix/torrent@v1.47.0/torrent.go:857
github.com/anacrolix/torrent.(*Torrent).NumPieces(...)
        github.com/anacrolix/torrent@v1.47.0/t.go:84
github.com/ledgerwatch/erigon/cmd/downloader/downloader.(*Downloader).verify.func1(0xc00d0a0000)
        github.com/ledgerwatch/erigon/cmd/downloader/downloader/downloader.go:206 +0xb6
created by github.com/ledgerwatch/erigon/cmd/downloader/downloader.(*Downloader).verify
        github.com/ledgerwatch/erigon/cmd/downloader/downloader/downloader.go:204 +0x17c

````

**Comment by du5** [comment]
start without --downloader.verify

```
root@Ubuntu-2204-jammy-amd64-base ~ # erigon --chain=bsc --port=30411 --http.api=eth,web3,net --v5disc --torrent.upload.rate=32mb --torrent.download.rate=25000mb  --db.pagesize=16k --prune= --prune.r.before=16000000 --prune.h.older=5000 --prune.t.older=5000 --prune.c.older=5000 --verbosity 3 
INFO[10-21|23:31:57.756] Build info                               git_branch=HEAD git_tag=v2.28.1 git_commit=9711af6ddf01f1eb96c9dfb7bf33c5d69e6f648a
INFO[10-21|23:31:57.757] Starting Erigon on BSC mainnet... 
INFO[10-21|23:31:57.761] Maximum peer count                       ETH=100 total=100
INFO[10-21|23:31:57.762] starting HTTP APIs                       APIs=eth,web3,net
INFO[10-21|23:31:57.762] torrent verbosity                        level=WRN
INFO[10-21|23:31:59.864] Set global gas cap                       cap=50000000
INFO[10-21|23:31:59.872] Opening Database                         label=chaindata path=/root/.local/share/erigon/chaindata
INFO[10-21|23:31:59.874] Initialised chain configuration          config="{ChainID: 56 Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Euler: 18907621, Gibbs: <nil>, Nano: 21962149, Moran: 22107423, Engine: parlia}" genesis=0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b
INFO[10-21|23:31:59.874] Effective                                prune_flags="--prune.h.older=5000 --prune.r.before=16000000 --prune.t.older=5000 --prune.c.older=5000" snapshot_flags="--snapshots=true" history.v3=false
INFO[10-21|23:32:00.916] Initialising Ethereum protocol           network=56
INFO[10-21|23:32:01.323] Starting private RPC server              on=127.0.0.1:9090
INFO[10-21|23:32:01.323] new subscription to logs established
INFO[10-21|23:32:01.323] rpc filters: subscribing to Erigon events
INFO[10-21|23:32:01.323] new subscription to newHeaders established
INFO[10-21|23:32:01.323] New txs subscriber joined
INFO[10-21|23:32:01.323] Reading JWT secret                       path=/root/.local/share/erigon/jwt.hex
INFO[10-21|23:32:01.323] Generated JWT secret                     path=/root/.local/share/erigon/jwt.hex
INFO[10-21|23:32:01.324] HTTP endpoint opened for Engine API      url=localhost:8551 ws=true ws.compression=true
INFO[10-21|23:32:01.324] HTTP endpoint opened                     url=localhost:8545 ws=false ws.compression=true grpc=false
INFO[10-21|23:32:01.337] [1/16 Snapshots] Fetching torrent files metadata
INFO[10-21|23:32:01.351] Started P2P networking                   version=66 self=enode://4cfa5b242af23caa5876af9ab87055fadd9231b89dc62c958467012d8031d2d439c6e0aec1eb92c858657b4ddbabdb1dc5102886e0386de9fc05b0f81a3ef307@127.0.0.1:30411 name=erigon/v2.28.1-stable-9711af6d/linux-amd64/go1.18.1
INFO[10-21|23:32:01.664] [txpool] Started
INFO[10-21|23:32:04.955] [Snapshots] Blocks Stat                  blocks=20500k indices=20500k alloc=2.7GB sys=2.8GB
INFO[10-21|23:32:04.955] [2/16 Headers] Waiting for headers...    from=22348996
INFO[10-21|23:32:24.955] [2/16 Headers] Wrote block headers       number=22371202 blk/second=1110.300 alloc=2.9GB sys=3.1GB
INFO[10-21|23:32:26.864] [2/16 Headers] Processed                 highest inserted=22371208 age=2s
INFO[10-21|23:32:41.805] [5/16 Bodies] Processing bodies...       from=22348996 to=22371208
INFO[10-21|23:32:42.250] [5/16 Bodies] Writing block bodies       block_num=22349098 remaining=22110 alloc=3.1GB sys=3.4GB
INFO[10-21|23:32:42.568] [5/16 Bodies] Writing block bodies       block_num=22349124 remaining=22084 alloc=3.3GB sys=3.5GB
INFO[10-21|23:32:42.678] [5/16 Bodies] Writing block bodies       block_num=22349213 remaining=21995 alloc=3.3GB sys=3.6GB
INFO[10-21|23:32:42.878] [5/16 Bodies] Writing block bodies       block_num=22349380 remaining=21828 alloc=3.4GB sys=3.6GB
INFO[10-21|23:32:43.038] [5/16 Bodies] Writing block bodies       block_num=22349474 remaining=21734 alloc=3.4GB sys=3.7GB
INFO[10-21|23:32:43.694] [5/16 Bodies] Writing block bodies       block_num=22349744 remaining=21464 alloc=3.5GB sys=3.8GB
INFO[10-21|23:32:43.715] [5/16 Bodies] Writing block bodies       block_num=22349764 remaining=21444 alloc=3.5GB sys=3.8GB
INFO[10-21|23:32:44.099] [5/16 Bodies] Writing block bodies       block_num=22349868 remaining=21340 alloc=3.6GB sys=3.8GB
INFO[10-21|23:32:45.819] [5/16 Bodies] Writing block bodies       block_num=22350020 remaining=21188 alloc=3.6GB sys=3.9GB
INFO[10-21|23:33:01.324] [txpool] stat                            block=22348996 pending=2357 baseFee=6 queued=7942 alloc=3.6GB sys=3.9GB
INFO[10-21|23:33:01.805] [5/16 Bodies] Downloading block bodies   block_num=22350020 delivery/sec=1.1MB wasted/sec=0B remaining=21187 delivered=1024 alloc=3.6GB sys=3.9GB

```

**Comment by AskAlexSharov** [comment]
fixing by https://github.com/ledgerwatch/erigon/pull/5833

**Comment by du5** [comment]
> fixing by #5833

thank you for your help

```
root@Ubuntu-2204-jammy-amd64-base ~ # erigon --chain=bsc --port=30411 --http.api=eth,web3,net --v5disc --torrent.upload.rate=32mb --torrent.download.rate=25000mb  --db.pagesize=16k --prune= --prune.r.before=16000000 --prune.h.older=5000 --prune.t.older=5000 --prune.c.older=5000 --downloader.verify
WARN[10-22|13:49:30.097] no log dir set, console logging only
WARN[10-22|13:49:30.097] no log dir set, console logging only
INFO[10-22|13:49:30.097] Build info                               git_branch=HEAD git_tag=v2021.10.03-2148-g8641d8151 git_commit=8641d81511153bccabe9e95f8800538d66bb5c44
INFO[10-22|13:49:30.097] Starting Erigon on BSC mainnet...
INFO[10-22|13:49:30.102] Maximum peer count                       ETH=100 total=100
INFO[10-22|13:49:30.103] starting HTTP APIs                       APIs=eth,web3,net
INFO[10-22|13:49:30.103] torrent verbosity                        level=WRN
INFO[10-22|13:49:32.206] Set global gas cap                       cap=50000000
INFO[10-22|13:49:32.214] Opening Database                         label=chaindata path=/root/.local/share/erigon/chaindata
INFO[10-22|13:49:32.217] Initialised chain configuration          config="{ChainID: 56 Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Euler: 18907621, Gibbs: <nil>, Nano: 21962149, Moran: 22107423, Engine: parlia}" genesis=0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b
INFO[10-22|13:49:32.217] Effective                                prune_flags="--prune.h.older=5000 --prune.r.before=16000000 --prune.t.older=5000 --prune.c.older=5000" snapshot_flags="--snapshots=true" history.v3=false
INFO[10-22|13:49:34.845] Initialising Ethereum protocol           network=56
INFO[10-22|13:49:37.409] Starting private RPC server              on=127.0.0.1:9090
INFO[10-22|13:49:37.409] rpc filters: subscribing to Erigon events
INFO[10-22|13:49:37.409] new subscription to logs established
INFO[10-22|13:49:37.409] New txs subscriber joined
INFO[10-22|13:49:37.409] new subscription to newHeaders established
INFO[10-22|13:49:37.410] Reading JWT secret                       path=/root/.local/share/erigon/jwt.hex
INFO[10-22|13:49:37.410] HTTP endpoint opened for Engine API      url=localhost:8551 ws=true ws.compression=true
INFO[10-22|13:49:37.410] HTTP endpoint opened                     url=localhost:8545 ws=false ws.compression=true grpc=false
INFO[10-22|13:49:37.423] [1/16 Snapshots] Fetching torrent files metadata
INFO[10-22|13:49:37.440] Started P2P networking                   version=66 self=enode://4cfa5b242af23caa5876af9ab87055fadd9231b89dc62c958467012d8031d2d439c6e0aec1eb92c858657b4ddbabdb1dc5102886e0386de9fc05b0f81a3ef307@127.0.0.1:30411 name=erigon/v2.28.1-dev-8641d815/linux-amd64/go1.18.1
INFO[10-22|13:49:57.059] [txpool] Started
INFO[10-22|13:49:57.425] [1/16 Snapshots] Waiting for torrents metadata: 136/138
INFO[10-22|13:50:17.425] [1/16 Snapshots] Waiting for torrents metadata: 137/138
INFO[10-22|13:50:37.410] [txpool] stat                            block=22388206 pending=419 baseFee=8 queued=370 alloc=314.7MB sys=584.4MB
INFO[10-22|13:50:37.425] [1/16 Snapshots] download finished       time=1m0.000464536s
WARN[10-22|13:50:51.417] "v1-020000-020500-headers.seg": would have banned 2a01:4f8:242:1858::2 for touching piece 24 after failed piece check
INFO[10-22|13:50:57.454] [snapshots] Verifying                    progress=3.45%
INFO[10-22|13:51:17.458] [snapshots] Verifying                    progress=6.98%
WARN[10-22|13:51:31.262] "v1-020000-020500-headers.seg": would have banned 168.119.70.93 for touching piece 103 after failed piece check
INFO[10-22|13:51:34.858] [p2p] GoodPeers                          eth66=92
INFO[10-22|13:51:37.426] [txpool] stat                            block=22388206 pending=419 baseFee=8 queued=370 alloc=543.3MB sys=1.7GB
INFO[10-22|13:51:37.435] [snapshots] Verifying                    progress=10.14%
WARN[10-22|13:51:44.482] "v1-021000-021500-headers.seg": would have banned 64.46.114.34 for touching piece 14 after failed piece check
WARN[10-22|13:51:44.761] "v1-021000-021500-headers.seg": would have banned 2a03:cfc0:8000:27::c303:df6d for touching piece 26 after failed piece check
WARN[10-22|13:51:45.292] "v1-021000-021500-headers.seg": would have banned 64.46.114.34 for touching piece 14 after failed piece check
WARN[10-22|13:51:46.838] "v1-021000-021500-headers.seg": would have banned 64.46.114.34 for touching piece 15 after failed piece check
WARN[10-22|13:51:46.951] "v1-021000-021500-headers.seg": would have banned 2600:1700:65a2:d090:11c:f72b:788a:eec8 for touching piece 14 after failed piece check
WARN[10-22|13:51:47.716] "v1-021000-021500-headers.seg": would have banned 64.46.114.34 for touching piece 0 after failed piece check
WARN[10-22|13:51:47.937] "v1-021000-021500-headers.seg": would have banned 2600:1700:65a2:d090:11c:f72b:788a:eec8 for touching piece 32 after failed piece check
WARN[10-22|13:51:51.635] "v1-021000-021500-headers.seg": would have banned 2600:1700:65a2:d090:11c:f72b:788a:eec8 for touching piece 16 after failed piece check
INFO[10-22|13:51:57.435] [snapshots] Verifying                    progress=13.51%
```

**Comment by du5** [comment]
```
INFO[10-22|14:01:57.428] [snapshots] Verifying                    progress=98.41%
INFO[10-22|14:02:20.940] [Snapshots] Blocks Stat                  blocks=22100k indices=22100k alloc=2.5GB sys=3.0GB
INFO[10-22|14:02:20.945] [1/16 Snapshots] DONE                    in=12m43.525718866s
```
