### ISSUE TITLE
To fix `checkptr` fatal error

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#5830]
```
 go test -race -run=TestEliasFano ./recsplit/eliasfano32
fatal error: checkptr: converted pointer straddles multiple allocations

goroutine 35 [running]:
runtime.throw({0x13bb5bf?, 0x13446ca?})
	runtime/panic.go:1047 +0x5d fp=0xc000137790 sp=0xc000137760 pc=0x108a13d
runtime.checkptrAlignment(0xa9?, 0x0?, 0x0?)
	runtime/checkptr.go:26 +0x6c fp=0xc0001377b0 sp=0xc000137790 pc=0x1059f8c
github.com/ledgerwatch/erigon-lib/recsplit/eliasfano32.Min({0xc00012c280, 0x40, 0x40})
	github.com/ledgerwatch/erigon-lib/recsplit/eliasfano32/elias_fano.go:324 +0x36f fp=0xc000137868 sp=0xc0001377b0 pc=0x133e66f
github.com/ledgerwatch/erigon-lib/recsplit/eliasfano32.TestEliasFano(0x0?)
	github.com/ledgerwatch/erigon-lib/recsplit/eliasfano32/elias_fano_test.go:58
```

**Comment by fenghaojiang** [comment]
Any suggestion to fix this error? 
I use the same way to read EliasFano in function `ReadEliasFano`.

```go
p := (*[maxDataSize / 8]uint64)(unsafe.Pointer(&r[16]))
```
When I submit I use test without `-race` flag.

**Comment by fenghaojiang** [comment]
Same problem will show when test `state` pkg.

```shell
go test -race  -run=TestHistoryCollationBuild ./state
```

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon-lib/pull/697

**Comment by AskAlexSharov** [comment]
it's because `maxDataSize / 8` is bigger than actual size of `r`

**Comment by fenghaojiang** [comment]
Ok. Thank you
