### ISSUE TITLE
runtime error: slice bounds out of range [297203082:2621440]

### ISSUE THREAD

**Issue by i11m20n** [ledgerwatch/erigon#6146]
#### System information

Erigon version: `2.30.0-stable`

OS & Version: `CentOS Linux release 7.9.2009 (Core)`

Commit hash : 35f493c5d021965f994bee615d441b2b35811f8f

#### Expected behaviour
Follow the BSC chain synchronization

#### Actual behaviour
Crash and restart to continue crashing

#### Steps to reproduce the behaviour
start command
```shell
nohup ./erigon --chain=bsc --datadir=/home/erigon/.bscnode --torrent.port=42096 --torrent.download.rate=64mb --db.pagesize=64kb --http=false --private.api.addr=127.0.0.1:19090 > node.log 2>&1 &
```

restart command
```shell
nohup ./erigon --chain=bsc --datadir=/home/erigon/.bscnode --torrent.port=42096 --torrent.download.rate=64mb --db.pagesize=64kb --http=false --private.api.addr=127.0.0.1:19090 --snap.stop > node.log 2>&1 &
```

#### Backtrace
initial log（tail -n 100 node.log）

````log
[WARN] [11-14|07:08:36.871] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions-to-block.idx idxtime=2022-09-06T13:54:56-0400
[INFO] [11-14|07:08:54.567] [1/16 Snapshots] Indexing                progress="v1-020500-021000-headers.seg=50%, v1-020000-020500-headers.seg=48%, v1-020500-021000-transactions.seg=0%, v1-020000-020500-transactions.seg=0%" total-indexing-time=20s alloc=79.9GB sys=124.0GB
[INFO] [11-14|07:09:00.627] [p2p] GoodPeers                          eth66=20
[INFO] [11-14|07:09:03.254] [txpool] stat                            block=23036446 pending=10000 baseFee=351 queued=30000 alloc=79.9GB sys=124.0GB
[EROR] [11-14|07:09:15.311] Staged Sync                              err="[1/16 Snapshots] BuildMissedIndices: HeadersIdx: at=v1-020500-021000-headers.seg, file: /home/erigon/.bscnode/snapshots/v1-020500-021000-headers.seg, runtime error: slice bounds out of range [915:610], [decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571], [block_snapshots.go:1825 panic.go:838 decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571]"
[INFO] [11-14|07:09:30.278] [1/16 Snapshots] Fetching torrent files metadata
[INFO] [11-14|07:09:30.373] [Snapshots] Blocks Stat                  blocks=20000k indices=20000k alloc=79.1GB sys=124.0GB
[WARN] [11-14|07:09:30.748] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-headers.seg segtime=2022-10-12T03:30:03-0400 idxfile=v1-020000-020500-headers.idx idxtime=2022-08-30T11:08:03-0400
[WARN] [11-14|07:09:30.749] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-headers.seg segtime=2022-10-12T02:40:44-0400 idxfile=v1-020500-021000-headers.idx idxtime=2022-09-06T04:10:38-0400
[WARN] [11-14|07:09:33.548] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions.idx idxtime=2022-08-30T21:53:14-0400
[WARN] [11-14|07:09:33.548] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions-to-block.idx idxtime=2022-08-30T22:01:36-0400
[WARN] [11-14|07:09:33.550] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions.idx idxtime=2022-09-06T13:47:21-0400
[WARN] [11-14|07:09:33.552] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions-to-block.idx idxtime=2022-09-06T13:54:56-0400
[INFO] [11-14|07:09:50.383] [1/16 Snapshots] Indexing                progress="v1-020500-021000-headers.seg=48%, v1-020000-020500-headers.seg=45%, v1-020500-021000-transactions.seg=0%, v1-020000-020500-transactions.seg=0%" total-indexing-time=20s alloc=78.9GB sys=124.0GB
[INFO] [11-14|07:10:03.058] [txpool] stat                            block=23036446 pending=10000 baseFee=351 queued=30000 alloc=78.8GB sys=124.0GB
[INFO] [11-14|07:10:10.380] [1/16 Snapshots] Indexing                progress="v1-020500-021000-headers.seg=96%, v1-020000-020500-headers.seg=95%, v1-020500-021000-transactions.seg=0%, v1-020000-020500-transactions.seg=0%" total-indexing-time=40s alloc=79.0GB sys=124.0GB
[EROR] [11-14|07:10:11.882] Staged Sync                              err="[1/16 Snapshots] BuildMissedIndices: HeadersIdx: at=v1-020500-021000-headers.seg, file: /home/erigon/.bscnode/snapshots/v1-020500-021000-headers.seg, runtime error: slice bounds out of range [915:610], [decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571], [block_snapshots.go:1825 panic.go:838 decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571]"
[INFO] [11-14|07:10:24.348] [1/16 Snapshots] Fetching torrent files metadata
[INFO] [11-14|07:10:24.577] [Snapshots] Blocks Stat                  blocks=20000k indices=20000k alloc=79.1GB sys=124.0GB
[WARN] [11-14|07:10:25.070] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-headers.seg segtime=2022-10-12T03:30:03-0400 idxfile=v1-020000-020500-headers.idx idxtime=2022-08-30T11:08:03-0400
[WARN] [11-14|07:10:25.071] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-headers.seg segtime=2022-10-12T02:40:44-0400 idxfile=v1-020500-021000-headers.idx idxtime=2022-09-06T04:10:38-0400
[WARN] [11-14|07:10:26.935] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions.idx idxtime=2022-08-30T21:53:14-0400
[WARN] [11-14|07:10:27.112] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions-to-block.idx idxtime=2022-08-30T22:01:36-0400
[WARN] [11-14|07:10:27.113] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions.idx idxtime=2022-09-06T13:47:21-0400
[WARN] [11-14|07:10:27.113] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions-to-block.idx idxtime=2022-09-06T13:54:56-0400
[INFO] [11-14|07:10:44.584] [1/16 Snapshots] Indexing                progress="v1-020500-021000-headers.seg=43%, v1-020000-020500-headers.seg=41%, v1-020500-021000-transactions.seg=0%, v1-020000-020500-transactions.seg=0%" total-indexing-time=20s alloc=79.1GB sys=124.0GB
[INFO] [11-14|07:11:00.653] [p2p] GoodPeers                          eth66=20
[INFO] [11-14|07:11:02.989] [txpool] stat                            block=23036446 pending=10000 baseFee=351 queued=30000 alloc=79.2GB sys=124.0GB
[INFO] [11-14|07:11:04.589] [1/16 Snapshots] Indexing                progress="v1-020500-021000-headers.seg=98%, v1-020000-020500-headers.seg=92%, v1-020500-021000-transactions.seg=0%, v1-020000-020500-transactions.seg=0%" total-indexing-time=40s alloc=79.5GB sys=124.0GB
[EROR] [11-14|07:11:05.318] Staged Sync                              err="[1/16 Snapshots] BuildMissedIndices: HeadersIdx: at=v1-020500-021000-headers.seg, file: /home/erigon/.bscnode/snapshots/v1-020500-021000-headers.seg, runtime error: slice bounds out of range [915:610], [decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571], [block_snapshots.go:1825 panic.go:838 decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571]"
[INFO] [11-14|07:11:16.315] [1/16 Snapshots] Fetching torrent files metadata
[INFO] [11-14|07:11:16.448] [Snapshots] Blocks Stat                  blocks=20000k indices=20000k alloc=80.3GB sys=124.0GB
[WARN] [11-14|07:11:16.775] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-headers.seg segtime=2022-10-12T03:30:03-0400 idxfile=v1-020000-020500-headers.idx idxtime=2022-08-30T11:08:03-0400
[WARN] [11-14|07:11:16.776] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-headers.seg segtime=2022-10-12T02:40:44-0400 idxfile=v1-020500-021000-headers.idx idxtime=2022-09-06T04:10:38-0400
[WARN] [11-14|07:11:18.720] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions.idx idxtime=2022-08-30T21:53:14-0400
[WARN] [11-14|07:11:18.851] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions-to-block.idx idxtime=2022-08-30T22:01:36-0400
[WARN] [11-14|07:11:18.852] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions.idx idxtime=2022-09-06T13:47:21-0400
[WARN] [11-14|07:11:18.853] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions-to-block.idx idxtime=2022-09-06T13:54:56-0400
[INFO] [11-14|07:11:36.463] [1/16 Snapshots] Indexing                progress="v1-020500-021000-headers.seg=40%, v1-020000-020500-headers.seg=42%, v1-020500-021000-transactions.seg=0%, v1-020000-020500-transactions.seg=0%" total-indexing-time=20s alloc=81.6GB sys=124.0GB
[INFO] [11-14|07:11:56.457] [1/16 Snapshots] Indexing                progress="v1-020500-021000-headers.seg=88%, v1-020000-020500-headers.seg=89%, v1-020500-021000-transactions.seg=0%, v1-020000-020500-transactions.seg=0%" total-indexing-time=40s alloc=81.5GB sys=124.0GB
[EROR] [11-14|07:12:00.622] Staged Sync                              err="[1/16 Snapshots] BuildMissedIndices: HeadersIdx: at=v1-020000-020500-headers.seg, file: /home/erigon/.bscnode/snapshots/v1-020000-020500-headers.seg, runtime error: slice bounds out of range [610:36], [decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571], [block_snapshots.go:1825 panic.go:838 decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571]"
[INFO] [11-14|07:12:03.616] [txpool] stat                            block=23036446 pending=10000 baseFee=351 queued=30000 alloc=81.6GB sys=124.0GB
[INFO] [11-14|07:12:11.646] [1/16 Snapshots] Fetching torrent files metadata
[INFO] [11-14|07:12:11.943] [Snapshots] Blocks Stat                  blocks=20000k indices=20000k alloc=81.6GB sys=124.0GB
[WARN] [11-14|07:12:12.592] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-headers.seg segtime=2022-10-12T03:30:03-0400 idxfile=v1-020000-020500-headers.idx idxtime=2022-08-30T11:08:03-0400
[WARN] [11-14|07:12:12.774] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-headers.seg segtime=2022-10-12T02:40:44-0400 idxfile=v1-020500-021000-headers.idx idxtime=2022-09-06T04:10:38-0400
[WARN] [11-14|07:12:14.923] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions.idx idxtime=2022-08-30T21:53:14-0400
[WARN] [11-14|07:12:15.046] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions-to-block.idx idxtime=2022-08-30T22:01:36-0400
[WARN] [11-14|07:12:15.047] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions.idx idxtime=2022-09-06T13:47:21-0400
[WARN] [11-14|07:12:15.048] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions-to-block.idx idxtime=2022-09-06T13:54:56-0400
[INFO] [11-14|07:12:31.975] [1/16 Snapshots] Indexing                progress="v1-020000-020500-headers.seg=40%, v1-020500-021000-headers.seg=36%, v1-020500-021000-transactions.seg=0%, v1-020000-020500-transactions.seg=0%" total-indexing-time=20s alloc=81.6GB sys=124.0GB
[INFO] [11-14|07:12:51.126] [index] calculating                      file=v1-021000-021500-transactions.idx
[INFO] [11-14|07:12:51.957] [1/16 Snapshots] Indexing                progress="v1-020000-020500-headers.seg=84%, v1-020500-021000-headers.seg=84%, v1-020500-021000-transactions.seg=0%, v1-020000-020500-transactions.seg=0%" total-indexing-time=40s alloc=81.6GB sys=124.0GB
[EROR] [11-14|07:12:58.711] Staged Sync                              err="[1/16 Snapshots] BuildMissedIndices: HeadersIdx: at=v1-020000-020500-headers.seg, file: /home/erigon/.bscnode/snapshots/v1-020000-020500-headers.seg, runtime error: slice bounds out of range [610:36], [decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571], [block_snapshots.go:1825 panic.go:838 decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571]"
[INFO] [11-14|07:13:00.616] [p2p] GoodPeers                          eth66=20
[INFO] [11-14|07:13:03.402] [txpool] stat                            block=23036446 pending=10000 baseFee=351 queued=30000 alloc=81.6GB sys=124.0GB
[INFO] [11-14|07:13:08.800] [1/16 Snapshots] Fetching torrent files metadata
[INFO] [11-14|07:13:08.941] [Snapshots] Blocks Stat                  blocks=20000k indices=20000k alloc=81.6GB sys=124.0GB
[WARN] [11-14|07:13:09.441] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-headers.seg segtime=2022-10-12T03:30:03-0400 idxfile=v1-020000-020500-headers.idx idxtime=2022-08-30T11:08:03-0400
[WARN] [11-14|07:13:09.441] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-headers.seg segtime=2022-10-12T02:40:44-0400 idxfile=v1-020500-021000-headers.idx idxtime=2022-09-06T04:10:38-0400
[WARN] [11-14|07:13:11.515] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions.idx idxtime=2022-08-30T21:53:14-0400
[WARN] [11-14|07:13:11.516] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions-to-block.idx idxtime=2022-08-30T22:01:36-0400
[WARN] [11-14|07:13:11.518] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions.idx idxtime=2022-09-06T13:47:21-0400
[WARN] [11-14|07:13:11.519] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions-to-block.idx idxtime=2022-09-06T13:54:56-0400
[INFO] [11-14|07:13:28.960] [1/16 Snapshots] Indexing                progress="v1-020500-021000-headers.seg=40%, v1-020000-020500-headers.seg=43%, v1-021000-021500-transactions.seg=0%, v1-020000-020500-transactions.seg=0%, v1-020500-021000-transactions.seg=0%" total-indexing-time=20s alloc=84.1GB sys=124.0GB
[INFO] [11-14|07:13:48.955] [1/16 Snapshots] Indexing                progress="v1-020500-021000-headers.seg=80%, v1-020000-020500-headers.seg=81%, v1-021000-021500-transactions.seg=0%, v1-020000-020500-transactions.seg=0%, v1-020500-021000-transactions.seg=0%" total-indexing-time=40s alloc=84.9GB sys=124.0GB
[EROR] [11-14|07:13:57.387] Staged Sync                              err="[1/16 Snapshots] BuildMissedIndices: HeadersIdx: at=v1-020000-020500-headers.seg, file: /home/erigon/.bscnode/snapshots/v1-020000-020500-headers.seg, runtime error: slice bounds out of range [610:36], [decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571], [block_snapshots.go:1825 panic.go:838 decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571]"
[INFO] [11-14|07:14:03.238] [txpool] stat                            block=23036446 pending=10000 baseFee=351 queued=30000 alloc=84.4GB sys=124.0GB
[INFO] [11-14|07:14:08.254] [1/16 Snapshots] Fetching torrent files metadata
[INFO] [11-14|07:14:08.421] [Snapshots] Blocks Stat                  blocks=20000k indices=20000k alloc=84.2GB sys=124.0GB
[WARN] [11-14|07:14:09.167] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-headers.seg segtime=2022-10-12T03:30:03-0400 idxfile=v1-020000-020500-headers.idx idxtime=2022-08-30T11:08:03-0400
[WARN] [11-14|07:14:09.168] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-headers.seg segtime=2022-10-12T02:40:44-0400 idxfile=v1-020500-021000-headers.idx idxtime=2022-09-06T04:10:38-0400
[WARN] [11-14|07:14:11.603] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions.idx idxtime=2022-08-30T21:53:14-0400
[WARN] [11-14|07:14:11.605] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions-to-block.idx idxtime=2022-08-30T22:01:36-0400
[WARN] [11-14|07:14:11.725] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions.idx idxtime=2022-09-06T13:47:21-0400
[WARN] [11-14|07:14:11.726] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions-to-block.idx idxtime=2022-09-06T13:54:56-0400
[INFO] [11-14|07:14:28.431] [1/16 Snapshots] Indexing                progress="v1-020500-021000-headers.seg=35%, v1-020000-020500-headers.seg=39%, v1-020000-020500-transactions.seg=0%, v1-021000-021500-transactions.seg=0%, v1-020500-021000-transactions.seg=0%" total-indexing-time=20s alloc=84.8GB sys=124.0GB
[INFO] [11-14|07:14:48.425] [1/16 Snapshots] Indexing                progress="v1-020500-021000-headers.seg=80%, v1-020000-020500-headers.seg=84%, v1-020000-020500-transactions.seg=0%, v1-021000-021500-transactions.seg=0%, v1-020500-021000-transactions.seg=0%" total-indexing-time=40s alloc=84.9GB sys=124.0GB
[EROR] [11-14|07:14:55.308] Staged Sync                              err="[1/16 Snapshots] BuildMissedIndices: HeadersIdx: at=v1-020000-020500-headers.seg, file: /home/erigon/.bscnode/snapshots/v1-020000-020500-headers.seg, runtime error: slice bounds out of range [610:36], [decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571], [block_snapshots.go:1825 panic.go:838 decompress.go:551 panic.go:838 panic.go:117 decompress.go:578 block_snapshots.go:1917 block_snapshots.go:1841 block_snapshots.go:866 block_snapshots.go:917 asm_amd64.s:1571]"
[INFO] [11-14|07:15:00.626] [p2p] GoodPeers                          eth66=21
[INFO] [11-14|07:15:03.162] [txpool] stat                            block=23036446 pending=10000 baseFee=351 queued=30000 alloc=84.9GB sys=124.0GB
[INFO] [11-14|07:15:06.911] [1/16 Snapshots] Fetching torrent files metadata
[INFO] [11-14|07:15:07.274] [Snapshots] Blocks Stat                  blocks=20000k indices=20000k alloc=84.9GB sys=124.0GB
[WARN] [11-14|07:15:07.815] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-headers.seg segtime=2022-10-12T03:30:03-0400 idxfile=v1-020000-020500-headers.idx idxtime=2022-08-30T11:08:03-0400
[WARN] [11-14|07:15:07.816] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-headers.seg segtime=2022-10-12T02:40:44-0400 idxfile=v1-020500-021000-headers.idx idxtime=2022-09-06T04:10:38-0400
[WARN] [11-14|07:15:09.759] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions.idx idxtime=2022-08-30T21:53:14-0400
[WARN] [11-14|07:15:09.761] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020000-020500-transactions.seg segtime=2022-10-12T03:53:52-0400 idxfile=v1-020000-020500-transactions-to-block.idx idxtime=2022-08-30T22:01:36-0400
[WARN] [11-14|07:15:09.762] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions.idx idxtime=2022-09-06T13:47:21-0400
[WARN] [11-14|07:15:09.764] Index file has timestamp before segment file, will be recreated segfile=/home/erigon/.bscnode/snapshots/v1-020500-021000-transactions.seg segtime=2022-10-12T03:27:00-0400 idxfile=v1-020500-021000-transactions-to-block.idx idxtime=2022-09-06T13:54:56-0400
panic: runtime error: slice bounds out of range [297203082:2621440]

goroutine 8641024 [running]:
github.com/ledgerwatch/erigon-lib/recsplit.OpenIndex({0xcbbb765590, 0x41})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20221111035555-f9fe50d566fb/recsplit/index.go:101 +0x9ec
github.com/ledgerwatch/erigon/turbo/snapshotsync.hasIdxFile(0xc1a75bbf50)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1300 +0x29e
github.com/ledgerwatch/erigon/turbo/snapshotsync.BuildMissedIndices.func1()
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:902 +0x1bb
created by github.com/ledgerwatch/erigon/turbo/snapshotsync.BuildMissedIndices
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:895 +0x413
````

restart log
```log
[INFO] [11-28|03:28:43.546] Build info                               git_branch= git_tag= git_commit=
[INFO] [11-28|03:28:43.546] Starting Erigon on BSC mainnet...
[INFO] [11-28|03:28:43.552] Maximum peer count                       ETH=100 total=100
[INFO] [11-28|03:28:43.553] starting HTTP APIs                       APIs=eth,erigon,engine
[INFO] [11-28|03:28:43.553] torrent verbosity                        level=WRN
[INFO] [11-28|03:28:45.655] Set global gas cap                       cap=50000000
[INFO] [11-28|03:28:45.662] Opening Database                         label=chaindata path=/home/erigon/.bscnode/chaindata
[INFO] [11-28|03:28:45.667] Initialised chain configuration          config="{ChainID: 56 Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Euler: 18907621, Gibbs: <nil>, Nano: 21962149, Moran: 22107423, Engine: parlia}" genesis=0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b
[WARN] [11-28|03:28:45.668] Incorrect snapshot enablement            got=false change_to=true
[INFO] [11-28|03:28:45.668] Effective                                prune_flags= snapshot_flags="--snapshots=true --snap.stop=true" history.v3=false
[EROR] [11-28|03:28:51.593] catch panic                              err="runtime error: slice bounds out of range [297203082:2621440]" stack="[main.go:32 panic.go:838 panic.go:117 index.go:101 block_snapshots.go:249 block_snapshots.go:276 block_snapshots.go:675 block_snapshots.go:727 kv_mdbx.go:645 block_snapshots.go:722 block_snapshots.go:708 backend.go:870 backend.go:265 node.go:115 main.go:62 app.go:526 app.go:286 main.go:37 proc.go:250 asm_amd64.s:1571]"
```

**Comment by i11m20n** [comment]
Please help me, what should I do to restore sync?
full log: [node.log](https://github.com/ledgerwatch/erigon/files/10109412/node.log)

**Comment by binhgo** [comment]
@i11m20n are you facing this issue when upgrade Erigon client? I am also facing this when upgrade from 2.28.1 to 2.30.0

**Comment by i11m20n** [comment]
> @i11m20n您在升级 Erigon 客户端时遇到这个问题吗？从 2.28.1 升级到 2.30.0 时我也面临这个问题

No, my erigon upgrade process didn't crash.
The crash didn't happen until yesterday.

**Comment by i11m20n** [comment]
> @i11m20n are you facing this issue when upgrade Erigon client? I am also facing this when upgrade from 2.28.1 to 2.30.0

No, my erigon upgrade process didn't crash.
The crash didn't happen until yesterday.

**Comment by i11m20n** [comment]
@binhgo How did you solve it?

**Comment by AskAlexSharov** [comment]
@i11m20n try start erigon with --downloader.verify flag once

**Comment by i11m20n** [comment]
> @i11m20n try start erigon with --downloader.verify flag once

As you suggested, it still crash.

command: `nohup ./erigon --chain=bsc --datadir=/home/erigon/.bscnode --torrent.port=42096 --torrent.download.rate=64mb --db.pagesize=64kb --http=false --private.api.addr=127.0.0.1:19090 --downloader.verify --snap.stop > node.log 2>&1 &`

```log
[INFO] [11-29|03:22:28.519] Build info                               git_branch= git_tag= git_commit=
[INFO] [11-29|03:22:28.520] Starting Erigon on BSC mainnet...
[INFO] [11-29|03:22:28.526] Maximum peer count                       ETH=100 total=100
[INFO] [11-29|03:22:28.527] starting HTTP APIs                       APIs=eth,erigon,engine
[INFO] [11-29|03:22:28.527] torrent verbosity                        level=WRN
[INFO] [11-29|03:22:30.631] Set global gas cap                       cap=50000000
[INFO] [11-29|03:22:30.640] Opening Database                         label=chaindata path=/home/erigon/.bscnode/chaindata
[INFO] [11-29|03:22:30.657] Initialised chain configuration          config="{ChainID: 56 Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Euler: 18907621, Gibbs: <nil>, Nano: 21962149, Moran: 22107423, Engine: parlia}" genesis=0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b
[INFO] [11-29|03:22:30.658] Effective                                prune_flags= snapshot_flags="--snapshots=true --snap.stop=true" history.v3=false
[EROR] [11-29|03:22:42.507] catch panic                              err="runtime error: slice bounds out of range [297203082:2621440]" stack="[main.go:32 panic.go:838 panic.go:117 index.go:101 block_snapshots.go:249 block_snapshots.go:276 block_snapshots.go:675 block_snapshots.go:727 kv_mdbx.go:645 block_snapshots.go:722 block_snapshots.go:708 backend.go:870 backend.go:265 node.go:115 main.go:62 app.go:526 app.go:286 main.go:37 proc.go:250 asm_amd64.s:1571]"
```

**Comment by AskAlexSharov** [comment]
@i11m20n remove .idx

**Comment by i11m20n** [comment]
> @i11m20n remove .idx

These `.idx` Do you want to delete all?

![image](https://user-images.githubusercontent.com/13911593/205532614-f78b335a-de5d-40e8-b719-f0cfb5ac0124.png)

**Comment by binhgo** [comment]
@i11m20n : i added --snap.stop into the cmd. my full one: /home/erigon/build/bin/erigon --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --datadir /home/erigonchaindata --private.api.addr=0.0.0.0:9090 --chain=bsc --snap.stop

**Comment by i11m20n** [comment]
> --snap.stop

add --snap.stop can't solve my problem

**Comment by i11m20n** [comment]
> @i11m20n : i added --snap.stop into the cmd. my full one: /home/erigon/build/bin/erigon --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --datadir /home/erigonchaindata --private.api.addr=0.0.0.0:9090 --chain=bsc --snap.stop

add --snap.stop can't solve my problem

**Comment by AndriyAntonenko** [comment]
Hi everyone! I've met the same issue. What is --snap.stop flag is actually doing?

**Comment by AskAlexSharov** [comment]
@AndriyAntonenko 
`Workaround to stop producing new snapshots, if you meet some snapshots-related critical bug. It will stop move historical data from DB to new snapshots`
