### ISSUE TITLE
missing method MarshalSSZ

### ISSUE THREAD

**Issue by SuperEdison** [ledgerwatch/erigon#6630]
#### System information

Erigon version: 2.35.1

OS & Version: linux

Commit hash : 

#### Backtrace

````
[INFO] [01-19|21:27:12.030] [txpool] stat                            block=8338252 pending=0 baseFee=0 queued=0 alloc=1.1GB sys=1.2GB
[INFO] [01-19|21:27:12.030] [LightClient] P2P                        peers=4
panic: interface conversion: *cltypes.SignedVoluntaryExit is not ssz_utils.Marshaler: missing method MarshalSSZ

goroutine 1010 [running]:
github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/service.(*SentinelServer).handleGossipPacket(0xc033a60480, 0xc049f8a0a0)
        github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/service/service.go:136 +0x14d
github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/service.(*SentinelServer).ListenToGossip(0xc033a60480)
        github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/service/service.go:122 +0x2e
created by github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/service.StartServe
        github.com/ledgerwatch/erigon/cmd/sentinel/sentinel/service/start.go:96 +0x1d8
````

**Comment by Giulio2002** [comment]
It should be fixed now
