### ISSUE TITLE
Erigon Node randomly crashed

### ISSUE THREAD

**Issue by imulmat4** [ledgerwatch/erigon#6727]
#### System information

Erigon version: `./erigon --version`
2.33.0
OS & Version: Windows/Linux/OSX
Ubuntu 22.04
Commit hash : 

#### Expected behaviour
Erigon doesnt randomly crash and corrupt the chain state

#### Actual behavior
Erigon randomly crashed and corrupted the chain state

#### Backtrace

````
[backtrace]
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         github.com/anacrolix/torrent@v1.48.0/tracker_scraper.go:206 +0x12e
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: goroutine 774 [select, 7163 minutes]:
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: runtime.gopark(0xc0986407a8?, 0x2?, 0x60?, 0x6?, 0xc09864078c?)
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         runtime/proc.go:363 +0xd6 fp=0xc098640610 sp=0xc0986405f0 pc=0x463c76
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: runtime.selectgo(0xc0986407a8, 0xc098640788, 0x0?, 0x0, 0x0?, 0x1)
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         runtime/select.go:328 +0x7bc fp=0xc098640750 sp=0xc098640610 pc=0x473b5c
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: github.com/anacrolix/torrent.(*trackerScraper).Run.func1()
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         github.com/anacrolix/torrent@v1.48.0/tracker_scraper.go:208 +0xca fp=0xc0986407e0 sp=0xc098640750 pc=0xd812>
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: runtime.goexit()
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         runtime/asm_amd64.s:1594 +0x1 fp=0xc0986407e8 sp=0xc0986407e0 pc=0x4956e1
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: created by github.com/anacrolix/torrent.(*trackerScraper).Run
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         github.com/anacrolix/torrent@v1.48.0/tracker_scraper.go:206 +0x12e
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: goroutine 1149 [select]:
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: runtime.gopark(0xc088733f08?, 0x3?, 0x36?, 0x30?, 0xc088733eaa?)
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         runtime/proc.go:363 +0xd6 fp=0xc088733d20 sp=0xc088733d00 pc=0x463c76
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: runtime.selectgo(0xc088733f08, 0xc088733ea4, 0x3f939a0?, 0x0, 0x0?, 0x1)
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         runtime/select.go:328 +0x7bc fp=0xc088733e60 sp=0xc088733d20 pc=0x473b5c
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: github.com/anacrolix/torrent.(*trackerScraper).Run(0xc09865e9a0)
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         github.com/anacrolix/torrent@v1.48.0/tracker_scraper.go:250 +0x513 fp=0xc088733fc8 sp=0xc088733e60 pc=0xd81>
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: github.com/anacrolix/torrent.(*Torrent).startScrapingTracker.func1.1()
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         github.com/anacrolix/torrent@v1.48.0/torrent.go:1687 +0x26 fp=0xc088733fe0 sp=0xc088733fc8 pc=0xd77ca6
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: runtime.goexit()
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         runtime/asm_amd64.s:1594 +0x1 fp=0xc088733fe8 sp=0xc088733fe0 pc=0x4956e1
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: created by github.com/anacrolix/torrent.(*Torrent).startScrapingTracker.func1
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         github.com/anacrolix/torrent@v1.48.0/torrent.go:1687 +0x25c
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: goroutine 1150 [select, 17 minutes]:
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: runtime.gopark(0xc0a4ff7f08?, 0x3?, 0x3e?, 0x30?, 0xc0a4ff7eaa?)
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         runtime/proc.go:363 +0xd6 fp=0xc08e429d20 sp=0xc08e429d00 pc=0x463c76
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]: runtime.selectgo(0xc08e429f08, 0xc0a4ff7ea4, 0x3f939a0?, 0x0, 0x0?, 0x1)
Jan 22 16:53:37 ip-10-127-0-96 erigon[247531]:         runtime/select.go:328 +0x7bc fp=0xc08e429e60 sp=0xc08e429d20 pc=0x473b5c

````

**Comment by DicksonWu654** [comment]
Same this happened a lot on Ubuntu, I switched to debian and it's now much more stable
