### ISSUE TITLE
sentry panic after upgrade to v2.38.1

### ISSUE THREAD

**Issue by rasdotsu** [ledgerwatch/erigon#6858]
#### System information

erigon version 2.38.1-stable-52fd6d60

OS & Version: Linux, docker

Commit hash: 52fd6d60e180a267e99a25662f169797570e356e

Chain/Network: bnb

#### Backtrace

````
erigon-sentry-1  | 2023-02-13T12:18:17.773414752Z [WARN] [02-13|12:18:17.773] no log dir set, console logging only
erigon-sentry-1  | 2023-02-13T12:18:17.773480802Z [WARN] [02-13|12:18:17.773] no log dir set, console logging only
erigon-sentry-1  | 2023-02-13T12:18:17.776833795Z panic: runtime error: invalid memory address or nil pointer dereference
erigon-sentry-1  | 2023-02-13T12:18:17.776853639Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1180622]
erigon-sentry-1  | 2023-02-13T12:18:17.776859545Z
erigon-sentry-1  | 2023-02-13T12:18:17.776863759Z goroutine 1 [running]:
erigon-sentry-1  | 2023-02-13T12:18:17.776868163Z github.com/ledgerwatch/erigon/cmd/sentry/sentry.NewGrpcServer({0x24f5398?, 0xc001c41a00}, 0x0, 0x2286db8, 0xc0002ca000, 0x43)
erigon-sentry-1  | 2023-02-13T12:18:17.776888903Z       github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_grpc_server.go:570 +0x1a2
erigon-sentry-1  | 2023-02-13T12:18:17.776894298Z github.com/ledgerwatch/erigon/cmd/sentry/sentry.Sentry({0x24f5398, 0xc001c41a00}, {{0x7ffdb1258f57, 0x20}, {0x7ffdb1258f57, 0x20}, {0xc001c20a20, 0x2a}, {0xc001c20a50, 0x25}, ...}, ...)
erigon-sentry-1  | 2023-02-13T12:18:17.776898913Z       github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_grpc_server.go:626 +0xa5
erigon-sentry-1  | 2023-02-13T12:18:17.776904338Z main.glob..func3(0x319bd00, {0x1b2c9bf?, 0x2?, 0x2?})
erigon-sentry-1  | 2023-02-13T12:18:17.776911840Z       github.com/ledgerwatch/erigon/cmd/sentry/main.go:94 +0x3ad
erigon-sentry-1  | 2023-02-13T12:18:17.776934981Z github.com/spf13/cobra.(*Command).execute(0x319bd00, {0xc00011a190, 0x2, 0x2})
erigon-sentry-1  | 2023-02-13T12:18:17.776941659Z       github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
erigon-sentry-1  | 2023-02-13T12:18:17.776996032Z github.com/spf13/cobra.(*Command).ExecuteC(0x319bd00)
erigon-sentry-1  | 2023-02-13T12:18:17.777061733Z       github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
erigon-sentry-1  | 2023-02-13T12:18:17.777069161Z github.com/spf13/cobra.(*Command).Execute(...)
erigon-sentry-1  | 2023-02-13T12:18:17.777074921Z       github.com/spf13/cobra@v1.6.1/command.go:968
erigon-sentry-1  | 2023-02-13T12:18:17.777123503Z github.com/spf13/cobra.(*Command).ExecuteContext(...)
erigon-sentry-1  | 2023-02-13T12:18:17.777152379Z       github.com/spf13/cobra@v1.6.1/command.go:961
erigon-sentry-1  | 2023-02-13T12:18:17.777179505Z main.main()
erigon-sentry-1  | 2023-02-13T12:18:17.777206789Z       github.com/ledgerwatch/erigon/cmd/sentry/main.go:101 +0x76
````

and this all time

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/6859

**Comment by rasdotsu** [comment]
Thanks, solved.
