### ISSUE TITLE
libp2p: putting the same entry twice not supported

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#6882]
mainnet, when start fresh node:
 
```
panic: putting the same entry twice not supported

goroutine 198 [running]:
github.com/libp2p/go-libp2p-pubsub/timecache.FirstSeenCache.Add({0xc000716720?, 0xc000716750?, 0xc000beb710?, 0xc00550c5e8?}, {0xc0333894b8, 0x14})
	github.com/libp2p/go-libp2p-pubsub@v0.9.0/timecache/first_seen_cache.go:32 +0x28d
github.com/libp2p/go-libp2p-pubsub.(*PubSub).markSeen(0xc000305440, {0xc0333894b8, 0x14})
	github.com/libp2p/go-libp2p-pubsub@v0.9.0/pubsub.go:1002 +0x102
github.com/libp2p/go-libp2p-pubsub.(*PubSub).pushMsg(0xc000305440, 0xc027ef6940)
	github.com/libp2p/go-libp2p-pubsub@v0.9.0/pubsub.go:1168 +0x34d
github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleIncomingRPC(0xc000305440, 0xc032547ab0)
	github.com/libp2p/go-libp2p-pubsub@v0.9.0/pubsub.go:1109 +0x8c5
github.com/libp2p/go-libp2p-pubsub.(*PubSub).processLoop(0xc000305440, {0x2c85f90, 0xc0000580b0})
	github.com/libp2p/go-libp2p-pubsub@v0.9.0/pubsub.go:639 +0xb4c
created by github.com/libp2p/go-libp2p-pubsub.NewPubSub
	github.com/libp2p/go-libp2p-pubsub@v0.9.0/pubsub.go:335 +0xd7e
```

**Comment by matthewdarwin** [comment]
Seeing this on v2.39.0 as well

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/6924
