### ISSUE TITLE
ChainTipSubscriber: nil ptr 

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#6905]
```
received error                           err="�sNaPpY�z��REQUEST_ERROR_RATE_LIMITED"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1553585]

goroutine 50650 [running]:
github.com/ledgerwatch/erigon/cmd/lightclient/lightclient.(*ChainTipSubscriber).StartLoop.func1()
	github.com/ledgerwatch/erigon/cmd/lightclient/lightclient/subscriber.go:70 +0x105
created by github.com/ledgerwatch/erigon/cmd/lightclient/lightclient.(*ChainTipSubscriber).StartLoop
	github.com/ledgerwatch/erigon/cmd/lightclient/lightclient/subscriber.go:60 +0x1aa

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/6924

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/6922
