### ISSUE TITLE
SIGSEGV on Error Rate Limited

### ISSUE THREAD

**Issue by keithchew** [ledgerwatch/erigon#6913]
Using latest v2.39.0 on goerli, just received this error. Likely an edge case not handling a rate limit error.
```
[INFO] [02-20|22:00:14.602] [LightClient] P2P                        peers=2
[WARN] [02-20|22:00:27.065] received error                           err="�sNaPpY�zREQUEST_ERROR_RATE_LIMITED"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1575905]

goroutine 64964 [running]:
github.com/ledgerwatch/erigon/cmd/lightclient/lightclient.(*ChainTipSubscriber).StartLoop.func1()
        github.com/ledgerwatch/erigon/cmd/lightclient/lightclient/subscriber.go:70 +0x105
created by github.com/ledgerwatch/erigon/cmd/lightclient/lightclient.(*ChainTipSubscriber).StartLoop
        github.com/ledgerwatch/erigon/cmd/lightclient/lightclient/subscriber.go:60 +0x1aa
```

**Comment by whidrasl** [comment]
https://github.com/ledgerwatch/erigon/issues/6905

**Comment by AskAlexSharov** [comment]
I added some `sleep(3sec)` before retries in `devel` as a hot-fix. Will need add some retry-with-backoff strategy later. And of course not die because of error from third-party server.

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/6922
closing as duplicate
