### ISSUE TITLE
Polygon mumbai persistant crashing

### ISSUE THREAD

**Issue by theSwissAlex** [ledgerwatch/erigon#6929]
I am running Erigon with Mumbai (testnet) for now and it crashes daily, mostly even multiple times a day. That is with Testnet.
Running 3 nodes on dedicated metal servers in our hosting facility. All same Hardware. 64GB Ram, 8 TB SSSD, 16 Cores.

**Before it is suggested there is a hardware issue**: already 2 servers were replaced and errors keep coming. It can be ruled out as highly unlikely as it would mean 2 brand new deviced fail from their first day of action. 

The node is under rather heavy RPC load as every block is fully parsed but only one of them. The other too sit idle in case one node goes down. The feeling is that the nodes go down as they are used by RPC calls.

I have unfortunately not more details. Below are the first error reports. it would be thousands of lines for all of them. I can share them if required.

```

[INFO] [02-21|23:38:27.232] [2/16 Headers] Waiting for headers...    from=32272060
fatal error: concurrent map iteration and map write

goroutine 4102 [running]:
github.com/ledgerwatch/erigon/turbo/engineapi.(*ForkValidator).clean(0xc046dd0ba0)
        github.com/ledgerwatch/erigon/turbo/engineapi/fork_validator.go:321 +0x71
github.com/ledgerwatch/erigon/turbo/engineapi.(*ForkValidator).TryAddingPoWBlock(0xc046dd0ba0, 0xc07f653490)
        github.com/ledgerwatch/erigon/turbo/engineapi/fork_validator.go:255 +0x189
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).newBlock66(0xc02ac2ad80, {0x2b545b8, 0xc0017b4340}, 0xc08e7d3630, {0x2b726e0, 0xc028695e78})
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:492 +0x558
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).handleInboundMessage(0x66?, {0x2b545b8?, 0xc0017b4340?}, 0x2c?, {0x2b726e0?, 0xc028695e78?})
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:704 +0x5d
github.com/ledgerwatch/erigon/cmd/sentry/sentry.(*MultiClient).HandleInboundMessage(0x7792ee54b5be?, {0x2b545b8, 0xc0017b4340}, 0xc08e7d3630, {0x2b726e0?, 0xc028695e78?})
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:679 +0xb9
github.com/ledgerwatch/erigon/cmd/sentry/sentry.pumpStreamLoop[...].func2()
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:214 +0xde
created by github.com/ledgerwatch/erigon/cmd/sentry/sentry.pumpStreamLoop[...]
        github.com/ledgerwatch/erigon/cmd/sentry/sentry/sentry_multi_client.go:212 +0x2ce

goroutine 1 [chan receive, 217 minutes]:
github.com/ledgerwatch/erigon/node.(*Node).Wait(...)
        github.com/ledgerwatch/erigon/node/node.go:266
github.com/ledgerwatch/erigon/turbo/node.(*ErigonNode).Serve(0xc063c0ec80)
        github.com/ledgerwatch/erigon/turbo/node/node.go:32 +0x7c
main.runErigon(0xc001116640?)
        github.com/ledgerwatch/erigon/cmd/erigon/main.go:67 +0x350
github.com/urfave/cli/v2.(*Command).Run(0xc001116640, 0xc001133840, {0xc000052070, 0x7, 0x7})
        github.com/urfave/cli/v2@v2.23.5/command.go:271 +0xaab
github.com/urfave/cli/v2.(*App).RunContext(0xc001150000, {0x2b545f0?, 0xc000056088}, {0xc000052070, 0x7, 0x7})
        github.com/urfave/cli/v2@v2.23.5/app.go:329 +0x665
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.23.5/app.go:306
main.main()
        github.com/ledgerwatch/erigon/cmd/erigon/main.go:37 +0x85
```

Also maybe this one is of importance. Found it in the middle of the error messages:

```
goroutine 20118553 [IO wait]:
internal/poll.runtime_pollWait(0x7f24b44d8360, 0x77)
        runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc07c51b880?, 0x0?, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitWrite(...)
        internal/poll/fd_poll_runtime.go:93
internal/poll.(*FD).WaitWrite(...)
        internal/poll/fd_unix.go:741
net.(*netFD).connect(0xc07c51b880, {0x2b565f8?, 0xc07a198b80}, {0xc07c9056f8?, 0x43527f?}, {0x2b414e0?, 0xc0851b3740?})
        net/fd_unix.go:141 +0x719
net.(*netFD).dial(0xc07c51b880, {0x2b565f8, 0xc07a198b80}, {0x2b60c70?, 0x0?}, {0x2b60c70?, 0xc080707ce0}, 0x585158?)
        net/sock_posix.go:149 +0x385
net.socket({0x2b565f8, 0xc07a198b80}, {0xc002db0218, 0x4}, 0x2, 0x1, 0x2b60c70?, 0x0?, {0x2b60c70, 0x0}, ...)
        net/sock_posix.go:70 +0x2b2
net.internetSocket({0x2b565f8, 0xc07a198b80}, {0xc002db0218, 0x4}, {0x2b60c70, 0x0}, {0x2b60c70, 0xc080707ce0}, 0xc?, 0x0, ...)
        net/ipsock_posix.go:142 +0xf8
net.(*sysDialer).doDialTCP(0xc08927f710, {0x2b565f8, 0xc07a198b80}, 0x0, 0x1dda640?)
        net/tcpsock_posix.go:68 +0xa5
net.(*sysDialer).dialTCP(0x3f53e26?, {0x2b565f8?, 0xc07a198b80?}, 0xc07c905988?, 0x49a0e5?)
        net/tcpsock_posix.go:64 +0x69
net.(*sysDialer).dialSingle(0xc08927f710, {0x2b565f8, 0xc07a198b80}, {0x2b4afe0?, 0xc080707ce0})
        net/dial.go:582 +0x214
net.(*sysDialer).dialSerial(0xc08927f710, {0x2b565f8, 0xc07a198b80}, {0xc095ae1670?, 0x1, 0x584635?})
        net/dial.go:550 +0x312
net.(*sysDialer).dialParallel(0x0?, {0x2b565f8?, 0xc07a198b80?}, {0xc095ae1670?, 0xc07a198b80?, 0x20df59e?}, {0x0?, 0xc002db0218?, 0xc07391bdc0?})
        net/dial.go:451 +0x413
net.(*Dialer).DialContext(0x3f18260, {0x2b565f8, 0xc07a198b80}, {0xc002db0218, 0x4}, {0xc08e434300, 0x13})
        net/dial.go:428 +0x705
github.com/anacrolix/torrent.NetworkDialer.Dial(...)
        github.com/anacrolix/torrent@v1.47.0/dialer.go:33
github.com/anacrolix/torrent.dialFromSocket({0x2b565f8?, 0xc07a198b80?}, {0x77185aa80998?, 0xc0006d5680?}, {0xc08e434300?, 0xc079fe8300?})
        github.com/anacrolix/torrent@v1.47.0/client.go:667 +0x46
github.com/anacrolix/torrent.DialFirst.func2()
        github.com/anacrolix/torrent@v1.47.0/client.go:639 +0x4b
created by github.com/anacrolix/torrent.DialFirst
        github.com/anacrolix/torrent@v1.47.0/client.go:637 +0x45e
```

Lots of those:

```
goroutine 718 [select, 851 minutes]:
github.com/anacrolix/torrent.(*trackerScraper).Run.func1()
        github.com/anacrolix/torrent@v1.47.0/tracker_scraper.go:207 +0xca
created by github.com/anacrolix/torrent.(*trackerScraper).Run
        github.com/anacrolix/torrent@v1.47.0/tracker_scraper.go:205 +0x12e

goroutine 524 [select, 851 minutes]:
github.com/anacrolix/torrent.(*trackerScraper).Run.func1()
        github.com/anacrolix/torrent@v1.47.0/tracker_scraper.go:207 +0xca
created by github.com/anacrolix/torrent.(*trackerScraper).Run
        github.com/anacrolix/torrent@v1.47.0/tracker_scraper.go:205 +0x12e

goroutine 640 [select, 851 minutes]:
github.com/anacrolix/torrent.(*trackerScraper).Run.func1()
        github.com/anacrolix/torrent@v1.47.0/tracker_scraper.go:207 +0xca
created by github.com/anacrolix/torrent.(*trackerScraper).Run
        github.com/anacrolix/torrent@v1.47.0/tracker_scraper.go:205 +0x12e

goroutine 958 [select, 851 minutes]:
github.com/anacrolix/torrent.(*trackerScraper).Run.func1()
        github.com/anacrolix/torrent@v1.47.0/tracker_scraper.go:207 +0xca
created by github.com/anacrolix/torrent.(*trackerScraper).Run
        github.com/anacrolix/torrent@v1.47.0/tracker_scraper.go:205 +0x12e

goroutine 957 [select, 851 minutes]:
github.com/anacrolix/torrent.(*trackerScraper).Run.func1()
        github.com/anacrolix/torrent@v1.47.0/tracker_scraper.go:207 +0xca
created by github.com/anacrolix/torrent.(*trackerScraper).Run
        github.com/anacrolix/torrent@v1.47.0/tracker_scraper.go:205 +0x12e
```

**Comment by harveyff** [comment]
I use the fork branch of matic to run, and I have not encountered this problem. I suggest you use it too
https://github.com/maticnetwork/erigon.git

**Comment by hexoscott** [comment]
Hi @theSwissAlex,

Which version are you running?  I can see a commit that looks to fix this issue on 29/01/2023.  Looks like this got into version 2.37.0.

**Comment by hexoscott** [comment]
Hi @theSwissAlex, if you're running a fork you'll need to wait until the upstream is pulled and takes the changes in version 2.37.0 from the erigon repo for this issue.  I'm closing the issue for now as that is out of our hands.
