### ISSUE TITLE
[2.29.0] Panic: putting the same entry twice not supported

### ISSUE THREAD

**Issue by Texnomic** [ledgerwatch/erigon#6977]
#### System information

Erigon version: `erigon version 2.39.0-stable-b5891e2c`

OS & Version: `Linux ethereum-erigon2 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

Erigon Command (with flags/config): `yaml file`

Concensus Layer: `Built-in LightClient`

Chain/Network: `mainnet`

#### Expected behaviour

Normal Operation.

#### Actual behaviour

```shell
INFO[02-25|15:04:17.803] [7/15 Execution] Executed blocks         number=16661331 blk/s=3.8 tx/s=520.0 Mgas/s=58.0 gasState=0.14 batch=148.0MB alloc=4.0GB sys=8.6GB
INFO[02-25|15:04:37.779] [7/15 Execution] Executed blocks         number=16661390 blk/s=3.0 tx/s=394.4 Mgas/s=45.4 gasState=0.14 batch=149.8MB alloc=4.4GB sys=8.6GB
INFO[02-25|15:04:57.706] [7/15 Execution] Executed blocks         number=16661449 blk/s=3.0 tx/s=370.8 Mgas/s=44.7 gasState=0.14 batch=151.6MB alloc=4.8GB sys=8.6GB
INFO[02-25|15:05:07.958] [txpool] stat                            block=16656408 pending=8144 baseFee=7882 queued=41209 alloc=2.6GB sys=8.6GB
INFO[02-25|15:05:17.666] [7/15 Execution] Executed blocks         number=16661513 blk/s=3.2 tx/s=428.3 Mgas/s=48.2 gasState=0.14 batch=153.6MB alloc=2.8GB sys=8.6GB
INFO[02-25|15:05:19.717] [p2p] GoodPeers                          eth67=11 eth66=1 eth68=2
INFO[02-25|15:05:37.968] [7/15 Execution] Executed blocks         number=16661570 blk/s=2.8 tx/s=363.8 Mgas/s=43.5 gasState=0.14 batch=155.4MB alloc=3.2GB sys=8.6GB
INFO[02-25|15:05:57.704] [7/15 Execution] Executed blocks         number=16661628 blk/s=2.9 tx/s=412.6 Mgas/s=43.4 gasState=0.14 batch=157.1MB alloc=3.6GB sys=8.6GB
INFO[02-25|15:06:07.922] [txpool] stat                            block=16656408 pending=8193 baseFee=7905 queued=41584 alloc=3.8GB sys=8.6GB
INFO[02-25|15:06:17.664] [7/15 Execution] Executed blocks         number=16661686 blk/s=2.9 tx/s=390.9 Mgas/s=43.9 gasState=0.15 batch=158.8MB alloc=3.9GB sys=8.6GB
INFO[02-25|15:06:37.667] [7/15 Execution] Executed blocks         number=16661744 blk/s=2.9 tx/s=359.3 Mgas/s=43.9 gasState=0.15 batch=160.5MB alloc=4.3GB sys=8.6GB
INFO[02-25|15:06:57.913] [7/15 Execution] Executed blocks         number=16661801 blk/s=2.8 tx/s=377.0 Mgas/s=43.3 gasState=0.15 batch=162.2MB alloc=4.7GB sys=8.6GB
INFO[02-25|15:07:07.916] [txpool] stat                            block=16656408 pending=8248 baseFee=7925 queued=42038 alloc=2.6GB sys=8.6GB
panic: putting the same entry twice not supported

goroutine 4627 [running]:
github.com/libp2p/go-libp2p-pubsub/timecache.FirstSeenCache.Add({0xc0a7b443f0?, 0xc0a7b44420?, 0xc095243710?, 0xc0a7692a20?}, {0xc1861c03a8, 0x14})
        github.com/libp2p/go-libp2p-pubsub@v0.9.0/timecache/first_seen_cache.go:32 +0x28d
github.com/libp2p/go-libp2p-pubsub.(*PubSub).markSeen(0xc0a7afb8c0, {0xc1861c03a8, 0x14})
        github.com/libp2p/go-libp2p-pubsub@v0.9.0/pubsub.go:1002 +0x102
github.com/libp2p/go-libp2p-pubsub.(*PubSub).pushMsg(0xc0a7afb8c0, 0xc0c5190a80)
        github.com/libp2p/go-libp2p-pubsub@v0.9.0/pubsub.go:1168 +0x34c
github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleIncomingRPC(0xc0a7afb8c0, 0xc05e2b4070)
        github.com/libp2p/go-libp2p-pubsub@v0.9.0/pubsub.go:1109 +0x8c5
github.com/libp2p/go-libp2p-pubsub.(*PubSub).processLoop(0xc0a7afb8c0, {0x2c34890, 0xc000134020})
        github.com/libp2p/go-libp2p-pubsub@v0.9.0/pubsub.go:639 +0xb4c
created by github.com/libp2p/go-libp2p-pubsub.NewPubSub
        github.com/libp2p/go-libp2p-pubsub@v0.9.0/pubsub.go:335 +0xd6a
```

**Comment by temuera** [comment]
same problem+1

**Comment by AskAlexSharov** [comment]
Fixed in devel branch
