### ISSUE TITLE
SIGSEGV upon startup in version 2.40.1 and 2.40.0 (x86 version)

### ISSUE THREAD

**Issue by aldredb** [ledgerwatch/erigon#7130]
#### System information

Erigon version: `erigon version 2.40.1-stable`

OS & Version: Ubuntu 22.04 (x86)

Commit hash: Binary downloaded from https://github.com/ledgerwatch/erigon/releases/download/v2.40.1/erigon_2.40.1_linux_amd64.tar.gz,  https://github.com/ledgerwatch/erigon/releases/download/v2.40.0/erigon_2.40.0_linux_amd64.tar.gz and https://github.com/ledgerwatch/erigon/releases/download/v2.39.0/erigon_2.39.0_linux_amd64.tar.gz

Erigon Command (with flags/config):

```
erigon \
 --chain bor-mainnet \
 --torrent.download.rate 1gb \
 --datadir /data/erigon \
 --private.api.addr 127.0.0.1:9090 \
 --authrpc.addr 127.0.0.1 \
 --http.addr 0.0.0.0 \
 --http.port 8545 \
 --http.vhosts "*" \
 --http.corsdomain "*" \
 --metrics \
 --http.api "eth,debug,net,trace,web3,erigon" \
 --ws \
 --bor.heimdall http://127.0.0.1:1317 \
 --maxpeers 20
```

Chain/Network: Polygon

#### Expected behaviour

Starts OK

#### Actual behaviour

SIGSEGV error and crashes

#### Steps to reproduce the behaviour

Start erigon. data folder is empty and permission is fine. Tested on both Intel and AMD CPUs.

FYI:
[ARM version](https://github.com/ledgerwatch/erigon/releases/download/v2.40.1/erigon_2.40.1_linux_arm64.tar.gz) - works OK

[x86 2.31.0 version](https://github.com/ledgerwatch/erigon/releases/download/v2.31.0/erigon_2.31.0_linux_amd64.tar.gz) - works OK

#### Backtrace

````
usr/bin/erigon  --chain bor-mainnet  --torrent.download.rate 1gb  --datadir /data/erigon  --private.api.addr 127.0.0.1:9090--authrpc.addr 127.0.0.1  --http.addr 0.0.0.0  --http.port 8545  --http.vhosts "*"  --http.corsdomain "*"  --metrics  --http.api "eth,debug,net,trace,web3,erigon"  --ws  --bor.heimdall http://127.0.0.1:1317
WARN[03-18|01:10:02.372] no log dir set, console logging only
INFO[03-18|01:10:02.372] Starting metrics server                  addr=http://127.0.0.1:6060/debug/metrics/prometheus
WARN[03-18|01:10:02.377] no log dir set, console logging only
INFO[03-18|01:10:02.377] Build info                               git_branch= git_tag= git_commit=
INFO[03-18|01:10:02.377] Starting Erigon on Bor Mainnet...
INFO[03-18|01:10:02.378] Maximum peer count                       ETH=100 total=100
INFO[03-18|01:10:02.378] starting HTTP APIs                       APIs=eth,debug,net,trace,web3,erigon
INFO[03-18|01:10:02.378] torrent verbosity                        level=WRN
INFO[03-18|01:10:04.480] Set global gas cap                       cap=50000000
INFO[03-18|01:10:04.481] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=1gb upload.rate=4mb
INFO[03-18|01:10:04.481] Opening Database                         label=chaindata path=/data/erigon/chaindata
INFO[03-18|01:10:04.484] Initialised chain configuration          config="{ChainID: 137, Homestead: 0, DAO: <nil>, DAO Support: true, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000,Arrow Glacier: <nil>, Gray Glacier: <nil>, Terminal Total Difficulty: <nil>, Merge Netsplit: <nil>, Shanghai: <nil>, Cancun: <nil>, Sharding: <nil>, Prague: <nil>, Engine: bor}" genesis=0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b
INFO[03-18|01:10:04.484] Effective                                prune_flags= snapshot_flags="--snapshots=true" history.v3=false
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f180a7fd072 pc=0x7417c74a6a7f]

runtime stack:
runtime.throw({0x25b9218?, 0x0?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f180a7fb7d8 sp=0x7f180a7fb7a8 pc=0x45837d
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:819 +0x369 fp=0x7f180a7fb828 sp=0x7f180a7fb7d8 pc=0x46eda9

goroutine 230 [syscall]:
runtime.cgocall(0x1d37140, 0xc0012ddd98)
        /usr/local/go/src/runtime/cgocall.go:158 +0x5c fp=0xc0012ddd70 sp=0xc0012ddd38 pc=0x421e7c
net._C2func_getaddrinfo(0xc00077e030, 0x0, 0xc000776180, 0xc00076a008)
        _cgo_gotypes.go:94 +0x56 fp=0xc0012ddd98 sp=0xc0012ddd70 pc=0x5959d6
net.cgoLookupIPCNAME.func1({0xc00077e030, 0x7f184a59bd28?, 0x30?}, 0xc0012c24b7?, 0xc000776120?)
        /usr/local/go/src/net/cgo_unix.go:160 +0x9f fp=0xc0012dddf0 sp=0xc0012ddd98 pc=0x59771f
net.cgoLookupIPCNAME({0x23ee045, 0x2}, {0xc0012c24b7, 0x16})
        /usr/local/go/src/net/cgo_unix.go:160 +0x173 fp=0xc0012ddf38 sp=0xc0012dddf0 pc=0x596f73
net.cgoIPLookup(0xc0003da750?, {0x23ee045?, 0xc0012ddfd0?}, {0xc0012c24b7?, 0xc0012ceee0?})
        /usr/local/go/src/net/cgo_unix.go:217 +0x3b fp=0xc0012ddfa8 sp=0xc0012ddf38 pc=0x5977db
net.cgoLookupIP.func1()
        /usr/local/go/src/net/cgo_unix.go:227 +0x36 fp=0xc0012ddfe0 sp=0xc0012ddfa8 pc=0x597c16
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0012ddfe8 sp=0xc0012ddfe0 pc=0x48ca01
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:227 +0x12a
...
````

See whole backtrace here: [backtrace.txt](https://github.com/ledgerwatch/erigon/files/11007170/backtrace.txt)

**Comment by AskAlexSharov** [comment]
Try add —downloader.verify

**Comment by aldredb** [comment]
```
sudo erigon \
 --chain bor-mainnet \
 --torrent.download.rate 1gb \
 --datadir /data/erigon \
 --private.api.addr 127.0.0.1:9090 \
 --authrpc.addr 127.0.0.1 \
 --http.addr 0.0.0.0 \
 --http.port 8545 \
 --http.vhosts "*" \
 --http.corsdomain "*" \
 --metrics \
 --http.api "eth,debug,net,trace,web3,erigon" \
 --ws \
 --bor.heimdall http://127.0.0.1:1317 \
 --maxpeers 20 \
 —-downloader.verify
```

Same result:

```
WARN[03-18|06:44:50.452] no log dir set, console logging only
INFO[03-18|06:44:50.452] Starting metrics server                  addr=http://127.0.0.1:6060/debug/metrics/prometheus
WARN[03-18|06:44:50.459] no log dir set, console logging only
INFO[03-18|06:44:50.459] Build info                               git_branch= git_tag= git_commit=
INFO[03-18|06:44:50.459] Starting Erigon on Bor Mainnet...
INFO[03-18|06:44:50.459] Maximum peer count                       ETH=20 total=20
INFO[03-18|06:44:50.459] starting HTTP APIs                       APIs=eth,debug,net,trace,web3,erigon
INFO[03-18|06:44:50.459] torrent verbosity                        level=WRN
INFO[03-18|06:44:52.561] Set global gas cap                       cap=50000000
INFO[03-18|06:44:52.562] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=1gb upload.rate=4mb
INFO[03-18|06:44:52.562] Opening Database                         label=chaindata path=/data/erigon/chaindata
INFO[03-18|06:44:52.564] Initialised chain configuration          config="{ChainID: 137, Homestead: 0, DAO: <nil>, DAO Support: true, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000,Arrow Glacier: <nil>, Gray Glacier: <nil>, Terminal Total Difficulty: <nil>, Merge Netsplit: <nil>, Shanghai: <nil>, Cancun: <nil>, Sharding: <nil>, Prague: <nil>, Engine: bor}" genesis=0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b
INFO[03-18|06:44:52.564] Effective                                prune_flags= snapshot_flags="--snapshots=true" history.v3=false
INFO[03-18|06:44:52.566] Initialising Ethereum protocol           network=137
INFO[03-18|06:44:52.572] Starting private RPC server              on=127.0.0.1:9090
INFO[03-18|06:44:52.572] new subscription to logs established
INFO[03-18|06:44:52.572] rpc filters: subscribing to Erigon events
INFO[03-18|06:44:52.572] New txs subscriber joined
INFO[03-18|06:44:52.572] new subscription to newHeaders established
INFO[03-18|06:44:52.572] Reading JWT secret                       path=/data/erigon/jwt.hex
INFO[03-18|06:44:52.573] HTTP endpoint opened for Engine API      url=127.0.0.1:8551 ws=true ws.compression=true
INFO[03-18|06:44:52.573] HTTP endpoint opened                     url=[::]:8545 ws=true ws.compression=true grpc=false
INFO[03-18|06:44:52.578] Started P2P networking                   version=67 self=enode://5239473eac912ba02d0149febaf056ec7480729c5f5df792f6f1a66c91e6e3975983d7069dee614c65c148055ef181db652b8c16093a043fc90a8b683ea846e7@127.0.0.1:30303 name=erigon/v2.40.1/linux-amd64/go1.19.5
INFO[03-18|06:44:52.580] Started P2P networking                   version=68 self=enode://5239473eac912ba02d0149febaf056ec7480729c5f5df792f6f1a66c91e6e3975983d7069dee614c65c148055ef181db652b8c16093a043fc90a8b683ea846e7@127.0.0.1:30304 name=erigon/v2.40.1/linux-amd64/go1.19.5
INFO[03-18|06:44:52.583] [txpool] Started
INFO[03-18|06:44:52.583] [1/15 Snapshots] Fetching torrent files metadata
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f84067fd072 pc=0x6e8343806a7f]
```

**Comment by whidrasl** [comment]
same on Goerli

**Comment by AskAlexSharov** [comment]
@0xStrobe show 100 log lines

**Comment by 0xStrobe** [comment]
Turns out it was already fixed if compiled binary from latest devel brand instead of using a precompiled release. :)

Haven't tried with polygon so not sure if it would work for OP too.

**Comment by DefiDebauchery** [comment]
Can confirm for v2.41, as well. The pre-compiled binary release failed with the same errors; running the binary compiled from source works fine.
