### ISSUE TITLE
Panic crash during node sync (slice bounds out of range [:32] with capacity 4

### ISSUE THREAD

**Issue by NicolasWent** [ledgerwatch/erigon#7161]
#### System information

Erigon version: `erigon version 2.40.1-stable-94b4cee5`

OS & Version: `Debian GNU/Linux 11 (bullseye)`

uname -r (kernel version): `5.10.0-21-amd64`

go version: `go version go1.20.2 linux/amd64`

Commit hash: `stable branch`

Erigon Command (with flags/config):
`erigon --datadir=~/ethereum --snapshots=true --prune=hrtc --torrent.download.rate=512mb --torrent.upload.rate=256mb  --fakepow=true`

Concensus Layer: Not sure what to put there, did not change anything and just ran the above command

Concensus Layer Command (with flags/config): Did not change anything

Chain/Network: Ethereum mainnet

#### Expected behaviour

I was synching the node since 3-4 days, I hope it would sync.

#### Actual behaviour

At step [8/15 HashState] it just crashed

#### Steps to reproduce the behaviour

I first ran these commands to prevent localhost connections: https://github.com/ledgerwatch/erigon/issues/6034#issuecomment-1355853027
I just ran the command above in a fresh linux.

#### Backtrace

````
INFO[03-21|17:54:10.360] [8/15 HashState] ETL [1/2] Extracting    current_prefix=7be8076f alloc=5.7GB sys=10.1GB
INFO[03-21|17:54:13.677] [downloader] error sending packet: write udp4 0.0.0.0:42069->172.174.141.156:22069: sendto: operation not permitted torrent_log_type=unknown or=NIL
WARN[03-21|17:54:13.983] Could not send beacon block to ETH1      err="missing attestation data"
INFO[03-21|17:54:15.611] [downloader] error sending packet: write udp4 0.0.0.0:42069->100.27.45.47:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:54:22.277] [downloader] error sending packet: write udp4 0.0.0.0:42069->100.27.45.47:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:54:24.511] [downloader] error sending packet: write udp4 0.0.0.0:42069->100.2.1.41:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:54:25.611] [downloader] error sending packet: write udp4 0.0.0.0:42069->172.70.13.219:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
WARN[03-21|17:54:27.034] Could not send beacon block to ETH1      err="missing attestation data"
INFO[03-21|17:54:27.511] [downloader] error sending packet: write udp4 0.0.0.0:42069->172.13.72.239:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:54:28.411] [downloader] error sending packet: write udp4 0.0.0.0:42069->172.248.195.186:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:54:30.410] [downloader] error sending packet: write udp4 0.0.0.0:42069->100.27.45.47:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:54:31.177] [downloader] error sending packet: write udp4 0.0.0.0:42069->100.2.1.41:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:54:32.277] [downloader] error sending packet: write udp4 0.0.0.0:42069->172.70.13.219:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:54:32.512] [downloader] error sending packet: write udp4 0.0.0.0:42069->172.13.72.239:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:54:33.411] [downloader] error sending packet: write udp4 0.0.0.0:42069->172.248.195.186:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:54:37.077] [downloader] error sending packet: write udp4 0.0.0.0:42069->100.27.45.47:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:54:37.700] [txpool] stat                            block=16499999 pending=0 baseFee=0 queued=30000 alloc=3.7GB sys=10.1GB
INFO[03-21|17:54:39.016] [LightClient] P2P                        peers=11
WARN[03-21|17:54:39.016] Could not send beacon block to ETH1      err="missing attestation data"
INFO[03-21|17:54:40.346] [8/15 HashState] ETL [1/2] Extracting    current_prefix=7f268357 alloc=3.8GB sys=10.1GB
WARN[03-21|17:54:54.212] Could not send beacon block to ETH1      err="missing attestation data"
INFO[03-21|17:55:11.717] [8/15 HashState] ETL [1/2] Extracting    current_prefix=7fc66500 alloc=5.0GB sys=10.1GB
WARN[03-21|17:55:26.512] Could not send beacon block to ETH1      err="missing attestation data"
INFO[03-21|17:55:28.511] [downloader] error sending packet: write udp4 0.0.0.0:42069->172.70.19.153:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:55:31.011] [downloader] error sending packet: write udp4 0.0.0.0:42069->100.27.45.47:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:55:35.177] [downloader] error sending packet: write udp4 0.0.0.0:42069->172.70.19.153:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:55:36.598] [p2p] GoodPeers                          eth67=84 eth66=16 eth68=100
INFO[03-21|17:55:37.678] [downloader] error sending packet: write udp4 0.0.0.0:42069->100.27.45.47:42069: sendto: operation not permitted torrent_log_type=unknown or=NIL
INFO[03-21|17:55:37.691] [LightClient] P2P                        peers=12
INFO[03-21|17:55:37.692] [txpool] stat                            block=16499999 pending=0 baseFee=0 queued=30000 alloc=4.5GB sys=10.1GB
panic: runtime error: slice bounds out of range [:32] with capacity 4

goroutine 93523290 [running]:
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxCursor).Next(0xc0a9704780)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230306114514-2c4c92fd1fce/kv/mdbx/kv_mdbx.go:1247 +0x27e
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*cursor2iter).Next(0xc0a83259a0)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230306114514-2c4c92fd1fce/kv/mdbx/kv_mdbx.go:1793 +0xc8
github.com/ledgerwatch/erigon/eth/stagedsync.parallelWarmup.func1.1({0x2dcb0c8, 0xc0a97046c0})
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_hashstate.go:326 +0xc2
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).View(0xc12dd8c540?, {0x2daf688?, 0xc130c0eeb0?}, 0xc1307d82c0)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230306114514-2c4c92fd1fce/kv/mdbx/kv_mdbx.go:649 +0xa6
github.com/ledgerwatch/erigon/eth/stagedsync.parallelWarmup.func1()
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_hashstate.go:320 +0xb8
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
````

**Comment by AskAlexSharov** [comment]
Seems you have some bad value in db. Maybe hardware corruption (or no space left on disk). 

Can you try: 
use tools like https://www.memtest86.com to test RAM and tools like https://www.smartmontools.org to test Disk

also can try:
make db-tools
./build/bin/mdbx_chk <datadir>/chaindata
