### ISSUE TITLE
[BUG] fail to decode gossip packet

### ISSUE THREAD

**Issue by TangMonk** [ledgerwatch/erigon#7168]
#### System information

Erigon version: `2.30.0-stable-35f493c5`
OS & Version: Linux
Chain/Network:  ethereum mainnet

For the past few days, I've had Erigon up and running, but today it seems to be encountering some problems.

error with following:
```
Could not validate update                err="invalid sync committee"
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
fail to decode gossip packet             err="incorrect size" topic=/eth2/4a26c58b/beacon_block/ssz_snappy pkt=*cltypes.SignedBeaconBlockBellatrix
```

**Comment by TangMonk** [comment]
So I tried to switch to latest erigon verion of `2.40.1-stable`, but error still:

```
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7fe426ffe072 pc=0x7492a0583a7f]
runtime stack:
runtime.throw({0x25b9218?, 0x4?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7fe426ffc7d8 sp=0x7fe426ffc7a8 pc=0x45837d
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:819 +0x369 fp=0x7fe426ffc828 sp=0x7fe426ffc7d8 pc=0x46eda9
goroutine 88 [syscall]:
runtime.cgocall(0x1d37140, 0xc098314598)
        /usr/local/go/src/runtime/cgocall.go:158 +0x5c fp=0xc098314570 sp=0xc098314538 pc=0x421e7c
net._C2func_getaddrinfo(0xc0982821e0, 0x0, 0xc003d9c7e0, 0xc00011e610)
        _cgo_gotypes.go:94 +0x56 fp=0xc098314598 sp=0xc098314570 pc=0x5959d6
net.cgoLookupIPCNAME.func1({0xc0982821e0, 0xc0055f23c0?, 0xc0973a4fc0?}, 0xc09813e2a7?, 0xc0973a4fc0?)
        /usr/local/go/src/net/cgo_unix.go:160 +0x9f fp=0xc0983145f0 sp=0xc098314598 pc=0x59771f
net.cgoLookupIPCNAME({0x23ee045, 0x2}, {0xc09813e2a7, 0x1a})
        /usr/local/go/src/net/cgo_unix.go:160 +0x173 fp=0xc098314738 sp=0xc0983145f0 pc=0x596f73
net.cgoIPLookup(0xc098314728?, {0x23ee045?, 0x149f1ce?}, {0xc09813e2a7?, 0x0?})
        /usr/local/go/src/net/cgo_unix.go:217 +0x3b fp=0xc0983147a8 sp=0xc098314738 pc=0x5977db
net.cgoLookupIP.func1()
        /usr/local/go/src/net/cgo_unix.go:227 +0x36 fp=0xc0983147e0 sp=0xc0983147a8 pc=0x597c16
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0983147e8 sp=0xc0983147e0 pc=0x48ca01
created by net.cgoLookupIP
```

**Comment by TangMonk** [comment]
> ^^ is this true? ^^ I am on v2.33.2 and would like to go to v2.40.1 as well

it is true, there are someone ran into the same problem
