### ISSUE TITLE
prometheus install doc out of date?

### ISSUE THREAD

**Issue by TangMonk** [ledgerwatch/erigon#7180]
not works when `docker compose up -d prometheus grafana or make prometheus`

```
$sudo docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS                          PORTS     NAMES
a7c187339d52   grafana/grafana:9.3.6     "/run.sh"                12 minutes ago   Restarting (1) 43 seconds ago             erigon-grafana-1
6e4f4b4c5c96   prom/prometheus:v2.42.0   "/bin/prometheus --l…"   12 minutes ago   Restarting (2) 37 seconds ago             erigon-prometheus-1
```

```
$sudo docker logs -f 6e4f4b4c5c96

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x7ffff521cee3, 0xb}, 0x14, {0x3d8ba20, 0xc000517270})
	/app/promql/query_logger.go:121 +0x3cd
main.main()
	/app/cmd/prometheus/main.go:618 +0x69d3
ts=2023-03-25T07:15:47.419Z caller=query_logger.go:91 level=error component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x7fffd76e5ee3, 0xb}, 0x14, {0x3d8ba20, 0xc000888d70})
	/app/promql/query_logger.go:121 +0x3cd
main.main()
	/app/cmd/prometheus/main.go:618 +0x69d3
ts=2023-03-25T07:16:47.784Z caller=query_logger.go:91 level=error component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x7fff26db8ee3, 0xb}, 0x14, {0x3d8ba20, 0xc0000c7770})
	/app/promql/query_logger.go:121 +0x3cd
main.main()
	/app/cmd/prometheus/main.go:618 +0x69d3
```

```
$ sudo docker logs -f a7c187339d52

You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
```

**Comment by AskAlexSharov** [comment]
permission denied - is permission denied :-)
docker-compose.yml has
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000} # Uses erigon user from Dockerfile
and
    user: "472:0" # required for grafana version >= 7.3

i can find same numbers in `make setup_xdg_data_home`

**Comment by TangMonk** [comment]
why `docker-compose.yml` file missed in `cmd/prometheus` folder

<img width="719" alt="image" src="https://user-images.githubusercontent.com/3498786/227703995-f5be2431-13b5-499e-830f-415023666813.png">

**Comment by AskAlexSharov** [comment]
@TangMonk because it's in root folder

**Comment by TangMonk** [comment]
@AskAlexSharov Ok, I got

**Comment by TangMonk** [comment]
> permission denied - is permission denied :-)
> 
> I see in docker-compose.yml user: DOCKERUID:−1000:{DOCKER_GID:-1000} # Uses erigon user from Dockerfile and user: "472:0" # required for grafana version >= 7.3
> 
> i can find same numbers in `make setup_xdg_data_home`

What's your mean, Am I need to run `make setup_xdg_data_home`?

**Comment by TangMonk** [comment]
Oh, I `make setup_xdg_data_home` then grafana container started, but prometheus not

**Comment by TangMonk** [comment]
I got my id:
```
$ id
uid=1000(david) gid=1000(david) groups=1000(david),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),110(lxd)
```

and changed to `1000`
```
prometheus:
    image: prom/prometheus:v2.42.0
    user: "1000:1000"
```

but still same problem with prometheus

**Comment by TangMonk** [comment]
I changed to `user: "0:0"`, works
