### ISSUE TITLE
RPCDaemon in docker-compose fails invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by syahrul12345** [ledgerwatch/erigon#7601]
I am using the docker-compose to run erigon component seperately. RPC daemon is currently failing with this error:
```
erigon-code-rpcdaemon-1   | [INFO] [05-30|03:52:06.551] logging to file system                   log dir=/home/erigon/.local/share/erigon/logs file prefix=rpcdaemon log level=info json=false
erigon-code-rpcdaemon-1   | [INFO] [05-30|03:52:06.552] DB schemas compatible                    reader=6.0.0 database=6.0.0
erigon-code-rpcdaemon-1   | panic: runtime error: invalid memory address or nil pointer dereference
erigon-code-rpcdaemon-1   | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x157a872]
erigon-code-rpcdaemon-1   | 
erigon-code-rpcdaemon-1   | goroutine 1 [running]:
erigon-code-rpcdaemon-1   | github.com/ledgerwatch/erigon/cmd/rpcdaemon/cli.RemoteServices.func2({0x208c380?, 0xc001328960})
erigon-code-rpcdaemon-1   | 	github.com/ledgerwatch/erigon/cmd/rpcdaemon/cli/config.go:317 +0x52
erigon-code-rpcdaemon-1   | github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).View(0x207a690?, {0x207a6c8?, 0xc00004a010?}, 0xc00133cf30)
erigon-code-rpcdaemon-1   | 	github.com/ledgerwatch/erigon-lib@v0.0.0-20230529131121-c7c31ee01f09/kv/mdbx/kv_mdbx.go:650 +0xa6
erigon-code-rpcdaemon-1   | github.com/ledgerwatch/erigon/cmd/rpcdaemon/cli.RemoteServices({_, _}, {0x1, {0x7ffc3099ef20, 0xb}, 0x0, 0x1, {0x7ffc3099ef54, 0x20}, {{0x7ffc3099ef54, ...}, ...}, ...}, ...)
erigon-code-rpcdaemon-1   | 	github.com/ledgerwatch/erigon/cmd/rpcdaemon/cli/config.go:316 +0xe62
erigon-code-rpcdaemon-1   | main.main.func1(0x2bdd760?, {0x1969885?, 0x7?, 0x7?})
erigon-code-rpcdaemon-1   | 	github.com/ledgerwatch/erigon/cmd/rpcdaemon/main.go:27 +0x225
erigon-code-rpcdaemon-1   | github.com/spf13/cobra.(*Command).execute(0x2bdd760, {0xc000040090, 0x7, 0x7})
erigon-code-rpcdaemon-1   | 	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
erigon-code-rpcdaemon-1   | github.com/spf13/cobra.(*Command).ExecuteC(0x2bdd760)
erigon-code-rpcdaemon-1   | 	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
erigon-code-rpcdaemon-1   | github.com/spf13/cobra.(*Command).Execute(...)
erigon-code-rpcdaemon-1   | 	github.com/spf13/cobra@v1.7.0/command.go:992
erigon-code-rpcdaemon-1   | github.com/spf13/cobra.(*Command).ExecuteContext(...)
erigon-code-rpcdaemon-1   | 	github.com/spf13/cobra@v1.7.0/command.go:985
erigon-code-rpcdaemon-1   | main.main()

```
I am using the image ` thorax/erigon:v2.43.1`

**Comment by syahrul12345** [comment]
All other services are working fine

**Comment by geomad** [comment]
This happens for me as well on  git_branch=stable git_tag=v2.44.0-dirty git_commit=f4f10f3b7cad36d6b3e7985cfe974764df53d8f7 without docker.

When running with rpc embed with erigon everything works fine. When trying to run as a seperate proccess it looks like `--datadir` causes the crash (doesn't crash without this flag)

```
Started rpcdaemon.service - Erigon rpc daemon.
[INFO] [06-04|00:16:18.221] logging to file system                   log dir=/chain/erigon/logs file prefix=rpcdaemon log level=info json=false
[INFO] [06-04|00:16:18.223] DB schemas compatible                    reader=6.0.0 database=6.0.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x15789b2]
goroutine 1 [running]:
github.com/ledgerwatch/erigon/cmd/rpcdaemon/cli.RemoteServices.func2({0x2086490?, 0xc001510b40})
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/cli/config.go:315 +0x52
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).View(0x20747b0?, {0x20747e8?, 0xc000044070?}, 0xc00158eea0)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230602102715-f166e7deb76f/kv/mdbx/kv_mdbx.go:650 +0xa6
github.com/ledgerwatch/erigon/cmd/rpcdaemon/cli.RemoteServices({_, _}, {0x1, {0x7fff9800cd87, 0xe}, 0x0, 0x1, {0x7fff9800cd52, 0xd}, {{0x7fff9800cd52, ...}, ...}, ...}, ...)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/cli/config.go:314 +0xe62
main.main.func1(0x2bd7e80?, {0x1963781?, 0xd?, 0xd?})
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/main.go:27 +0x225
github.com/spf13/cobra.(*Command).execute(0x2bd7e80, {0xc0000400f0, 0xd, 0xd})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x2bd7e80)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.7.0/command.go:985
main.main()
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/main.go:48 +0xfe
rpcdaemon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
rpcdaemon.service: Failed with result 'exit-code'.
```

**Comment by oddaf** [comment]
Same here, exact same log, tried both with latest stable version and devel. I'm not using docker.

**Comment by AskAlexSharov** [comment]
thank you
fixed by https://github.com/ledgerwatch/erigon/pull/7657
released https://github.com/ledgerwatch/erigon/releases/tag/v2.44.1
