### ISSUE TITLE
Polygon testnet panics

### ISSUE THREAD

**Issue by mikolajsobolewski** [ledgerwatch/erigon#7741]
Erigon version: `erigon version 2.45.1-stable-29f8e97

Polygon 2.45.2 has the same behavior

#### Backtrace

````
[WARN] [06-15|14:42:57.066] [downloader] Rejected header marked as bad hash=0x55d66e5a016431162ccc9d622ca622c2a511f2ea121c0496ccd1f4b03290992e height=36881217
panic: no gaps in tx ids are allowed: block 36777233 does jump from 292567633 to 292567656

goroutine 4511 [running]:
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs.func3.1({0x7ccfe874125c?, 0xc0775f01b8?, 0x8?}, {0x7ccfe8741264?, 0x22fb320?, 0x12?})
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1429 +0x314
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).ForAmount(0x2cb0370?, {0x247f50d?, 0xd17b2f2cba556066?}, {0xc0775f01b8, 0x8, 0x8}, 0x13, 0xc077c72780)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20230607134918-6106e5abdf0b/kv/mdbx/kv_mdbx.go:1911 +0x1a8
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs.func3({0x2cb0370, 0xc0747f1680}, {0x7d4680e53fc8?, 0x8?, 0x42360f0?}, {0x7d4680e53fd0?, 0x0?, 0xc0754fb278?})
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1426 +0x85c
github.com/ledgerwatch/erigon-lib/kv.BigChunks.func1({0x2cb0370, 0xc0747f1680})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20230607134918-6106e5abdf0b/kv/helpers.go:70 +0x1eb
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).View(0xdf8475800?, {0x2c92978?, 0xc00012e020?}, 0xc07760ff00)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20230607134918-6106e5abdf0b/kv/mdbx/kv_mdbx.go:650 +0xa6
github.com/ledgerwatch/erigon-lib/kv.BigChunks({0x2c99f78, 0xc0005424e0}, {0x246e5ff, 0xf}, {0xc0775f01c8, 0x8, 0x8}, 0xc0766da750)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20230607134918-6106e5abdf0b/kv/helpers.go:48 +0x192
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs({0x2c92940?, 0xc00053e140}, {0x2c99f78?, 0xc0005424e0}, 0x2312c28, 0x2313010, 0xc0754fba20, 0x1, 0x4, {0x2ca4da8, ...}, ...)
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1382 +0x716
github.com/ledgerwatch/erigon/turbo/snapshotsync.dumpBlocksRange({_, _}, _, _, {_, _}, {_, _}, _, {0x2c99f78, ...}, ...)
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1234 +0xbd1
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpBlocks({0x2c92940, 0xc00053e140}, 0x2312c28, 0x2313010, 0x7a120, {0xc001c73668, 0x12}, {0xc001c73680, 0x17}, 0x11702ef8, ...)
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1164 +0x27a
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocks(0xc015ca4e00, {0x2c92940, 0xc00053e140}, 0x2312c28, 0x2313010, 0x4)
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1077 +0x3a5
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground.func1()
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1147 +0x105
created by github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground
	github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1139 +0xd3````

**Comment by ArielTM** [comment]
I'm afraid this happens to us also on polygon mainnet . running 2.45.2

```
INFO[06-15|15:21:35.235] RPC Daemon notified of new headers       from=43937399 to=43938423 hash=0x9cb67141aa5ff67819b68656cf0f03f60dd1f3bc938aac14596c8c9b5a2b63fb header sending=18.066794ms log sending=262ns
INFO[06-15|15:21:35.237] Commit cycle                             in=49.962083762s                                                                                                                                                
INFO[06-15|15:21:35.237] Timings (slower than 50ms)               Snapshots=66ms Headers=2m1.189s CumulativeIndex=109ms BlockHashes=5.788s Bodies=18m36.108s Senders=18.286s Execution=47m2.797s HashState=30m42.648s Intermediate
Hashes=41m1.357s CallTraces=7m2.466s AccountHistoryIndex=3m38.762s StorageHistoryIndex=16m44.742s LogIndex=10m48.893s TxLookup=5m27.802s
INFO[06-15|15:21:35.238] Tables                                   PlainState=261.7GB AccountChangeSet=256.2GB StorageChangeSet=745.6GB BlockTransaction=7.5GB TransactionLog=2.8TB FreeList=93.6MB ReclaimableSpace=374.4GB
INFO[06-15|15:21:35.618] [2/15 Headers] Waiting for headers...    from=43938423                                                                                                                                                   
panic: no gaps in tx ids are allowed: block 43806076 does jump from 2856697172 to 2856697227
                                                                                                                                                                                                                                  
goroutine 3920929 [running]:                                                                                     
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs.func3.1({0xf067ab3ad546?, 0x40e9c9b550?, 0x8?}, {0xf067ab3ad54e?, 0x0?, 0xda4a?})
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1429 +0x270                                                                                                                                           
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).ForAmount(0x29de6b0?, {0x21ada4a?, 0x853d8fb4df5219ff?}, {0x40e9c9b550, 0x8, 0x8}, 0x22, 0x4182625680)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230611135853-ba7975b03348/kv/mdbx/kv_mdbx.go:1906 +0x140
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs.func3({0x29de6b0, 0x417054b020}, {0xf08c10317e88?, 0x8?, 0x4107fdd228?}, {0xf08c10317e90?, 0x0?, 0x4731c0?})
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1426 +0x664
github.com/ledgerwatch/erigon-lib/kv.BigChunks.func1({0x29de6b0, 0x417054b020})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230611135853-ba7975b03348/kv/helpers.go:70 +0x158
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).View(0xdf8475800?, {0x29c0fd0?, 0x4000130040?}, 0x4109065700)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230611135853-ba7975b03348/kv/mdbx/kv_mdbx.go:650 +0x90
github.com/ledgerwatch/erigon-lib/kv.BigChunks({0x29c8638, 0x40008941a0}, {0x219cb3b, 0xf}, {0x40e9c9b560, 0x8, 0x8}, 0x4106cc1110)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230611135853-ba7975b03348/kv/helpers.go:48 +0x174
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs({0x29c0f98?, 0x4000936820}, {0x29c8638?, 0x40008941a0}, 0x29c6d30, 0x29c7118, 0x4107fdd9e8, 0x1, 0x4, {0x29d3388?, ...}, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1382 +0x580
github.com/ledgerwatch/erigon/turbo/snapshotsync.dumpBlocksRange({_, _}, _, _, {_, _}, {_, _}, _, {_, ...}, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1234 +0x7e8
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpBlocks({0x29c0f98, 0x4000936820}, 0x29c6d30, 0x29c7118, 0x7a120, {0x400084c800, 0x19}, {0x400084c820, 0x1e}, 0x5050100004841c8?, ...)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1164 +0x1ac
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocks(0x40e61bbf00, {0x29c0f98, 0x4000936820}, 0x29c6d30, 0x29c7118, 0x4)
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1077 +0x298
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground.func1()
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1147 +0xcc
created by github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground
        github.com/ledgerwatch/erigon/turbo/snapshotsync/block_snapshots.go:1139 +0x100
```

**Comment by AskAlexSharov** [comment]
@ArielTM 
workaround: --snap.stop
fix: integration stage_headers --reset

**Comment by roderik** [comment]
After doing the fix, i get a million lines of the following

```
[EROR] [06-16|16:57:52.875] Staged Sync                              err="[2/15 Headers] ancestor is nil. height 1, hash 7b66506a9ebdbf30d32b43c5f15a3b1216269a1ec3a75aa3182b86176a2b1ca7"
```

**Comment by ArielTM** [comment]
@AskAlexSharov thanks, that did the trick for me

**Comment by RitudhwajA** [comment]
> After doing the fix, i get a million lines of the following
> 
> ```
> [EROR] [06-16|16:57:52.875] Staged Sync                              err="[2/15 Headers] ancestor is nil. height 1, hash 7b66506a9ebdbf30d32b43c5f15a3b1216269a1ec3a75aa3182b86176a2b1ca7"
> ```

Hi @roderik facing same issue. Were you able to find a solution for it?

**Comment by icculp** [comment]
@RitudhwajA @roderik encountering this after resetting headers, did you find a solution?
