### ISSUE TITLE
Program exits with "signal arrived during external code execution" on windows

### ISSUE THREAD

**Issue by LeoHLee** [ledgerwatch/erigon#7754]
#### System information

Erigon version: erigon version 2.45.0-dev-eae2d9a7

OS & Version: Windows 10 22H2 19045.3086

Go Version: go version go1.20.5 windows/amd64

GCC Version: gcc.exe (tdm64-1) 10.3.0

Commit hash: eae2d9a79cb70dbe30b3a6b79c436872e4605458

Erigon Command (with flags/config): .\erigon --datadir erigon-data

Concensus Layer: None

Chain/Network: Mainnet

#### Expected behaviour
Erigon starts and wait for consensus node connection

#### Actual behaviour
Erigon exits and outputs the following information:
```
PS D:\erigon\build\bin> .\erigon.exe --datadir erigon-data
INFO[06-17|20:29:35.276] logging to file system                   log dir=erigon-data\\logs file prefix=erigon log level=info json=false
INFO[06-17|20:29:35.297] Build info                               git_branch=devel git_tag=y1.2.5-268-geae2d9a79 git_commit=eae2d9a79cb70dbe30b3a6b79c436872e4605458
INFO[06-17|20:29:35.298] Starting Erigon on Ethereum mainnet...
INFO[06-17|20:29:35.302] Maximum peer count                       ETH=100 total=100
INFO[06-17|20:29:35.303] starting HTTP APIs                       APIs=eth,erigon,engine
INFO[06-17|20:29:35.303] torrent verbosity                        level=WRN
INFO[06-17|20:29:37.434] Set global gas cap                       cap=50000000
INFO[06-17|20:29:37.489] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=16mb
 upload.rate=4mb
INFO[06-17|20:29:37.492] Opening Database                         label=chaindata path=D:\\erigon\\build\\bin\\erigon-data\\chaindata
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
signal arrived during external code execution

runtime.cgocall(0x7ff7d251baa0, 0xc000819530)
        runtime/cgocall.go:157 +0x4a fp=0xc000819508 sp=0xc0008194d0 pc=0x7ff7d0bf52ca
github.com/torquem-ch/mdbx-go/mdbx._Cfunc_mdbx_env_create(0xc001bbcde0)
        _cgo_gotypes.go:649 +0x52 fp=0xc000819530 sp=0xc000819508 pc=0x7ff7d1523fb2
github.com/torquem-ch/mdbx-go/mdbx.NewEnv.func1(0xc001bbcde0)
        github.com/torquem-ch/mdbx-go@v0.27.10/mdbx/env.go:137 +0x46 fp=0xc000819560 sp=0xc000819530 pc=0x7ff7d1528686
github.com/torquem-ch/mdbx-go/mdbx.NewEnv()
        github.com/torquem-ch/mdbx-go@v0.27.10/mdbx/env.go:137 +0x2f fp=0xc000819590 sp=0xc000819560 pc=0x7ff7d152854f
github.com/ledgerwatch/erigon-lib/kv/mdbx.MdbxOpts.Open({{0x7ff7d3894268, 0xc0001a0500}, 0xc0001f0050, 0x7ff7d359a738, {0xc0001a43c0, 0x29}, 0x0, 0x30000000000, 0x80000000, 0xffffffffffffffff, ...})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230617020636-2aa24aa05de6/kv/mdbx/kv_mdbx.go:233 +0x305 fp=0xc000819a08 sp=0xc000819590 pc=0x7ff7d19ffc05
github.com/ledgerwatch/erigon/node.OpenDatabase.func1(0x0)
        github.com/ledgerwatch/erigon/node/node.go:327 +0x4a5 fp=0xc000819f80 sp=0xc000819a08 pc=0x7ff7d1ea28c5
github.com/ledgerwatch/erigon/node.OpenDatabase(0xc0013da000, 0x0, {0x7ff7d3894268, 0xc0001a0500})
        github.com/ledgerwatch/erigon/node/node.go:330 +0x27f fp=0xc00081a060 sp=0xc000819f80 pc=0x7ff7d1ea213f
github.com/ledgerwatch/erigon/eth.New(0xc0001c4000, 0x7ff7d27bbec0, {0x7ff7d3894268, 0xc0001a0500})
        github.com/ledgerwatch/erigon/eth/backend.go:208 +0x45c fp=0xc00081b9a8 sp=0xc00081a060 pc=0x7ff7d24f56bc
github.com/ledgerwatch/erigon/turbo/node.New(0x7ff7d387bf40?, 0x7ff7d3894268?, {0x7ff7d3894268, 0xc0001a0500})
        github.com/ledgerwatch/erigon/turbo/node/node.go:109 +0x89 fp=0xc00081ba08 sp=0xc00081b9a8 pc=0x7ff7d2504fc9
main.runErigon(0x1?)
        github.com/ledgerwatch/erigon/cmd/erigon/main.go:66 +0x2bc fp=0xc00081bae8 sp=0xc00081ba08 pc=0x7ff7d2510abc
github.com/ledgerwatch/erigon/turbo/app.MakeApp.func1(0xc001387340)
        github.com/ledgerwatch/erigon/turbo/app/make_app.go:42 +0xc2 fp=0xc00081bbe8 sp=0xc00081bae8 pc=0x7ff7d2507e42
github.com/urfave/cli/v2.(*Command).Run(0xc000acd340, 0xc001387340, {0xc0001d2000, 0x3, 0x4})
        github.com/urfave/cli/v2@v2.25.6/command.go:274 +0x9eb fp=0xc00081be88 sp=0xc00081bbe8 pc=0x7ff7d0e4996b
github.com/urfave/cli/v2.(*App).RunContext(0xc0000ee1e0, {0x7ff7d3882558?, 0xc0001a6098}, {0xc0001d2000, 0x3, 0x4})
        github.com/urfave/cli/v2@v2.25.6/app.go:332 +0x616 fp=0xc00081bef8 sp=0xc00081be88 pc=0x7ff7d0e46296
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.25.6/app.go:309
main.main()
        github.com/ledgerwatch/erigon/cmd/erigon/main.go:37 +0x8f fp=0xc00081bf80 sp=0xc00081bef8 pc=0x7ff7d251070f
runtime.main()
        runtime/proc.go:250 +0x1f7 fp=0xc00081bfe0 sp=0xc00081bf80 pc=0x7ff7d0c2f817
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc00081bfe8 sp=0xc00081bfe0 pc=0x7ff7d0c62141

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc00008ffb0 sp=0xc00008ff90 pc=0x7ff7d0c2fc36
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.forcegchelper()
        runtime/proc.go:305 +0xb2 fp=0xc00008ffe0 sp=0xc00008ffb0 pc=0x7ff7d0c2fa52
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc00008ffe8 sp=0xc00008ffe0 pc=0x7ff7d0c62141
created by runtime.init.6
        runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x7ff7d48e5401?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc000091f80 sp=0xc000091f60 pc=0x7ff7d0c2fc36
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.bgsweep(0x0?)
        runtime/mgcsweep.go:319 +0xde fp=0xc000091fc8 sp=0xc000091f80 pc=0x7ff7d0c177de
runtime.gcenable.func1()
        runtime/mgc.go:178 +0x26 fp=0xc000091fe0 sp=0xc000091fc8 pc=0x7ff7d0c0c986
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc000091fe8 sp=0xc000091fe0 pc=0x7ff7d0c62141
created by runtime.gcenable
        runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00009c000?, 0x7ff7d38585c8?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000a3f70 sp=0xc0000a3f50 pc=0x7ff7d0c2fc36
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.(*scavengerState).park(0x7ff7d48e65e0)
        runtime/mgcscavenge.go:400 +0x53 fp=0xc0000a3fa0 sp=0xc0000a3f70 pc=0x7ff7d0c15673
runtime.bgscavenge(0x0?)
        runtime/mgcscavenge.go:633 +0x65 fp=0xc0000a3fc8 sp=0xc0000a3fa0 pc=0x7ff7d0c15c85
runtime.gcenable.func2()
        runtime/mgc.go:179 +0x26 fp=0xc0000a3fe0 sp=0xc0000a3fc8 pc=0x7ff7d0c0c926
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000a3fe8 sp=0xc0000a3fe0 pc=0x7ff7d0c62141
created by runtime.gcenable
        runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x1a0?, 0x7ff7d25aa8a0?, 0x0?, 0x60?, 0xc000093f70?)
        runtime/proc.go:381 +0xd6 fp=0xc000093e28 sp=0xc000093e08 pc=0x7ff7d0c2fc36
runtime.runfinq()
        runtime/mfinal.go:193 +0x107 fp=0xc000093fe0 sp=0xc000093e28 pc=0x7ff7d0c0b9e7
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc000093fe8 sp=0xc000093fe0 pc=0x7ff7d0c62141
created by runtime.createfing
        runtime/mfinal.go:163 +0x45

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc00009ff50 sp=0xc00009ff30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc00009ffe0 sp=0xc00009ff50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc00009ffe8 sp=0xc00009ffe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x7ff7d494ca60?, 0x3?, 0x44?, 0x52?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000a1f50 sp=0xc0000a1f30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc0000a1fe0 sp=0xc0000a1f50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000a1fe8 sp=0xc0000a1fe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x35af57ce7d4?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc000589f50 sp=0xc000589f30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc000589fe0 sp=0xc000589f50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc000589fe8 sp=0xc000589fe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x35a6f574924?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc000585f50 sp=0xc000585f30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc000585fe0 sp=0xc000585f50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc000585fe8 sp=0xc000585fe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x35af57ce7d4?, 0x1?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000a5f50 sp=0xc0000a5f30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc0000a5fe0 sp=0xc0000a5f50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000a5fe8 sp=0xc0000a5fe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x35af57ce7d4?, 0x3?, 0x10?, 0x4a?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc000587f50 sp=0xc000587f30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc000587fe0 sp=0xc000587f50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc000587fe8 sp=0xc000587fe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x35af57ce7d4?, 0x3?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000aff50 sp=0xc0000aff30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc0000affe0 sp=0xc0000aff50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000affe8 sp=0xc0000affe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 23 [GC worker (idle)]:
runtime.gopark(0x35af57ce7d4?, 0x3?, 0x6c?, 0x35?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000abf50 sp=0xc0000abf30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc0000abfe0 sp=0xc0000abf50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000abfe8 sp=0xc0000abfe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x35af5b3b9d0?, 0x3?, 0x10?, 0x4a?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000b1f50 sp=0xc0000b1f30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc0000b1fe0 sp=0xc0000b1f50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000b1fe8 sp=0xc0000b1fe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 24 [GC worker (idle)]:
runtime.gopark(0x35af57ce7d4?, 0x3?, 0x48?, 0xb9?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000adf50 sp=0xc0000adf30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc0000adfe0 sp=0xc0000adf50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000adfe8 sp=0xc0000adfe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x35af57ce7d4?, 0x1?, 0xf0?, 0xfb?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000b7f50 sp=0xc0000b7f30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc0000b7fe0 sp=0xc0000b7f50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000b7fe8 sp=0xc0000b7fe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 25 [GC worker (idle)]:
runtime.gopark(0x35af57ce7d4?, 0x1?, 0xb0?, 0xd1?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000b3f50 sp=0xc0000b3f30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc0000b3fe0 sp=0xc0000b3f50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000b3fe8 sp=0xc0000b3fe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x35af57ce7d4?, 0x1?, 0x10?, 0x4a?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000b9f50 sp=0xc0000b9f30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc0000b9fe0 sp=0xc0000b9f50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000b9fe8 sp=0xc0000b9fe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 26 [GC worker (idle)]:
runtime.gopark(0x35af57ce7d4?, 0x1?, 0x8?, 0x43?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000b5f50 sp=0xc0000b5f30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc0000b5fe0 sp=0xc0000b5f50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000b5fe8 sp=0xc0000b5fe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 10 [GC worker (idle)]:
runtime.gopark(0x35af5ac0d5c?, 0x3?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000c1f50 sp=0xc0000c1f30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc0000c1fe0 sp=0xc0000c1f50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000c1fe8 sp=0xc0000c1fe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 27 [GC worker (idle)]:
runtime.gopark(0x7ff7d494ca60?, 0x3?, 0xcc?, 0x77?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000bdf50 sp=0xc0000bdf30 pc=0x7ff7d0c2fc36
runtime.gcBgMarkWorker()
        runtime/mgc.go:1275 +0xf1 fp=0xc0000bdfe0 sp=0xc0000bdf50 pc=0x7ff7d0c0e731
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000bdfe8 sp=0xc0000bdfe0 pc=0x7ff7d0c62141
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1199 +0x25

goroutine 50 [sleep]:
runtime.gopark(0x35a6646e984?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc0000bff40 sp=0xc0000bff20 pc=0x7ff7d0c2fc36
time.Sleep(0x22ecb25c00)
        runtime/time.go:195 +0x13a fp=0xc0000bff80 sp=0xc0000bff40 pc=0x7ff7d0c5edfa
github.com/VictoriaMetrics/metrics.summariesSwapCron(0x45d964b800)
        github.com/VictoriaMetrics/metrics@v1.23.1/summary.go:237 +0x36 fp=0xc0000bffc8 sp=0xc0000bff80 pc=0x7ff7d1538596
github.com/VictoriaMetrics/metrics.registerSummaryLocked.func1()
        github.com/VictoriaMetrics/metrics@v1.23.1/summary.go:211 +0x26 fp=0xc0000bffe0 sp=0xc0000bffc8 pc=0x7ff7d15382a6
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000bffe8 sp=0xc0000bffe0 pc=0x7ff7d0c62141
created by github.com/VictoriaMetrics/metrics.registerSummaryLocked
        github.com/VictoriaMetrics/metrics@v1.23.1/summary.go:211 +0x128

goroutine 35 [chan receive]:
runtime.gopark(0x7ff7d2b78ce0?, 0xc001509faf?, 0xb0?, 0x56?, 0xc000884488?)
        runtime/proc.go:381 +0xd6 fp=0xc0017e5ee0 sp=0xc0017e5ec0 pc=0x7ff7d0c2fc36
runtime.chanrecv(0xc000945650, 0xc001509faf, 0x1)
        runtime/chan.go:583 +0x49d fp=0xc0017e5f70 sp=0xc0017e5ee0 pc=0x7ff7d0bf813d
runtime.chanrecv2(0xc0013d2420?, 0x7ff7d0c36b65?)
        runtime/chan.go:447 +0x18 fp=0xc0017e5f98 sp=0xc0017e5f70 pc=0x7ff7d0bf7c78
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc0013d2420)
        gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:379 +0x45 fp=0xc0017e5fc8 sp=0xc0017e5f98 pc=0x7ff7d1ab97e5
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1.1()
        gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:390 +0x26 fp=0xc0017e5fe0 sp=0xc0017e5fc8 pc=0x7ff7d1ab99a6
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0017e5fe8 sp=0xc0017e5fe0 pc=0x7ff7d0c62141
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
        gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:390 +0x96

goroutine 28 [IO wait]:
runtime.gopark(0xc00055a0c8?, 0xc00055a048?, 0x58?, 0xa0?, 0xc0015a1b40?)
        runtime/proc.go:381 +0xd6 fp=0xc0015a1ad0 sp=0xc0015a1ab0 pc=0x7ff7d0c2fc36
runtime.netpollblock(0xc000000001?, 0xd0bf4d4f?, 0xf7?)
        runtime/netpoll.go:527 +0xf7 fp=0xc0015a1b08 sp=0xc0015a1ad0 pc=0x7ff7d0c25f57
internal/poll.runtime_pollWait(0x2ba65de2988, 0x72)
        runtime/netpoll.go:306 +0x89 fp=0xc0015a1b28 sp=0xc0015a1b08 pc=0x7ff7d0c5b3a9
internal/poll.(*pollDesc).wait(0x7ff7d0c2fc36?, 0x7ff7d0c5fe93?, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc0015a1b50 sp=0xc0015a1b28 pc=0x7ff7d0ce41f2
internal/poll.execIO(0xc00055a018, 0x7ff7d359e8b8)
        internal/poll/fd_windows.go:175 +0xf7 fp=0xc0015a1bc0 sp=0xc0015a1b50 pc=0x7ff7d0ce5877
internal/poll.(*FD).ReadFromInet4(0xc00055a000, {0xc000542150, 0x35b58b567f4?, 0x80000000000?}, 0xc0015a1cb0)
        internal/poll/fd_windows.go:604 +0x150 fp=0xc0015a1c20 sp=0xc0015a1bc0 pc=0x7ff7d0ce7730
net.(*netFD).readFromInet4(0xc00055a000, {0xc000542150?, 0x0?, 0x1000000000000?}, 0x2?)
        net/fd_posix.go:66 +0x29 fp=0xc0015a1c70 sp=0xc0015a1c20 pc=0x7ff7d0d5c1a9
net.(*UDPConn).readFrom(0xc0015a1da8?, {0xc000542150?, 0xc00055a000?, 0xc000542114?}, 0xc0015a1e68)
        net/udpsock_posix.go:52 +0x1b8 fp=0xc0015a1d60 sp=0xc0015a1c70 pc=0x7ff7d0d81058
net.(*UDPConn).readFromUDP(0xc000538028, {0xc000542150?, 0x7ff7d48e6220?, 0x7ff7d48e6220?}, 0x0?)
        net/udpsock.go:149 +0x31 fp=0xc0015a1db8 sp=0xc0015a1d60 pc=0x7ff7d0d7ebd1
net.(*UDPConn).ReadFromUDP(...)
        net/udpsock.go:141
github.com/jackpal/go-nat-pmp.(*network).call(0xc00054c018, {0xc000542114, 0x2, 0x2}, 0x0)
        github.com/jackpal/go-nat-pmp@v1.0.2/network.go:54 +0x38e fp=0xc0015a1eb0 sp=0xc0015a1db8 pc=0x7ff7d15921ee
github.com/jackpal/go-nat-pmp.(*Client).rpc(0x2ba5ea40a28?, {0xc000542114, 0x2, 0x2}, 0x0?)
        github.com/jackpal/go-nat-pmp@v1.0.2/natpmp.go:108 +0x46 fp=0xc0015a1f18 sp=0xc0015a1eb0 pc=0x7ff7d1591b06
github.com/jackpal/go-nat-pmp.(*Client).GetExternalAddress(0x0?)
        github.com/jackpal/go-nat-pmp@v1.0.2/natpmp.go:58 +0x50 fp=0xc0015a1f78 sp=0xc0015a1f18 pc=0x7ff7d1591730
github.com/ledgerwatch/erigon/p2p/nat.discoverPMP.func1()
        github.com/ledgerwatch/erigon/p2p/nat/natpmp.go:79 +0xef fp=0xc0015a1fe0 sp=0xc0015a1f78 pc=0x7ff7d15ac64f
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0015a1fe8 sp=0xc0015a1fe0 pc=0x7ff7d0c62141
created by github.com/ledgerwatch/erigon/p2p/nat.discoverPMP
        github.com/ledgerwatch/erigon/p2p/nat/natpmp.go:76 +0x6f
rax     0x0
rbx     0xc001bbcde0
rcx     0x2ba5d299548
rdi     0xc00081c000
rsi     0x7ff979f715c0
rbp     0xc0008194f8
rsp     0xc13c9ffd28
r8      0x1000
r9      0x2e0b63000
r10     0x0
r11     0x246
r12     0x2ba5d2993c0
r13     0x0
r14     0xc00008c000
r15     0x40
rip     0x0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
```
#### Steps to reproduce the behaviour
Using the provided `wmake.ps1` to build, and run `erigon --datadir data`

**Comment by 0xSheller** [comment]
AFAIK this is probably because it's not best to run erigon on windows. 

Might work for you, but try setting this ENV variable `GO_EXTLINK_ENABLED=0` or rebuild and add `-linkmode internal` as a build arg

**Comment by LeoHLee** [comment]
> AFAIK this is probably because it's not best to run erigon on windows.
> 
> Might work for you, but try setting this ENV variable `GO_EXTLINK_ENABLED=0` or rebuild and add `-linkmode internal` as a build arg
> 
> This will disable linking which with cmd/go and windows doesn't play well together (https://pkg.go.dev/cmd/go)

I tried to add `-linkmode internal` to `$Erigon.BuildFlags`, but unfortunately my go.exe cannot recognize this flag.

I will try WSL for now while still looking forward to a available native Windows version, because WSL takes additional memory and lowers IO speed anyway.
