### ISSUE TITLE
stuck at Waiting for Consensus Layer when using internalcl

### ISSUE THREAD

**Issue by mike-code** [ledgerwatch/erigon#7923]
### description of the problem

I synced `sepolia` chain from scratch on one machine and it worked just fine. Then I moved the files (rsynced) to another machine (the same operating system/cpu arch), preserved access/modification time fot the `datadir`, but the chain won't sync any further. I've performed the rsync with erigon stopped. 

Now I tried to continue the sync on the new machine, but It's stuck at `2/15 Waiting for Consensus Layer` with peers changing, but progress moving no further. The `print_stages` output differs between old and new machines but it's mystery to me how to read it so I'll count on your help.

Thanks!

#### System information

```
❯ erigon --version
erigon version 2.48.0-stable

❯ uname -a
Linux _ 6.4.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 06 Jul 2023 18:35:54 +0000 x86_64 GNU/Linux
```

Concensus Layer: internal
Chain/Network: sepolia

#### start command
```
/usr/bin/erigon \
    --chain=sepolia \
    --datadir=/mnt/storage/ansible-managed/ethereum/data \
    --ethash.dagdir=/mnt/storage/ansible-managed/ethereum/data \
    --http=true \
    --healthcheck=true \
    --sentinel.addr=127.0.0.1 \
    --http.addr=127.0.0.1 \
    --http.port=8545 \
    --private.api.addr 127.0.0.1:8546 \
    --http.api=eth,erigon,engine,web3,net,txpool \
    --authrpc.addr=127.0.0.1 \
    --authrpc.jwtsecret=/mnt/storage/ansible-managed/ethereum/jwt.hex \
    --metrics=true \
    --internalcl \
    --snapshots=true \
    --torrent.download.slots=4 \
    --torrent.download.rate=128mb \
    --torrent.upload.rate=4mb \
    --verbosity info \
    --log.console.verbosity info
```

### print_stages OLD machine

```
INFO[07-23|23:24:13.183] [snapshots] Blocks Stat                  blocks=3855k indices=3855k alloc=100.9MB sys=127.0MB
Note: prune_at doesn't mean 'all data before were deleted' - it just mean stage.Prune function were run to this block. Because 1 stage may prune multiple data types to different prune distance.

 				 stage_at 	 prune_at
Snapshots 			 3945832 	 0
Headers 			 3945833 	 0
BlockHashes 			 3945833 	 0
Bodies 				 3945833 	 0
Senders 			 3945833 	 0
Execution 			 3945833 	 3945833
Translation 			 0 		 0
HashState 			 3945833 	 0
IntermediateHashes 		 3945833 	 3945833
AccountHistoryIndex 		 3945833 	 0
StorageHistoryIndex 		 3945833 	 0
LogIndex 			 3945833 	 0
CallTraces 			 3945833 	 3945833
TxLookup 			 3945833 	 3559600
Finish 				 3945833 	 0
--
prune distance:

blocks.v2: blocks=3854999, segments=3854999, indices=3854999

history.v3: false,  idx steps: 0.00, lastMaxTxNum=0->1, lastBlockInSnap=0

sequence: EthTx=48195739, NonCanonicalTx=0

in db: first header 3855000, last header 3945833, first body 3855000, last body 3945833
```

### print_stages NEW machine

```
INFO[07-23|23:22:05.550] [snapshots] Blocks Stat                  blocks=3855k indices=3855k alloc=101.9MB sys=160.6MB
Note: prune_at doesn't mean 'all data before were deleted' - it just mean stage.Prune function were run to this block. Because 1 stage may prune multiple data types to different prune distance.

 				 stage_at 	 prune_at
Snapshots 			 3854999 	 0
Headers 			 3854999 	 0
BlockHashes 			 3945833 	 0
Bodies 				 3854999 	 0
Senders 			 3854999 	 0
Execution 			 3945833 	 3945833
Translation 			 0 		 0
HashState 			 3945833 	 0
IntermediateHashes 		 3945833 	 3945833
AccountHistoryIndex 		 3945833 	 0
StorageHistoryIndex 		 3945833 	 0
LogIndex 			 3945833 	 0
CallTraces 			 3945833 	 3945833
TxLookup 			 3945833 	 3559600
Finish 				 3945833 	 0
--
prune distance:

blocks.v2: blocks=3854999, segments=3854999, indices=3854999

history.v3: false,  idx steps: 0.00, lastMaxTxNum=0->0, lastBlockInSnap=0

sequence: EthTx=43472220, NonCanonicalTx=0

in db: first header 0, last header 0, first body 0, last body 0
--
```

#### Log

```
Started Erigon execution client.
[INFO] [07-23|23:09:17.026] logging to file system                   log dir=/mnt/storage/ansible-managed/ethereum/data/logs file prefix=erigon log level=info json=false
[INFO] [07-23|23:09:17.027] Starting metrics server                  addr=http://127.0.0.1:6060/debug/metrics/prometheus
[INFO] [07-23|23:09:17.027] Build info                               git_branch= git_tag=v2.48.0 git_commit=
[INFO] [07-23|23:09:17.027] Starting Erigon on Sepolia testnet...
[INFO] [07-23|23:09:17.028] Maximum peer count                       ETH=100 total=100
[INFO] [07-23|23:09:17.028] starting HTTP APIs                       APIs=eth,erigon,engine,web3,net,txpool
[INFO] [07-23|23:09:17.028] torrent verbosity                        level=WRN
[INFO] [07-23|23:09:19.133] Set global gas cap                       cap=50000000
[INFO] [07-23|23:09:19.134] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=128mb upload.rate=4mb
[INFO] [07-23|23:09:19.134] Opening Database                         label=chaindata path=/mnt/storage/ansible-managed/ethereum/data/chaindata
[INFO] [07-23|23:09:19.319] Initialised chain configuration          config="{ChainID: 11155111, Homestead: 0, DAO: <nil>, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 0, Muir Glacier: 0, Berlin: 0, London: 0, Arrow Glacier: <nil>, Gray Glacier: <nil>, Terminal Total Difficulty: 17000000000000000, Merge Netsplit: 1735371, Shanghai: 1677557088, Cancun: <nil>, Prague: <nil>, Engine: ethash}" genesis=0x25a5cc106eea7138acab33231d7160d69cb777ee0c2c553fcddf5138993e6dd9
[INFO] [07-23|23:09:19.380] Initialising Ethereum protocol           network=11155111
[INFO] [07-23|23:09:19.380] Disk storage enabled for ethash DAGs     dir=/mnt/storage/ansible-managed/ethereum/data count=2
[INFO] [07-23|23:09:19.382] Starting private RPC server              on=127.0.0.1:8546
[INFO] [07-23|23:09:19.382] new subscription to logs established
[INFO] [07-23|23:09:19.382] [Checkpoint Sync] Requesting beacon state uri=https://checkpoint-sync.sepolia.ethpandaops.io/eth/v2/debug/beacon/states/finalized
[INFO] [07-23|23:09:21.268] Static peers                             len=0
[INFO] [07-23|23:09:21.268] [Sentinel] Sentinel started              enr=enr:-Ly4QCIpZR6dAeg0596PkTyT0jjmutWreYIyBi1Ksv42K2tDAHdffByAYCN5278oqJQM4l4JEJKa6dtKE3pW2zE5jncBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBH63KzBAAAAP__________gmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQL0onynPEVVhRUtpMjN5SGezaF5KPr4j2k5UHAWVcm41YhzeW5jbmV0cwCDdGNwgg-hg3VkcIIPoA
[INFO] [07-23|23:09:21.269] rpc filters: subscribing to Erigon events
[INFO] [07-23|23:09:21.269] new subscription to newHeaders established
[INFO] [07-23|23:09:21.269] New txs subscriber joined
[INFO] [07-23|23:09:21.269] Reading JWT secret                       path=/mnt/storage/ansible-managed/ethereum/jwt.hex
[INFO] [07-23|23:09:21.270] HTTP endpoint opened for Engine API      url=127.0.0.1:8551 ws=true ws.compression=true
[INFO] [07-23|23:09:21.270] HTTP endpoint opened                     url=127.0.0.1:8545 ws=false ws.compression=true grpc=false
[INFO] [07-23|23:09:21.275] Started P2P networking                   version=68 self=enode://8029b30e80b12b7c9a2255bcb30b23066232397ac191a146610c5c5ac4f03cbb4b670b98a89a52422a0eb54cac90aea39c9fe99fb066958c6cd084cd6da9c1b5@127.0.0.1:0 name=erigon/v2.48.0/linux-amd64/go1.20.5
[INFO] [07-23|23:09:21.278] Started P2P networking                   version=67 self=enode://8029b30e80b12b7c9a2255bcb30b23066232397ac191a146610c5c5ac4f03cbb4b670b98a89a52422a0eb54cac90aea39c9fe99fb066958c6cd084cd6da9c1b5@127.0.0.1:0 name=erigon/v2.48.0/linux-amd64/go1.20.5
[INFO] [07-23|23:09:21.279] [txpool] Started
[INFO] [07-23|23:09:21.324] [1/15 Snapshots] Fetching torrent files metadata
[INFO] [07-23|22:03:59.160] Started Ethereum 2.0 Gossip Service
[INFO] [07-23|22:03:59.255] [snapshots] Blocks Stat                  blocks=3855k indices=3855k alloc=152.1MB sys=219.4MB
[INFO] [07-23|22:03:59.256] [2/15 Headers] Waiting for Consensus Layer...
[EROR] [07-23|22:04:56.859] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"
[INFO] [07-23|22:04:59.067] [txpool] stat                            pending=10 baseFee=0 queued=331 alloc=372.1MB sys=499.6MB
[INFO] [07-23|22:04:59.160] [Caplin] P2P                             peers=3
[INFO] [07-23|22:05:56.131] [p2p] GoodPeers                          eth67=5 eth68=1
[INFO] [07-23|22:05:59.068] [txpool] stat                            pending=23 baseFee=0 queued=512 alloc=217.1MB sys=500.1MB
[INFO] [07-23|22:05:59.161] [Caplin] P2P                             peers=4
[INFO] [07-23|22:06:59.067] [txpool] stat                            pending=42 baseFee=0 queued=712 alloc=263.2MB sys=544.8MB
[INFO] [07-23|22:06:59.160] [Caplin] P2P                             peers=5
[INFO] [07-23|22:07:56.131] [p2p] GoodPeers                          eth68=1 eth67=5
[INFO] [07-23|22:07:59.067] [txpool] stat                            pending=56 baseFee=0 queued=888 alloc=316.1MB sys=570.2MB
[INFO] [07-23|22:07:59.160] [Caplin] P2P                             peers=6
[INFO] [07-23|22:08:59.067] [txpool] stat                            pending=75 baseFee=0 queued=1076 alloc=240.6MB sys=676.0MB
[INFO] [07-23|22:08:59.161] [Caplin] P2P                             peers=6
[EROR] [07-23|22:09:16.573] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"
[INFO] [07-23|22:09:56.131] [p2p] GoodPeers                          eth68=2 eth67=5
[INFO] [07-23|22:09:59.067] [txpool] stat                            pending=102 baseFee=0 queued=1254 alloc=230.3MB sys=676.3MB
[INFO] [07-23|22:09:59.161] [Caplin] P2P                             peers=5
[INFO] [07-23|22:10:59.068] [txpool] stat                            pending=131 baseFee=0 queued=1425 alloc=251.4MB sys=676.5MB
[INFO] [07-23|22:10:59.161] [Caplin] P2P                             peers=6
[INFO] [07-23|22:11:56.131] [p2p] GoodPeers                          eth68=3 eth67=6
[INFO] [07-23|22:11:59.067] [txpool] stat                            pending=151 baseFee=0 queued=1589 alloc=285.6MB sys=676.5MB
[INFO] [07-23|22:11:59.160] [Caplin] P2P                             peers=7
[INFO] [07-23|22:12:59.067] [txpool] stat                            pending=173 baseFee=0 queued=1793 alloc=259.0MB sys=676.8MB
[INFO] [07-23|22:12:59.160] [Caplin] P2P                             peers=8
[INFO] [07-23|22:13:56.131] [p2p] GoodPeers                          eth68=3 eth67=6
[INFO] [07-23|22:13:59.067] [txpool] stat                            pending=187 baseFee=0 queued=1985 alloc=364.8MB sys=676.8MB
[INFO] [07-23|22:13:59.160] [Caplin] P2P                             peers=8
[INFO] [07-23|22:14:59.069] [txpool] stat                            pending=205 baseFee=0 queued=2146 alloc=315.2MB sys=676.8MB
[INFO] [07-23|22:14:59.160] [Caplin] P2P                             peers=11
[EROR] [07-23|22:15:52.117] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"
[INFO] [07-23|22:15:56.131] [p2p] GoodPeers                          eth68=4 eth67=6
[INFO] [07-23|22:15:59.067] [txpool] stat                            pending=223 baseFee=0 queued=2331 alloc=472.8MB sys=677.0MB
[INFO] [07-23|22:15:59.161] [Caplin] P2P                             peers=9
[INFO] [07-23|22:16:59.067] [txpool] stat                            pending=247 baseFee=0 queued=2536 alloc=379.9MB sys=677.3MB
[INFO] [07-23|22:16:59.160] [Caplin] P2P                             peers=14
[INFO] [07-23|22:17:56.131] [p2p] GoodPeers                          eth68=6 eth67=6 eth66=1
[INFO] [07-23|22:17:59.068] [txpool] stat                            pending=269 baseFee=0 queued=2725 alloc=263.4MB sys=677.3MB
[INFO] [07-23|22:17:59.161] [Caplin] P2P                             peers=16
[INFO] [07-23|22:18:59.067] [txpool] stat                            pending=289 baseFee=0 queued=3014 alloc=423.3MB sys=677.3MB
[INFO] [07-23|22:18:59.160] [Caplin] P2P                             peers=21
[INFO] [07-23|22:19:56.131] [p2p] GoodPeers                          eth68=8 eth67=7 eth66=1
[INFO] [07-23|22:19:59.068] [txpool] stat                            pending=310 baseFee=0 queued=3188 alloc=316.4MB sys=677.3MB
[INFO] [07-23|22:19:59.161] [Caplin] P2P                             peers=18
[INFO] [07-23|22:20:59.067] [txpool] stat                            pending=323 baseFee=0 queued=3360 alloc=369.3MB sys=677.3MB
[INFO] [07-23|22:20:59.160] [Caplin] P2P                             peers=14
[EROR] [07-23|22:21:46.335] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"
[INFO] [07-23|22:21:56.131] [p2p] GoodPeers                          eth68=8 eth67=7 eth66=1
[INFO] [07-23|22:21:59.067] [txpool] stat                            pending=347 baseFee=0 queued=3532 alloc=354.2MB sys=677.3MB
[INFO] [07-23|22:21:59.160] [Caplin] P2P                             peers=12
[EROR] [07-23|22:21:59.920] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"
[INFO] [07-23|22:22:59.067] [txpool] stat                            pending=367 baseFee=0 queued=3718 alloc=274.9MB sys=677.3MB
[INFO] [07-23|22:22:59.161] [Caplin] P2P                             peers=12
[INFO] [07-23|22:23:56.131] [p2p] GoodPeers                          eth68=8 eth67=7 eth66=1
[INFO] [07-23|22:23:59.067] [txpool] stat                            pending=395 baseFee=0 queued=3902 alloc=273.2MB sys=677.3MB
[INFO] [07-23|22:23:59.160] [Caplin] P2P                             peers=13
[INFO] [07-23|22:24:59.067] [txpool] stat                            pending=430 baseFee=0 queued=4068 alloc=318.3MB sys=686.4MB
[INFO] [07-23|22:24:59.161] [Caplin] P2P                             peers=13
[INFO] [07-23|22:25:56.131] [p2p] GoodPeers                          eth66=1 eth67=7 eth68=8
[INFO] [07-23|22:25:59.068] [txpool] stat                            pending=451 baseFee=0 queued=4222 alloc=396.7MB sys=702.4MB
[INFO] [07-23|22:25:59.160] [Caplin] P2P                             peers=15
[INFO] [07-23|22:26:59.067] [txpool] stat                            pending=472 baseFee=0 queued=4337 alloc=316.3MB sys=702.4MB
[INFO] [07-23|22:26:59.160] [Caplin] P2P                             peers=20
[INFO] [07-23|22:27:56.131] [p2p] GoodPeers                          eth68=8 eth67=8 eth66=1
[INFO] [07-23|22:27:59.067] [txpool] stat                            pending=503 baseFee=0 queued=4445 alloc=463.4MB sys=702.4MB
[INFO] [07-23|22:27:59.160] [Caplin] P2P                             peers=16
[EROR] [07-23|22:28:33.017] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"
[INFO] [07-23|22:28:59.068] [txpool] stat                            pending=516 baseFee=0 queued=4528 alloc=257.5MB sys=702.4MB
[INFO] [07-23|22:28:59.161] [Caplin] P2P                             peers=14
[INFO] [07-23|22:29:20.260] Got interrupt, shutting down...
Stopping Erigon execution client...
```

**Comment by wmitsuda** [comment]
I saw something similar, a couple of restarts fixed the issue by itself, I think for some reason caplin internal process is not starting sometimes, when it works you can see a ethereum 2.0 like log message.

**Comment by mike-code** [comment]
I've tried that a few times but without luck. Is there some minimum number of peers needed before the sync starts?

**Comment by mike-code** [comment]
> I saw something similar, a couple of restarts fixed the issue by itself, I think for some reason caplin internal process is not starting sometimes, when it works you can see a ethereum 2.0 like log message.

I've tried that a few times, but without luck. Is there some minimum number of peers needed for sync to start?

**Comment by Giulio2002** [comment]
so we have a bunch of pre used checkpoint sync URLs, I had problems with them on Sepolia. will take a look

**Comment by wmitsuda** [comment]
ah, just for the record, I've seen it on mainnet

**Comment by Giulio2002** [comment]
some things to add, i think the solution is better logging, the CL is doing something but if checkpoint is too far, it may go silent for a long time.

**Comment by clamcy** [comment]
Me too, encountering the similar problem on the sepolia testnet.

In the past 7 hours, the number of p2p peers keeps changing, no further progress.
The eth.blockNumber did not change, `eth.blockNumber == 3997098`, and `eth.syncing == false`
Also happend after
```log
[2/15 Headers] Waiting for Consensus Layer...
```

Some history logs below which might help:
```log
INFO[08-02|00:32:48.816] [Caplin] P2P                             peers=24                                                                                      [1926/1984]
EROR[08-02|00:33:21.182] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"                                                                                                                                                                       
EROR[08-02|00:33:26.325] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"                                                                                                                                                                       
INFO[08-02|00:33:43.359] [p2p] GoodPeers                          eth68=9 eth67=9                                                                                          
INFO[08-02|00:33:48.615] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=245.2MB sys=744.3MB                                           
INFO[08-02|00:33:48.816] [Caplin] P2P                             peers=18                                                                                                 
INFO[08-02|00:34:48.609] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=457.1MB sys=744.3MB                                           
INFO[08-02|00:34:48.816] [Caplin] P2P                             peers=20                                                                                                 
EROR[08-02|00:35:09.766] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"                                                                                                                                                                       
EROR[08-02|00:35:15.012] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"                                                                                                                                                                       
EROR[08-02|00:35:15.021] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"                                                                                                                                                                       
INFO[08-02|00:35:43.359] [p2p] GoodPeers                          eth68=10 eth67=9                                                                                         
INFO[08-02|00:35:48.617] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=428.1MB sys=744.3MB                                           
INFO[08-02|00:35:48.816] [Caplin] P2P                             peers=20                                                                                                 
EROR[08-02|00:36:09.386] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"                                                                                                                                                                       
EROR[08-02|00:36:22.560] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"                                                                                                                                                                       
INFO[08-02|00:36:48.610] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=420.8MB sys=744.3MB                                           
INFO[08-02|00:36:48.816] [Caplin] P2P                             peers=22                                                                                                 
EROR[08-02|00:37:24.521] [pubsubhandler] stream handler           name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"                                                                                                                                                                       
INFO[08-02|00:37:43.359] [p2p] GoodPeers                          eth68=10 eth67=9                                                                                         
INFO[08-02|00:37:48.615] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=380.3MB sys=744.3MB                                           
INFO[08-02|00:37:48.817] [Caplin] P2P                             peers=20                                                                                                 
INFO[08-02|00:38:48.609] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=322.1MB sys=744.3MB
```

**Comment by clamcy** [comment]
Tried the devel branch, and core dumped.
Maybe the following logs could help locating the problem.

```log
INFO[..] [2/14 Headers] Waiting for Consensus Layer... 
INFO[..] Started P2P networking   version=67 self=enode://d4551...28e6@127.0.0.1:0 name=erigon/v2.49.0-dev-e4612fd6/linux-amd64/go1.20.3
INFO[..] Started P2P networking   version=68 self=enode://d4551...28e6@127.0.0.1:0 name=erigon/v2.49.0-dev-e4612fd6/linux-amd64/go1.20.3
INFO[..] [txpool] stat  pending=0 baseFee=0 queued=37 alloc=172.5MB sys=329.3MB
INFO[..] [Caplin] P2P   peers=7
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x185b255]

goroutine 2086 [running]:
github.com/ledgerwatch/erigon/cl/phase1/execution_client.(*ExecutionClientDirect).NewPayload(0x0, 0xc000ecc900, 0x3afc82fb7a85a884?)
  github.com/ledgerwatch/erigon/cl/phase1/execution_client/execution_client_direct.go:79 +0x6d5
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).OnBlock(0xc00a74ea80, 0xc00a69d960, 0x1, 0xf1?)
  github.com/ledgerwatch/erigon/cl/phase1/forkchoice/on_block.go:50 +0x2cb
github.com/ledgerwatch/erigon/cl/phase1/stages.startDownloadService.func1(0x545553?, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
  github.com/ledgerwatch/erigon/cl/phase1/stages/stage_fork_choice.go:114 +0x149
github.com/ledgerwatch/erigon/cl/phase1/network.(*ForwardBeaconDownloader).RequestMore(0xc00646e1e0, {0x2caa450?, 0xc00ab405d0?})
  github.com/ledgerwatch/erigon/cl/phase1/network/beacon_downloader.go:83 +0x184
github.com/ledgerwatch/erigon/cl/phase1/stages.startDownloadService(0x4376e8?, {{0x0, 0x0}, 0xc00646e1e0, 0xc005fe4ed0, 0xc003578000, 0x0, 0xc00b0c54a0, 0xc0076ba000, 0xc00a74ea80, ...})
  github.com/ledgerwatch/erigon/cl/phase1/stages/stage_fork_choice.go:204 +0x512
github.com/ledgerwatch/erigon/cl/phase1/stages.SpawnStageForkChoice({{0x0, 0x0}, 0xc00646e1e0, 0xc005fe4ed0, 0xc003578000, 0x0, 0xc00b0c54a0, 0xc0076ba000, 0xc00a74ea80, {0x0, ...}}, ...)
  github.com/ledgerwatch/erigon/cl/phase1/stages/stage_fork_choice.go:94 +0x286
github.com/ledgerwatch/erigon/cmd/caplin-phase1/caplin1.RunCaplinPhase1({0x2caa3e0?, 0xc0010eaf00}, {0x2cb1a50?, 0xc005e038e0}, 0xc003578000, 0xc005fe4ed0, {0x2c9e9c0, 0x0}, 0xc00b0c54a0, {0x0, ...})
  github.com/ledgerwatch/erigon/cmd/caplin-phase1/caplin1/run.go:47 +0x54a
created by github.com/ledgerwatch/erigon/eth.New
  github.com/ledgerwatch/erigon/eth/backend.go:636 +0x3df8
```

**Comment by clamcy** [comment]
> some things to add, i think the solution is better logging, the CL is doing something but if checkpoint is too far, it may go silent for a long time.

You are right, the CL was working.
I left the erigon (stable branch) running, and now it is OK, the sync is now pushing forward.
The log shows that downloading the PoS header took 6 hours and 34 minutes.
Before the download was completed, there was no log output related to the progress, so it looks like the program was frozen.

```log
INFO[...] [Caplin] P2P   peers=13  
EROR[...] [pubsubhandler] stream handler   name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"
INFO[...] [2/15 Headers] Downloading PoS headers... height=unknown hash=0xb9c205d978a8d90cabea38e83260d79eac6c8ee813c58aad837b46a90627785b requestId=1  
INFO[...] [2/15 Headers] DONE  in=6h34m19.308105345s  
INFO[...] Timings (slower than 50ms)   Snapshots=81ms Headers=6h34m19.308s TxLookup=58ms  
INFO[...] Tables   PlainState=5.1GB AccountChangeSet=432.1MB StorageChangeSet=965.4MB BlockTransaction=54.0GB TransactionLog=29.1GB FreeList=2
.4MB ....9GB  
INFO[...] [snapshots] Blocks Stat  blocks=3565k indices=3565k alloc=487.6MB sys=1.1GB   
INFO[...] [txpool] stat  pending=3991 baseFee=0 queued=30000 alloc=498.4MB sys=1.1GB  
INFO[...] [Caplin] P2P   peers=15  
EROR[...] [pubsubhandler] stream handler   name=/eth2/beacon_chain/req/status/1/ssz_snappy err="unable to read varint from message prefix: stream reset"
INFO[...] [p2p] GoodPeers  eth68=11 eth67=14   
INFO[...] [txpool] stat  pending=4002 baseFee=0 queued=30000 alloc=731.6MB sys=1.1GB  
INFO[...] [Caplin] P2P   peers=24  
INFO[...] [downloader] Downloaded PoS Headers  now=4008716 blk/sec=6.400  
INFO[...] [downloader] Downloaded PoS Headers  now=4008524 blk/sec=6.400
```

**Comment by Zorato** [comment]
Got the same issue on ETH mainnet when running Caplin
```
[INFO] [08-17|12:42:21.205] [p2p] GoodPeers                          eth68=100 eth67=33
[INFO] [08-17|12:42:24.449] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=5.8GB sys=14.6GB
[INFO] [08-17|12:42:53.112] [Caplin] P2P                             peers=33
[INFO] [08-17|12:43:24.453] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=7.7GB sys=14.6GB
[INFO] [08-17|12:43:53.113] [Caplin] P2P                             peers=33
[INFO] [08-17|12:44:21.205] [p2p] GoodPeers                          eth68=100 eth67=33
[INFO] [08-17|12:44:24.451] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=5.7GB sys=14.6GB
[INFO] [08-17|12:44:53.112] [Caplin] P2P                             peers=33
[INFO] [08-17|12:45:24.453] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=7.5GB sys=14.6GB
[INFO] [08-17|12:45:53.113] [Caplin] P2P                             peers=33
[INFO] [08-17|12:46:21.205] [p2p] GoodPeers                          eth68=100 eth67=33
[INFO] [08-17|12:46:24.450] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=5.7GB sys=14.6GB
[INFO] [08-17|12:46:51.691] new subscription to newHeaders established 
[INFO] [08-17|12:46:51.691] New txs subscriber joined 
[INFO] [08-17|12:46:53.113] [Caplin] P2P                             peers=33
[INFO] [08-17|12:47:24.453] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=7.6GB sys=14.6GB
[INFO] [08-17|12:47:53.113] [Caplin] P2P                             peers=33
[INFO] [08-17|12:48:21.205] [p2p] GoodPeers                          eth68=100 eth67=33
[INFO] [08-17|12:48:24.453] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=5.7GB sys=14.6GB
[INFO] [08-17|12:48:53.112] [Caplin] P2P                             peers=33
[INFO] [08-17|12:49:24.452] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=7.7GB sys=14.6GB
[INFO] [08-17|12:49:53.113] [Caplin] P2P                             peers=33
[INFO] [08-17|12:50:21.205] [p2p] GoodPeers                          eth68=100 eth67=33
[INFO] [08-17|12:50:24.453] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=5.6GB sys=14.6GB
[INFO] [08-17|12:50:53.112] [Caplin] P2P                             peers=33
[INFO] [08-17|12:51:24.453] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=7.7GB sys=14.6GB
[INFO] [08-17|12:51:53.113] [Caplin] P2P                             peers=33
[INFO] [08-17|12:52:01.886] New txs subscriber joined 
[INFO] [08-17|12:52:01.886] new subscription to newHeaders established 
[INFO] [08-17|12:52:21.205] [p2p] GoodPeers                          eth68=100 eth67=33
[INFO] [08-17|12:52:24.453] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=5.6GB sys=14.6GB
[INFO] [08-17|12:52:53.113] [Caplin] P2P                             peers=33
[INFO] [08-17|12:53:24.460] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=7.5GB sys=14.6GB
[INFO] [08-17|12:53:53.112] [Caplin] P2P                             peers=33
[INFO] [08-17|12:54:21.205] [p2p] GoodPeers                          eth68=100 eth67=33
[INFO] [08-17|12:54:24.454] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=5.6GB sys=14.6GB
[INFO] [08-17|12:54:53.113] [Caplin] P2P                             peers=33
[INFO] [08-17|12:55:24.453] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=7.6GB sys=14.6GB
[INFO] [08-17|12:55:53.112] [Caplin] P2P                             peers=33
[INFO] [08-17|12:56:21.205] [p2p] GoodPeers                          eth68=100 eth67=33
[INFO] [08-17|12:56:24.449] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=5.6GB sys=14.6GB
```
Just suddenly stops importing new blocks, keeps stalling for a few hours, then gets back to business. Restarting erigon helps.
