### ISSUE TITLE
Segfault after update to v2.49.0 ("nonce too low"...)

### ISSUE THREAD

**Issue by mizu-eth** [ledgerwatch/erigon#8167]
#### System information

Erigon version: v2.49.0 

OS & Version: Linux

Commit hash: 034ef6381859a80799814f0b3e10baac9a2cf7db

Erigon Command (with flags/config): erigon --nat=stun --port=... --http.addr=... --http.vhosts=... --http.corsdomain=... --http.trace --http.api=eth,erigon,engine,web3,net,debug,trace,txpool **--internalcl** **--batchSize=128M** **--db.pagesize=16K** --metrics --metrics.addr=... --maxpeers=40 --staticpeers=...

Concensus Layer: --internalcl

Chain/Network: mainnet

#### Expected behaviour

Does not segfault.

#### Actual behaviour

Segfaults.

#### Steps to reproduce the behaviour

Run above command on v2.49.0.

#### Backtrace

````
[INFO] [09-08|20:34:36.981] [5/7 Execution] Completed on             block=18094105
[INFO] [09-08|20:34:37.457] [updateForkchoice] Fork choice update: flushing in-memory state (built by previous newPayload) 
[INFO] [09-08|20:34:38.597] RPC Daemon notified of new headers       from=18094104 to=18094105 hash=0x593650c2a3963ebdad2a0f9eedf4c1b07efae565e77cc437ddd27200f26fc976 header sending=12.804µs log sending=251ns
[INFO] [09-08|20:34:38.597] head updated                             hash=0x593650c2a3963ebdad2a0f9eedf4c1b07efae565e77cc437ddd27200f26fc976 number=18094105
[INFO] [09-08|20:34:48.534] [5/7 Execution] Completed on             block=18094106
[INFO] [09-08|20:34:49.123] [updateForkchoice] Fork choice update: flushing in-memory state (built by previous newPayload) 
[INFO] [09-08|20:34:50.837] RPC Daemon notified of new headers       from=18094105 to=18094106 hash=0x72631068c181df6a7e1f8e8e8ee5b605e479334fbea5a3fd993c4ee88ceebb4a header sending=17.103µs log sending=250ns
[INFO] [09-08|20:34:50.838] head updated                             hash=0x72631068c181df6a7e1f8e8e8ee5b605e479334fbea5a3fd993c4ee88ceebb4a number=18094106
[INFO] [09-08|20:34:58.888] [txpool] stat                            pending=102 baseFee=127 queued=161 alloc=5.9GB sys=6.6GB
[INFO] [09-08|20:35:03.492] [5/7 Execution] Completed on             block=18094107
[INFO] [09-08|20:35:05.025] [5/12 HashState] Unwinding started       from=18094106 to=18094100 storage=false codes=true
[INFO] [09-08|20:35:05.029] [5/12 HashState] Unwinding started       from=18094106 to=18094100 storage=false codes=false
[INFO] [09-08|20:35:05.080] [5/12 HashState] Unwinding started       from=18094106 to=18094100 storage=true codes=false
[INFO] [09-08|20:35:05.160] [6/12 IntermediateHashes] Unwinding      from=18094106 to=18094100 csbucket=AccountChangeSet
[INFO] [09-08|20:35:05.169] [6/12 IntermediateHashes] Unwinding      from=18094106 to=18094100 csbucket=StorageChangeSet
[INFO] [09-08|20:35:05.320] [6/12 IntermediateHashes] Trie root      hash=0x7d2bffb524cff1430146b6a58259a732685784bba209c5a843e0e554729f7d3f
[INFO] [09-08|20:35:05.514] [4/12 Execution] Unwind Execution        from=18094106 to=18094100
[INFO] [09-08|20:35:05.698] [4/12 Execution] Completed on            block=18094101
[INFO] [09-08|20:35:08.850] RPC Daemon notified of new headers       from=18093077 to=18094107 hash=0x0000000000000000000000000000000000000000000000000000000000000000 header sending=3.632915ms log sending=340ns
[INFO] [09-08|20:35:08.850] head updated                             hash=0xd6085c1c09af6d8041726b17c38cb9f46293a10cfa01c38f285e495ebcbb7dfa number=18094101
[INFO] [09-08|20:35:12.863] Execution ForkValidator.ValidatePayload  foundCanonical=true currentHash=0x72631068c181df6a7e1f8e8e8ee5b605e479334fbea5a3fd993c4ee88ceebb4a unwindPoint=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
[WARN] [09-08|20:35:12.931] [5/7 Execution] Execution failed         block=18094102 hash=0x2e08258ab4e607f22fc784b46e2b25467615dea8dfd513c0c36ae63ba0c9f309 err="could not apply tx 3 from block 18094102 [0xd06b9cbf0a3f00cc91de2e260219dc9071c2dc43f965e106f77b879179c2aa7c]: nonce too low: address 0x1ebaECda1347c67eE580C5dE46B98289f0caB4Db, tx: 84 state: 85"
[WARN] [09-08|20:35:12.931] Could not validate block                 err="[5/7 Execution] could not apply tx 3 from block 18094102 [0xd06b9cbf0a3f00cc91de2e260219dc9071c2dc43f965e106f77b879179c2aa7c]: nonce too low: address 0x1ebaECda1347c67eE580C5dE46B98289f0caB4Db, tx: 84 state: 85"
18094101
[INFO] [09-08|20:35:29.460] P2P                                      app=caplin peers=15
[INFO] [09-08|20:35:58.439] [p2p] GoodPeers                          eth68=24 eth67=4
[INFO] [09-08|20:35:58.889] [txpool] stat                            pending=1186 baseFee=180 queued=200 alloc=5.2GB sys=6.6GB
[INFO] [09-08|20:36:29.460] P2P                                      app=caplin peers=25
[INFO] [09-08|20:36:58.890] [txpool] stat                            pending=1593 baseFee=211 queued=230 alloc=6.0GB sys=8.8GB
[INFO] [09-08|20:37:29.461] P2P                                      app=caplin peers=32
[INFO] [09-08|20:37:58.438] [p2p] GoodPeers                          eth68=24 eth67=5 eth66=1
[INFO] [09-08|20:37:58.892] [txpool] stat                            pending=1959 baseFee=249 queued=294 alloc=7.2GB sys=9.0GB
[INFO] [09-08|20:38:29.460] P2P                                      app=caplin peers=29
[INFO] [09-08|20:38:58.889] [txpool] stat                            pending=2342 baseFee=278 queued=392 alloc=7.9GB sys=9.1GB
[INFO] [09-08|20:39:29.461] P2P                                      app=caplin peers=30
[INFO] [09-08|20:39:58.439] [p2p] GoodPeers                          eth68=24 eth67=5 eth66=1
[INFO] [09-08|20:39:58.889] [txpool] stat                            pending=2674 baseFee=325 queued=480 alloc=4.6GB sys=9.2GB
[INFO] [09-08|20:40:29.460] P2P                                      app=caplin peers=18
[INFO] [09-08|20:40:58.888] [txpool] stat                            pending=3010 baseFee=412 queued=582 alloc=5.6GB sys=9.3GB
[INFO] [09-08|20:41:29.461] P2P                                      app=caplin peers=22
[INFO] [09-08|20:41:58.438] [p2p] GoodPeers                          eth68=25 eth67=6
[INFO] [09-08|20:41:58.889] [txpool] stat                            pending=3318 baseFee=506 queued=691 alloc=6.6GB sys=9.3GB
[INFO] [09-08|20:42:29.460] P2P                                      app=caplin peers=24
[INFO] [09-08|20:42:58.889] [txpool] stat                            pending=3686 baseFee=603 queued=824 alloc=4.6GB sys=9.4GB
[INFO] [09-08|20:43:29.461] P2P                                      app=caplin peers=31
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19510ef]
goroutine 620105 [running]:
github.com/ledgerwatch/erigon/turbo/execution/eth1.(*EthereumExecutionModule).purgeBadChain(0xc0aa938a20?, {0x2d98980, 0xc0001d2960}, {0x2dc34e0?, 0xc0aa938a20}, {0xd6, 0x8, 0x5c, 0x1c, 0x9, ...}, ...)
	github.com/ledgerwatch/erigon/turbo/execution/eth1/ethereum_execution.go:189 +0xef
github.com/ledgerwatch/erigon/turbo/execution/eth1.(*EthereumExecutionModule).ValidateChain(0xc0a9cacf00, {0x2d98980, 0xc0001d2960}, 0xc016f6fbc0)
	github.com/ledgerwatch/erigon/turbo/execution/eth1/ethereum_execution.go:164 +0x7df
github.com/ledgerwatch/erigon-lib/direct.(*ExecutionClientDirect).ValidateChain(0xc08a45da40?, {0x2d98980?, 0xc0001d2960?}, 0x1?, {0x1?, 0x0?, 0xc012a80120?})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20230906031217-cb36bf043c5c/direct/execution_client.go:59 +0x2e
github.com/ledgerwatch/erigon/turbo/execution/eth1/eth1_chain_reader%2ego.ChainReaderWriterEth1.ValidateChain({{0x2d98980, 0xc0001d2960}, 0xc0000521e0, {0x2dafcd0, 0xc0a48d7ef0}, 0x3e8}, {0x73, 0x64, 0x8, 0x60, ...}, ...)
	github.com/ledgerwatch/erigon/turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go:288 +0x1f0
github.com/ledgerwatch/erigon/cl/phase1/execution_client.(*ExecutionClientDirect).NewPayload(0xc0840415c0, 0xc000f6fd40, 0x450b8fc0c4e1fc55?)
	github.com/ledgerwatch/erigon/cl/phase1/execution_client/execution_client_direct.go:46 +0x334
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).OnBlock(0xc09b0670a0, 0xc17ad45d50, 0x1, 0x1?)
	github.com/ledgerwatch/erigon/cl/phase1/forkchoice/on_block.go:55 +0x2eb
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func1(0xc02442be90, 0xc4?, 0x5d?)
	github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:164 +0x65
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func10({0x2d98980, 0xc1837af310}, {0x2daac50, 0xc16a4328a0}, 0xc103216690, {0x12, 0x378e2, 0x378e3, 0x6f1c6e, 0x6f1c6d})
	github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:351 +0x87a
github.com/ledgerwatch/erigon/cl/clstages.(*StageGraph[...]).StartWithStage.func1()
	github.com/ledgerwatch/erigon/cl/clstages/clstages.go:39 +0xe4
created by github.com/ledgerwatch/erigon/cl/clstages.(*StageGraph[...]).StartWithStage
	github.com/ledgerwatch/erigon/cl/clstages/clstages.go:33 +0x3e5

````

**Comment by mizu-eth** [comment]
When reverting back to 2.48.1, this error does not seem to occur.

**Comment by Giulio2002** [comment]
recover the node with make integration && ./build/bin/integration stage_headers --unwind=1000 --chain=mainnet --datadir=<whatever>

**Comment by Giulio2002** [comment]
This bug is now fixed in devel

**Comment by Giulio2002** [comment]
2.49.1 has a fix
