### ISSUE TITLE
polygon snapshots downloads error

### ISSUE THREAD

**Issue by SuperEdison** [ledgerwatch/erigon#8180]
#### System information

Erigon version: `./erigon --version`
v2.49.1

OS & Version: Windows/Linux/OSX

Commit hash: 
git_commit=205eeda01fd8f8a2956276d6760b9298f70bd18f
Erigon Command (with flags/config):
/data/ledgerwatch-erigon/build/bin/erigon --datadir=/mnt/polygon/polygondata --http.api=eth,erigon,engine,trace,web3 --http.addr=0.0.0.0 --http.port=80 --http.vhosts=* --chain=bor-mainnet --rpc.batch.concurrency=32 --db.read.concurrency=256 --bor.heimdall=http://localhost:1317 --batchSize=1g --db.size.limit=7T
Concensus Layer:
heimdall
Concensus Layer Command (with flags/config):

Chain/Network: 
bor
#### Expected behaviour
```log
[INFO] [09-12|16:32:23.290] Build info                               git_branch=HEAD git_tag=v2.49.1 git_commit=205eeda01fd8f8a2956276d6760b9298f70bd18f
[INFO] [09-12|16:32:23.290] Starting Erigon on Bor Mainnet... 
[INFO] [09-12|16:32:23.291] Maximum peer count                       ETH=100 total=100
[INFO] [09-12|16:32:23.291] starting HTTP APIs                       APIs=eth,erigon,engine,trace,web3
[INFO] [09-12|16:32:23.291] torrent verbosity                        level=WRN
[INFO] [09-12|16:32:25.393] Set global gas cap                       cap=50000000
[INFO] [09-12|16:32:25.394] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=16mb upload.rate=4mb
[INFO] [09-12|16:32:25.394] Opening Database                         label=chaindata path=/mnt/polygon/polygondata/chaindata
[INFO] [09-12|16:32:31.203] Initialised chain configuration          config="{ChainID: 137, Homestead: 0, DAO: <nil>, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, Gray Glacier: <nil>, Terminal Total Difficulty: <nil>, Merge Netsplit: <nil>, Shanghai: <nil>, Cancun: <nil>, Prague: <nil>, Engine: bor}" genesis=0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b
[INFO] [09-12|16:32:34.130] Initialising Ethereum protocol           network=137
[INFO] [09-12|16:32:34.130] Opening Database                         label=bor path=/mnt/polygon/polygondata/bor
[INFO] [09-12|16:32:34.636] Starting private RPC server              on=127.0.0.1:9090
[INFO] [09-12|16:32:34.636] new subscription to logs established 
[INFO] [09-12|16:32:34.636] rpc filters: subscribing to Erigon events 
[INFO] [09-12|16:32:34.636] new subscription to newHeaders established 
[INFO] [09-12|16:32:34.636] New txs subscriber joined 
[INFO] [09-12|16:32:34.637] Reading JWT secret                       path=/mnt/polygon/polygondata/jwt.hex
[INFO] [09-12|16:32:34.637] HTTP endpoint opened for Engine API      url=127.0.0.1:8551 ws=true ws.compression=true
[INFO] [09-12|16:32:34.637] HTTP endpoint opened                     url=[::]:80 ws=false ws.compression=true grpc=false
[WARN] [09-12|16:32:34.639] NAT ExternalIP resolution has failed, try to pass a different --nat option err="no UPnP or NAT-PMP router discovered"
[WARN] [09-12|16:32:34.640] NAT ExternalIP resolution has failed, try to pass a different --nat option err="no UPnP or NAT-PMP router discovered"
[INFO] [09-12|16:32:34.647] [txpool] Started 
[INFO] [09-12|16:32:34.647] Started P2P networking                   version=67 self=enode://b7141d7c0ec4a1132fa094355663f8a758edd91fd253538a712933f93e2b4e650e8c38db69fccd2aef41c4204c92018c5bc6a220bec0e4248337e60a070e11eb@127.0.0.1:0 name=erigon/v2.49.1-stable-205eeda0/linux-amd64/go1.20.4
[INFO] [09-12|16:32:34.649] Started P2P networking                   version=68 self=enode://b7141d7c0ec4a1132fa094355663f8a758edd91fd253538a712933f93e2b4e650e8c38db69fccd2aef41c4204c92018c5bc6a220bec0e4248337e60a070e11eb@127.0.0.1:0 name=erigon/v2.49.1-stable-205eeda0/linux-amd64/go1.20.4
[INFO] [09-12|16:32:34.662] [1/15 Snapshots] Fetching torrent files metadata 
[INFO] [09-12|16:51:23.267] [1/15 Snapshots] download                progress="99.97% 741.0GB/741.3GB" download-time-left=999hrs:99m total-download-time=20s download=0B/s upload=0B/s
[INFO] [09-12|16:51:23.267] [1/15 Snapshots] download                peers=0 connections=0 files=464 alloc=4.6GB sys=4.8GB
[INFO] [09-12|16:51:43.267] [1/15 Snapshots] download                progress="99.97% 741.0GB/741.3GB" download-time-left=999hrs:99m total-download-time=40s download=0B/s upload=0B/s
[INFO] [09-12|16:51:43.267] [1/15 Snapshots] download                peers=0 connections=0 files=464 alloc=4.6GB sys=4.9GB
[INFO] [09-12|16:52:03.239] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=4.7GB sys=5.0GB
[INFO] [09-12|16:52:03.267] [1/15 Snapshots] download                progress="99.97% 741.3GB/741.5GB" download-time-left=10hrs:59m total-download-time=1m0s download=6.7KB/s upload=0B/s
[INFO] [09-12|16:52:03.267] [1/15 Snapshots] download                peers=1 connections=1 files=464 alloc=4.7GB sys=5.0GB
[INFO] [09-12|16:52:23.266] [1/15 Snapshots] download                progress="99.97% 741.3GB/741.5GB" download-time-left=999hrs:99m total-download-time=1m20s download=0B/s upload=0B/s
[INFO] [09-12|16:52:23.266] [1/15 Snapshots] download                peers=2 connections=2 files=464 alloc=4.8GB sys=5.1GB
[INFO] [09-12|16:52:43.267] [1/15 Snapshots] download                progress="99.97% 741.7GB/742.0GB" download-time-left=0hrs:12m total-download-time=1m40s download=349.3KB/s upload=0B/s
[INFO] [09-12|16:52:43.267] [1/15 Snapshots] download                peers=0 connections=0 files=464 alloc=4.9GB sys=5.1GB
[INFO] [09-12|16:53:02.782] [p2p] GoodPeers 
[INFO] [09-12|16:53:03.238] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=4.9GB sys=5.2GB
[INFO] [09-12|16:53:03.266] [1/15 Snapshots] download                progress="99.97% 741.7GB/742.0GB" download-time-left=999hrs:99m total-download-time=2m0s download=0B/s upload=0B/s
[INFO] [09-12|16:53:03.266] [1/15 Snapshots] download                peers=0 connections=0 files=464 alloc=4.9GB sys=5.2GB
[INFO] [09-12|16:53:23.267] [1/15 Snapshots] download                progress="99.97% 742.0GB/742.2GB" download-time-left=0hrs:7m total-download-time=2m20s download=558.5KB/s upload=0B/s
[INFO] [09-12|16:53:23.267] [1/15 Snapshots] download                peers=0 connections=0 files=464 alloc=3.2GB sys=5.2GB
[INFO] [09-12|16:53:43.267] [1/15 Snapshots] download                progress="99.97% 742.0GB/742.2GB" download-time-left=999hrs:99m total-download-time=2m40s download=0B/s upload=0B/s
[INFO] [09-12|16:53:43.267] [1/15 Snapshots] download                peers=0 connections=0 files=464 alloc=3.3GB sys=5.2GB
[INFO] [09-12|16:54:03.238] [txpool] stat                            pending=234 baseFee=286 queued=1788 alloc=3.4GB sys=5.2GB
[INFO] [09-12|16:54:03.267] [1/15 Snapshots] download                progress="99.97% 742.0GB/742.2GB" download-time-left=7hrs:36m total-download-time=3m0s download=9.0KB/s upload=0B/s
[INFO] [09-12|16:54:03.267] [1/15 Snapshots] download                peers=0 connections=0 files=464 alloc=3.4GB sys=5.2GB
[INFO] [09-12|16:54:23.267] [1/15 Snapshots] download                progress="99.97% 743.5GB/743.8GB" download-time-left=6hrs:11m total-download-time=3m20s download=11.0KB/s upload=0B/s
[INFO] [09-12|16:54:23.267] [1/15 Snapshots] download                peers=1 connections=1 files=464 alloc=3.4GB sys=5.2GB
[INFO] [09-12|16:54:43.267] [1/15 Snapshots] download                progress="99.97% 755.2GB/755.4GB" download-time-left=4hrs:46m total-download-time=3m40s download=14.2KB/s upload=0B/s
[INFO] [09-12|16:54:43.267] [1/15 Snapshots] download                peers=1 connections=1 files=464 alloc=3.5GB sys=5.2GB
[INFO] [09-12|16:55:02.781] [p2p] GoodPeers                          eth68=1
[INFO] [09-12|16:55:03.239] [txpool] stat                            pending=491 baseFee=286 queued=3340 alloc=3.5GB sys=5.2GB
[INFO] [09-12|16:55:03.267] [1/15 Snapshots] download                progress="99.97% 755.2GB/755.4GB" download-time-left=999hrs:99m total-download-time=4m0s download=0B/s upload=0B/s
[INFO] [09-12|16:55:03.267] [1/15 Snapshots] download                peers=1 connections=1 files=464 alloc=3.5GB sys=5.2GB
[EROR] [09-12|16:55:22.328] [txpool] flush is local history          err="table: PoolTransaction, err: mdbx_cursor_put: MDBX_MAP_FULL: Environment mapsize limit reached"
[INFO] [09-12|16:55:23.267] [1/15 Snapshots] download                progress="99.97% 755.2GB/755.4GB" download-time-left=2hrs:38m total-download-time=4m20s download=25.6KB/s upload=0B/s
[INFO] [09-12|16:55:23.267] [1/15 Snapshots] download                peers=1 connections=2 files=464 alloc=3.2GB sys=5.2GB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14f1ac7]

goroutine 9081 [running]:
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).flushLocked(0xc003f50e00, {0x2dc9800?, 0xc128d1d440})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230911021829-c23d49fb5d32/txpool/pool.go:1614 +0xa7
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).flush.func1({0x2dc9800?, 0xc128d1d440})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230911021829-c23d49fb5d32/txpool/pool.go:1598 +0x4b
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).Update(0x501010000?, {0x2d9eca0?, 0xc0006a41e0?}, 0xc0ce7ee0e0)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230911021829-c23d49fb5d32/kv/mdbx/kv_mdbx.go:670 +0xb6
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).flush(0xc003f50e00, {0x2d9eca0, 0xc0006a41e0}, {0x2db0958, 0xc0010ecea0})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230911021829-c23d49fb5d32/txpool/pool.go:1597 +0x21f
github.com/ledgerwatch/erigon-lib/txpool.MainLoop({0x2d9eca0?, 0xc0006a41e0}, {0x2db0958, 0xc0010ecea0}, {0x1b?, 0x1b?}, 0xc003f50e00, 0xc0a0716de0, 0xc0a02fd450, 0xc0e9145788, ...)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230911021829-c23d49fb5d32/txpool/pool.go:1483 +0x36a
created by github.com/ledgerwatch/erigon/eth.New
        github.com/ledgerwatch/erigon/eth/backend.go:656 +0x3ff1
```

#### Backtrace

````
[backtrace]
````

**Comment by 0xKrishna** [comment]
Fixed in the latest version, Please try again.
