### ISSUE TITLE
Invalid memory address or nil pointer dereference on 2.49.1

### ISSUE THREAD

**Issue by ncocchiaro** [ledgerwatch/erigon#8209]
#### System information

Erigon version: 2.49.1-stable. Pre-built binary

OS & Version: Linux

Commit hash: 205eeda01fd8f8a2956276d6760b9298f70bd18f

Erigon Command (with flags/config): erigon --chain=mainnet  --pprof --rpc.gascap 500000000 --nat=stun  --authrpc.addr=0.0.0.0 --authrpc.vhosts=* --http --http.addr 0.0.0.0 --http.corsdomain * --http.port 8545 --http.api eth,trace,net,engine,web3 --http.vhosts * --port 30303 --maxpeers 50 --txpool.nolocals --txpool.accountslots 32 --txpool.globalslots 8192 --txpool.accountqueue 128 --txpool.globalqueue 2048 --txpool.lifetime 3h0m0s --datadir /mnt/local/ethereum --ws    --authrpc.jwtsecret /mnt/local/ethereum/engine-jwt.key

Consensus Layer: Teku 23.9.0

Consensus Layer Command (with flags/config): teku --log-destination=console --data-base-path=/mnt/local/ethereum --network=mainnet --ee-endpoint=http://localhost:8551 --eth1-endpoint=http://localhost:8545 --ee-jwt-secret-file=/mnt/local/ethereum/engine-jwt.key --rest-api-enabled=true --rest-api-host-allowlist=* --rest-api-interface=0.0.0.0 --rest-api-port=5051 --metrics-enabled=true --metrics-host-allowlist=* --metrics-interface=0.0.0.0 --metrics-port=8008 --metrics-block-timing-tracking-enabled=true

Chain/Network: Ethereum mainnet

#### Expected behaviour

Erigon doesn't crash and syncs to head.

#### Actual behaviour

Erigon crashes with:

```
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14e1a87]
```

In this case there's a number of warnings beforehand about a timestamp discrepancy between the index file and segment file, and other errors, as seen in this log excerpt leading up to the panic:

```
Sep 15 15:13:19 ip-10-0-69-130 erigon[407070]: [WARN] [09-15|15:13:19.777] Index file has timestamp before segment file, will be recreated segfile=/mnt/local/ethereum/sna>
Sep 15 15:13:19 ip-10-0-69-130 erigon[407070]: [WARN] [09-15|15:13:19.777] Index file has timestamp before segment file, will be recreated segfile=/mnt/local/ethereum/sna>
Sep 15 15:13:19 ip-10-0-69-130 erigon[407070]: [WARN] [09-15|15:13:19.778] Index file has timestamp before segment file, will be recreated segfile=/mnt/local/ethereum/sna>
Sep 15 15:13:19 ip-10-0-69-130 erigon[407070]: [WARN] [09-15|15:13:19.778] Index file has timestamp before segment file, will be recreated segfile=/mnt/local/ethereum/sna>
Sep 15 15:13:19 ip-10-0-69-130 erigon[407070]: [WARN] [09-15|15:13:19.779] Index file has timestamp before segment file, will be recreated segfile=/mnt/local/ethereum/sna>
Sep 15 15:13:19 ip-10-0-69-130 erigon[407070]: [WARN] [09-15|15:13:19.779] Index file has timestamp before segment file, will be recreated segfile=/mnt/local/ethereum/sna>
Sep 15 15:13:19 ip-10-0-69-130 erigon[407070]: [WARN] [09-15|15:13:19.780] Index file has timestamp before segment file, will be recreated segfile=/mnt/local/ethereum/sna>
Sep 15 15:13:19 ip-10-0-69-130 erigon[407070]: [WARN] [09-15|15:13:19.780] Index file has timestamp before segment file, will be recreated segfile=/mnt/local/ethereum/sna>
Sep 15 15:13:19 ip-10-0-69-130 erigon[407070]: [WARN] [09-15|15:13:19.781] Index file has timestamp before segment file, will be recreated segfile=/mnt/local/ethereum/sna>
Sep 15 15:13:19 ip-10-0-69-130 erigon[407070]: [WARN] [09-15|15:13:19.782] Index file has timestamp before segment file, will be recreated segfile=/mnt/local/ethereum/sna>
Sep 15 15:13:19 ip-10-0-69-130 erigon[407070]: [WARN] [09-15|15:13:19.783] Index file has timestamp before segment file, will be recreated segfile=/mnt/local/ethereum/sna>
Sep 15 15:13:19 ip-10-0-69-130 erigon[407070]: [WARN] [09-15|15:13:19.790] Index file has timestamp before segment file, will be recreated segfile=/mnt/local/ethereum/sna>
Sep 15 15:13:31 ip-10-0-69-130 erigon[407070]: [EROR] [09-15|15:13:31.752] [txpool] flush is local history          err="table: PoolTransaction, err: mdbx_cursor_put: MDB>
Sep 15 15:13:39 ip-10-0-69-130 erigon[407070]: [INFO] [09-15|15:13:39.731] [1/12 Snapshots] Indexing                progress="v1-001000-001500-transactions.seg=32%, v1-00>
Sep 15 15:13:47 ip-10-0-69-130 erigon[407070]: [EROR] [09-15|15:13:47.346] [txpool] flush is local history          err="table: PoolTransaction, err: mdbx_cursor_put: MDB>
Sep 15 15:13:59 ip-10-0-69-130 erigon[407070]: [INFO] [09-15|15:13:59.730] [1/12 Snapshots] Indexing                progress="v1-001000-001500-transactions.seg=50%, v1-00>
Sep 15 15:14:02 ip-10-0-69-130 erigon[407070]: [EROR] [09-15|15:14:02.950] [txpool] flush is local history          err="table: PoolTransaction, err: mdbx_cursor_put: MDB>
Sep 15 15:14:16 ip-10-0-69-130 erigon[407070]: [INFO] [09-15|15:14:16.141] [txpool] stat                            pending=34 baseFee=5 queued=313 alloc=8.4GB sys=14.3GB
Sep 15 15:14:18 ip-10-0-69-130 erigon[407070]: [EROR] [09-15|15:14:18.554] [txpool] flush is local history          err="table: PoolTransaction, err: mdbx_cursor_put: MDB>
Sep 15 15:14:19 ip-10-0-69-130 erigon[407070]: [INFO] [09-15|15:14:19.733] [1/12 Snapshots] Indexing                progress="v1-001000-001500-transactions.seg=50%, v1-00>
Sep 15 15:14:34 ip-10-0-69-130 erigon[407070]: [EROR] [09-15|15:14:34.158] [txpool] flush is local history          err="table: PoolTransaction, err: mdbx_cursor_put: MDB>
Sep 15 15:14:39 ip-10-0-69-130 erigon[407070]: [INFO] [09-15|15:14:39.733] [1/12 Snapshots] Indexing                progress="v1-001000-001500-transactions.seg=50%, v1-00>
Sep 15 15:14:49 ip-10-0-69-130 erigon[407070]: [EROR] [09-15|15:14:49.765] [txpool] flush is local history          err="table: PoolTransaction, err: mdbx_cursor_put: MDB>
Sep 15 15:14:59 ip-10-0-69-130 erigon[407070]: [INFO] [09-15|15:14:59.730] [1/12 Snapshots] Indexing                progress="v1-001000-001500-transactions.seg=50%, v1-00>
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14e1a87]
```

#### Steps to reproduce the behaviour

Attempt to sync to head after upgrading Erigon to 2.49.1, with an existing DB created with 2.43.1.

#### Backtrace

````
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]: goroutine 2587 [running]:
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]: github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).flushLocked(0xc0b184a800, {0x2eba900?, 0xc34b254720})
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]:         /root/go/pkg/mod/github.com/ledgerwatch/erigon-lib@v0.0.0-20230911021829-c23d49fb5d32/txpool/pool.go:1614 +0xa7
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]: github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).flush.func1({0x2eba900?, 0xc34b254720})
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]:         /root/go/pkg/mod/github.com/ledgerwatch/erigon-lib@v0.0.0-20230911021829-c23d49fb5d32/txpool/pool.go:1598 +0x4b
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]: github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).Update(0x501010001?, {0x2e8fda0?, 0xc001418190?}, 0xc34b220580)
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]:         /root/go/pkg/mod/github.com/ledgerwatch/erigon-lib@v0.0.0-20230911021829-c23d49fb5d32/kv/mdbx/kv_mdbx.go:670 +0xb6
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]: github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).flush(0xc0b184a800, {0x2e8fda0, 0xc001418190}, {0x2ea1a58, 0xc0b496a1a0})
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]:         /root/go/pkg/mod/github.com/ledgerwatch/erigon-lib@v0.0.0-20230911021829-c23d49fb5d32/txpool/pool.go:1597 +0x21f
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]: github.com/ledgerwatch/erigon-lib/txpool.MainLoop({0x2e8fda0?, 0xc001418190}, {0x2ea1a58, 0xc0b496a1a0}, {0x0?, 0xc09beb600>
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]:         /root/go/pkg/mod/github.com/ledgerwatch/erigon-lib@v0.0.0-20230911021829-c23d49fb5d32/txpool/pool.go:1483 +0x36a
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]: created by github.com/ledgerwatch/erigon/eth.New
Sep 15 15:15:05 ip-10-0-69-130 erigon[407070]:         /go/src/github.com/ledgerwatch/erigon/eth/backend.go:656 +0x3ff1
````

**Comment by AskAlexSharov** [comment]
Please remove datadir/txpool folder

**Comment by mans17** [comment]
> Please remove datadir/txpool folder

I confirm this fix works here, `v2.49.2`, upgraded from ` v2.48.0`

**Comment by mbwmbw1337** [comment]
See: https://github.com/ledgerwatch/erigon/issues/8236

**Comment by ncocchiaro** [comment]
Haven't seen this again since the removal of that dir.
