### ISSUE TITLE
mdbx_env_open: cannot allocate memory

### ISSUE THREAD

**Issue by c29r3** [ledgerwatch/erigon#8221]
#### System information

Erigon version: `./erigon --version`  
`erigon version 2.49.0-stable`  

OS & Version: Windows/Linux/OSX  
```
Processor  : AMD Ryzen 9 7950X3D 16-Core Processor
CPU cores  : 32 @ 4200.000 MHz
AES-NI     : ✔ Enabled
VM-x/AMD-V : ✔ Enabled
RAM        : 125.5 GiB
Swap       : 50.0 GiB
Disk       : 10.4 TiB
Distro     : Ubuntu 22.04.3 LTS
Kernel     : 5.15.0-83-generic
VM Type    : NONE
IPv4/IPv6  : ✔ Online / ✔ Online


free -h
               total        used        free      shared  buff/cache   available
Mem:           125Gi        51Gi       1.0Gi        13Mi        73Gi        73Gi
Swap:           49Gi       2.1Gi        47Gi

ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 513516
max locked memory           (kbytes, -l) 64
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1048576
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 513516
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

Commit hash: 

Erigon Command (with flags/config):  
```
erigon \
  --datadir mainnet \
  --private.api.addr=127.0.0.1:9090 \
  --chain=mainnet \
  --port=30303 \
  --http.port=8545 \
  --torrent.port=42069 \
  --http --http.addr=127.0.0.1 \
  --ws --http.api=eth,debug,net,trace,web3,txpool,erigon \
  --metrics --metrics.addr="0.0.0.0" \
  --metrics.port="44451" \
  --prune htc \
  --prune.r.before=11052984 \
  --authrpc.jwtsecret="$HOME/erigon/mainnet/jwt.hex"
```

Concensus Layer:   
`Lighthouse v4.4.1-2841f60`

Concensus Layer Command (with flags/config):  
```
lighthouse beacon_node \
--suggested-fee-recipient <ADDR> \
--datadir="$HOME/lighthouse" \
--network="mainnet" \
--staking \
--execution-jwt="$HOME/erigon/mainnet/jwt.hex" \
--execution-endpoint="http://127.0.0.1:8551" \
--http --http-address="127.0.0.1" \
--http-allow-origin="*" \
--metrics --metrics-address="0.0.0.0" --metrics-port="44450" \
--metrics-allow-origin="*" \
--subscribe-all-subnets \
--import-all-attestations \
--validator-monitor-auto \
--checkpoint-sync-url=https://beaconstate.info \
--private \
--disable-upnp
```

Chain/Network: 
`mainnet`

#### Actual behaviour  
erigon service was restarted

#### Steps to reproduce the behaviour
I don't know how to reproduce this. I have a similar configuration on another server, but there were no such problems

#### Backtrace

````
Sep 17 11:27:36 erigon[66564]: [WARN] [09-17|11:27:36.515] [EngineBlockDownloader] Could create temporary mdbx err="mdbx_env_open: cannot allocate memory, label: inMem, trace: [kv_mdbx.go:263 util.go:49 kv_mdbx_temporary.go:38 core.go:41 asm_amd64.s:1598]"
Sep 17 11:27:37 erigon[66564]: [INFO] [09-17|11:27:37.614] [EngineBlockDownloader] Downloading PoS headers... height=unknown hash=0x21e91669ace88a0539b62bdb633c68674e9cec225751a4e233304c3519896414 requestId=0
Sep 17 11:27:37 erigon[66564]: [WARN] [09-17|11:27:37.662] [EngineBlockDownloader] Could create temporary mdbx err="mdbx_env_open: cannot allocate memory, label: inMem, trace: [kv_mdbx.go:263 util.go:49 kv_mdbx_temporary.go:38 core.go:41 asm_amd64.s:1598]"
Sep 17 11:27:40 erigon[66564]: [INFO] [09-17|11:27:40.671] [p2p] GoodPeers                          eth68=98 eth67=32
Sep 17 11:27:41 erigon[66564]: [INFO] [09-17|11:27:41.540] [txpool] stat                            pending=10000 baseFee=3515 queued=30000 alloc=6.3GB sys=10.6GB
Sep 17 11:27:49 erigon[66564]: [INFO] [09-17|11:27:49.824] [NewPayload] Handling new payload        height=18154578 hash=0x64ab350e777b2346119ee687b3e437826d6ed9f165552d895d22b42b87cc62f1
Sep 17 11:27:49 erigon[66564]: [INFO] [09-17|11:27:49.824] [EngineBlockDownloader] Downloading PoS headers... height=unknown hash=0x21e91669ace88a0539b62bdb633c68674e9cec225751a4e233304c3519896414 requestId=0
Sep 17 11:27:49 erigon[66564]: [WARN] [09-17|11:27:49.861] [EngineBlockDownloader] Could create temporary mdbx err="mdbx_env_open: cannot allocate memory, label: inMem, trace: [kv_mdbx.go:263 util.go:49 kv_mdbx_temporary.go:38 core.go:41 asm_amd64.s:1598]"
Sep 17 11:27:50 erigon[66564]: [INFO] [09-17|11:27:50.936] [EngineBlockDownloader] Downloading PoS headers... height=unknown hash=0x64ab350e777b2346119ee687b3e437826d6ed9f165552d895d22b42b87cc62f1 requestId=0
Sep 17 11:27:50 erigon[66564]: [WARN] [09-17|11:27:50.978] [EngineBlockDownloader] Could create temporary mdbx err="mdbx_env_open: cannot allocate memory, label: inMem, trace: [kv_mdbx.go:263 util.go:49 kv_mdbx_temporary.go:38 core.go:41 asm_amd64.s:1598]"
Sep 17 11:27:59 erigon[66564]: [INFO] [09-17|11:27:59.733] [NewPayload] Handling new payload        height=18154579 hash=0x30ebf63bcdae766bd0cba274a2d78c00eaf669124897b4fb234081c9dffab0fa
Sep 17 11:27:59 erigon[66564]: [INFO] [09-17|11:27:59.733] [EngineBlockDownloader] Downloading PoS headers... height=unknown hash=0x64ab350e777b2346119ee687b3e437826d6ed9f165552d895d22b42b87cc62f1 requestId=0
Sep 17 11:27:59 erigon[66564]: [WARN] [09-17|11:27:59.760] [EngineBlockDownloader] Could create temporary mdbx err="mdbx_env_open: cannot allocate memory, label: inMem, trace: [kv_mdbx.go:263 util.go:49 kv_mdbx_temporary.go:38 core.go:41 asm_amd64.s:1598]"
Sep 17 11:28:00 erigon[66564]: [INFO] [09-17|11:28:00.851] [EngineBlockDownloader] Downloading PoS headers... height=unknown hash=0x30ebf63bcdae766bd0cba274a2d78c00eaf669124897b4fb234081c9dffab0fa requestId=0
Sep 17 11:28:00 erigon[66564]: [INFO] [09-17|11:28:00.903] [EngineBlockDownloader] Processing bodies... from=18154467 to=18154579
Sep 17 11:28:12 erigon[66564]: [INFO] [09-17|11:28:12.498] [EngineBlockDownloader] Processed        highest=18154579
Sep 17 11:28:12 erigon[66564]: [INFO] [09-17|11:28:12.498] Beginning downloaded blocks insertion
Sep 17 11:28:12 erigon[66564]: [INFO] [09-17|11:28:12.599] [EngineBlockDownloader] Finished downloading blocks from=18154467 to=18154579
Sep 17 11:28:13 erigon[66564]: [INFO] [09-17|11:28:13.212] [NewPayload] Handling new payload        height=18154580 hash=0x5739d012b112dddcb80c4e216916ca6ed9d8d9d657fed5b598d9c1532fef5a6d
Sep 17 11:28:13 erigon[66564]: [INFO] [09-17|11:28:13.345] [3/12 Senders] Started                   from=18154466 to=18154580
Sep 17 11:28:13 erigon[66564]: [INFO] [09-17|11:28:13.397] [4/12 Execution] Blocks execution        from=18154466 to=18154580
Sep 17 11:28:24 erigon[66564]: [INFO] [09-17|11:28:24.081] [NewPayload] Handling new payload        height=18154581 hash=0x108066c2a7dee666e5ef9614ef906cc1dacbb4b79fa116cb85795fac25041f71
Sep 17 11:28:24 erigon[66564]: [INFO] [09-17|11:28:24.195] [3/12 Senders] Started                   from=18154466 to=18154581
Sep 17 11:28:24 erigon[66564]: [INFO] [09-17|11:28:24.242] [4/12 Execution] Blocks execution        from=18154466 to=18154581
Sep 17 11:28:24 erigon[66564]: runtime/cgo: pthread_create failed: 	
Sep 17 11:28:24 erigon[66564]: SIGABRT: abort
Sep 17 11:28:24 erigon[66564]: PC=0x1f765e1 m=2 sigcode=18446744073709551610
Sep 17 11:28:24 erigon[66564]: goroutine 0 [idle]:
Sep 17 11:28:24 erigon[66564]: runtime: g 0: unknown pc 0x1f765e1
Sep 17 11:28:24 erigon[66564]: stack: frame={sp:0x7f8c44326bb0, fp:0x0} stack=[0x7f8c43b27680,0x7f8c44327280)
Sep 17 11:28:24 erigon[66564]: 0x00007f8c44326ab0:  0x0000000000000000  0x0000000000000000
...
*super long traceback*
````

**Comment by AskAlexSharov** [comment]
- please upgrade to 2.49.2
- how much space left in datadir/tmp?

**Comment by AskAlexSharov** [comment]
Try set explicit —db.size.limit

**Comment by AskAlexSharov** [comment]
Let’s try v2.51.0
