### ISSUE TITLE
Unhandled Exception - panic: runtime error: index out of range [32] with length 32

### ISSUE THREAD

**Issue by mbwmbw1337** [ledgerwatch/erigon#8235]
I run a cluster of over 30 Erigon full archive nodes. About 30-50% have been having this unhandled panic causing the application to completely exit. I restarted the Application, and it seems to progress.

May be related to:
- https://github.com/golang/go/issues/60860
- https://github.com/hajimehoshi/ebiten/issues/1173

**Version**
```
/home/erigon/erigon/build/bin/erigon -v
erigon version 2.49.0-dev-8983128d
```

**Command**
#bin/bash
```
/home/erigon/erigon/build/bin/erigon \
--chain=mainnet \
--torrent.upload.rate="1024mb" \
--torrent.download.rate="1024mb" \
--datadir="$(eval echo ~$USER)/erigon-eth" \
--internalcl \
--chain=mainnet \
--port=30501 \
--http.port=9201 \
--authrpc.port=9101 \
--authrpc.addr=0.0.0.0 \
--authrpc.vhosts=* \
--torrent.port=42501 \
--private.api.addr=127.0.0.1:9090 \
--nat="extip:$(curl -s ifconfig.me)" \
--http \
--http.api=eth,erigon,web3,net,debug,trace,txpool \
--ws \
--ws.compression
```

```
INFO[09-19|02:04:08.874] head updated                             hash=0x6c1b7d9718a6a3ca96697f0d9d491b4dbfc7bf9bfa0a5c271b9d81253bfd84ec number=18165895
INFO[09-19|02:04:08.952] [5/7 Execution] Completed on             block=18165896
INFO[09-19|02:04:09.050] [Caplin] Downloading epochs from reqresp app=caplin stage=CatchUpEpochs from=229826 to=229837
INFO[09-19|02:04:09.885] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=229826
INFO[09-19|02:04:11.283] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=229827
INFO[09-19|02:04:13.362] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=229828
INFO[09-19|02:04:17.599] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=229829
INFO[09-19|02:04:19.601] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=229830
INFO[09-19|02:04:24.058] [txpool] stat                            pending=10000 baseFee=30000 queued=30000 alloc=8.9GB sys=22.3GB
INFO[09-19|02:04:26.528] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=229831
INFO[09-19|02:04:28.791] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=229832
INFO[09-19|02:04:32.869] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=229833
INFO[09-19|02:04:34.886] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=229834
INFO[09-19|02:04:39.550] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=229835
INFO[09-19|02:04:42.288] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=229836
INFO[09-19|02:04:47.409] [Caplin] Epoch downloaded                app=caplin stage=CatchUpEpochs epoch=229837
INFO[09-19|02:04:57.524] [3/12 Senders] Started                   from=18165895 to=18166277
INFO[09-19|02:04:57.945] [4/12 Execution] Blocks execution        from=18165895 to=18166277
panic: runtime error: index out of range [32] with length 32

goroutine 102629835 [running]:
github.com/tidwall/btree.(*Map[...]).nodeAscend(0x2ddd7a0?, 0xc02ea62960, 0x1?, 0xc0c1685e78, 0x60)
        github.com/tidwall/btree@v1.6.0/map.go:530 +0x225
github.com/tidwall/btree.(*Map[...]).nodeAscend(0x2ddd7a0?, 0xc03447ddc8, 0x1?, 0xc0c1685e78, 0xe0)
        github.com/tidwall/btree@v1.6.0/map.go:516 +0x12d
github.com/tidwall/btree.(*Map[...]).ascend(...)
        github.com/tidwall/btree@v1.6.0/map.go:504
github.com/tidwall/btree.(*Map[...]).AscendMut(0x43c6aa?, 0xc18b0ac4a0?, 0x10?)
        github.com/tidwall/btree@v1.6.0/map.go:497 +0x45
github.com/ledgerwatch/erigon/cl/persistence.(*GossipSource).PurgeRange(0xc17e0e36d8?, {0x5707d6?, 0x2d925a0?}, 0xc07fa10500?, 0xc21e90aeb0?)
        github.com/ledgerwatch/erigon/cl/persistence/block_store.go:112 +0xf5
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func16({0x2d925a0, 0xc21e90aeb0}, {0x2da4870?, 0xc0a89a7b60?}, 0xc032c18780, {0x18, 0x381cd, 0x381ce, 0x7039c6, 0x7039c6})
        github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:492 +0x5b
github.com/ledgerwatch/erigon/cl/clstages.(*StageGraph[...]).StartWithStage.func1()
        github.com/ledgerwatch/erigon/cl/clstages/clstages.go:39 +0xe4
created by github.com/ledgerwatch/erigon/cl/clstages.(*StageGraph[...]).StartWithStage
        github.com/ledgerwatch/erigon/cl/clstages/clstages.go:33 +0x3e5
```

**Comment by AskAlexSharov** [comment]
I think you didn’t upgrade to 2.49.2

**Comment by mbwmbw1337** [comment]
I just updated now and have not had a repeat of this issue. I will reopen if I do.

**Comment by mbwmbw1337** [comment]
Specifically still occurring on
```
/home/erigon/erigon/build/bin/erigon --version
erigon version 2.49.2-stable-a8ae8a03
```
