### ISSUE TITLE
Unhandled Exception - panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x194f18f]

### ISSUE THREAD

**Issue by mbwmbw1337** [ledgerwatch/erigon#8236]
**Version**
```
/home/erigon/erigon/build/bin/erigon -v
erigon version 2.49.0-dev-8983128d
```

**Command**
#bin/bash
```
/home/erigon/erigon/build/bin/erigon \
--chain=mainnet \
--torrent.upload.rate="1024mb" \
--torrent.download.rate="1024mb" \
--datadir="$(eval echo ~$USER)/erigon-eth" \
--internalcl \
--chain=mainnet \
--port=30501 \
--http.port=9201 \
--authrpc.port=9101 \
--authrpc.addr=0.0.0.0 \
--authrpc.vhosts=* \
--torrent.port=42501 \
--private.api.addr=127.0.0.1:9090 \
--nat="extip:$(curl -s ifconfig.me)" \
--http \
--http.api=eth,erigon,web3,net,debug,trace,txpool \
--ws \
--ws.compression
```

```
=945.934µs log sending=227ns
INFO[09-19|10:15:18.910] head updated                             hash=0xe8df7abf068b2bd9fe6e872de41166d6ba3ee93c12dd844b8bc52e693a6f69ce number=18168681
INFO[09-19|10:15:18.939] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0x8ff704f391a25eac7455f578d0c6ee547650bd806a2fc5bdf63c03d626355335 unwindPoint=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO[09-19|10:15:18.940] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0x65bdb844b2bc7e37cd9262614dddc0ef69d5c4b2ef62cc00d6e753eb61c980c9 unwindPoint=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO[09-19|10:15:18.942] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0x0360c3e071279b617509da13bc3e3b61e434ae8dfc1a1255e50afb2db25854c9 unwindPoint=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO[09-19|10:15:18.943] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0x77270c511fad57a77d0b73ff4f60e924ba5b21abf56944dd40328f4561e2c3b1 unwindPoint=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO[09-19|10:15:18.944] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0xf4465f03354ddc608895d17c3d81bd4c3aa7f1d38f516f34d5dd7d4b1b158c61 unwindPoint=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO[09-19|10:15:18.945] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0x1d79bd6e141794af758e410e43bd9edff56deb7f9a4237c4039763bebca93040 unwindPoint=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO[09-19|10:15:18.946] Execution ForkValidator.ValidatePayload  foundCanonical=false currentHash=0x791f0c39d06a60d0641e8a632993bd62b46f611ecb8a9f96bbab90bf8624560b unwindPoint=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO[09-19|10:15:18.947] Execution ForkValidator.ValidatePayload  foundCanonical=true currentHash=0x48cb7b8297e37d644f5de184cb589d0a185116b6cf8c7553d1dd496e53d1aaa1 unwindPoint=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
WARN[09-19|10:15:18.990] [5/7 Execution] Execution failed         block=18168682 hash=0xd66b87c1011f1bc27de3a5cb9673deed1b727b76f3e08e1568f7328c00101553 err="could not apply tx 16 from block 18168682 [0x87b14456d812e2da617d19924a2d03ca047c1c7070a270368612707e58432795]: insufficient funds for gas * price + value: address 0xc87c50fAE9c6cdED6DB46eD0b6aa7c579a33A331 have 0 want 261377840783750000"
WARN[09-19|10:15:18.991] Could not validate block                 err="[5/7 Execution] could not apply tx 16 from block 18168682 [0x87b14456d812e2da617d19924a2d03ca047c1c7070a270368612707e58432795]: insufficient funds for gas * price + value: address 0xc87c50fAE9c6cdED6DB46eD0b6aa7c579a33A331 have 0 want 261377840783750000"
18168681
INFO[09-19|10:15:35.011] [txpool] stat                            pending=2929 baseFee=30000 queued=21471 alloc=6.1GB sys=9.9GB
INFO[09-19|10:15:51.826] P2P                                      app=caplin peers=35
INFO[09-19|10:16:33.145] [p2p] GoodPeers                          eth68=13 eth67=30
INFO[09-19|10:16:35.035] [txpool] stat                            pending=3323 baseFee=30000 queued=21602 alloc=6.5GB sys=9.9GB
INFO[09-19|10:16:51.825] P2P                                      app=caplin peers=25
INFO[09-19|10:17:35.010] [txpool] stat                            pending=3757 baseFee=30000 queued=21762 alloc=7.0GB sys=9.9GB
INFO[09-19|10:17:51.826] P2P                                      app=caplin peers=30
INFO[09-19|10:18:33.145] [p2p] GoodPeers                          eth68=13 eth67=30
INFO[09-19|10:18:35.029] [txpool] stat                            pending=4262 baseFee=30000 queued=21909 alloc=7.7GB sys=9.9GB
INFO[09-19|10:18:51.826] P2P                                      app=caplin peers=29
INFO[09-19|10:19:35.010] [txpool] stat                            pending=4704 baseFee=30000 queued=22069 alloc=7.9GB sys=9.9GB
INFO[09-19|10:19:51.826] P2P                                      app=caplin peers=36
INFO[09-19|10:20:33.145] [p2p] GoodPeers                          eth68=15 eth67=30
INFO[09-19|10:20:35.029] [txpool] stat                            pending=5108 baseFee=30000 queued=22292 alloc=8.7GB sys=9.9GB
INFO[09-19|10:20:51.826] P2P                                      app=caplin peers=30
INFO[09-19|10:21:35.011] [txpool] stat                            pending=5428 baseFee=30000 queued=22610 alloc=4.8GB sys=9.9GB
INFO[09-19|10:21:51.826] P2P                                      app=caplin peers=32
INFO[09-19|10:22:33.145] [p2p] GoodPeers                          eth67=31 eth68=19
INFO[09-19|10:22:35.030] [txpool] stat                            pending=5746 baseFee=30000 queued=22776 alloc=5.6GB sys=9.9GB
INFO[09-19|10:22:51.826] P2P                                      app=caplin peers=32
INFO[09-19|10:23:35.011] [txpool] stat                            pending=6041 baseFee=30000 queued=22951 alloc=6.7GB sys=9.9GB
INFO[09-19|10:23:51.826] P2P                                      app=caplin peers=33
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x194f18f]

goroutine 5011880 [running]:
github.com/ledgerwatch/erigon/turbo/execution/eth1.(*EthereumExecutionModule).purgeBadChain(0xc08a871380?, {0x2d925a0, 0xc001300370}, {0x2dbd100?, 0xc08a871380}, {0xe8, 0xdf, 0x7a, 0xbf, 0x6, ...}, ...)
        github.com/ledgerwatch/erigon/turbo/execution/eth1/ethereum_execution.go:189 +0xef
github.com/ledgerwatch/erigon/turbo/execution/eth1.(*EthereumExecutionModule).ValidateChain(0xc01b456e60, {0x2d925a0, 0xc001300370}, 0xc0821a5800)
        github.com/ledgerwatch/erigon/turbo/execution/eth1/ethereum_execution.go:164 +0x7eb
github.com/ledgerwatch/erigon-lib/direct.(*ExecutionClientDirect).ValidateChain(0x0?, {0x2d925a0?, 0xc001300370?}, 0x1?, {0x1?, 0x0?, 0x1000000010000?})
        github.com/ledgerwatch/erigon-lib@v0.0.0-20230904034409-568d783b0d85/direct/execution_client.go:59 +0x2e
github.com/ledgerwatch/erigon/turbo/execution/eth1/eth1_chain_reader%2ego.ChainReaderWriterEth1.ValidateChain({{0x2d925a0, 0xc001300370}, 0xc00025e0f0, {0x2da98f0, 0xc0c0e4aba0}, 0x3e8}, {0x5d, 0x72, 0xd8, 0x21, ...}, ...)
        github.com/ledgerwatch/erigon/turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go:288 +0x1f0
github.com/ledgerwatch/erigon/cl/phase1/execution_client.(*ExecutionClientDirect).NewPayload(0xc08b2989c0, 0xc17eaf8240, 0xcc7910296e54430f?)
        github.com/ledgerwatch/erigon/cl/phase1/execution_client/execution_client_direct.go:46 +0x334
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).OnBlock(0xc033fa6380, 0xc154446230, 0x1, 0x1?)
        github.com/ledgerwatch/erigon/cl/phase1/forkchoice/on_block.go:55 +0x2eb
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func1(0xc17f604048, 0xc4?, 0x7d?)
        github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:164 +0x65
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func10({0x2d925a0, 0xc17925e370}, {0x2da4870, 0xc179208680}, 0xc030f212c0, {0x21, 0x38219, 0x3821a, 0x704352, 0x704351}) 
        github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:351 +0x87a
github.com/ledgerwatch/erigon/cl/clstages.(*StageGraph[...]).StartWithStage.func1()
        github.com/ledgerwatch/erigon/cl/clstages/clstages.go:39 +0xe4
created by github.com/ledgerwatch/erigon/cl/clstages.(*StageGraph[...]).StartWithStage
        github.com/ledgerwatch/erigon/cl/clstages/clstages.go:33 +0x3e5
```

**Comment by Giulio2002** [comment]
Fixed
