### ISSUE TITLE
Interrupt (ctrl+c) or soft kill process never exits.

### ISSUE THREAD

**Issue by mbwmbw1337** [ledgerwatch/erigon#8237]
I will sit at this point for hours and never go anywhere else. End up having to ctrl+c panic 9 more times to exit. Any suggestions on how to properly stop the process?

**Version**
```
/home/erigon/erigon/build/bin/erigon -v
erigon version 2.49.0-dev-8983128d
```

**Command**
#bin/bash
```
/home/erigon/erigon/build/bin/erigon \
--chain=mainnet \
--torrent.upload.rate="1024mb" \
--torrent.download.rate="1024mb" \
--datadir="$(eval echo ~$USER)/erigon-eth" \
--internalcl \
--chain=mainnet \
--port=30501 \
--http.port=9201 \
--authrpc.port=9101 \
--authrpc.addr=0.0.0.0 \
--authrpc.vhosts=* \
--torrent.port=42501 \
--private.api.addr=127.0.0.1:9090 \
--nat="extip:$(curl -s ifconfig.me)" \
--http \
--http.api=eth,erigon,web3,net,debug,trace,txpool \
--ws \
--ws.compression
```

```
INFO[09-19|11:59:57.652] [4/12 Execution] Executed blocks         number=13308485 blk/s=30.0 tx/s=5709.5 Mgas/s=465.1 gasState=0.16 batch=165.1MB alloc=11.4GB sys=19.5GB
^CINFO[09-19|12:00:01.215] Got interrupt, shutting down...
INFO[09-19|12:00:01.216] Exiting...
INFO[09-19|12:00:01.216] RPC server shutting down
INFO[09-19|12:00:01.216] [Caplin] exiting clstages loop           app=caplin
INFO[09-19|12:00:01.217] HTTP endpoint closed                     url=127.0.0.1:9201
INFO[09-19|12:00:01.216] Exiting Engine...
WARN[09-19|12:00:01.216] [Beacon Gossip] Fatal error receiving gossip err=EOF
INFO[09-19|12:00:01.217] RPC server shutting down
INFO[09-19|12:00:01.218] RPC server shutting down
INFO[09-19|12:00:01.218] Engine HTTP endpoint close               url=[::]:9101
EROR[09-19|12:00:01.243] Could not start execution service        err="[4/12 Execution] batch commit: loadIntoTable IncarnationMap: stopped"
```

**Comment by mbwmbw1337** [comment]
It's a massive stack trace; I will post as much as I can. Probably 1000+ goroutines.

**Comment by mbwmbw1337** [comment]
Here is part of a stack trace:

```
        github.com/libp2p/go-mplex@v0.7.0/stream.go:117 +0x65
github.com/libp2p/go-libp2p/p2p/muxer/mplex.(*stream).Read(0x4842f9?, {0xc050bf3300?, 0x0?, 0xc020274be8?})
        github.com/libp2p/go-libp2p@v0.28.2/p2p/muxer/mplex/stream.go:17 +0x1e
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Stream).Read(0xc043b8ad80, {0xc050bf3300?, 0x3?, 0xc020274c58?})
        github.com/libp2p/go-libp2p@v0.28.2/p2p/net/swarm/swarm_stream.go:55 +0x33
io.ReadAtLeast({0x7a6cfcd8e770, 0xc043b8ad80}, {0xc050bf3300, 0x1, 0x1}, 0x1)
        io/io.go:332 +0x9a
io.ReadFull(...)
        io/io.go:351
github.com/libp2p/go-msgio.(*simpleByteReader).ReadByte(0xc050bf32f0)
        github.com/libp2p/go-msgio@v0.3.0/varint.go:185 +0x37
github.com/multiformats/go-varint.ReadUvarint({0x2d89ee0, 0xc050bf32f0})
        github.com/multiformats/go-varint@v0.0.7/varint.go:80 +0x5a
github.com/libp2p/go-msgio.(*varintReader).nextMsgLen(0xc050bf6b00)
        github.com/libp2p/go-msgio@v0.3.0/varint.go:119 +0x30
github.com/libp2p/go-msgio.(*varintReader).ReadMsg(0xc050bf6b00)
        github.com/libp2p/go-msgio@v0.3.0/varint.go:149 +0xbc
github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleNewStream(0xc0012e5200, {0x2db7d10, 0xc043b8ad80})
        github.com/libp2p/go-libp2p-pubsub@v0.9.3/comm.go:66 +0x3eb
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1({0xc08e2ad0e0?, 0xaae3a0?}, {0x7a6cfcd8e740?, 0xc043b8ad80})
        github.com/libp2p/go-libp2p@v0.28.2/p2p/host/basic/basic_host.go:598 +0x45
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
        github.com/libp2p/go-libp2p@v0.28.2/p2p/host/basic/basic_host.go:440 +0x74f

goroutine 4666711 [select, 5 minutes]:
github.com/libp2p/go-mplex.(*Multiplex).Accept(...)
        github.com/libp2p/go-mplex@v0.7.0/multiplex.go:180
github.com/libp2p/go-libp2p/p2p/muxer/mplex.(*conn).AcceptStream(0xc07b4c0460)
        github.com/libp2p/go-libp2p@v0.28.2/p2p/muxer/mplex/conn.go:39 +0x6c
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Conn).start.func1()
        github.com/libp2p/go-libp2p@v0.28.2/p2p/net/swarm/swarm_conn.go:114 +0xae
created by github.com/libp2p/go-libp2p/p2p/net/swarm.(*Conn).start
        github.com/libp2p/go-libp2p@v0.28.2/p2p/net/swarm/swarm_conn.go:109 +0x56

goroutine 4732597 [chan send, 3 minutes]:
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func10.1()
        github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:345 +0x93
created by github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func10
        github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:339 +0x367

goroutine 5129642 [sleep]:
time.Sleep(0x1e2c715d4)
        runtime/time.go:195 +0x135
github.com/anacrolix/torrent.(*Client).dialAndCompleteHandshake(0xc0906f1900, {{{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...})
        github.com/anacrolix/torrent@v1.52.6-0.20230914125831-4fb12d06b31b/client.go:750 +0x79
github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc0906f1900, {{{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...}, ...)
        github.com/anacrolix/torrent@v1.52.6-0.20230914125831-4fb12d06b31b/client.go:863 +0x78
created by github.com/anacrolix/torrent.initiateConn
        github.com/anacrolix/torrent@v1.52.6-0.20230914125831-4fb12d06b31b/torrent.go:2433 +0x295

goroutine 4753740 [select]:
github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleSendingMessages(0x1d3dee0?, {0x2d9ffd8, 0xc000058058}, {0x2db7c80?, 0xc1518dc260}, 0xc09ffa70e0)
        github.com/libp2p/go-libp2p-pubsub@v0.9.3/comm.go:175 +0x16b
created by github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleNewPeer
        github.com/libp2p/go-libp2p-pubsub@v0.9.3/comm.go:127 +0x32a

goroutine 5124069 [sleep]:
time.Sleep(0x1e2c7ad24)
        runtime/time.go:195 +0x135
github.com/anacrolix/torrent.(*Client).dialAndCompleteHandshake(0xc0906f1900, {{{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...})
        github.com/anacrolix/torrent@v1.52.6-0.20230914125831-4fb12d06b31b/client.go:750 +0x79
github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc0906f1900, {{{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...}, ...)
        github.com/anacrolix/torrent@v1.52.6-0.20230914125831-4fb12d06b31b/client.go:863 +0x78
created by github.com/anacrolix/torrent.initiateConn
        github.com/anacrolix/torrent@v1.52.6-0.20230914125831-4fb12d06b31b/torrent.go:2433 +0x295

goroutine 4666832 [chan send, 5 minutes]:
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func10.1()
        github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:345 +0x93
created by github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func10
        github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:339 +0x367
```

**Comment by AskAlexSharov** [comment]
> It's a massive stack trace; I will post as much as I can. Probably 1000+ goroutines.

In massive traces - important are first 100 lines usually. Also you can put it to .txt file - github allows such files. Anyway - it’s useful.
