### ISSUE TITLE
invalid memory address or nil pointer dereference on polygon mumbai

### ISSUE THREAD

**Issue by mikolajsobolewski** [ledgerwatch/erigon#8319]
#### System information
Erigon version: 2.50.0-b8744d91
OS & Version: Windows/Linux/OSX Ubuntu 22
Commit hash: b8744d91c6ff5e090f59f4ae1ae4e8f1d7fbde8d
Erigon Command (with flags/config):
```
--chain=mumbai --bor.heimdall=http://heimdallr-mumbai:1317 --bor.milestone=true --datadir=/data --http=true --http.addr=0.0.0.0 --http.compression=true --http.vhosts=*
```
```
[INFO] [09-28|15:10:47.808] Got new milestone from heimdall          start=40613492 end=40613698 hash=0x7124e8abf9bc0895900156cc7ecda1d25e2abf6b8a0a48ca6d3ca7086a98b460
[WARN] [09-28|15:10:47.809] unable to start the whitelist milestone service - first run err="missing blocks"
[INFO] [09-28|15:10:47.809] Got new checkpoint from heimdall         start=40610563 end=40611074 rootHash=0x6b121b8f359e58677310524a99db6e3e2a6ffc2a58343bcc8c436276d7e37089
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16e4986]

goroutine 325 [running]:
github.com/ledgerwatch/erigon/eth/borfinality.borVerify({0x2f36d10?, 0xc000e4a4b0?}, 0xc0003703f0, 0x26bab03, 0x26bad02, {0xc003124372, 0x40}, 0x1)
	github.com/ledgerwatch/erigon/eth/borfinality/bor_checkpoint_verifier.go:78 +0x1a6
github.com/ledgerwatch/erigon/eth/borfinality.fetchWhitelistCheckpoint({0x2f36d10, 0xc000e4a4b0}, {0x2f48e48?, 0xc001b5f620?}, 0xc0037bfe48, 0x533fca?)
	github.com/ledgerwatch/erigon/eth/borfinality/whitelist_helpers.go:45 +0x4fc
github.com/ledgerwatch/erigon/eth/borfinality.handleWhitelistCheckpoint({0x2f36d10?, 0xc000e4a4b0?}, {0x2f48e48?, 0xc001b5f620?}, 0x0?)
	github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:152 +0x75
github.com/ledgerwatch/erigon/eth/borfinality.retryHeimdallHandler(0x2c1e3e0, 0xc0003703f0, 0x0?, 0x0?, {0x2805656, 0x14})
	github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:118 +0xdb
github.com/ledgerwatch/erigon/eth/borfinality.RetryHeimdallHandler(...)
	github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:100
github.com/ledgerwatch/erigon/eth/borfinality.startCheckpointWhitelistService(0xc002fb1550?)
	github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:65 +0x45
created by github.com/ledgerwatch/erigon/eth/borfinality.Whitelist
	github.com/ledgerwatch/erigon/eth/borfinality/whitelist.go:46 +0x225
```

**Comment by mikolajsobolewski** [comment]
Delete <datadir>/txpool resolved this issue
