### ISSUE TITLE
Panic at launch due to permissions issue

### ISSUE THREAD

**Issue by adamgall** [ledgerwatch/erigon#8396]
#### System information

Erigon version: `./erigon --version`
2.51.0

OS & Version: Windows/Linux/OSX
Ubuntu Server 22.04.3

Commit hash:
a0160beee4032491501d89c5347bb1c4710ee6cc

Erigon Command (with flags/config):
```
[Unit]
Description=Erigon Execution Client
Wants=network-online.target
After=network-online.target

[Service]
User=erigon
Group=erigon

Type=simple
Restart=always

ExecStart=/usr/local/bin/erigon \
        --datadir=/var/lib/erigon \
        --port=30403 \
        --p2p.allowed-ports=30403,30404 \
        --authrpc.jwtsecret=/var/lib/ethereum-shared/jwt-backup.hex \
        --authrpc.port=8552 \
        --http.addr=10.0.0.110 \
        --http.port=8546 \
        --http.vhosts=not.telling.you.com \
        --http.api=eth,erigon,engine,net,ots \
        --http.corsdomain=* \
        --rpc.returndata.limit=1000000 \
        --torrent.download.rate=64mb \
        --maxpeers=20 \

[Install]
WantedBy=multi-user.target
```

Concensus Layer:
Lighthouse v4.5.0-441fc16

Concensus Layer Command (with flags/config):
```
[Unit]
Description=Lighthouse Beacon Node Backup
Wants=network-online.target
After=network-online.target

[Service]
User=lighthouse-beacon
Group=lighthouse-beacon

Type=simple
Restart=always

ExecStart=/usr/local/bin/lighthouse bn \
        --datadir=/var/lib/lighthouse-beacon-backup \
        --execution-endpoint=http://127.0.0.1:8552 \
        --execution-jwt=/var/lib/ethereum-shared/jwt-backup.hex \
        --builder=http://127.0.0.1:18550 \
        --port=9100 \
        --http=true \
        --http-address=10.0.0.110 \
        --http-port=5053 \
        --http-allow-origin=https://not.telling.you.com \
        --reconstruct-historic-states=true \
        --genesis-backfill=true \
        --disable-backfill-rate-limiting=true \

[Install]
WantedBy=multi-user.target
```

Chain/Network: 
mainnet

#### Expected behaviour
erigon starts normally.

#### Actual behaviour
erigon crashes immediately with a panic.

#### Steps to reproduce the behaviour
Start erigon from a systemd service file using a system user that doesn't have a home directory.
I'm speculating that this is part of the issue, due to the panic error referencing `/home/erigon` which doesn't exist.

#### Backtrace

````
Oct 07 00:19:49 nuc systemd[1]: Started Erigon Execution Client.
Oct 07 00:19:49 nuc erigon[578745]: panic: mkdir /home/erigon: permission denied
Oct 07 00:19:49 nuc erigon[578745]: goroutine 1 [running]:
Oct 07 00:19:49 nuc erigon[578745]: github.com/ledgerwatch/erigon-lib/common/dir.MustExist(...)
Oct 07 00:19:49 nuc erigon[578745]:         github.com/ledgerwatch/erigon-lib@v1.0.0/common/dir/rw_dir.go:28
Oct 07 00:19:49 nuc erigon[578745]: github.com/ledgerwatch/erigon-lib/common/datadir.New({0xc00079a4e0, 0x20})
Oct 07 00:19:49 nuc erigon[578745]:         github.com/ledgerwatch/erigon-lib@v1.0.0/common/datadir/dirs.go:74 +0x86e
Oct 07 00:19:49 nuc erigon[578745]: github.com/ledgerwatch/erigon/node/nodecfg.init()
Oct 07 00:19:49 nuc erigon[578745]:         github.com/ledgerwatch/erigon/node/nodecfg/defaults.go:43 +0x33
Oct 07 00:19:49 nuc systemd[1]: erigon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 07 00:19:49 nuc systemd[1]: erigon.service: Failed with result 'exit-code'.
````

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/8398
