### ISSUE TITLE
Graceful shutdown bug. "WaitGroup is reused before previous Wait has returned"

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#8678]
```
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 3664371 [running]:
sync.(*WaitGroup).Wait(0x3?)
        sync/waitgroup.go:118 +0x7f
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).Close(0xc00172ec00?)
        github.com/ledgerwatch/erigon-lib@v1.0.0/kv/mdbx/kv_mdbx.go:492 +0x45
github.com/ledgerwatch/erigon/p2p/enode.(*DB).Close(0xc002a85320)
        github.com/ledgerwatch/erigon/p2p/enode/nodedb.go:615 +0x65
github.com/ledgerwatch/erigon/p2p.(*Server).Stop(0xc001730300)
        github.com/ledgerwatch/erigon/p2p/server.go:451 +0xed
github.com/ledgerwatch/erigon/p2p/sentry.(*GrpcServer).Close(...)
        github.com/ledgerwatch/erigon/p2p/sentry/sentry_grpc_server.go:1209
github.com/ledgerwatch/erigon/eth.(*Ethereum).Stop(0xc000973340)
        github.com/ledgerwatch/erigon/eth/backend.go:1356 +0x237
github.com/ledgerwatch/erigon/node.(*Node).stopServices(0xc000076278?, {0xc0017ec890, 0x1, 0xc002f2f770?})
        github.com/ledgerwatch/erigon/node/node.go:216 +0xb2
github.com/ledgerwatch/erigon/node.(*Node).Close(0xc000d99b20)
        github.com/ledgerwatch/erigon/node/node.go:159 +0x18b
created by github.com/ledgerwatch/erigon/turbo/debug.ListenSignals
        github.com/ledgerwatch/erigon/turbo/debug/signal.go:29 +0x273
```

**Comment by battlmonstr** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/9240
