### ISSUE TITLE
Erigon node crashing after cancelling request on RPC

### ISSUE THREAD

**Issue by AymericNoel** [ledgerwatch/erigon#8765]
#### System information

Erigon version: `2.53.4`

OS & Version: Linux

Erigon Command (with flags/config): Running Erigon with config file :

````
# Enable http rpc requests
http = true
"http.addr" = "0.0.0.0"
"http.api" = ["eth","net","engine","erigon","web3","ots","txpool"]
"http.vhosts" = "*"
"http.corsdomain" = "*"

# Enable metrics at port 6060 and exposed
metrics = true
"metrics.addr" = "0.0.0.0"

# Increase txpool size
"txpool.globalslots" = 30000
"txpool.globalbasefeeslots" = 90000
"txpool.accountqueue" = 256
"txpool.globalqueue" = 90000

# Otterscan namespace configuration
"ots.search.max.pagesize" = 5000
````

Consensus Layer: Embedded erigon consensus client 

Chain/Network: Ethereum mainnet

#### Expected behaviour

When requesting Otterscan rpc endpoint: `ots_searchTransactionsAfter` or even  `ots_searchTransactionsBefore` and cancelling it after, the request should be aborted normally.

#### Actual behaviour

Actually when pressing `CTRL-C` after hitting a request, Node crashes and restarts immediately after.

#### Steps to reproduce the behaviour

1. Activate `ots` namespace
2. Run a request in order to fetch transactions for a specific address: `curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0", "id": 1, "method":"ots_searchTransactionsAfter","params":["0x7e794eD35788b698AE60cefC98eE48015C4876dA", 16308945, 5000]}' http://localhost:8545`
3. Press `CTRL-C` in order to cancel that request

#### Backtrace

````
2023-11-16 14:04:14.232	
[INFO] [11-16|14:04:14.232] Starting private RPC server              on=127.0.0.1:9090
2023-11-16 14:04:05.143	
18429999
2023-11-16 14:04:05.140	
[INFO] [11-16|14:04:05.140] Disk storage enabled for ethash DAGs     dir=/opt/node/ethereum/ethash-dags count=2
2023-11-16 14:04:05.140	
[INFO] [11-16|14:04:05.140] Initialising Ethereum protocol           network=1
2023-11-16 14:03:34.059	
[INFO] [11-16|14:03:34.059] Initialised chain configuration          config="{ChainID: 1, Homestead: 1150000, DAO: 1920000, Tangerine Whistle: 2463000, Spurious Dragon: 2675000, Byzantium: 4370000, Constantinople: 7280000, Petersburg: 7280000, Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Gray Glacier: 15050000, Terminal Total Difficulty: 58750000000000000000000, Merge Netsplit: <nil>, Shanghai: 1681338455, Cancun: <nil>, Prague: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
2023-11-16 14:03:34.050	
[INFO] [11-16|14:03:34.050] [db] chaindata                           sizeLimit=3TB pageSize=4096
2023-11-16 14:03:34.045	
[INFO] [11-16|14:03:34.044] Opening Database                         label=chaindata path=/opt/node/ethereum/chaindata
2023-11-16 14:03:33.893	
[INFO] [11-16|14:03:33.893] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=16mb upload.rate=4mb
2023-11-16 14:03:33.807	
[INFO] [11-16|14:03:33.807] Set global gas cap                       cap=50000000
2023-11-16 14:03:31.700	
[INFO] [11-16|14:03:31.699] torrent verbosity                        level=WRN
2023-11-16 14:03:31.698	
[INFO] [11-16|14:03:31.698] starting HTTP APIs                       APIs=eth,net,engine,erigon,web3,ots,txpool
2023-11-16 14:03:31.698	
[INFO] [11-16|14:03:31.698] Maximum peer count                       ETH=100 total=100
2023-11-16 14:03:31.691	
[INFO] [11-16|14:03:31.689] Starting Erigon on Ethereum mainnet...
2023-11-16 14:03:31.691	
[INFO] [11-16|14:03:31.689] Build info                               git_branch= git_tag= git_commit=
2023-11-16 14:03:31.691	
[INFO] [11-16|14:03:31.689] Enabling metrics export to prometheus    path=http://0.0.0.0:6060/debug/metrics/prometheus
2023-11-16 14:03:31.689	
[INFO] [11-16|14:03:31.687] logging to file system                   log dir=/opt/node/ethereum/logs file prefix=erigon log level=info json=false
2023-11-16 14:03:11.811	
panic: runtime error: index out of range [42] with length 0



2023-11-16 14:03:11.811	
created by github.com/ledgerwatch/erigon/turbo/jsonrpc.(*OtterscanAPIImpl).traceBlocks
2023-11-16 14:03:11.811	
	/go/src/github.com/ledgerwatch/erigon/turbo/jsonrpc/otterscan_search_trace.go:33 +0x206
2023-11-16 14:03:11.811	
github.com/ledgerwatch/erigon/turbo/jsonrpc.(*OtterscanAPIImpl).searchTraceBlock(0xc0997eed00, {0x31823e0, 0xc0d5ffc000}, 0xc1763c956c?, {0x7e, 0x79, 0x4e, 0xd3, 0x57, 0x88, ...}, ...)
2023-11-16 14:03:11.811	
	/go/src/github.com/ledgerwatch/erigon/turbo/jsonrpc/otterscan_search_trace.go:99 +0x12f3
2023-11-16 14:03:11.811	
github.com/ledgerwatch/erigon/turbo/jsonrpc.(*OtterscanAPIImpl).traceBlock(0xc0997eed00, {0x31a22d8?, 0xc08e190780}, {0x31823e0?, 0xc0d5ffc000}, 0x4896db?, {0x7e, 0x79, 0x4e, 0xd3, ...}, ...)
2023-11-16 14:03:11.811	
goroutine 700995314 [running]:
2023-11-16 14:03:11.811	
[EROR] [11-16|14:03:11.799] Search trace error                       err="context canceled"
2023-11-16 14:03:11.811	
	/go/src/github.com/ledgerwatch/erigon/turbo/jsonrpc/otterscan_api.go:461 +0xa7
2023-11-16 14:03:11.810	
[EROR] [11-16|14:03:11.797] Search trace error                       err="context canceled"
2023-11-16 14:03:11.810	
[EROR] [11-16|14:03:11.799] Search trace error                       err="context canceled"
2023-11-16 14:03:11.809	
[EROR] [11-16|14:03:11.796] Search trace error                       err="context canceled"
2023-11-16 14:03:11.809	
[EROR] [11-16|14:03:11.797] Search trace error                       err="context canceled"
2023-11-16 14:03:11.808	
[EROR] [11-16|14:03:11.797] Search trace error                       err="context canceled"
2023-11-16 14:03:11.807	
[EROR] [11-16|14:03:11.797] Search trace error                       err="context canceled"
2023-11-16 14:03:11.807	
[EROR] [11-16|14:03:11.798] Search trace error                       err="context canceled"
2023-11-16 14:03:11.806	
[EROR] [11-16|14:03:11.797] Search trace error                       err="context canceled"
````

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/erigon/pull/8790

**Comment by AymericNoel** [comment]
Thanks @AskAlexSharov. I'll test it with the next release !

**Comment by wmitsuda** [comment]
thanks for fixing it!

**Comment by yperbasis** [comment]
Please re-open this issue if it still happens with [v2.59.2](https://github.com/ledgerwatch/erigon/releases/tag/v2.59.2) or later.
