### ISSUE TITLE
panic in enode DB Close on shutdown

### ISSUE THREAD

**Issue by battlmonstr** [ledgerwatch/erigon#9237]
erigon stable v2.56.2
chain: mumbai

```
[INFO] [01-15|08:05:20.949] RPC server shutting down 
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 508149 [running]:
sync.(*WaitGroup).Wait(0x3?)
        sync/waitgroup.go:118 +0x7f
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).Close(0xc0076199e0?)
        github.com/ledgerwatch/erigon-lib@v1.0.0/kv/mdbx/kv_mdbx.go:497 +0x45
github.com/ledgerwatch/erigon/p2p/enode.(*DB).Close(0xc002708030)
        github.com/ledgerwatch/erigon/p2p/enode/nodedb.go:615 +0x65
github.com/ledgerwatch/erigon/p2p.(*Server).Stop(0xc000004c00)
        github.com/ledgerwatch/erigon/p2p/server.go:451 +0xed
github.com/ledgerwatch/erigon/p2p/sentry.(*GrpcServer).Close(...)
        github.com/ledgerwatch/erigon/p2p/sentry/sentry_grpc_server.go:1209
github.com/ledgerwatch/erigon/eth.(*Ethereum).Stop(0xc000a9d080)
        github.com/ledgerwatch/erigon/eth/backend.go:1395 +0x237
github.com/ledgerwatch/erigon/node.(*Node).stopServices(0x49872e?, {0xc00450ce70, 0x1, 0x465fa0?})
        github.com/ledgerwatch/erigon/node/node.go:216 +0xb2
github.com/ledgerwatch/erigon/node.(*Node).Close(0xc00216cf50)
        github.com/ledgerwatch/erigon/node/node.go:159 +0x18b
created by github.com/ledgerwatch/erigon/turbo/debug.ListenSignals
        github.com/ledgerwatch/erigon/turbo/debug/signal.go:29 +0x273
```

reported in Discord #general by laibe

**Comment by battlmonstr** [comment]
duplicate of https://github.com/ledgerwatch/erigon/issues/8678

fixed by https://github.com/ledgerwatch/erigon/pull/9240
