### ISSUE TITLE
[Sepolia] Erigon v2.57.0 broken after upgrading from v2.55.1 version

### ISSUE THREAD

**Issue by luarx** [ledgerwatch/erigon#9288]
#### System information

Erigon version: v2.57.0

OS & Version: Docker

Consensus Layer: v4.4.1

Chain/Network: Sepolia

#### Actual behaviour
Node breaks when it starts
```
[INFO] [01-23|13:58:55.318] [EngineBlockDownloader] Downloading PoS headers... hash=0x1a8621ae1236acde99afae7c351d39aa4fe1dd1f0718110684fa46564f9308a2 requestId=0
unexpected fault address 0x77b17650d020
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x77b17650d020 pc=0x49bc0e]

goroutine 21677 [running]:
runtime.throw({0x2a2cc9b?, 0x0?})
        runtime/panic.go:1047 +0x5d fp=0xc0097a4c28 sp=0xc0097a4bf8 pc=0x46309d
runtime.sigpanic()
        runtime/signal_unix.go:838 +0x125 fp=0xc0097a4c88 sp=0xc0097a4c28 pc=0x47a3c5
runtime.memmove()
        runtime/memmove_amd64.s:372 +0x42e fp=0xc0097a4c90 sp=0xc0097a4c88 pc=0x49bc0e
github.com/anacrolix/torrent/mmap_span.copyBytes(...)
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/mmap_span/mmap_span.go:79
github.com/anacrolix/torrent/mmap_span.(*MMapSpan).locateCopy.func1(0x482dde?, {0x425b5c0?, 0x49b36e0?})
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/mmap_span/mmap_span.go:86 +0xdf fp=0xc0097a4d20 sp=0xc0097a4c90 pc=0xc248df
github.com/anacrolix/torrent/segments.Index.Locate.func2(0x0?, {0xc0097a4d80?, 0x4a33e8?})
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/segments/index.go:43 +0x24 fp=0xc0097a4d48 sp=0xc0097a4d20 pc=0xc23a24
github.com/anacrolix/torrent/segments.Scan(0xc0097a4db0, {0xc0097a4df0?, 0xc8b365?}, 0xc0097a4dd8)
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/segments/segments.go:43 +0xdc fp=0xc0097a4d90 sp=0xc0097a4d48 pc=0xc23c3c
github.com/anacrolix/torrent/segments.Index.Locate({{0xc0008fdef0, 0x1, 0x1}}, {0xcc00000, 0x40000}, 0xc0097a4e50)
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/segments/index.go:42 +0x190 fp=0xc0097a4e18 sp=0xc0097a4d90 pc=0xc23990
github.com/anacrolix/torrent/mmap_span.(*MMapSpan).locateCopy(0xc00b33dda0?, 0xc0097a4f80?, {0xc00ab32000, 0x40000, 0x40000}, 0xc27194?)
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/mmap_span/mmap_span.go:83 +0x94 fp=0xc0097a4e88 sp=0xc0097a4e18 pc=0xc24794
github.com/anacrolix/torrent/mmap_span.(*MMapSpan).WriteAt(0x100c001282980?, {0xc00ab32000?, 0x40000, 0x10?}, 0xc009767400?)
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/mmap_span/mmap_span.go:102 +0xe8 fp=0xc0097a4f08 sp=0xc0097a4e88 pc=0xc24b08
github.com/anacrolix/missinggo/v2.(*SectionWriter).WriteAt(0x6?, {0xc00ab32000?, 0xc008b6aac0?, 0x251d9e0?}, 0xc008b6aac8?)
        github.com/anacrolix/missinggo/v2@v2.7.2-0.20230527121029-a582b4f397b9/section_writer.go:22 +0x56 fp=0xc0097a4f40 sp=0xc0097a4f08 pc=0xb98916
github.com/anacrolix/torrent/storage.(*mmapStoragePiece).WriteAt(0x251d9e0?, {0xc00ab32000?, 0xc0097a4fb0?, 0xc001282980?}, 0x66?)
        <autogenerated>:1 +0x30 fp=0xc0097a4f78 sp=0xc0097a4f40 pc=0xc2a490
github.com/anacrolix/torrent/storage.Piece.WriteAt({{0x32abc00?, 0xc00b33dda0?}, {0xc001282980?, 0x1010000032862e0?}}, {0xc00ab32000, 0x40000, 0x40000}, 0x0)
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/storage/wrappers.go:68 +0x199 fp=0xc0097a5040 sp=0xc0097a4f78 pc=0xc28af9
github.com/anacrolix/torrent.(*Torrent).writeChunk(0xc001fdb500, 0x66, 0xc0097a5110?, {0xc00ab32000, 0x40000, 0x40000})
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/torrent.go:949 +0xe7 fp=0xc0097a50e8 sp=0xc0097a5040 pc=0xe4eae7
github.com/anacrolix/torrent.(*Peer).receiveChunk.func5(0xc0013ca500, 0xc00b36a5b8?, 0xc007864b60)
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/peer.go:695 +0xee fp=0xc0097a5178 sp=0xc0097a50e8 pc=0xe303ae
github.com/anacrolix/torrent.(*Peer).receiveChunk(0xc007f1d500, 0xc007864b60)
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/peer.go:696 +0x7c5 fp=0xc0097a54b0 sp=0xc0097a5178 pc=0xe2fd45
github.com/anacrolix/torrent.(*PeerConn).mainReadLoop(0xc007f1d500)
        github.com/anacrolix/torrent@v1.52.6-0.20231201115409-7ea994b6bbd8/peerconn.go:790 +0x9da fp=0xc0097a5980 sp=0xc0097a54b0 pc=0xe35f1a
github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc0013ca500, 0xc007f1d500, 0xc001fdb500)
```

#### Steps to reproduce the behaviour
Upgrade from Erigon v2.55.1 version to v2.57.0
I tried to downgrade to v2.55.1 again but same issue around

**Comment by luarx** [comment]
This is was because it increased the used disk spasce almost 100gb all of a sudden
![image](https://github.com/ledgerwatch/erigon/assets/22997139/861466c5-d81b-418b-856a-fa98dc805513)

**Comment by luarx** [comment]
Because of my last comment, I will open a new issue as it is more related with a disk usage spike
