### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by peonante** [ledgerwatch/erigon#9443]
**erigon version 2.57.3-705814b1**

```
 ./build/bin/erigon --chain=goerli --http --http.api=eth,web3,net,txpool --ws --http.compression --ws.compression --datadir="F:\Goerli2 " --metrics --maxpeers=1 --torrent.download.rate=5mb
```
it happens that when I interrupt the command, the next startup generates this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x240 pc=0x7ff72870fbff]

goroutine 1739 [running]:
github.com/ledgerwatch/erigon/consensus/misc.eip1559Calculator.CurrentFees({}, 0xc000869400, {0x18ffb794df8, 0xc029d645a0})
        github.com/ledgerwatch/erigon/consensus/misc/eip1559.go:80 +0xbf
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).fromDB(0xc029a13180, {0x7ff72b2b68f8, 0xc00162d400}, {0x7ff72b2d8590?, 0xc029d64540}, {0x7ff72b2d8590?, 0xc029d645a0?})
        github.com/ledgerwatch/erigon-lib@v1.0.0/txpool/pool.go:2095 +0x873
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).Start.func1({0x7ff72b2d8590, 0xc029d64540})
        github.com/ledgerwatch/erigon-lib@v1.0.0/txpool/pool.go:329 +0xf5
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).View(0x29e8d60800?, {0x7ff72b2b68f8?, 0xc00162d400?}, 0xc029d58780)
        github.com/ledgerwatch/erigon-lib@v1.0.0/kv/mdbx/kv_mdbx.go:749 +0x95
github.com/ledgerwatch/erigon-lib/txpool.(*TxPool).Start(0xc029a13180, {0x7ff72b2b68f8?, 0xc00162d400}, {0x7ff72b2cb580, 0xc02b24a8c0})
        github.com/ledgerwatch/erigon-lib@v1.0.0/txpool/pool.go:319 +0xc4
github.com/ledgerwatch/erigon-lib/txpool.MainLoop({0x7ff72b2b68f8?, 0xc00162d400}, {0x7ff72b2cb580, 0xc02b24a8c0}, 0xc029a13180, 0xc029f3eae0, 0xc020f7aa00, 0xc01f27be18, 0xc029d88370)
        github.com/ledgerwatch/erigon-lib@v1.0.0/txpool/pool.go:1729 +0x1f9
created by github.com/ledgerwatch/erigon/eth.New in goroutine 1
        github.com/ledgerwatch/erigon/eth/backend.go:718 +0x3e7d
```

how do I solve the problem?

**Comment by AskAlexSharov** [comment]
Upgrade plz

**Comment by peonante** [comment]
> Upgrade plz

upgrade what? I have the latest version of erigon
