### ISSUE TITLE
panic: runtime error: index out of range [3] with length 3

### ISSUE THREAD

**Issue by 0x19dG87** [ledgerwatch/erigon#9498]
#### System information

Erigon version: v2.58.1

OS & Version: Ubuntu 22.04

Erigon Command (with flags/config):
```
--chain=mainnet
      --internalcl
      --caplin.archive
      --beacon.api
      --beacon.api.addr=0.0.0.0
      --beacon.api.port=5555
      --nat=stun
      --http.addr=0.0.0.0
      --http.port=8545
      --http.api=eth,web3,net,debug,trace,txpool
      --http.vhosts=*
      --http.corsdomain=*
      --ws
      --ws.port=8546
      --metrics
      --metrics.addr=0.0.0.0
      --pprof
      --pprof.addr=0.0.0.0
      --pprof.port=6070
      --authrpc.addr=0.0.0.0
      --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwt.hex
      --authrpc.vhosts=*
      --torrent.download.rate=100mb
      --torrent.upload.rate=16mb
      --datadir=/home/erigon/.local/share/erigon
```

Consensus Layer: Caplin (--internalcl)

Chain/Network: 

#### Actual behaviour
Panic
```
[INFO] [02-23|09:32:45.499] head updated                             hash=0xf7530db74bd7e24fff8047f90f3e039fe1c3792e5914aa0927b8b4caedcca86b number=19289418
[INFO] [02-23|09:32:45.499] [snapshots] Prune Blocks                 to=19199000 limit=100
[INFO] [02-23|09:32:55.557] P2P                                      app=caplin peers=48
panic: runtime error: index out of range [3] with length 3

goroutine 104364 [running]:
encoding/binary.bigEndian.Uint32(...)
	encoding/binary/binary.go:157
github.com/ledgerwatch/erigon/cl/persistence/base_encoding.Decode64FromBytes4(...)
	github.com/ledgerwatch/erigon/cl/persistence/base_encoding/primitives.go:18
github.com/ledgerwatch/erigon/cl/persistence/beacon_indicies.ReadBlockSlotByBlockRoot({0x3012370, 0xc04d7c81e0}, {0x47, 0xc5, 0x6b, 0x45, 0x5e, 0x45, 0xc9, 0xa1, ...})
	github.com/ledgerwatch/erigon/cl/persistence/beacon_indicies/indicies.go:43 +0xcc
github.com/ledgerwatch/erigon/cl/phase1/network.(*BackwardBeaconDownloader).RequestMore(0xc0dfedfd80, {0x2fefc80?, 0x511f920})
	github.com/ledgerwatch/erigon/cl/phase1/network/backward_beacon_downloader.go:186 +0x77f
github.com/ledgerwatch/erigon/cl/phase1/stages.SpawnStageHistoryDownload.func3()
	github.com/ledgerwatch/erigon/cl/phase1/stages/stage_history_download.go:198 +0x66
created by github.com/ledgerwatch/erigon/cl/phase1/stages.SpawnStageHistoryDownload in goroutine 104362
	github.com/ledgerwatch/erigon/cl/phase1/stages/stage_history_download.go:196 +0x6d3
```

#### Steps to reproduce the behaviour
Run node

**Comment by 0x19dG87** [comment]
As soon as I remove `--caplin.archive` panic has gone.
