### ISSUE TITLE
Return error message when empty val faced in PlainState 

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#9522]
```
INFO[02-23|15:58:00.320] Progress                                 table=PlainState progress=5.6m/4696.0m key=00000000000000adc04c56bf30ac9d3c0aaf14dc0000000000000001ab7d24d7e69c579ead52bca297c698206de6022b8adec36a071509e5ac3151d2 alloc=22.9MB sys=89.0MB
INFO[02-23|15:58:17.371] Progress                                 table=PlainState progress=5.7m/4696.0m key=00000000000000adc04c56bf30ac9d3c0aaf14dc0000000000000001b132b7d75b3e632dc248abc086024d78d72cf889c193a029219f768e4311aef5 alloc=17.5MB sys=89.0MB
INFO[02-23|15:58:33.920] Progress                                 table=PlainState progress=5.8m/4696.0m key=00000000000000adc04c56bf30ac9d3c0aaf14dc0000000000000001b6ee90ea6995b02f1fa45be9d848b4018ebb86b4737d40acf9fd4b8655c23c13 alloc=26.6MB sys=89.0MB
INFO[02-23|15:58:50.863] Progress                                 table=PlainState progress=5.9m/4696.0m key=00000000000000adc04c56bf30ac9d3c0aaf14dc0000000000000001bca2cee31f47c5679217ca70795a20dfe60f4bb85a2daa9966c04b238ce1206e alloc=26.5MB sys=89.0MB
INFO[02-23|15:59:22.842] Progress                                 table=PlainState progress=6.1m/4696.0m key=00000000000000adc04c56bf30ac9d3c0aaf14dc0000000000000001c81fa3b82f89299f969caf1b9237410c0c4af190044be30670b1160e48fb6a5a alloc=26.7MB sys=89.0MB
panic: runtime error: slice bounds out of range [:32] with capacity 0

goroutine 590953 [running]:
github.com/ledgerwatch/erigon-lib/kv/mdbx.(MdbxCursor).Next(0xc001f8e420)
        github.com/ledgerwatch/erigon-lib@v1.0.0/kv/mdbx/kv_mdbx.go:1272 +0x27e
github.com/ledgerwatch/erigon-lib/kv/mdbx.(cursor2iter).Next(0xc001676be0)
        github.com/ledgerwatch/erigon-lib@v1.0.0/kv/mdbx/kv_mdbx.go:1812 +0xc8
github.com/ledgerwatch/erigon/turbo/backup.WarmupTable.func2.1({0x1fcabb8, 0xc001f8e3c0})
        github.com/ledgerwatch/erigon/turbo/backup/backup.go:195 +0x138
github.com/ledgerwatch/erigon-lib/kv/mdbx.(MdbxKV).View(0x67d0d8074fd0?, {0x1fb9250?, 0xc000425e50?}, 0xc0009f7f40)
        github.com/ledgerwatch/erigon-lib@v1.0.0/kv/mdbx/kv_mdbx.go:675 +0xa6
github.com/ledgerwatch/erigon/turbo/backup.WarmupTable.func2()
        github.com/ledgerwatch/erigon/turbo/backup/backup.go:189 +0x16a
golang.org/x/sync/errgroup.(Group).Go.func1()
        golang.org/x/sync@v0.5.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.5.0/errgroup/errgroup.go:72 +0xa5
root@ip-172-31-34-70:/home/ubuntu/erigon#
```

**Comment by yperbasis** [comment]
Please re-open the issue if it still happens with [v2.59.2](https://github.com/ledgerwatch/erigon/releases/tag/v2.59.2) or later.
