### ISSUE TITLE
Error upgrading from 2.58 to 2.59.0

### ISSUE THREAD

**Issue by raulpuente** [ledgerwatch/erigon#9771]
#### System information

Erigon version: `./erigon --version`: erigon version 2.59.0-0f0a4452

OS & Version: Windows/Linux/OSX: Linux

Commit hash: 0f0a4452

Erigon Command (with flags/config): ./build/bin/integration stage_headers --reset --datadir=/mnt/bigdata/erigon-data --chain=mainnet

Chain/Network: Mainnet

#### Behaviour

I was using the node with version 2.58.0 and moved to 2.59.0. And did it what says in release:
```
rm -rf <datadir>/caplin <datadir>/snapshots <datadir>/downloader
make integration
./build/bin/integration stage_headers --reset --datadir=<datadir>
./build/bin/integration stage_snapshots --reset --datadir=<datadir> 
```
I executed: `./build/bin/integration stage_headers --reset --datadir=/mnt/bigdata/erigon-data --chain=mainnet `

And the output is:

```
INFO[03-20|15:42:42.314] logging to file system                   log dir=/mnt/bigdata/erigon-data/logs file prefix=integration log level=info json=false
INFO[03-20|15:42:42.315] [db] open                                lable=chaindata sizeLimit=12TB pageSize=8192
panic: fail to open mdbx: create table: BalancesDump, mdbx_dbi_open: MDBX_NOTFOUND: No matching key/data pair found

goroutine 1 [running]:
github.com/ledgerwatch/erigon-lib/kv/mdbx.MdbxOpts.MustOpen({{0x1eccd60, 0xc000e15280}, 0xc0009d6910, 0x1ccc990, {0xc0000e3530, 0x22}, 0x0, 0x20000000000, 0x80000000, 0xffffffffffffffff, ...})
	github.com/ledgerwatch/erigon-lib@v1.0.0/kv/mdbx/kv_mdbx.go:461 +0xc8
github.com/ledgerwatch/erigon/cmd/integration/commands.openDB({{0x1eccd60, 0xc000e15280}, 0xc0009d6910, 0x1ccc990, {0xc0000e3530, 0x22}, 0x0, 0x20000000000, 0x80000000, 0xffffffffffffffff, ...}, ...)
	github.com/ledgerwatch/erigon/cmd/integration/commands/root.go:76 +0x78
github.com/ledgerwatch/erigon/cmd/integration/commands.glob..func11(0x2aaeb80, {0x1a1e8a7?, 0x3?, 0x3?})
	github.com/ledgerwatch/erigon/cmd/integration/commands/stages.go:89 +0xf9
github.com/spf13/cobra.(*Command).execute(0x2aaeb80, {0xc000ab9710, 0x3, 0x3})
	github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x2ab2220)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(0x469105?, {0x1ec30f0?, 0xc0009d68c0?})
	github.com/spf13/cobra@v1.8.0/command.go:1032 +0x4a
main.main()
	github.com/ledgerwatch/erigon/cmd/integration/main.go:15 +0xed
```

**Comment by Giulio2002** [comment]
start erigon for like 15 sec and stop it and try again

**Comment by raulpuente** [comment]
Ok, after start and stop, it seems it worked:

```
root@node:/mnt/bigdata/erigon# ./build/bin/integration stage_headers --reset --datadir=/mnt/bigdata/erigon-data --chain=mainnet
INFO[03-20|16:22:54.340] logging to file system                   log dir=/mnt/bigdata/erigon-data/logs file prefix=integration log level=info json=false
INFO[03-20|16:22:54.342] [db] open                                lable=chaindata sizeLimit=12TB pageSize=8192
INFO[03-20|16:22:54.359] [snapshots:all] Blocks Stat              blocks=0k indices=0k alloc=15.6MB sys=41.4MB
INFO[03-20|16:22:54.362] [snapshots:all] Blocks Stat              blocks=0k indices=0k alloc=16.4MB sys=41.4MB
INFO[03-20|16:22:54.478] Disk storage enabled for ethash DAGs     dir=/root/.local/share/erigon-ethash count=2
INFO[03-20|16:23:15.757] TruncateBlocks                           block=19395560
INFO[03-20|16:23:35.756] TruncateBlocks                           block=19405167
INFO[03-20|16:23:55.756] TruncateBlocks                           block=19414721
INFO[03-20|16:24:15.756] TruncateBlocks                           block=19424420
INFO[03-20|16:24:35.756] TruncateBlocks                           block=19435621
INFO[03-20|16:24:55.756] TruncateBlocks                           block=19447249
INFO[03-20|16:25:15.756] TruncateBlocks                           block=19458566
INFO[03-20|16:25:35.756] TruncateBlocks                           block=19469035
INFO[03-20|16:27:00.326] Clear                                    table=NonCanonicalTransaction
INFO[03-20|16:27:00.326] Clear                                    table=BlockTransaction
INFO[03-20|16:27:00.366] Clear                                    table=MaxTxNum
```
```
root@node:/mnt/bigdata/erigon# ./build/bin/integration stage_snapshots --reset --datadir=/mnt/bigdata/erigon-data
INFO[03-20|16:28:05.038] logging to file system                   log dir=/mnt/bigdata/erigon-data/logs file prefix=integration log level=info json=false
INFO[03-20|16:28:05.040] [db] open                                lable=chaindata sizeLimit=12TB pageSize=8192
INFO[03-20|16:28:05.040] Progress                                 snapshots=0
```

And now is downloading snapshots

Thank you
