### ISSUE TITLE
Sudden crash on statechange.processRewardsAndPenaltiesPostAltair

### ISSUE THREAD

**Issue by hjawhar** [ledgerwatch/erigon#9848]
#### System information

Erigon version: erigon version 2.59.2

OS & Version: Linux

Commit hash: 

Erigon Command (with flags/config):

./erigon --datadir="/home/mainnet" --chain=mainnet --port=30303 --http --http.api=eth,debug,net,trace,web3,erigon --http.addr=0.0.0.0 --http.vhosts=* --http.port=8545 --http.corsdomain=* --authrpc.addr=0.0.0.0 --authrpc.vhosts=* --authrpc.port=8551 --private.api.addr=127.0.0.1:9090 --ws --torrent.port=42069 --healthcheck --internalcl

Consensus Layer: internalcl

Consensus Layer Command (with flags/config): NA

Chain/Network: Mainnet (ETH)

#### Expected behaviour
NA

#### Actual behaviour
NA

#### Steps to reproduce the behaviour
Suddenly stopped and crashed

#### Backtrace

````
INFO[04-01|17:20:52.922] RPC Daemon notified of new headers       from=19562427 to=19562428 amount=1 hash=0x4ab6eebb801b8ba5e9ce0a77569320db98341ef0f7a83699bd468f50c120d912 header sending=8.797µs log sending=281ns
INFO[04-01|17:20:52.922] head updated                             hash=0x4ab6eebb801b8ba5e9ce0a77569320db98341ef0f7a83699bd468f50c120d912 number=19562428
INFO[04-01|17:21:04.281] [updateForkchoice] Fork choice update: flushing in-memory state (built by previous newPayload)
INFO[04-01|17:21:04.492] RPC Daemon notified of new headers       from=19562428 to=19562429 amount=1 hash=0x1f6e61be64824a61411657164d301728d6bd04dc5e18af78af289da00fc5d7d9 header sending=8.917µs log sending=280ns
INFO[04-01|17:21:04.492] head updated                             hash=0x1f6e61be64824a61411657164d301728d6bd04dc5e18af78af289da00fc5d7d9 number=19562429
INFO[04-01|17:21:04.909] P2P                                      app=caplin peers=53
INFO[04-01|17:21:17.446] [updateForkchoice] Fork choice update: flushing in-memory state (built by previous newPayload)
INFO[04-01|17:21:17.675] RPC Daemon notified of new headers       from=19562429 to=19562430 amount=1 hash=0xc34372f19f5c2b07a29ada3328e37f0d88d548b700638eceac9e1b4f5687fe2b header sending=10.8µs log sending=291ns
INFO[04-01|17:21:17.675] head updated                             hash=0xc34372f19f5c2b07a29ada3328e37f0d88d548b700638eceac9e1b4f5687fe2b number=19562430
panic: runtime error: integer divide by zero

goroutine 331409849 [running]:
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.processRewardsAndPenaltiesPostAltair({0x316d998, 0xc1345af800}, {0xc318d24000, 0xeeff8, 0x0?}, {0xc210a5f130, 0x3, 0x3})
        /go/src/github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_rewards_and_penalties.go:46 +0x6b7
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.ProcessRewardsAndPenalties({0x316d998?, 0xc1345af800}, {0xc318d24000, 0xeeff8, 0x14502e}, {0xc210a5f130, 0x3, 0x3})
        /go/src/github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_rewards_and_penalties.go:230 +0x106
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.ProcessEpoch({0x316d998, 0xc1345af800})
        /go/src/github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_epoch.go:47 +0x1dc
github.com/ledgerwatch/erigon/cl/transition/impl/eth2.(*impl).ProcessSlots(0xc000661c20?, {0x316d998, 0xc1345af800}, 0x85ba60)
        /go/src/github.com/ledgerwatch/erigon/cl/transition/impl/eth2/operations.go:844 +0x196
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).getCheckpointState(0xc092190000, {0xc1ae57fc5c, 0x28, 0x88})
        /go/src/github.com/ledgerwatch/erigon/cl/phase1/forkchoice/utils.go:128 +0x20d
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).OnAttestation(0xc092190000, 0xc1ae57fc00, 0x1, 0x0)
        /go/src/github.com/ledgerwatch/erigon/cl/phase1/forkchoice/on_attestation.go:48 +0x299
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func8.3.1(0xc0c416a9c0?, 0xc1c09ffb60?, 0xc1778161b0?)
        /go/src/github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:669 +0x65
github.com/ledgerwatch/erigon/cl/cltypes/solid.(*ListSSZ[...]).Range(0x195, 0xc12ffcdfb8?)
        /go/src/github.com/ledgerwatch/erigon/cl/cltypes/solid/list_ssz.go:142 +0x6c
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func8.3()
        /go/src/github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:666 +0x65
created by github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func8 in goroutine 331395176
       /go/src/github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:665 +0x179e
````

**Comment by temuera** [comment]
++++++++++++++++++1

SOS!!!


all archive  node down!   2.59.3

**Comment by Giulio2002** [comment]
try restarting for now, will investigate.

**Comment by Giulio2002** [comment]
Fixed
