### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by temuera** [ledgerwatch/erigon#9884]
2.59.3 with --internalCL .

```
INFO[04-08|16:20:03.056] [mem] memory stats                       Rss=178.2MB Size=0B Pss=178.2MB SharedClean=4B SharedDirty=0B PrivateClean=131.4MB PrivateDirty=46.7MB Referenced=168.3MB Anonymous=46.7MB Swap=14.3KB alloc=11.1GB sys=19.8GB
INFO[04-08|16:20:22.609] [4/12 Execution] Completed on            block=19609721
INFO[04-08|16:20:23.602] RPC Daemon notified of new headers       from=19609719 to=19609721 amount=2 hash=0x3c7062cc5a00fda4d393841f2de5d52e6cac76d2971fbaa233c593f8e7acd60a header sending=23.756µs log sending=451ns
INFO[04-08|16:20:23.602] head updated                             hash=0x3c7062cc5a00fda4d393841f2de5d52e6cac76d2971fbaa233c593f8e7acd60a number=19609721
panic: runtime error: integer divide by zero

goroutine 1469425332 [running]:
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.processRewardsAndPenaltiesPostAltair({0x316d9b8, 0xc0019d3e00}, {0xc3d096c000, 0xef7fb, 0xc0016b7ac0?}, {0xc1c40122d0, 0x3, 0x3})
        /go/src/github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_rewards_and_penalties.go:46 +0x6b7
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.ProcessRewardsAndPenalties({0x316d9b8?, 0xc0019d3e00}, {0xc3d096c000, 0xef7fb, 0x148390}, {0xc1c40122d0, 0x3, 0x3})
        /go/src/github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_rewards_and_penalties.go:230 +0x106
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.ProcessEpoch({0x316d9b8, 0xc0019d3e00})
        /go/src/github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_epoch.go:47 +0x1dc
github.com/ledgerwatch/erigon/cl/transition/impl/eth2.(*impl).ProcessSlots(0xc000bbfc00?, {0x316d9b8, 0xc0019d3e00}, 0x8674a0)
        /go/src/github.com/ledgerwatch/erigon/cl/transition/impl/eth2/operations.go:844 +0x196
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).getCheckpointState(0xc0001ff600, {0xc07b027c5c, 0x28, 0x88})
        /go/src/github.com/ledgerwatch/erigon/cl/phase1/forkchoice/utils.go:128 +0x20d
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).OnAttestation(0xc0001ff600, 0xc07b027c00, 0x1, 0x0)
        /go/src/github.com/ledgerwatch/erigon/cl/phase1/forkchoice/on_attestation.go:48 +0x299
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func8.3.1(0xc0255fc980?, 0xc24ca5a5a0?, 0xc1dc0560f0?)
        /go/src/github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:669 +0x65
github.com/ledgerwatch/erigon/cl/cltypes/solid.(*ListSSZ[...]).Range(0x195, 0xc08737bfb8?)
        /go/src/github.com/ledgerwatch/erigon/cl/cltypes/solid/list_ssz.go:142 +0x6c
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func8.3()
        /go/src/github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:666 +0x65
created by github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func8 in goroutine 1469360454
        /go/src/github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:665 +0x179e
```

**Comment by muratso** [comment]
Same thing happened with me, around the same block. I wonder if one of these blocks had anything to do with it.
However, after restarting my erigon, I didn't see it happening again.
```bash
[INFO] [04-08|08:20:34.297] [4/12 Execution] Completed on            block=19609722
[INFO] [04-08|08:20:35.370] RPC Daemon notified of new headers       from=19609720 to=19609722 amount=2 hash=0xd980753e2eede8a59c1d7649747aa8ca7f73332f1e7624e961dc8babcce836b2 header sending=27.413µs log sending=328ns
[INFO] [04-08|08:20:35.370] head updated                             hash=0xd980753e2eede8a59c1d7649747aa8ca7f73332f1e7624e961dc8babcce836b2 number=19609722
[INFO] [04-08|08:20:55.450] P2P                                      app=caplin peers=62
panic: runtime error: integer divide by zero

goroutine 718954935 [running]:
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.processRewardsAndPenaltiesPostAltair({0x2e43800, 0x4132cb5c80}, {0x438d650000, 0xef7fb, 0x0?}, {0x42b2678d70, 0x3, 0x3})
	github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_rewards_and_penalties.go:46 +0x4f4
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.ProcessRewardsAndPenalties({0x2e43800?, 0x4132cb5c80}, {0x438d650000, 0xef7fb, 0x148390}, {0x42b2678d70, 0x3, 0x3})
	github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_rewards_and_penalties.go:230 +0xdc
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.ProcessEpoch({0x2e43800, 0x4132cb5c80})
	github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_epoch.go:47 +0x15c
github.com/ledgerwatch/erigon/cl/transition/impl/eth2.(*impl).ProcessSlots(0x4000dca940?, {0x2e43800, 0x4132cb5c80}, 0x8674a0)
	github.com/ledgerwatch/erigon/cl/transition/impl/eth2/operations.go:844 +0x120
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).getCheckpointState(0x40001298c0, {0x42b447365c, 0x28, 0x88})
	github.com/ledgerwatch/erigon/cl/phase1/forkchoice/utils.go:128 +0x1a0
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).OnAttestation(0x40001298c0, 0x42b4473600, 0x1, 0x0)
	github.com/ledgerwatch/erigon/cl/phase1/forkchoice/on_attestation.go:48 +0x1c8
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func8.3.1(0x42b6191640?, 0x42cfd3e2a0?, 0x4222b35668?)
	github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:669 +0x64
github.com/ledgerwatch/erigon/cl/cltypes/solid.(*ListSSZ[...]).Range(0x195, 0x40ed5b3fb0?)
	github.com/ledgerwatch/erigon/cl/cltypes/solid/list_ssz.go:142 +0x7c
github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func8.3()
	github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:666 +0x60
created by github.com/ledgerwatch/erigon/cl/phase1/stages.ConsensusClStages.func8 in goroutine 718946416
	github.com/ledgerwatch/erigon/cl/phase1/stages/clstages.go:665 +0x12c4
```

**Comment by wmitsuda** [comment]
I do confirm this bug exists, I saw the same on the test node I run caplin, exactly same block:

```
INFO[04-08|08:20:06.091] RPC Daemon notified of new headers       from=19609719 to=19609720 amount=1 hash=0xf45e41c39d
a1f66739e60bb255a082970835a753902899c1f88a1e8cca607d0e header sending=19.105µs log sending=280ns
INFO[04-08|08:20:06.092] head updated                             hash=0xf45e41c39da1f66739e60bb255a082970835a75390289
9c1f88a1e8cca607d0e number=19609720
INFO[04-08|08:20:29.876] [updateForkchoice] Fork choice update: flushing in-memory state (built by previous newPayload
)
panic: runtime error: integer divide by zero

goroutine 839599633 [running]:
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.processRewardsAndPenaltiesPostAltair({0x314af00, 0xc
1521e3b60}, {0xc2a1c0a000, 0xef7fb, 0x0?}, {0xc0c127a7d0, 0x3, 0x3})
        github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_rewards_and_penalties.go:46 +0x697
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.ProcessRewardsAndPenalties({0x314af00, 0xc1521e3b60}
, {0xc2a1c0a000, 0xef7fb, 0x148390}, {0xc0c127a7d0, 0x3, 0x3})
        github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_rewards_and_penalties.go:230 +0xf9
github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange.ProcessEpoch({0x314af00, 0xc1521e3b60})
        github.com/ledgerwatch/erigon/cl/transition/impl/eth2/statechange/process_epoch.go:47 +0x17c
github.com/ledgerwatch/erigon/cl/transition/impl/eth2.(*impl).ProcessSlots(0xc000a1ec80?, {0x314af00, 0xc1521e3b60}, 0
x8674a0)
        github.com/ledgerwatch/erigon/cl/transition/impl/eth2/operations.go:844 +0x196
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).getCheckpointState(0xc02e1be588, {0xc2986d985c,
0x28, 0x88})
        github.com/ledgerwatch/erigon/cl/phase1/forkchoice/utils.go:128 +0x20d
github.com/ledgerwatch/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).OnAttestation(0xc02e1be588, 0xc2986d9800, 0x1, 0
x0)
```

**Comment by Giulio2002** [comment]
fyi this is fixed in devel. next release will have fix. restarting your node should help for now

**Comment by Giulio2002** [comment]
for whoever wants to cherry-pick the fix: https://github.com/ledgerwatch/erigon/commit/a035c5a06adee56db1aae6499ae94b1205112cf9
