### ISSUE TITLE
e35: nil-ptr during or after merge

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#9963]
```
[INFO] [04-16|17:01:30.863] [snapshots] merge state accounts(val:120-122, hist:120-122, idx:120-122), storage(val:120-122, hist:120-122, idx:120-122), code(val:120-122, hist:120-122, idx:120-122), commitment(val:120-122), logAddr=120-122, logTopic=120-122, traceFrom=120-122, traceTo=120-122
[INFO] [04-16|17:01:32.016] [sync] jump by 1K blocks                 currentJumpTo=5554999 bigJumpTo=5712033
[INFO] [04-16|17:01:32.021] [1/12 Snapshots] Requesting downloads
[INFO] [04-16|17:01:32.244] [snapshots:download] Blocks Stat         blocks=5508k indices=5508k alloc=3.0GB sys=12.7GB
[INFO] [04-16|17:01:32.244] [snapshots] History Stat                 blocks=5520k txs=189m txNum2blockNum="64=4659K,96=5168K,112=5377K,120=5503K,121=5520K" first_history_idx_in_db=5520611 last_comitment_block=5535739 last_comitment_tx_num=190625000 alloc=3.0GB sys=12.7GB
[INFO] [04-16|17:01:32.245] [3/12 Senders] Started                   from=5544999 to=5554999
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1200a7c]

goroutine 42508033 [running]:
github.com/ledgerwatch/erigon-lib/seg.(*Decompressor).MakeGetter(...)
	github.com/ledgerwatch/erigon-lib@v1.0.0/seg/decompress.go:573
github.com/ledgerwatch/erigon-lib/state.(*HistoryRoTx).mergeFiles(0xc03579e820, {0x3193f28, 0xc0b0fd3090}, {0xc110b71e50, 0x2, 0x2}, {0xc110b71cc0, 0x2, 0x495317?}, {0xb2d05e0, ...}, ...)
	github.com/ledgerwatch/erigon-lib@v1.0.0/state/merge.go:884 +0x91c
github.com/ledgerwatch/erigon-lib/state.(*DomainRoTx).mergeFiles(0xc0550d51e0, {0x3193f28, 0xc0b0fd3090}, {0xc05cc784a0, 0x2, 0x2?}, {0xc110b71e50, 0x2, 0x2}, {0xc110b71cc0, ...}, ...)
	github.com/ledgerwatch/erigon-lib@v1.0.0/state/merge.go:521 +0x2a5
github.com/ledgerwatch/erigon-lib/state.(*AggregatorRoTx).mergeFiles.func2()
	github.com/ledgerwatch/erigon-lib@v1.0.0/state/aggregator_v3.go:1464 +0x28d
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 42508032
	golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x96
exit status 2
```

**Comment by awskii** [comment]
Closed by https://github.com/ledgerwatch/erigon/pull/9954

**Comment by awskii** [comment]
I did not seen this issue for past month. Reopen if happened.
